| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | | <span style="color: tomato">70.1<small>%</small></span> | - | - | - |
| [KODEX 레버리지](/122630/) | 2<small>x</small> | <span style="color: tomato">165.6<small>%</small></span> | 4.1<small>%</small> | 4.3<small>%</small> | 8.2<small>%</small> |
| [TIGER 200선물레버리지](/267770/) | 2<small>x</small> | <span style="color: tomato">165.9<small>%</small></span> | 4.1<small>%</small> | 4.2<small>%</small> | 8.1<small>%</small> |
| [KODEX 인버스](/114800/) | -1<small>x</small> | <span style="color: cornflowerblue">-41.3<small>%</small></span> | 4.1<small>%</small> | -4.1<small>%</small> | 0.1<small>%</small> |
| [KODEX 200선물인버스2X](/252670/) | -2<small>x</small> | <span style="color: cornflowerblue">-67.9<small>%</small></span> | 11.8<small>%</small> | -5.3<small>%</small> | 7.2<small>%</small> |