| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | | <span style="color: tomato">13.8<small>%</small></span> | - | - | - |
| [KODEX 레버리지](/122630/) | 2<small>x</small> | <span style="color: tomato">17.3<small>%</small></span> | 4.1<small>%</small> | 5.5<small>%</small> | 9.4<small>%</small> |
| [TIGER 200선물레버리지](/267770/) | 2<small>x</small> | <span style="color: tomato">17.5<small>%</small></span> | 4.1<small>%</small> | 5.3<small>%</small> | 9.3<small>%</small> |
| [KODEX 인버스](/114800/) | -1<small>x</small> | <span style="color: cornflowerblue">-10.8<small>%</small></span> | 4.0<small>%</small> | -5.6<small>%</small> | -1.4<small>%</small> |
| [KODEX 200선물인버스2X](/252670/) | -2<small>x</small> | <span style="color: cornflowerblue">-26.1<small>%</small></span> | 11.4<small>%</small> | -7.9<small>%</small> | 4.4<small>%</small> |