| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | | <span style="color: tomato">4.4<small>%</small></span> | - | - | - |
| [KODEX 레버리지](/122630/) | 2<small>x</small> | <span style="color: cornflowerblue">-0.1<small>%</small></span> | 3.9<small>%</small> | 4.7<small>%</small> | 8.4<small>%</small> |
| [TIGER 200선물레버리지](/267770/) | 2<small>x</small> | <span style="color: cornflowerblue">-0.9<small>%</small></span> | 3.9<small>%</small> | 5.5<small>%</small> | 9.2<small>%</small> |
| [KODEX 인버스](/114800/) | -1<small>x</small> | <span style="color: cornflowerblue">-2.4<small>%</small></span> | 3.8<small>%</small> | -5.9<small>%</small> | -2.0<small>%</small> |
| [KODEX 200선물인버스2X](/252670/) | -2<small>x</small> | <span style="color: cornflowerblue">-12.2<small>%</small></span> | 10.7<small>%</small> | -7.3<small>%</small> | 4.2<small>%</small> |