| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 코스닥150 | | <span style="color: cornflowerblue">-8.5<small>%</small></span> | - | - | - |
| [KODEX 코스닥150레버리지](/233740/) | 2<small>x</small> | <span style="color: cornflowerblue">-24.1<small>%</small></span> | 6.9<small>%</small> | 2.6<small>%</small> | 9.3<small>%</small> |
| [RISE 코스닥150선물레버리지](/278240/) | 2<small>x</small> | <span style="color: cornflowerblue">-20.8<small>%</small></span> | 6.9<small>%</small> | -1.6<small>%</small> | 5.3<small>%</small> |
| [KODEX 코스닥150선물인버스](/251340/) | -1<small>x</small> | <span style="color: tomato">3.5<small>%</small></span> | 6.6<small>%</small> | -1.4<small>%</small> | 5.3<small>%</small> |
| [삼성 인버스 2X 코스닥150 선물 ETN](/530107/) | -2<small>x</small> | <span style="color: cornflowerblue">-7.2<small>%</small></span> | 18.4<small>%</small> | 4.7<small>%</small> | 22.3<small>%</small> |
| [미래에셋 인버스 2X 코스닥150 선물 ETN](/520057/) | -2<small>x</small> | <span style="color: cornflowerblue">-7.1<small>%</small></span> | 18.4<small>%</small> | 4.7<small>%</small> | 22.2<small>%</small> |