| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 코스닥150 | | <span style="color: tomato">5.7<small>%</small></span> | - | - | - |
| [KODEX 코스닥150레버리지](/233740/) | 2<small>x</small> | <span style="color: cornflowerblue">-0.2<small>%</small></span> | 6.8<small>%</small> | 4.2<small>%</small> | 10.7<small>%</small> |
| [RISE 코스닥150선물레버리지](/278240/) | 2<small>x</small> | <span style="color: tomato">0.1<small>%</small></span> | 6.8<small>%</small> | 3.9<small>%</small> | 10.5<small>%</small> |
| [KODEX 코스닥150선물인버스](/251340/) | -1<small>x</small> | <span style="color: cornflowerblue">-8.3<small>%</small></span> | 6.8<small>%</small> | -4.0<small>%</small> | 3.1<small>%</small> |
| [삼성 인버스 2X 코스닥150 선물 ETN](/530107/) | -2<small>x</small> | <span style="color: cornflowerblue">-25.5<small>%</small></span> | 18.9<small>%</small> | -2.7<small>%</small> | 16.7<small>%</small> |
| [미래에셋 인버스 2X 코스닥150 선물 ETN](/520057/) | -2<small>x</small> | <span style="color: cornflowerblue">-25.3<small>%</small></span> | 18.9<small>%</small> | -3.0<small>%</small> | 16.5<small>%</small> |