| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국달러선물 | | <span style="color: tomato">10.7<small>%</small></span> | - | - | - |
| [KODEX 미국달러선물레버리지](/261250/) | 2<small>x</small> | <span style="color: tomato">17.3<small>%</small></span> | 0.7<small>%</small> | 3.7<small>%</small> | 4.4<small>%</small> |
| [KODEX 미국달러선물인버스](/261270/) | -1<small>x</small> | <span style="color: cornflowerblue">-5.5<small>%</small></span> | 0.7<small>%</small> | -5.4<small>%</small> | -4.7<small>%</small> |
| [KODEX 미국달러선물인버스2X](/261260/) | -2<small>x</small> | <span style="color: cornflowerblue">-14.3<small>%</small></span> | 2.0<small>%</small> | -7.2<small>%</small> | -5.1<small>%</small> |