| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국달러선물 | | <span style="color: tomato">13.7<small>%</small></span> | - | - | - |
| [KODEX 미국달러선물레버리지](/261250/) | 2<small>x</small> | <span style="color: tomato">24.1<small>%</small></span> | 0.6<small>%</small> | 3.5<small>%</small> | 4.0<small>%</small> |
| [KODEX 미국달러선물인버스](/261270/) | -1<small>x</small> | <span style="color: cornflowerblue">-7.9<small>%</small></span> | 0.6<small>%</small> | -5.3<small>%</small> | -4.7<small>%</small> |
| [KODEX 미국달러선물인버스2X](/261260/) | -2<small>x</small> | <span style="color: cornflowerblue">-18.1<small>%</small></span> | 1.7<small>%</small> | -7.8<small>%</small> | -5.9<small>%</small> |