| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX KRX300 | | <span style="color: tomato">37.4<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [KODEX KRX300레버리지](/306950/) | 2<small>x</small> | <span style="color: tomato">73.1<small>%</small></span><sup><small>11개월</small></sup> | 4.0<small>%</small> | 4.4<small>%</small> | 8.2<small>%</small> |