| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX KRX300 | | <span style="color: tomato">102.8<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [KODEX KRX300레버리지](/306950/) | 2<small>x</small> | <span style="color: tomato">183.7<small>%</small></span><sup><small>11개월</small></sup> | 28.7<small>%</small> | 3.1<small>%</small> | 30.9<small>%</small> |