| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX KRX300 | | <span style="color: tomato">50.1<small>%</small></span> | - | - | - |
| [KODEX KRX300레버리지](/306950/) | 2<small>x</small> | <span style="color: tomato">103.4<small>%</small></span> | 4.2<small>%</small> | 5.7<small>%</small> | 9.7<small>%</small> |