| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 2차전지TOP10 | | <span style="color: tomato">4.6<small>%</small></span> | - | - | - |
| [TIGER 2차전지TOP10레버리지](/412570/) | 2<small>x</small> | <span style="color: cornflowerblue">-10.8<small>%</small></span> | 13.5<small>%</small> | 5.8<small>%</small> | 18.5<small>%</small> |