| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 2차전지TOP10 | | <span style="color: cornflowerblue">-28.4<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [TIGER 2차전지TOP10레버리지](/412570/) | 2<small>x</small> | <span style="color: cornflowerblue">-58.2<small>%</small></span><sup><small>11개월</small></sup> | 13.4<small>%</small> | 5.7<small>%</small> | 18.4<small>%</small> |