| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 2차전지TOP10 | | <span style="color: tomato">19.3<small>%</small></span> | - | - | - |
| [TIGER 2차전지TOP10레버리지](/412570/) | 2<small>x</small> | <span style="color: cornflowerblue">-1.4<small>%</small></span> | 27.9<small>%</small> | 3.8<small>%</small> | 30.6<small>%</small> |