| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국나스닥100(H) | | <span style="color: tomato">18.7<small>%</small></span> | - | - | - |
| [KIWOOM 미국나스닥100(H)](/453080/) | 1<small>x</small> | <span style="color: tomato">18.5<small>%</small></span> | -0.0<small>%</small> | 0.1<small>%</small> | 0.1<small>%</small> |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820/) | 2<small>x</small> | <span style="color: tomato">32.2<small>%</small></span> | 6.1<small>%</small> | -0.0<small>%</small> | 6.1<small>%</small> |