| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국S&P500(H) | | <span style="color: tomato">14.3<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [PLUS 미국S&P500(H)](/269540/) | 1<small>x</small> | <span style="color: tomato">13.9<small>%</small></span><sup><small>11개월</small></sup> | 0.0<small>%</small> | 0.3<small>%</small> | 0.3<small>%</small> |
| [TIGER 미국S&P500레버리지(합성 H)](/225040/) | 2<small>x</small> | <span style="color: tomato">25.8<small>%</small></span><sup><small>11개월</small></sup> | 1.9<small>%</small> | 1.7<small>%</small> | 3.6<small>%</small> |