| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국S&P500(H) | | <span style="color: tomato">12.7<small>%</small></span> | - | - | - |
| [PLUS 미국S&P500(H)](/269540/) | 1<small>x</small> | <span style="color: tomato">14.0<small>%</small></span> | 0.0<small>%</small> | -1.1<small>%</small> | -1.1<small>%</small> |
| [TIGER 미국S&P500레버리지(합성 H)](/225040/) | 2<small>x</small> | <span style="color: tomato">19.8<small>%</small></span> | 4.2<small>%</small> | 1.6<small>%</small> | 5.7<small>%</small> |