| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국나스닥100(H) | | <span style="color: tomato">22.0<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [KIWOOM 미국나스닥100(H)](/453080/) | 1<small>x</small> | <span style="color: tomato">21.9<small>%</small></span><sup><small>11개월</small></sup> | -0.0<small>%</small> | 0.1<small>%</small> | 0.1<small>%</small> |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820/) | 2<small>x</small> | <span style="color: tomato">41.4<small>%</small></span><sup><small>11개월</small></sup> | 4.0<small>%</small> | 1.0<small>%</small> | 5.0<small>%</small> |