| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 미국나스닥100(H) | | <span style="color: tomato">24.3<small>%</small></span> | - | - | - |
| [KIWOOM 미국나스닥100(H)](/453080/) | 1<small>x</small> | <span style="color: tomato">23.8<small>%</small></span> | 0.0<small>%</small> | 0.4<small>%</small> | 0.4<small>%</small> |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820/) | 2<small>x</small> | <span style="color: tomato">43.3<small>%</small></span> | 6.6<small>%</small> | 0.7<small>%</small> | 7.2<small>%</small> |