| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| RISE 2차전지TOP10 | | <span style="color: cornflowerblue">-23.6<small>%</small></span> | - | - | - |
| [RISE 2차전지TOP10인버스(합성)](/465350/) | -1<small>x</small> | <span style="color: tomato">11.4<small>%</small></span> | 15.5<small>%</small> | -0.8<small>%</small> | 14.9<small>%</small> |