| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| RISE 2차전지TOP10 | | <span style="color: tomato">52.0<small>%</small></span> | - | - | - |
| [RISE 2차전지TOP10인버스(합성)](/465350/) | -1<small>x</small> | <span style="color: cornflowerblue">-55.1<small>%</small></span> | 30.8<small>%</small> | 1.3<small>%</small> | 31.8<small>%</small> |