| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | | <span style="color: tomato">35.9<small>%</small></span> | - | - | - |
| [AAP2.L](/aap2/) | 2<small>x</small> | <span style="color: tomato">60.7<small>%</small></span> | 5.0<small>%</small> | 8.4<small>%</small> | 12.9<small>%</small> |
| [AAPU](/aapu/) | 2<small>x</small> | <span style="color: tomato">153.8<small>%</small></span><sup><small>6개월</small></sup> | 3.4<small>%</small> | 5.7<small>%</small> | 8.9<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>x</small> | <span style="color: tomato">82.9<small>%</small></span> | 14.1<small>%</small> | 15.1<small>%</small> | 27.1<small>%</small> |
| [AAPD](/aapd/) | -1<small>x</small> | <span style="color: cornflowerblue">-24.1<small>%</small></span> | 5.0<small>%</small> | -8.6<small>%</small> | -3.1<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>x</small> | <span style="color: cornflowerblue">-66.7<small>%</small></span> | 27.1<small>%</small> | -14.3<small>%</small> | 16.7<small>%</small> |