| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | | <span style="color: tomato">8.3<small>%</small></span> | - | - | - |
| [AAP2.L](/aap2/) | 2<small>x</small> | <span style="color: cornflowerblue">-4.0<small>%</small></span> | 9.5<small>%</small> | 9.6<small>%</small> | 18.2<small>%</small> |
| [AAPU](/aapu/) | 2<small>x</small> | <span style="color: cornflowerblue">-4.2<small>%</small></span> | 9.6<small>%</small> | 9.6<small>%</small> | 18.3<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>x</small> | <span style="color: cornflowerblue">-21.6<small>%</small></span> | 25.8<small>%</small> | 16.7<small>%</small> | 38.3<small>%</small> |
| [AAPD](/aapd/) | -1<small>x</small> | <span style="color: cornflowerblue">-10.7<small>%</small></span> | 9.9<small>%</small> | -7.4<small>%</small> | 3.2<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>x</small> | <span style="color: cornflowerblue">-57.8<small>%</small></span> | 48.0<small>%</small> | -3.2<small>%</small> | 46.3<small>%</small> |