| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | | <span style="color: tomato">38.1<small>%</small></span> | - | - | - |
| [AAP2.L](/aap2/) | 2<small>x</small> | <span style="color: tomato">64.6<small>%</small></span> | 6.0<small>%</small> | 8.1<small>%</small> | 13.7<small>%</small> |
| [AAPU](/aapu/) | 2<small>x</small> | <span style="color: tomato">61.8<small>%</small></span> | 6.1<small>%</small> | 8.5<small>%</small> | 14.1<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>x</small> | <span style="color: tomato">87.3<small>%</small></span> | 17.2<small>%</small> | 14.1<small>%</small> | 28.9<small>%</small> |
| [AAPD](/aapd/) | -1<small>x</small> | <span style="color: cornflowerblue">-27.2<small>%</small></span> | 6.1<small>%</small> | -6.4<small>%</small> | 0.0<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>x</small> | <span style="color: tomato">4754.1<small>%</small></span> | 31.0<small>%</small> | -18362.6<small>%</small> | -12639.0<small>%</small> |