| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | | <span style="color: tomato">25.5<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>x</small> | <span style="color: tomato">44.7<small>%</small></span> | 1.2<small>%</small> | 7.1<small>%</small> | 8.2<small>%</small> |
| [UDOW](/udow/) | 3<small>x</small> | <span style="color: tomato">66.9<small>%</small></span> | 3.6<small>%</small> | 12.5<small>%</small> | 15.6<small>%</small> |
| [DOG](/dog/) | -1<small>x</small> | <span style="color: cornflowerblue">-13.2<small>%</small></span> | 1.2<small>%</small> | -10.2<small>%</small> | -8.9<small>%</small> |
| [DXD](/dxd/) | -2<small>x</small> | <span style="color: cornflowerblue">-29.2<small>%</small></span> | 3.6<small>%</small> | -15.7<small>%</small> | -11.5<small>%</small> |
| [SDOW](/sdow/) | -3<small>x</small> | <span style="color: cornflowerblue">-43.3<small>%</small></span> | 7.1<small>%</small> | -20.9<small>%</small> | -12.3<small>%</small> |