| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | | <span style="color: tomato">19.4<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>x</small> | <span style="color: tomato">33.0<small>%</small></span> | 1.5<small>%</small> | 5.2<small>%</small> | 6.6<small>%</small> |
| [UDOW](/udow/) | 3<small>x</small> | <span style="color: tomato">47.1<small>%</small></span> | 4.5<small>%</small> | 9.4<small>%</small> | 13.5<small>%</small> |
| [DOG](/dog/) | -1<small>x</small> | <span style="color: cornflowerblue">-11.9<small>%</small></span> | 1.5<small>%</small> | -6.8<small>%</small> | -5.2<small>%</small> |
| [DXD](/dxd/) | -2<small>x</small> | <span style="color: cornflowerblue">-25.8<small>%</small></span> | 4.5<small>%</small> | -10.7<small>%</small> | -5.7<small>%</small> |
| [SDOW](/sdow/) | -3<small>x</small> | <span style="color: cornflowerblue">-38.2<small>%</small></span> | 8.9<small>%</small> | -15.4<small>%</small> | -5.1<small>%</small> |