| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | | <span style="color: tomato">27.5<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>x</small> | <span style="color: tomato">49.1<small>%</small></span> | 1.2<small>%</small> | 7.1<small>%</small> | 8.3<small>%</small> |
| [UDOW](/udow/) | 3<small>x</small> | <span style="color: tomato">74.6<small>%</small></span> | 3.6<small>%</small> | 12.6<small>%</small> | 15.8<small>%</small> |
| [DOG](/dog/) | -1<small>x</small> | <span style="color: cornflowerblue">-14.6<small>%</small></span> | 1.2<small>%</small> | -10.2<small>%</small> | -8.8<small>%</small> |
| [DXD](/dxd/) | -2<small>x</small> | <span style="color: cornflowerblue">-31.4<small>%</small></span> | 3.6<small>%</small> | -15.7<small>%</small> | -11.4<small>%</small> |
| [SDOW](/sdow/) | -3<small>x</small> | <span style="color: cornflowerblue">-47.0<small>%</small></span> | 7.2<small>%</small> | -18.3<small>%</small> | -9.8<small>%</small> |