| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | | <span style="color: tomato">15.3<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>x</small> | <span style="color: tomato">19.5<small>%</small></span> | 3.7<small>%</small> | 6.6<small>%</small> | 10.0<small>%</small> |
| [EWV](/ewv/) | -2<small>x</small> | <span style="color: cornflowerblue">-25.3<small>%</small></span> | 10.9<small>%</small> | -11.4<small>%</small> | 0.7<small>%</small> |