| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | | <span style="color: tomato">14.1<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>x</small> | <span style="color: tomato">17.1<small>%</small></span> | 3.9<small>%</small> | 6.3<small>%</small> | 10.0<small>%</small> |
| [EWV](/ewv/) | -2<small>x</small> | <span style="color: cornflowerblue">-24.6<small>%</small></span> | 11.5<small>%</small> | -10.9<small>%</small> | 1.8<small>%</small> |