| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | | <span style="color: tomato">12.4<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>x</small> | <span style="color: tomato">13.3<small>%</small></span> | 3.0<small>%</small> | 7.5<small>%</small> | 10.3<small>%</small> |
| [EWV](/ewv/) | -2<small>x</small> | <span style="color: cornflowerblue">-19.7<small>%</small></span> | 8.5<small>%</small> | -10.8<small>%</small> | -1.4<small>%</small> |