| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">36.7<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">63.2<small>%</small></span> | 8.5<small>%</small> | 4.6<small>%</small> | 12.6<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">62.6<small>%</small></span> | 8.5<small>%</small> | 4.9<small>%</small> | 13.0<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">7.7<small>%</small></span><sup><small>6개월</small></sup> | 16.2<small>%</small> | 5.4<small>%</small> | 20.8<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-74.7<small>%</small></span> | 43.2<small>%</small> | -13.7<small>%</small> | 35.5<small>%</small> |