| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">19.9<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">30.5<small>%</small></span> | 5.2<small>%</small> | 4.3<small>%</small> | 9.2<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">30.0<small>%</small></span> | 5.2<small>%</small> | 4.7<small>%</small> | 9.6<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">24.7<small>%</small></span> | 14.7<small>%</small> | 15.1<small>%</small> | 27.6<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-54.0<small>%</small></span> | 27.4<small>%</small> | -9.4<small>%</small> | 20.7<small>%</small> |