| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">22.4<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">35.3<small>%</small></span> | 5.1<small>%</small> | 4.8<small>%</small> | 9.7<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">35.3<small>%</small></span> | 5.1<small>%</small> | 4.9<small>%</small> | 9.8<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">31.6<small>%</small></span> | 14.7<small>%</small> | 16.0<small>%</small> | 28.3<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-56.4<small>%</small></span> | 27.4<small>%</small> | -10.3<small>%</small> | 19.9<small>%</small> |