| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FXI | | <span style="color: cornflowerblue">-4.8<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>x</small> | <span style="color: cornflowerblue">-18.1<small>%</small></span> | 3.9<small>%</small> | 5.8<small>%</small> | 9.5<small>%</small> |
| [YINN](/yinn/) | 3<small>x</small> | <span style="color: cornflowerblue">-31.7<small>%</small></span> | 11.4<small>%</small> | 10.6<small>%</small> | 20.8<small>%</small> |
| [YXI](/yxi/) | -1<small>x</small> | <span style="color: tomato">6.8<small>%</small></span> | 3.9<small>%</small> | -5.8<small>%</small> | -1.7<small>%</small> |
| [FXP](/fxp/) | -2<small>x</small> | <span style="color: tomato">7.7<small>%</small></span> | 11.3<small>%</small> | -10.0<small>%</small> | 2.4<small>%</small> |
| [YANG](/yang/) | -3<small>x</small> | <span style="color: tomato">6.1<small>%</small></span> | 21.3<small>%</small> | -16.3<small>%</small> | 8.5<small>%</small> |