| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FXI | | <span style="color: cornflowerblue">-6.2<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>x</small> | <span style="color: cornflowerblue">-20.4<small>%</small></span> | 3.8<small>%</small> | 5.9<small>%</small> | 9.5<small>%</small> |
| [YINN](/yinn/) | 3<small>x</small> | <span style="color: cornflowerblue">-34.8<small>%</small></span> | 11.1<small>%</small> | 11.1<small>%</small> | 21.0<small>%</small> |
| [YXI](/yxi/) | -1<small>x</small> | <span style="color: tomato">8.7<small>%</small></span> | 3.8<small>%</small> | -6.0<small>%</small> | -1.9<small>%</small> |
| [FXP](/fxp/) | -2<small>x</small> | <span style="color: tomato">11.3<small>%</small></span> | 11.0<small>%</small> | -10.0<small>%</small> | 2.1<small>%</small> |
| [YANG](/yang/) | -3<small>x</small> | <span style="color: tomato">11.8<small>%</small></span> | 20.8<small>%</small> | -16.5<small>%</small> | 7.8<small>%</small> |