| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FXI | | <span style="color: tomato">37.5<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>x</small> | <span style="color: tomato">56.3<small>%</small></span> | 10.4<small>%</small> | 7.7<small>%</small> | 17.3<small>%</small> |
| [YINN](/yinn/) | 3<small>x</small> | <span style="color: tomato">65.3<small>%</small></span> | 27.9<small>%</small> | 11.7<small>%</small> | 36.4<small>%</small> |
| [YXI](/yxi/) | -1<small>x</small> | <span style="color: cornflowerblue">-30.3<small>%</small></span> | 10.6<small>%</small> | -7.1<small>%</small> | 4.2<small>%</small> |
| [FXP](/fxp/) | -2<small>x</small> | <span style="color: cornflowerblue">-58.3<small>%</small></span> | 28.9<small>%</small> | -10.8<small>%</small> | 21.2<small>%</small> |
| [YANG](/yang/) | -3<small>x</small> | <span style="color: cornflowerblue">-77.4<small>%</small></span> | 50.1<small>%</small> | -18.0<small>%</small> | 41.1<small>%</small> |