| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| INDA | | <span style="color: tomato">27.4<small>%</small></span> | - | - | - |
| [INDL](/indl/) | 2<small>x</small> | <span style="color: tomato">48.0<small>%</small></span> | 2.0<small>%</small> | 7.0<small>%</small> | 8.9<small>%</small> |