| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | | <span style="color: tomato">10.1<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>x</small> | <span style="color: tomato">7.9<small>%</small></span> | 5.2<small>%</small> | 6.1<small>%</small> | 11.0<small>%</small> |
| [TNA](/tna/) | 3<small>x</small> | <span style="color: tomato">1.0<small>%</small></span> | 14.9<small>%</small> | 11.1<small>%</small> | 24.3<small>%</small> |
| [RWM](/rwm/) | -1<small>x</small> | <span style="color: cornflowerblue">-6.9<small>%</small></span> | 5.3<small>%</small> | -8.2<small>%</small> | -2.5<small>%</small> |
| [TWM](/twm/) | -2<small>x</small> | <span style="color: cornflowerblue">-21.2<small>%</small></span> | 15.1<small>%</small> | -12.5<small>%</small> | 4.5<small>%</small> |
| [TZA](/tza/) | -3<small>x</small> | <span style="color: cornflowerblue">-36.0<small>%</small></span> | 28.2<small>%</small> | -18.9<small>%</small> | 14.6<small>%</small> |