| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | | <span style="color: tomato">12.1<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>x</small> | <span style="color: tomato">11.6<small>%</small></span> | 5.3<small>%</small> | 6.3<small>%</small> | 11.2<small>%</small> |
| [TNA](/tna/) | 3<small>x</small> | <span style="color: tomato">6.4<small>%</small></span> | 15.0<small>%</small> | 11.2<small>%</small> | 24.5<small>%</small> |
| [RWM](/rwm/) | -1<small>x</small> | <span style="color: cornflowerblue">-8.7<small>%</small></span> | 5.3<small>%</small> | -8.1<small>%</small> | -2.4<small>%</small> |
| [TWM](/twm/) | -2<small>x</small> | <span style="color: cornflowerblue">-24.1<small>%</small></span> | 15.2<small>%</small> | -12.6<small>%</small> | 4.5<small>%</small> |
| [TZA](/tza/) | -3<small>x</small> | <span style="color: cornflowerblue">-39.5<small>%</small></span> | 28.3<small>%</small> | -18.9<small>%</small> | 14.7<small>%</small> |