| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | | <span style="color: tomato">15.6<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>x</small> | <span style="color: tomato">19.0<small>%</small></span> | 5.1<small>%</small> | 6.2<small>%</small> | 11.0<small>%</small> |
| [TNA](/tna/) | 3<small>x</small> | <span style="color: tomato">17.7<small>%</small></span> | 14.6<small>%</small> | 10.8<small>%</small> | 23.8<small>%</small> |
| [RWM](/rwm/) | -1<small>x</small> | <span style="color: cornflowerblue">-11.3<small>%</small></span> | 5.2<small>%</small> | -8.1<small>%</small> | -2.5<small>%</small> |
| [TWM](/twm/) | -2<small>x</small> | <span style="color: cornflowerblue">-28.5<small>%</small></span> | 14.8<small>%</small> | -12.3<small>%</small> | 4.4<small>%</small> |
| [TZA](/tza/) | -3<small>x</small> | <span style="color: cornflowerblue">-44.7<small>%</small></span> | 27.7<small>%</small> | -18.3<small>%</small> | 14.5<small>%</small> |