| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KWEB | | <span style="color: tomato">29.7<small>%</small></span> | - | - | - |
| [CWEB](/cweb/) | 2<small>x</small> | <span style="color: tomato">38.5<small>%</small></span> | 11.9<small>%</small> | 6.5<small>%</small> | 17.7<small>%</small> |