| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| MAGS | | <span style="color: tomato">47.3<small>%</small></span><sup><small>8개월</small></sup> | - | - | - |
| [MAGX](/magx/) | 2<small>x</small> | <span style="color: tomato">87.0<small>%</small></span><sup><small>8개월</small></sup> | 4.9<small>%</small> | 5.9<small>%</small> | 10.5<small>%</small> |
| [MAGQ](/magq/) | -1<small>x</small> | <span style="color: cornflowerblue">-12.6<small>%</small></span><sup><small>4개월</small></sup> | 3.0<small>%</small> | -5.0<small>%</small> | -1.8<small>%</small> |