| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| MAGS | | <span style="color: tomato">49.6<small>%</small></span><sup><small>8개월</small></sup> | - | - | - |
| [MAGX](/magx/) | 2<small>x</small> | <span style="color: tomato">92.3<small>%</small></span><sup><small>8개월</small></sup> | 4.8<small>%</small> | 5.9<small>%</small> | 10.4<small>%</small> |
| [MAGQ](/magq/) | -1<small>x</small> | <span style="color: cornflowerblue">-18.7<small>%</small></span><sup><small>4개월</small></sup> | 3.0<small>%</small> | -2.8<small>%</small> | 0.3<small>%</small> |