| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | | <span style="color: tomato">33.9<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>x</small> | <span style="color: tomato">22.5<small>%</small></span> | 22.2<small>%</small> | 12.1<small>%</small> | 31.6<small>%</small> |
| [3LNV.L](/3lnv/) | 3<small>x</small> | <span style="color: cornflowerblue">-17.7<small>%</small></span> | 53.8<small>%</small> | 25.6<small>%</small> | 65.7<small>%</small> |
| [NVDD](/nvdd/) | -1<small>x</small> | <span style="color: cornflowerblue">-36.3<small>%</small></span> | 21.6<small>%</small> | -8.8<small>%</small> | 14.7<small>%</small> |
| [NVD](/nvd/) | -2<small>x</small> | <span style="color: cornflowerblue">-70.5<small>%</small></span> | 52.4<small>%</small> | -10.9<small>%</small> | 47.2<small>%</small> |
| [3SNV.L](/3snv/) | -3<small>x</small> | <span style="color: cornflowerblue">-88.6<small>%</small></span> | 78.2<small>%</small> | -25.8<small>%</small> | 72.5<small>%</small> |