| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | | <span style="color: tomato">224.9<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>x</small> | <span style="color: tomato">494.1<small>%</small></span> | 23.2<small>%</small> | 26.7<small>%</small> | 43.8<small>%</small> |
| [3LNV.L](/3lnv/) | 3<small>x</small> | <span style="color: tomato">1607.7<small>%</small></span> | 54.5<small>%</small> | -9.3<small>%</small> | 50.3<small>%</small> |
| [NVDD](/nvdd/) | -1<small>x</small> | <span style="color: cornflowerblue">-74.5<small>%</small></span> | 24.0<small>%</small> | -8.9<small>%</small> | 17.3<small>%</small> |
| [NVD](/nvd/) | -2<small>x</small> | <span style="color: cornflowerblue">-94.5<small>%</small></span> | 57.0<small>%</small> | -34.4<small>%</small> | 42.2<small>%</small> |
| [3SNV.L](/3snv/) | -3<small>x</small> | <span style="color: cornflowerblue">-99.4<small>%</small></span> | 82.4<small>%</small> | -7.6<small>%</small> | 81.0<small>%</small> |