| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | | <span style="color: tomato">36.5<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>x</small> | <span style="color: tomato">27.3<small>%</small></span> | 22.1<small>%</small> | 12.2<small>%</small> | 31.6<small>%</small> |
| [3LNV.L](/3lnv/) | 3<small>x</small> | <span style="color: cornflowerblue">-6.3<small>%</small></span> | 53.8<small>%</small> | 19.9<small>%</small> | 63.0<small>%</small> |
| [NVDD](/nvdd/) | -1<small>x</small> | <span style="color: cornflowerblue">-37.4<small>%</small></span> | 21.5<small>%</small> | -9.0<small>%</small> | 14.5<small>%</small> |
| [NVD](/nvd/) | -2<small>x</small> | <span style="color: cornflowerblue">-71.9<small>%</small></span> | 52.2<small>%</small> | -9.7<small>%</small> | 47.6<small>%</small> |
| [3SNV.L](/3snv/) | -3<small>x</small> | <span style="color: cornflowerblue">-90.2<small>%</small></span> | 78.2<small>%</small> | -15.0<small>%</small> | 74.9<small>%</small> |