| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | | <span style="color: tomato">24.9<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>x</small> | <span style="color: tomato">42.1<small>%</small></span> | 3.9<small>%</small> | 5.2<small>%</small> | 8.9<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>x</small> | <span style="color: tomato">56.2<small>%</small></span> | 11.2<small>%</small> | 9.8<small>%</small> | 19.9<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>x</small> | <span style="color: tomato">46.0<small>%</small></span> | 32.8<small>%</small> | 27.3<small>%</small> | 51.2<small>%</small> |
| [PSQ](/psq/) | -1<small>x</small> | <span style="color: cornflowerblue">-17.8<small>%</small></span> | 3.9<small>%</small> | -6.9<small>%</small> | -2.7<small>%</small> |
| [QID](/qid/) | -2<small>x</small> | <span style="color: cornflowerblue">-36.9<small>%</small></span> | 11.2<small>%</small> | -11.0<small>%</small> | 1.5<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>x</small> | <span style="color: cornflowerblue">-53.3<small>%</small></span> | 21.2<small>%</small> | -15.7<small>%</small> | 8.8<small>%</small> |