| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | | <span style="color: tomato">29.0<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>x</small> | <span style="color: tomato">50.8<small>%</small></span> | 3.0<small>%</small> | 6.5<small>%</small> | 9.3<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>x</small> | <span style="color: tomato">72.4<small>%</small></span> | 8.7<small>%</small> | 11.9<small>%</small> | 19.6<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>x</small> | <span style="color: tomato">98.2<small>%</small></span> | 26.3<small>%</small> | 24.4<small>%</small> | 44.3<small>%</small> |
| [PSQ](/psq/) | -1<small>x</small> | <span style="color: cornflowerblue">-17.6<small>%</small></span> | 3.0<small>%</small> | -9.5<small>%</small> | -6.2<small>%</small> |
| [QID](/qid/) | -2<small>x</small> | <span style="color: cornflowerblue">-37.0<small>%</small></span> | 8.7<small>%</small> | -14.7<small>%</small> | -4.7<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>x</small> | <span style="color: cornflowerblue">-53.7<small>%</small></span> | 16.7<small>%</small> | -19.1<small>%</small> | 0.8<small>%</small> |