| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | | <span style="color: tomato">36.6<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>x</small> | <span style="color: tomato">69.4<small>%</small></span> | 3.0<small>%</small> | 6.5<small>%</small> | 9.3<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>x</small> | <span style="color: tomato">105.2<small>%</small></span> | 8.7<small>%</small> | 11.9<small>%</small> | 19.6<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>x</small> | <span style="color: tomato">162.3<small>%</small></span> | 26.2<small>%</small> | 25.5<small>%</small> | 45.0<small>%</small> |
| [PSQ](/psq/) | -1<small>x</small> | <span style="color: cornflowerblue">-22.3<small>%</small></span> | 3.0<small>%</small> | -9.5<small>%</small> | -6.2<small>%</small> |
| [QID](/qid/) | -2<small>x</small> | <span style="color: cornflowerblue">-43.9<small>%</small></span> | 8.7<small>%</small> | -14.8<small>%</small> | -4.8<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>x</small> | <span style="color: cornflowerblue">-61.6<small>%</small></span> | 16.6<small>%</small> | -17.6<small>%</small> | 2.0<small>%</small> |