| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | | <span style="color: tomato">39.4<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>x</small> | <span style="color: tomato">39.3<small>%</small></span> | 37.6<small>%</small> | 17.7<small>%</small> | 48.6<small>%</small> |
| [SOXS](/soxs/) | -3<small>x</small> | <span style="color: cornflowerblue">-83.2<small>%</small></span> | 64.8<small>%</small> | -29.9<small>%</small> | 54.3<small>%</small> |