| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | | <span style="color: tomato">27.0<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>x</small> | <span style="color: tomato">2.6<small>%</small></span> | 36.4<small>%</small> | 21.0<small>%</small> | 49.8<small>%</small> |
| [SOXS](/soxs/) | -3<small>x</small> | <span style="color: cornflowerblue">-75.7<small>%</small></span> | 63.5<small>%</small> | -36.2<small>%</small> | 50.2<small>%</small> |