| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | | <span style="color: tomato">38.0<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>x</small> | <span style="color: tomato">36.5<small>%</small></span> | 31.1<small>%</small> | 24.4<small>%</small> | 47.9<small>%</small> |
| [SOXS](/soxs/) | -3<small>x</small> | <span style="color: cornflowerblue">-73.7<small>%</small></span> | 51.9<small>%</small> | -44.2<small>%</small> | 30.7<small>%</small> |