| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | | <span style="color: tomato">37.4<small>%</small></span> | - | - | - |
| [SSO](/sso/) | 2<small>x</small> | <span style="color: tomato">73.9<small>%</small></span> | 1.5<small>%</small> | 6.5<small>%</small> | 7.9<small>%</small> |
| [SPXL](/spxl/) | 3<small>x</small> | <span style="color: tomato">119.0<small>%</small></span> | 4.5<small>%</small> | 11.7<small>%</small> | 15.6<small>%</small> |
| [SPYU](/spyu/) | 4<small>x</small> | <span style="color: tomato">120.2<small>%</small></span><sup><small>11개월</small></sup> | 8.4<small>%</small> | 25.6<small>%</small> | 31.9<small>%</small> |
| [SH](/sh/) | -1<small>x</small> | <span style="color: cornflowerblue">-22.7<small>%</small></span> | 1.5<small>%</small> | -7.9<small>%</small> | -6.3<small>%</small> |
| [SDS](/sds/) | -2<small>x</small> | <span style="color: cornflowerblue">-41.5<small>%</small></span> | 4.5<small>%</small> | -15.6<small>%</small> | -10.4<small>%</small> |
| [SPXU](/spxu/) | -3<small>x</small> | <span style="color: cornflowerblue">-57.3<small>%</small></span> | 8.7<small>%</small> | -21.6<small>%</small> | -10.9<small>%</small> |