| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | | <span style="color: tomato">18.5<small>%</small></span> | - | - | - |
| [SSO](/sso/) | 2<small>x</small> | <span style="color: tomato">27.6<small>%</small></span> | 3.6<small>%</small> | 5.8<small>%</small> | 9.2<small>%</small> |
| [SPXL](/spxl/) | 3<small>x</small> | <span style="color: tomato">34.0<small>%</small></span> | 10.4<small>%</small> | 10.2<small>%</small> | 19.5<small>%</small> |
| [SPYU](/spyu/) | 4<small>x</small> | <span style="color: tomato">19.8<small>%</small></span> | 19.7<small>%</small> | 24.5<small>%</small> | 39.3<small>%</small> |
| [SH](/sh/) | -1<small>x</small> | <span style="color: cornflowerblue">-11.6<small>%</small></span> | 3.7<small>%</small> | -8.8<small>%</small> | -4.7<small>%</small> |
| [SDS](/sds/) | -2<small>x</small> | <span style="color: cornflowerblue">-27.3<small>%</small></span> | 10.9<small>%</small> | -14.6<small>%</small> | -2.1<small>%</small> |
| [SPXU](/spxu/) | -3<small>x</small> | <span style="color: cornflowerblue">-42.4<small>%</small></span> | 21.1<small>%</small> | -21.5<small>%</small> | 4.1<small>%</small> |