| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | | <span style="color: tomato">15.9<small>%</small></span> | - | - | - |
| [SSO](/sso/) | 2<small>x</small> | <span style="color: tomato">21.5<small>%</small></span> | 3.9<small>%</small> | 5.9<small>%</small> | 9.6<small>%</small> |
| [SPXL](/spxl/) | 3<small>x</small> | <span style="color: tomato">23.8<small>%</small></span> | 11.2<small>%</small> | 10.6<small>%</small> | 20.6<small>%</small> |
| [SPYU](/spyu/) | 4<small>x</small> | <span style="color: tomato">7.0<small>%</small></span> | 21.1<small>%</small> | 24.9<small>%</small> | 40.7<small>%</small> |
| [SH](/sh/) | -1<small>x</small> | <span style="color: cornflowerblue">-9.7<small>%</small></span> | 4.0<small>%</small> | -9.0<small>%</small> | -4.7<small>%</small> |
| [SDS](/sds/) | -2<small>x</small> | <span style="color: cornflowerblue">-24.5<small>%</small></span> | 11.7<small>%</small> | -14.9<small>%</small> | -1.5<small>%</small> |
| [SPXU](/spxu/) | -3<small>x</small> | <span style="color: cornflowerblue">-39.3<small>%</small></span> | 22.4<small>%</small> | -21.8<small>%</small> | 5.5<small>%</small> |