| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | | <span style="color: cornflowerblue">-5.5<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>x</small> | <span style="color: cornflowerblue">-29.7<small>%</small></span> | 5.3<small>%</small> | 12.0<small>%</small> | 16.7<small>%</small> |
| [TBF](/tbf/) | -1<small>x</small> | <span style="color: tomato">12.0<small>%</small></span> | 1.8<small>%</small> | -7.7<small>%</small> | -5.8<small>%</small> |
| [TBT](/tbt/) | -2<small>x</small> | <span style="color: tomato">19.0<small>%</small></span> | 5.2<small>%</small> | -12.1<small>%</small> | -6.3<small>%</small> |
| [TMV](/tmv/) | -3<small>x</small> | <span style="color: tomato">26.5<small>%</small></span> | 10.1<small>%</small> | -18.8<small>%</small> | -6.7<small>%</small> |