| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | | <span style="color: cornflowerblue">-5.1<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>x</small> | <span style="color: cornflowerblue">-27.9<small>%</small></span> | 5.2<small>%</small> | 11.1<small>%</small> | 15.8<small>%</small> |
| [TBF](/tbf/) | -1<small>x</small> | <span style="color: tomato">11.3<small>%</small></span> | 1.8<small>%</small> | -7.6<small>%</small> | -5.7<small>%</small> |
| [TBT](/tbt/) | -2<small>x</small> | <span style="color: tomato">18.1<small>%</small></span> | 5.2<small>%</small> | -12.3<small>%</small> | -6.4<small>%</small> |
| [TMV](/tmv/) | -3<small>x</small> | <span style="color: tomato">25.5<small>%</small></span> | 10.1<small>%</small> | -19.5<small>%</small> | -7.4<small>%</small> |