| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | | <span style="color: cornflowerblue">-3.1<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>x</small> | <span style="color: cornflowerblue">-24.8<small>%</small></span> | 6.0<small>%</small> | 12.0<small>%</small> | 17.3<small>%</small> |
| [TBF](/tbf/) | -1<small>x</small> | <span style="color: tomato">10.3<small>%</small></span> | 2.1<small>%</small> | -9.1<small>%</small> | -6.8<small>%</small> |
| [TBT](/tbt/) | -2<small>x</small> | <span style="color: tomato">14.9<small>%</small></span> | 6.0<small>%</small> | -14.8<small>%</small> | -7.8<small>%</small> |
| [TMV](/tmv/) | -3<small>x</small> | <span style="color: tomato">18.9<small>%</small></span> | 11.7<small>%</small> | -22.4<small>%</small> | -8.1<small>%</small> |