| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | | <span style="color: tomato">54.4<small>%</small></span> | - | - | - |
| [TSLT](/tslt/) | 2<small>x</small> | <span style="color: tomato">24.0<small>%</small></span> | 38.6<small>%</small> | 15.3<small>%</small> | 48.0<small>%</small> |
| [TSLL](/tsll/) | 2<small>x</small> | <span style="color: tomato">28.9<small>%</small></span> | 38.6<small>%</small> | 12.0<small>%</small> | 45.9<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>x</small> | <span style="color: cornflowerblue">-28.1<small>%</small></span> | 77.1<small>%</small> | 14.7<small>%</small> | 80.5<small>%</small> |
| [TSLS](/tsls/) | -1<small>x</small> | <span style="color: cornflowerblue">-57.9<small>%</small></span> | 40.0<small>%</small> | -8.3<small>%</small> | 35.0<small>%</small> |