| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | | <span style="color: tomato">101.5<small>%</small></span> | - | - | - |
| [TSLT](/tslt/) | 2<small>x</small> | <span style="color: tomato">113.3<small>%</small></span> | 38.1<small>%</small> | 15.1<small>%</small> | 47.4<small>%</small> |
| [TSLL](/tsll/) | 2<small>x</small> | <span style="color: tomato">121.4<small>%</small></span> | 38.1<small>%</small> | 11.9<small>%</small> | 45.4<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>x</small> | <span style="color: tomato">55.2<small>%</small></span> | 76.4<small>%</small> | 19.6<small>%</small> | 81.0<small>%</small> |
| [TSLS](/tsls/) | -1<small>x</small> | <span style="color: cornflowerblue">-67.6<small>%</small></span> | 39.7<small>%</small> | -8.5<small>%</small> | 34.6<small>%</small> |