| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | | <span style="color: tomato">51.8<small>%</small></span> | - | - | - |
| [TSLT](/tslt/) | 2<small>x</small> | <span style="color: tomato">38.4<small>%</small></span> | 30.0<small>%</small> | 14.1<small>%</small> | 39.8<small>%</small> |
| [TSLL](/tsll/) | 2<small>x</small> | <span style="color: tomato">382.3<small>%</small></span><sup><small>8개월</small></sup> | 25.2<small>%</small> | 7.6<small>%</small> | 30.8<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>x</small> | <span style="color: tomato">0.0<small>%</small></span> | 65.9<small>%</small> | 15.7<small>%</small> | 71.3<small>%</small> |
| [TSLS](/tsls/) | -1<small>x</small> | <span style="color: cornflowerblue">-51.4<small>%</small></span> | 31.6<small>%</small> | -7.8<small>%</small> | 26.2<small>%</small> |