| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-39.9<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-62.0<small>%</small></span> | 17.3<small>%</small> | 1.4<small>%</small> | 18.4<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-82.0<small>%</small></span> | 39.4<small>%</small> | 17.8<small>%</small> | 50.2<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: tomato">9.1<small>%</small></span> | 19.4<small>%</small> | -4.9<small>%</small> | 15.5<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: cornflowerblue">-13.5<small>%</small></span> | 46.0<small>%</small> | 3.8<small>%</small> | 48.1<small>%</small> |