| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-26.6<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-50.7<small>%</small></span> | 19.5<small>%</small> | 2.6<small>%</small> | 21.6<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-74.0<small>%</small></span> | 44.2<small>%</small> | 13.6<small>%</small> | 51.8<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: cornflowerblue">-4.7<small>%</small></span> | 19.8<small>%</small> | -1.8<small>%</small> | 18.3<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: cornflowerblue">-30.7<small>%</small></span> | 45.0<small>%</small> | 7.5<small>%</small> | 49.1<small>%</small> |