| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-48.8<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-68.4<small>%</small></span> | 11.0<small>%</small> | 3.3<small>%</small> | 13.9<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-82.6<small>%</small></span> | 26.7<small>%</small> | 9.6<small>%</small> | 33.8<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: tomato">27.1<small>%</small></span> | 11.0<small>%</small> | -2.3<small>%</small> | 9.0<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: tomato">38.5<small>%</small></span> | 26.9<small>%</small> | 2.9<small>%</small> | 29.0<small>%</small> |