| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | | <span style="color: cornflowerblue">-11.5<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>x</small> | <span style="color: cornflowerblue">-50.9<small>%</small></span> | 20.2<small>%</small> | 11.2<small>%</small> | 29.2<small>%</small> |
| [LABD](/labd/) | -3<small>x</small> | <span style="color: tomato">10.3<small>%</small></span> | 35.5<small>%</small> | -18.6<small>%</small> | 23.5<small>%</small> |