| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | | <span style="color: tomato">26.9<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>x</small> | <span style="color: tomato">43.9<small>%</small></span> | 20.8<small>%</small> | 11.0<small>%</small> | 29.5<small>%</small> |
| [LABD](/labd/) | -3<small>x</small> | <span style="color: cornflowerblue">-63.5<small>%</small></span> | 37.0<small>%</small> | -18.3<small>%</small> | 25.4<small>%</small> |