| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | | <span style="color: cornflowerblue">-12.9<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>x</small> | <span style="color: cornflowerblue">-53.8<small>%</small></span> | 20.8<small>%</small> | 11.6<small>%</small> | 30.0<small>%</small> |
| [LABD](/labd/) | -3<small>x</small> | <span style="color: tomato">14.5<small>%</small></span> | 36.4<small>%</small> | -19.0<small>%</small> | 24.3<small>%</small> |