| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | | <span style="color: tomato">28.4<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>x</small> | <span style="color: tomato">43.5<small>%</small></span> | 7.5<small>%</small> | 5.9<small>%</small> | 12.9<small>%</small> |
| [TECL](/tecl/) | 3<small>x</small> | <span style="color: tomato">48.7<small>%</small></span> | 20.8<small>%</small> | 11.2<small>%</small> | 29.7<small>%</small> |
| [REW](/rew/) | -2<small>x</small> | <span style="color: cornflowerblue">-46.5<small>%</small></span> | 21.7<small>%</small> | -12.6<small>%</small> | 11.8<small>%</small> |
| [TECS](/tecs/) | -3<small>x</small> | <span style="color: cornflowerblue">-66.1<small>%</small></span> | 39.5<small>%</small> | -18.8<small>%</small> | 28.2<small>%</small> |