| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | | <span style="color: tomato">23.5<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>x</small> | <span style="color: tomato">33.5<small>%</small></span> | 6.9<small>%</small> | 6.0<small>%</small> | 12.5<small>%</small> |
| [TECL](/tecl/) | 3<small>x</small> | <span style="color: tomato">35.6<small>%</small></span> | 19.2<small>%</small> | 10.9<small>%</small> | 28.0<small>%</small> |
| [REW](/rew/) | -2<small>x</small> | <span style="color: cornflowerblue">-41.2<small>%</small></span> | 20.1<small>%</small> | -12.3<small>%</small> | 10.3<small>%</small> |
| [TECS](/tecs/) | -3<small>x</small> | <span style="color: cornflowerblue">-60.4<small>%</small></span> | 37.0<small>%</small> | -18.6<small>%</small> | 25.3<small>%</small> |