| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | | <span style="color: tomato">24.9<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>x</small> | <span style="color: tomato">36.6<small>%</small></span> | 6.9<small>%</small> | 5.9<small>%</small> | 12.4<small>%</small> |
| [TECL](/tecl/) | 3<small>x</small> | <span style="color: tomato">39.9<small>%</small></span> | 19.3<small>%</small> | 11.0<small>%</small> | 28.2<small>%</small> |
| [REW](/rew/) | -2<small>x</small> | <span style="color: cornflowerblue">-42.6<small>%</small></span> | 20.2<small>%</small> | -12.3<small>%</small> | 10.4<small>%</small> |
| [TECS](/tecs/) | -3<small>x</small> | <span style="color: cornflowerblue">-61.8<small>%</small></span> | 37.2<small>%</small> | -18.5<small>%</small> | 25.6<small>%</small> |