> **KOSPI**<a id="KOSPI"></a>

| 전체 업종 | 전체 종목 |
| :---: | :---: |
| [![KOSPI 전체 업종별 시가총액 비중](images/kospi_all_all_업종.png)](kospi_all_all_업종/) | [![KOSPI 전체 종목별 시가총액 비중](images/kospi_all_all_종목.png)](kospi_all_all_종목/) |
| 전기전자 <small>(61.9%)</small> | 기타금융 <small>(9.7%)</small> |
| [![KOSPI 전기전자 업종 종목별 시가총액 비중](images/kospi_업종_전기전자_종목.png)](kospi_업종_전기전자_종목/) | [![KOSPI 기타금융 업종 종목별 시가총액 비중](images/kospi_업종_기타금융_종목.png)](kospi_업종_기타금융_종목/) |
| 운송장비부품 <small>(6.7%)</small> | 화학 <small>(2.9%)</small> |
| [![KOSPI 운송장비부품 업종 종목별 시가총액 비중](images/kospi_업종_운송장비부품_종목.png)](kospi_업종_운송장비부품_종목/) | [![KOSPI 화학 업종 종목별 시가총액 비중](images/kospi_업종_화학_종목.png)](kospi_업종_화학_종목/) |
| 제약 <small>(2.6%)</small> | 보험 <small>(2.3%)</small> |
| [![KOSPI 제약 업종 종목별 시가총액 비중](images/kospi_업종_제약_종목.png)](kospi_업종_제약_종목/) | [![KOSPI 보험 업종 종목별 시가총액 비중](images/kospi_업종_보험_종목.png)](kospi_업종_보험_종목/) |
| IT서비스 <small>(2.0%)</small> | 유통 <small>(2.0%)</small> |
| [![KOSPI IT서비스 업종 종목별 시가총액 비중](images/kospi_업종_IT서비스_종목.png)](kospi_업종_IT서비스_종목/) | [![KOSPI 유통 업종 종목별 시가총액 비중](images/kospi_업종_유통_종목.png)](kospi_업종_유통_종목/) |
| 기계장비 <small>(1.7%)</small> | 금속 <small>(1.5%)</small> |
| [![KOSPI 기계장비 업종 종목별 시가총액 비중](images/kospi_업종_기계장비_종목.png)](kospi_업종_기계장비_종목/) | [![KOSPI 금속 업종 종목별 시가총액 비중](images/kospi_업종_금속_종목.png)](kospi_업종_금속_종목/) |
| 증권 <small>(1.0%)</small> | 운송창고 <small>(1.0%)</small> |
| [![KOSPI 증권 업종 종목별 시가총액 비중](images/kospi_업종_증권_종목.png)](kospi_업종_증권_종목/) | [![KOSPI 운송창고 업종 종목별 시가총액 비중](images/kospi_업종_운송창고_종목.png)](kospi_업종_운송창고_종목/) |
| 일반서비스 <small>(0.9%)</small> | 음식료담배 <small>(0.9%)</small> |
| [![KOSPI 일반서비스 업종 종목별 시가총액 비중](images/kospi_업종_일반서비스_종목.png)](kospi_업종_일반서비스_종목/) | [![KOSPI 음식료담배 업종 종목별 시가총액 비중](images/kospi_업종_음식료담배_종목.png)](kospi_업종_음식료담배_종목/) |
| 통신 <small>(0.7%)</small> | 건설 <small>(0.6%)</small> |
| [![KOSPI 통신 업종 종목별 시가총액 비중](images/kospi_업종_통신_종목.png)](kospi_업종_통신_종목/) | [![KOSPI 건설 업종 종목별 시가총액 비중](images/kospi_업종_건설_종목.png)](kospi_업종_건설_종목/) |
| 은행 <small>(0.5%)</small> | 전기가스 <small>(0.5%)</small> |
| [![KOSPI 은행 업종 종목별 시가총액 비중](images/kospi_업종_은행_종목.png)](kospi_업종_은행_종목/) | [![KOSPI 전기가스 업종 종목별 시가총액 비중](images/kospi_업종_전기가스_종목.png)](kospi_업종_전기가스_종목/) |
| 오락문화 <small>(0.2%)</small> | 부동산 <small>(0.2%)</small> |
| [![KOSPI 오락문화 업종 종목별 시가총액 비중](images/kospi_업종_오락문화_종목.png)](kospi_업종_오락문화_종목/) | [![KOSPI 부동산 업종 종목별 시가총액 비중](images/kospi_업종_부동산_종목.png)](kospi_업종_부동산_종목/) |
| 섬유의류 <small>(0.1%)</small> | 비금속 <small>(0.1%)</small> |
| [![KOSPI 섬유의류 업종 종목별 시가총액 비중](images/kospi_업종_섬유의류_종목.png)](kospi_업종_섬유의류_종목/) | [![KOSPI 비금속 업종 종목별 시가총액 비중](images/kospi_업종_비금속_종목.png)](kospi_업종_비금속_종목/) |
| 의료정밀기기 <small>(0.1%)</small> | 종이목재 <small>(0.0%)</small> |
| [![KOSPI 의료정밀기기 업종 종목별 시가총액 비중](images/kospi_업종_의료정밀기기_종목.png)](kospi_업종_의료정밀기기_종목/) | [![KOSPI 종이목재 업종 종목별 시가총액 비중](images/kospi_업종_종이목재_종목.png)](kospi_업종_종이목재_종목/) |
| 기타제조 <small>(0.0%)</small> | 농업임업및어업 <small>(0.0%)</small> |
| [![KOSPI 기타제조 업종 종목별 시가총액 비중](images/kospi_업종_기타제조_종목.png)](kospi_업종_기타제조_종목/) | [![KOSPI 농업임업및어업 업종 종목별 시가총액 비중](images/kospi_업종_농업임업및어업_종목.png)](kospi_업종_농업임업및어업_종목/) |


> **KOSDAQ**<a id="KOSDAQ"></a>

| 전체 업종 | 전체 종목 |
| :---: | :---: |
| [![KOSDAQ 전체 업종별 시가총액 비중](images/kosdaq_all_all_업종.png)](kosdaq_all_all_업종/) | [![KOSDAQ 전체 종목별 시가총액 비중](images/kosdaq_all_all_종목.png)](kosdaq_all_all_종목/) |
| 전기전자 <small>(20.0%)</small> | 기계장비 <small>(19.5%)</small> |
| [![KOSDAQ 전기전자 업종 종목별 시가총액 비중](images/kosdaq_업종_전기전자_종목.png)](kosdaq_업종_전기전자_종목/) | [![KOSDAQ 기계장비 업종 종목별 시가총액 비중](images/kosdaq_업종_기계장비_종목.png)](kosdaq_업종_기계장비_종목/) |
| 제약 <small>(13.1%)</small> | 일반서비스 <small>(12.7%)</small> |
| [![KOSDAQ 제약 업종 종목별 시가총액 비중](images/kosdaq_업종_제약_종목.png)](kosdaq_업종_제약_종목/) | [![KOSDAQ 일반서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_일반서비스_종목.png)](kosdaq_업종_일반서비스_종목/) |
| IT서비스 <small>(6.7%)</small> | 화학 <small>(5.3%)</small> |
| [![KOSDAQ IT서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_IT서비스_종목.png)](kosdaq_업종_IT서비스_종목/) | [![KOSDAQ 화학 업종 종목별 시가총액 비중](images/kosdaq_업종_화학_종목.png)](kosdaq_업종_화학_종목/) |
| 금융 <small>(4.5%)</small> | 의료정밀기기 <small>(4.3%)</small> |
| [![KOSDAQ 금융 업종 종목별 시가총액 비중](images/kosdaq_업종_금융_종목.png)](kosdaq_업종_금융_종목/) | [![KOSDAQ 의료정밀기기 업종 종목별 시가총액 비중](images/kosdaq_업종_의료정밀기기_종목.png)](kosdaq_업종_의료정밀기기_종목/) |
| 유통 <small>(3.6%)</small> | 운송장비부품 <small>(2.3%)</small> |
| [![KOSDAQ 유통 업종 종목별 시가총액 비중](images/kosdaq_업종_유통_종목.png)](kosdaq_업종_유통_종목/) | [![KOSDAQ 운송장비부품 업종 종목별 시가총액 비중](images/kosdaq_업종_운송장비부품_종목.png)](kosdaq_업종_운송장비부품_종목/) |
| 금속 <small>(2.0%)</small> | 오락문화 <small>(1.8%)</small> |
| [![KOSDAQ 금속 업종 종목별 시가총액 비중](images/kosdaq_업종_금속_종목.png)](kosdaq_업종_금속_종목/) | [![KOSDAQ 오락문화 업종 종목별 시가총액 비중](images/kosdaq_업종_오락문화_종목.png)](kosdaq_업종_오락문화_종목/) |
| 비금속 <small>(1.1%)</small> | 건설 <small>(1.0%)</small> |
| [![KOSDAQ 비금속 업종 종목별 시가총액 비중](images/kosdaq_업종_비금속_종목.png)](kosdaq_업종_비금속_종목/) | [![KOSDAQ 건설 업종 종목별 시가총액 비중](images/kosdaq_업종_건설_종목.png)](kosdaq_업종_건설_종목/) |
| 음식료담배 <small>(0.9%)</small> | 통신 <small>(0.3%)</small> |
| [![KOSDAQ 음식료담배 업종 종목별 시가총액 비중](images/kosdaq_업종_음식료담배_종목.png)](kosdaq_업종_음식료담배_종목/) | [![KOSDAQ 통신 업종 종목별 시가총액 비중](images/kosdaq_업종_통신_종목.png)](kosdaq_업종_통신_종목/) |
| 종이목재 <small>(0.3%)</small> | 섬유의류 <small>(0.2%)</small> |
| [![KOSDAQ 종이목재 업종 종목별 시가총액 비중](images/kosdaq_업종_종이목재_종목.png)](kosdaq_업종_종이목재_종목/) | [![KOSDAQ 섬유의류 업종 종목별 시가총액 비중](images/kosdaq_업종_섬유의류_종목.png)](kosdaq_업종_섬유의류_종목/) |
| 기타제조 <small>(0.2%)</small> | 운송창고 <small>(0.1%)</small> |
| [![KOSDAQ 기타제조 업종 종목별 시가총액 비중](images/kosdaq_업종_기타제조_종목.png)](kosdaq_업종_기타제조_종목/) | [![KOSDAQ 운송창고 업종 종목별 시가총액 비중](images/kosdaq_업종_운송창고_종목.png)](kosdaq_업종_운송창고_종목/) |
| 전기가스수도 <small>(0.1%)</small> | 농업임업및어업 <small>(0.0%)</small> |
| [![KOSDAQ 전기가스수도 업종 종목별 시가총액 비중](images/kosdaq_업종_전기가스수도_종목.png)](kosdaq_업종_전기가스수도_종목/) | [![KOSDAQ 농업임업및어업 업종 종목별 시가총액 비중](images/kosdaq_업종_농업임업및어업_종목.png)](kosdaq_업종_농업임업및어업_종목/) |
| 부동산 <small>(0.0%)</small> | 출판매체복제 <small>(0.0%)</small> |
| [![KOSDAQ 부동산 업종 종목별 시가총액 비중](images/kosdaq_업종_부동산_종목.png)](kosdaq_업종_부동산_종목/) | [![KOSDAQ 출판매체복제 업종 종목별 시가총액 비중](images/kosdaq_업종_출판매체복제_종목.png)](kosdaq_업종_출판매체복제_종목/) |