<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **5705.5** | <span style="color:cornflowerblue">60.4</span> | - |
| [포스코퓨처엠](/003670/) | P:전기전자 | **3439.2** | 3.8 | 0.1<small>%</small> |
| [이수스페셜티케미컬](/457190/) | P:화학 | **2615.4** | <span style="color:cornflowerblue">15.5</span> | - |
| [우리기술](/032820/) | Q:전기전자 | **2438.0** | <span style="color:cornflowerblue">16.1</span> | - |
| [LS머트리얼즈](/417200/) | Q:전기전자 | **2176.7** | 4.8 | 0.2<small>%</small> |
| [두산테스나](/131970/) | Q:일반서비스 | **1234.6** | 4.2 | 0.2<small>%</small> |
| [로보티즈](/108490/) | Q:기계장비 | **740.3** | <span style="color:cornflowerblue">13.1</span> | - |
| [삼천당제약](/000250/) | Q:제약 | **735.0** | <span style="color:cornflowerblue">14.0</span> | 0.0<small>%</small> |
| [두산에너빌리티](/034020/) | P:기계장비 | **603.8** | 6.6 | - |
| [나노신소재](/121600/) | Q:화학 | **397.8** | 2.6 | 0.5<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | **361.2** | 4.5 | 0.1<small>%</small> |
| [두산](/000150/) | P:전기전자 | **326.5** | <span style="color:cornflowerblue">15.8</span> | 0.3<small>%</small> |
| [주성엔지니어링](/036930/) | Q:기계장비 | **284.2** | <span style="color:cornflowerblue">17.2</span> | 0.0<small>%</small> |
| [후성](/093370/) | P:화학 | **282.4** | 4.5 | - |
| [에코프로비엠](/247540/) | Q:전기전자 | **267.2** | 6.1 | 0.1<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | **243.1** | <span style="color:tomato">0.4</span> | 2.4<small>%</small> |
| [에스피지](/058610/) | Q:전기전자 | **236.2** | 8.4 | 0.3<small>%</small> |
| [신세계](/004170/) | P:유통 | **213.8** | 0.7 | 1.5<small>%</small> |
| [에임드바이오](/0009K0/) | Q:일반서비스 | **199.1** | 7.2 | - |
| [현대무벡스](/319400/) | Q:기계장비 | **198.1** | <span style="color:cornflowerblue">14.0</span> | 0.2<small>%</small> |
| [테크윙](/089030/) | Q:기계장비 | **194.3** | 8.5 | 0.2<small>%</small> |
| [삼성전기](/009150/) | P:전기전자 | **163.5** | <span style="color:cornflowerblue">12.1</span> | 0.1<small>%</small> |
| [삼현](/437730/) | Q:운송장비부품 | **158.0** | <span style="color:cornflowerblue">11.6</span> | 0.1<small>%</small> |
| [LS마린솔루션](/060370/) | Q:건설 | **149.8** | 2.6 | 0.5<small>%</small> |
| [고영](/098460/) | Q:기계장비 | **137.3** | 6.0 | 0.5<small>%</small> |
| [알테오젠](/196170/) | Q:일반서비스 | **124.2** | <span style="color:cornflowerblue">39.9</span> | 0.1<small>%</small> |
| [큐렉소](/060280/) | Q:유통 | **121.3** | 3.5 | - |
| [카카오페이](/377300/) | P:기타금융 | **119.7** | 2.9 | - |
| [효성티앤씨](/298020/) | P:화학 | **114.0** | 0.8 | 3.5<small>%</small> |
| [한미반도체](/042700/) | P:기계장비 | **111.7** | <span style="color:cornflowerblue">34.6</span> | 0.3<small>%</small> |
| [네오셈](/253590/) | Q:기계장비 | **106.4** | 4.8 | 0.8<small>%</small> |
| [LS ELECTRIC](/010120/) | P:전기전자 | **106.3** | <span style="color:cornflowerblue">14.7</span> | 0.3<small>%</small> |
| [기가비스](/420770/) | Q:기계장비 | **105.8** | 7.8 | 0.6<small>%</small> |
| [이오테크닉스](/039030/) | Q:기계장비 | **105.7** | 8.9 | 0.2<small>%</small> |
| [S-Oil](/010950/) | P:화학 | **103.9** | 2.1 | 0.2<small>%</small> |