<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **6157.5** | <span style="color:cornflowerblue">65.2</span> | - |
| [포스코퓨처엠](/003670/) | P:전기전자 | **3664.7** | 4.1 | 0.1<small>%</small> |
| [이수스페셜티케미컬](/457190/) | P:화학 | **3119.2** | <span style="color:cornflowerblue">18.4</span> | - |
| [우리기술](/032820/) | Q:전기전자 | **2540.0** | <span style="color:cornflowerblue">16.8</span> | - |
| [LS머트리얼즈](/417200/) | Q:전기전자 | **2521.7** | 5.5 | 0.1<small>%</small> |
| [두산테스나](/131970/) | Q:일반서비스 | **1370.5** | 4.7 | 0.1<small>%</small> |
| [삼천당제약](/000250/) | Q:제약 | **915.9** | <span style="color:cornflowerblue">17.4</span> | 0.0<small>%</small> |
| [로보티즈](/108490/) | Q:기계장비 | **807.8** | <span style="color:cornflowerblue">14.3</span> | - |
| [두산에너빌리티](/034020/) | P:기계장비 | **614.4** | 6.7 | - |
| [나노신소재](/121600/) | Q:화학 | **437.5** | 2.9 | 0.4<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | **385.9** | 4.8 | 0.1<small>%</small> |
| [후성](/093370/) | P:화학 | **327.8** | 5.3 | - |
| [두산](/000150/) | P:전기전자 | **317.0** | <span style="color:cornflowerblue">15.3</span> | 0.3<small>%</small> |
| [주성엔지니어링](/036930/) | Q:기계장비 | **303.5** | <span style="color:cornflowerblue">18.3</span> | 0.0<small>%</small> |
| [에코프로비엠](/247540/) | Q:전기전자 | **291.4** | 6.7 | 0.1<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | **249.8** | <span style="color:tomato">0.4</span> | 2.3<small>%</small> |
| [에스피지](/058610/) | Q:전기전자 | **249.5** | 8.8 | 0.2<small>%</small> |
| [에임드바이오](/0009K0/) | Q:일반서비스 | **229.6** | 8.3 | - |
| [신세계](/004170/) | P:유통 | **208.8** | 0.7 | 1.6<small>%</small> |
| [테크윙](/089030/) | Q:기계장비 | **208.8** | 9.1 | 0.2<small>%</small> |
| [현대무벡스](/319400/) | Q:기계장비 | **201.9** | <span style="color:cornflowerblue">14.3</span> | 0.2<small>%</small> |
| [삼성전기](/009150/) | P:전기전자 | **169.2** | <span style="color:cornflowerblue">12.5</span> | 0.1<small>%</small> |
| [삼현](/437730/) | Q:운송장비부품 | **168.7** | <span style="color:cornflowerblue">12.4</span> | 0.1<small>%</small> |
| [LS마린솔루션](/060370/) | Q:건설 | **157.7** | 2.8 | 0.5<small>%</small> |
| [고영](/098460/) | Q:기계장비 | **152.2** | 6.7 | 0.4<small>%</small> |
| [큐렉소](/060280/) | Q:유통 | **131.0** | 3.8 | - |
| [알테오젠](/196170/) | Q:일반서비스 | **127.1** | <span style="color:cornflowerblue">40.9</span> | 0.1<small>%</small> |
| [네오셈](/253590/) | Q:기계장비 | **123.7** | 5.5 | 0.6<small>%</small> |
| [한미반도체](/042700/) | P:기계장비 | **120.6** | <span style="color:cornflowerblue">37.4</span> | 0.3<small>%</small> |
| [카카오페이](/377300/) | P:기타금융 | **119.8** | 2.9 | - |
| [이오테크닉스](/039030/) | Q:기계장비 | **113.5** | 9.5 | 0.2<small>%</small> |
| [에코프로머티](/450080/) | P:전기전자 | **110.1** | 2.5 | - |
| [S-Oil](/010950/) | P:화학 | **109.4** | 2.2 | 0.2<small>%</small> |
| [효성티앤씨](/298020/) | P:화학 | **108.7** | 0.8 | 3.7<small>%</small> |
| [LS ELECTRIC](/010120/) | P:전기전자 | **108.6** | <span style="color:cornflowerblue">15.1</span> | 0.3<small>%</small> |