<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **5931.5** | <span style="color:cornflowerblue">62.8</span> | - |
| [포스코퓨처엠](/003670/) | P:전기전자 | **3527.4** | 3.9 | 0.1<small>%</small> |
| [우리기술](/032820/) | Q:전기전자 | **2592.0** | <span style="color:cornflowerblue">17.2</span> | - |
| [이수스페셜티케미컬](/457190/) | P:화학 | **2453.8** | <span style="color:cornflowerblue">14.5</span> | - |
| [LS머트리얼즈](/417200/) | Q:전기전자 | **2230.0** | 4.9 | 0.2<small>%</small> |
| [두산테스나](/131970/) | Q:일반서비스 | **1201.3** | 4.1 | 0.2<small>%</small> |
| [로보티즈](/108490/) | Q:기계장비 | **781.8** | <span style="color:cornflowerblue">13.9</span> | - |
| [삼천당제약](/000250/) | Q:제약 | **733.2** | <span style="color:cornflowerblue">14.0</span> | 0.0<small>%</small> |
| [두산에너빌리티](/034020/) | P:기계장비 | **618.9** | 6.7 | - |
| [나노신소재](/121600/) | Q:화학 | **381.6** | 2.5 | 0.5<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | **360.0** | 4.5 | 0.1<small>%</small> |
| [두산](/000150/) | P:전기전자 | **357.4** | <span style="color:cornflowerblue">17.3</span> | 0.3<small>%</small> |
| [후성](/093370/) | P:화학 | **279.0** | 4.5 | - |
| [주성엔지니어링](/036930/) | Q:기계장비 | **268.2** | <span style="color:cornflowerblue">16.2</span> | 0.0<small>%</small> |
| [에코프로비엠](/247540/) | Q:전기전자 | **264.5** | 6.0 | 0.1<small>%</small> |
| [에스피지](/058610/) | Q:전기전자 | **244.4** | 8.7 | 0.2<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | **240.9** | <span style="color:tomato">0.4</span> | 2.4<small>%</small> |
| [신세계](/004170/) | P:유통 | **218.2** | 0.7 | 1.5<small>%</small> |
| [현대무벡스](/319400/) | Q:기계장비 | **203.4** | <span style="color:cornflowerblue">14.4</span> | 0.2<small>%</small> |
| [에임드바이오](/0009K0/) | Q:일반서비스 | **198.2** | 7.1 | - |
| [테크윙](/089030/) | Q:기계장비 | **186.9** | 8.2 | 0.3<small>%</small> |
| [삼현](/437730/) | Q:운송장비부품 | **169.1** | <span style="color:cornflowerblue">12.4</span> | 0.1<small>%</small> |
| [삼성전기](/009150/) | P:전기전자 | **161.3** | <span style="color:cornflowerblue">11.9</span> | 0.2<small>%</small> |
| [LS마린솔루션](/060370/) | Q:건설 | **156.5** | 2.7 | 0.5<small>%</small> |
| [고영](/098460/) | Q:기계장비 | **130.1** | 5.7 | 0.5<small>%</small> |
| [효성티앤씨](/298020/) | P:화학 | **123.8** | 0.8 | 3.2<small>%</small> |
| [알테오젠](/196170/) | Q:일반서비스 | **122.5** | <span style="color:cornflowerblue">39.4</span> | 0.1<small>%</small> |
| [카카오페이](/377300/) | P:기타금융 | **121.3** | 2.9 | - |
| [큐렉소](/060280/) | Q:유통 | **115.7** | 3.3 | - |
| [네오셈](/253590/) | Q:기계장비 | **108.6** | 4.9 | 0.7<small>%</small> |
| [한미반도체](/042700/) | P:기계장비 | **107.9** | <span style="color:cornflowerblue">33.5</span> | 0.3<small>%</small> |
| [LS ELECTRIC](/010120/) | P:전기전자 | **106.5** | <span style="color:cornflowerblue">14.8</span> | 0.3<small>%</small> |
| [이오테크닉스](/039030/) | Q:기계장비 | **102.7** | 8.6 | 0.2<small>%</small> |
| [S-Oil](/010950/) | P:화학 | **102.4** | 2.0 | 0.2<small>%</small> |
| [에코프로머티](/450080/) | P:전기전자 | **101.3** | 2.3 | - |