<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [한샘](/009240/) | P:유통업 | <span style="color:tomato">5.1</span> | 2.2 | **18.3**<small>%</small> |
| [현대엘리베이](/017800/) | P:기계 | 15.1 | 2.2 | **7.2**<small>%</small> |
| [강원랜드](/035250/) | P:서비스업 | 7.8 | 0.9 | **6.6**<small>%</small> |
| [골프존](/215000/) | Q:출판매체복제 | 7.5 | 0.8 | **6.6**<small>%</small> |
| [SK텔레콤](/017670/) | P:통신업 | 9.4 | 1.0 | **6.5**<small>%</small> |
| [SK네트웍스](/001740/) | P:유통업 | 19.4 | <span style="color:tomato">0.4</span> | **6.5**<small>%</small> |
| [LX인터내셔널](/001120/) | P:유통업 | <span style="color:tomato">6.4</span> | <span style="color:tomato">0.4</span> | **6.4**<small>%</small> |
| [한일시멘트](/300720/) | P:비금속광물 | <span style="color:tomato">6.8</span> | 0.7 | **5.5**<small>%</small> |
| [제일기획](/030000/) | P:서비스업 | 10.8 | 1.5 | **5.5**<small>%</small> |
| [TKG휴켐스](/069260/) | P:화학 | 9.0 | 0.8 | **5.5**<small>%</small> |
| [기아](/000270/) | P:운수장비 | <span style="color:tomato">4.8</span> | 0.8 | **5.5**<small>%</small> |
| [삼성카드](/029780/) | P:기타금융 | 8.5 | 0.7 | **5.3**<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통업 | - | <span style="color:tomato">0.1</span> | **5.3**<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">6.7</span> | 0.5 | **5.1**<small>%</small> |
| [하나투어](/039130/) | P:서비스업 | 8.9 | 4.2 | **4.9**<small>%</small> |
| [DB손해보험](/005830/) | P:보험 | <span style="color:tomato">4.6</span> | 0.9 | **4.8**<small>%</small> |
| [KG이니시스](/035600/) | Q:출판매체복제 | <span style="color:tomato">6.8</span> | 0.6 | **4.8**<small>%</small> |
| [한전KPS](/051600/) | P:건설업 | 13.7 | 1.8 | **4.7**<small>%</small> |
| [KG스틸](/016380/) | P:철강금속 | <span style="color:tomato">4.1</span> | <span style="color:tomato">0.3</span> | **4.6**<small>%</small> |
| [효성티앤씨](/298020/) | P:화학 | 7.1 | 0.7 | **4.5**<small>%</small> |
| [GS](/078930/) | P:기타금융 | 10.1 | <span style="color:tomato">0.4</span> | **4.5**<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | 6.8 | 0.6 | **4.4**<small>%</small> |
| [현대차](/005380/) | P:운수장비 | <span style="color:tomato">5.8</span> | 0.7 | **4.4**<small>%</small> |
| [파트론](/091700/) | Q:일반전기전자 | 6.9 | 0.7 | **4.2**<small>%</small> |
| [NH투자증권](/005940/) | P:증권 | 11.4 | 1.0 | **4.2**<small>%</small> |
| [삼성증권](/016360/) | P:증권 | 8.3 | 1.0 | **4.2**<small>%</small> |
| [LG유플러스](/032640/) | P:통신업 | 17.9 | 0.8 | **4.2**<small>%</small> |
| [한세실업](/105630/) | P:섬유의복 | 8.1 | 0.7 | **4.2**<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | 7.2 | <span style="color:tomato">0.5</span> | **4.2**<small>%</small> |
| [세아베스틸지주](/001430/) | P:철강금속 | 51.1 | 0.5 | **4.2**<small>%</small> |
| [JB금융지주](/175330/) | P:기타금융 | 7.0 | 0.8 | **4.1**<small>%</small> |
| [KT](/030200/) | P:통신업 | 25.9 | 0.8 | **4.0**<small>%</small> |
| [대상](/001680/) | P:음식료품 | 8.1 | 0.5 | **4.0**<small>%</small> |
| [오리온홀딩스](/001800/) | P:기타금융 | 7.6 | 0.5 | **3.9**<small>%</small> |