<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [현대엘리베이터](/017800/) | P:기계장비 | 10.1 | 2.0 | **19.1**<small>%</small> |
| [SOOP](/067160/) | Q:IT서비스 | <span style="color:tomato">4.0</span> | 0.9 | **8.8**<small>%</small> |
| [지역난방공사](/071320/) | P:전기가스 | <span style="color:tomato">2.6</span> | <span style="color:tomato">0.4</span> | **8.4**<small>%</small> |
| [메가스터디교육](/215200/) | Q:일반서비스 | <span style="color:tomato">4.5</span> | 0.8 | **8.2**<small>%</small> |
| [강원랜드](/035250/) | P:오락문화 | 9.2 | 0.7 | **6.6**<small>%</small> |
| [웹젠](/069080/) | Q:IT서비스 | 13.1 | <span style="color:tomato">0.5</span> | **6.5**<small>%</small> |
| [제일기획](/030000/) | P:일반서비스 | 9.3 | 1.2 | **6.4**<small>%</small> |
| [TKG휴켐스](/069260/) | P:화학 | 10.2 | 0.7 | **6.3**<small>%</small> |
| [한일시멘트](/300720/) | P:비금속 | 15.3 | 0.6 | **6.2**<small>%</small> |
| [삼성카드](/029780/) | P:기타금융 | 7.7 | 0.6 | **6.0**<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | - | <span style="color:tomato">0.3</span> | **5.4**<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">6.3</span> | <span style="color:tomato">0.4</span> | **5.2**<small>%</small> |
| [에스엘](/005850/) | P:운송장비부품 | 7.9 | 1.0 | **5.2**<small>%</small> |
| [기아](/000270/) | P:운송장비부품 | <span style="color:tomato">6.8</span> | 0.8 | **5.2**<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">5.7</span> | <span style="color:tomato">0.4</span> | **5.1**<small>%</small> |
| [NH투자증권](/005940/) | P:증권 | 9.0 | 1.0 | **5.0**<small>%</small> |
| [한국전력](/015760/) | P:전기가스 | <span style="color:tomato">2.4</span> | <span style="color:tomato">0.4</span> | **4.9**<small>%</small> |
| [한국금융지주](/071050/) | P:기타금융 | <span style="color:tomato">5.3</span> | 0.9 | **4.7**<small>%</small> |
| [대상](/001680/) | P:음식료담배 | - | 0.6 | **4.7**<small>%</small> |
| [미스토홀딩스](/081660/) | P:유통 | 10.4 | 1.2 | **4.7**<small>%</small> |
| [삼성증권](/016360/) | P:증권 | 7.7 | 1.0 | **4.6**<small>%</small> |
| [한국앤컴퍼니](/000240/) | P:기타금융 | <span style="color:tomato">6.5</span> | <span style="color:tomato">0.5</span> | **4.6**<small>%</small> |
| [KT](/030200/) | P:통신 | <span style="color:tomato">7.4</span> | 0.7 | **4.6**<small>%</small> |
| [하이트진로](/000080/) | P:음식료담배 | 26.0 | 1.0 | **4.5**<small>%</small> |
| [LG유플러스](/032640/) | P:통신 | 12.2 | 0.7 | **4.4**<small>%</small> |
| [동서](/026960/) | P:유통 | 17.9 | 1.5 | **4.3**<small>%</small> |
| [키움증권](/039490/) | P:증권 | <span style="color:tomato">6.0</span> | 1.1 | **4.3**<small>%</small> |
| [오리온홀딩스](/001800/) | P:기타금융 | 12.8 | 0.6 | **4.3**<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | 7.9 | 0.7 | **4.3**<small>%</small> |
| [F&F](/383220/) | P:섬유의류 | <span style="color:tomato">6.0</span> | 1.3 | **4.2**<small>%</small> |
| [DB손해보험](/005830/) | P:보험 | <span style="color:tomato">6.1</span> | 1.0 | **4.2**<small>%</small> |
| [동원시스템즈](/014820/) | P:화학 | 11.7 | 0.7 | **4.2**<small>%</small> |
| [JB금융지주](/175330/) | P:기타금융 | 7.5 | 0.9 | **4.2**<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통 | 52.7 | <span style="color:tomato">0.2</span> | **4.2**<small>%</small> |
| [컴투스](/078340/) | Q:IT서비스 | 9.9 | <span style="color:tomato">0.4</span> | **4.1**<small>%</small> |