<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [이마트](/139480/) | P:유통업 | - | **0.1** | 3.1<small>%</small> |
| [한화생명](/088350/) | P:보험 | <span style="color:tomato">3.0</span> | **0.2** | <span style="color:tomato">5.2<small>%</small></span> |
| [하림지주](/003380/) | Q:금융 | 13.7 | **0.2** | 2.3<small>%</small> |
| [현대제철](/004020/) | P:철강금속 | 7.3 | **0.2** | 3.9<small>%</small> |
| [영풍](/000670/) | P:철강금속 | - | **0.2** | 2.5<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통업 | 11.1 | **0.2** | <span style="color:tomato">5.9<small>%</small></span> |
| [현대백화점](/069960/) | P:유통업 | - | **0.2** | 2.8<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | <span style="color:tomato">3.8</span> | **0.2** | <span style="color:tomato">6.7<small>%</small></span> |
| [DL](/000210/) | P:화학 | - | **0.2** | 2.5<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | - | **0.2** | <span style="color:tomato">6.3<small>%</small></span> |
| [한화](/000880/) | P:화학 | 7.2 | **0.2** | 2.7<small>%</small> |
| [DL이앤씨](/375500/) | P:건설업 | 6.6 | **0.3** | 1.6<small>%</small> |
| [롯데케미칼](/011170/) | P:화학 | - | **0.3** | 3.7<small>%</small> |
| [GS](/078930/) | P:기타금융 | <span style="color:tomato">3.1</span> | **0.3** | <span style="color:tomato">5.9<small>%</small></span> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">5.1</span> | **0.3** | <span style="color:tomato">5.2<small>%</small></span> |
| [현대위아](/011210/) | P:운수장비 | 12.6 | **0.3** | 2.0<small>%</small> |
| [신세계](/004170/) | P:유통업 | 6.4 | **0.3** | 2.7<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | 24.9 | **0.3** | 4.1<small>%</small> |
| [KG스틸](/016380/) | P:철강금속 | <span style="color:tomato">2.9</span> | **0.3** | 3.0<small>%</small> |
| [대한유화](/006650/) | P:화학 | - | **0.4** | 0.9<small>%</small> |
| [GS건설](/006360/) | P:건설업 | - | **0.4** | - |
| [OCI홀딩스](/010060/) | P:기타금융 | <span style="color:tomato">1.9</span> | **0.4** | <span style="color:tomato">4.8<small>%</small></span> |
| [다우데이타](/032190/) | Q:유통 | 6.8 | **0.4** | 2.2<small>%</small> |
| [대우건설](/047040/) | P:건설업 | <span style="color:tomato">3.0</span> | **0.4** | - |
| [KCC](/002380/) | P:화학 | 9.1 | **0.4** | 3.0<small>%</small> |
| [세아베스틸지주](/001430/) | P:철강금속 | <span style="color:tomato">5.6</span> | **0.4** | <span style="color:tomato">6.0<small>%</small></span> |
| [한국가스공사](/036460/) | P:전기가스업 | - | **0.4** | - |
| [세아제강지주](/003030/) | P:기타금융 | <span style="color:tomato">2.3</span> | **0.4** | 1.2<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">4.6</span> | **0.4** | <span style="color:tomato">6.8<small>%</small></span> |
| [성우하이텍](/015750/) | Q:운송장비부품 | <span style="color:tomato">2.9</span> | **0.4** | 2.4<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | <span style="color:tomato">5.0</span> | **0.4** | <span style="color:tomato">6.2<small>%</small></span> |
| [현대해상](/001450/) | P:보험 | <span style="color:tomato">4.0</span> | **0.4** | <span style="color:tomato">6.8<small>%</small></span> |
| [현대건설](/000720/) | P:건설업 | 6.0 | **0.4** | 2.1<small>%</small> |
| [팬오션](/028670/) | P:운수창고업 | 7.6 | **0.4** | 2.4<small>%</small> |