<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [솔브레인홀딩스](/036830/) | Q:일반서비스 | **1.8** | 0.5 | 1.2<small>%</small> |
| [KCC](/002380/) | P:화학 | **2.3** | <span style="color:tomato">0.5</span> | 3.1<small>%</small> |
| [한국전력](/015760/) | P:전기가스 | **2.4** | <span style="color:tomato">0.4</span> | <span style="color:tomato">4.8<small>%</small></span> |
| [지역난방공사](/071320/) | P:전기가스 | **2.7** | <span style="color:tomato">0.4</span> | <span style="color:tomato">8.1<small>%</small></span> |
| [성우하이텍](/015750/) | Q:운송장비부품 | **2.8** | <span style="color:tomato">0.3</span> | 3.4<small>%</small> |
| [다우데이타](/032190/) | Q:유통 | **3.5** | <span style="color:tomato">0.5</span> | 2.8<small>%</small> |
| [현대해상](/001450/) | P:보험 | **3.9** | 0.8 | - |
| [대웅](/003090/) | P:제약 | **3.9** | 0.6 | 1.2<small>%</small> |
| [SOOP](/067160/) | Q:IT서비스 | **4.0** | 0.9 | <span style="color:tomato">8.9<small>%</small></span> |
| [동원산업](/006040/) | P:기타금융 | **4.3** | <span style="color:tomato">0.5</span> | 3.0<small>%</small> |
| [메가스터디교육](/215200/) | Q:일반서비스 | **4.4** | 0.7 | <span style="color:tomato">8.5<small>%</small></span> |
| [우리기술투자](/041190/) | Q:금융 | **4.4** | 0.6 | - |
| [하림지주](/003380/) | Q:금융 | **4.7** | <span style="color:tomato">0.3</span> | 1.1<small>%</small> |
| [에스엠](/041510/) | Q:오락문화 | **5.2** | 1.8 | 2.0<small>%</small> |
| [영원무역홀딩스](/009970/) | P:기타금융 | **5.4** | 0.7 | 3.9<small>%</small> |
| [한국금융지주](/071050/) | P:기타금융 | **5.5** | 0.9 | <span style="color:tomato">4.6<small>%</small></span> |
| [금호타이어](/073240/) | P:화학 | **5.9** | 1.0 | - |
| [키움증권](/039490/) | P:증권 | **6.1** | 1.1 | <span style="color:tomato">4.2<small>%</small></span> |
| [선익시스템](/171090/) | Q:기계장비 | **6.1** | 4.1 | 1.5<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | **6.1** | <span style="color:tomato">0.4</span> | <span style="color:tomato">4.8<small>%</small></span> |
| [F&F](/383220/) | P:섬유의류 | **6.3** | 1.3 | <span style="color:tomato">4.0<small>%</small></span> |
| [CJ대한통운](/000120/) | P:운송창고 | **6.5** | <span style="color:tomato">0.3</span> | 1.1<small>%</small> |
| [영원무역](/111770/) | P:유통 | **6.5** | 0.8 | 2.8<small>%</small> |
| [기업은행](/024110/) | P:은행 | **6.5** | <span style="color:tomato">0.5</span> | <span style="color:tomato">5.1<small>%</small></span> |
| [기아](/000270/) | P:운송장비부품 | **6.5** | 0.8 | <span style="color:tomato">5.4<small>%</small></span> |
| [세아제강지주](/003030/) | P:기타금융 | **6.6** | <span style="color:tomato">0.2</span> | 1.8<small>%</small> |
| [DB손해보험](/005830/) | P:보험 | **6.6** | 1.1 | <span style="color:tomato">3.9<small>%</small></span> |
| [이녹스첨단소재](/272290/) | Q:전기전자 | **6.6** | 1.0 | 1.7<small>%</small> |
| [한국앤컴퍼니](/000240/) | P:기타금융 | **6.7** | 0.5 | <span style="color:tomato">4.5<small>%</small></span> |
| [대웅제약](/069620/) | P:제약 | **6.8** | 1.3 | 0.5<small>%</small> |
| [네오위즈](/095660/) | Q:IT서비스 | **7.1** | 0.7 | 1.7<small>%</small> |
| [브이티](/018290/) | Q:화학 | **7.2** | 1.8 | - |
| [인카금융서비스](/211050/) | Q:금융 | **7.2** | 2.4 | 3.5<small>%</small> |
| [iM금융지주](/139130/) | P:기타금융 | **7.2** | <span style="color:tomato">0.5</span> | 3.9<small>%</small> |
| [코나아이](/052400/) | Q:IT서비스 | **7.3** | 2.1 | 3.2<small>%</small> |