<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [롯데쇼핑](/023530/) | P:유통업 | - | **0.1** | <span style="color:tomato">5.1<small>%</small></span> |
| [한화생명](/088350/) | P:보험 | <span style="color:tomato">3.2</span> | **0.2** | - |
| [DL](/000210/) | P:화학 | 9.8 | **0.2** | 2.6<small>%</small> |
| [이마트](/139480/) | P:유통업 | - | **0.2** | 2.5<small>%</small> |
| [현대제철](/004020/) | P:철강금속 | - | **0.2** | 2.5<small>%</small> |
| [롯데케미칼](/011170/) | P:화학 | - | **0.2** | 2.6<small>%</small> |
| [더블유씨피](/393890/) | Q:일반전기전자 | - | **0.2** | - |
| [KG스틸](/016380/) | P:철강금속 | <span style="color:tomato">4.0</span> | **0.3** | <span style="color:tomato">4.7<small>%</small></span> |
| [하림지주](/003380/) | Q:금융 | 30.0 | **0.3** | 1.5<small>%</small> |
| [세아제강지주](/003030/) | P:기타금융 | 12.8 | **0.3** | 1.3<small>%</small> |
| [영풍](/000670/) | P:철강금속 | - | **0.3** | 0.0<small>%</small> |
| [성우하이텍](/015750/) | Q:운송장비부품 | <span style="color:tomato">3.5</span> | **0.3** | 2.5<small>%</small> |
| [인탑스](/049070/) | Q:일반전기전자 | 9.8 | **0.3** | 1.5<small>%</small> |
| [한국가스공사](/036460/) | P:전기가스업 | <span style="color:tomato">3.1</span> | **0.3** | 3.6<small>%</small> |
| [대우건설](/047040/) | P:건설업 | <span style="color:tomato">6.1</span> | **0.3** | - |
| [코오롱인더](/120110/) | P:화학 | 15.7 | **0.3** | 3.2<small>%</small> |
| [DL이앤씨](/375500/) | P:건설업 | 7.2 | **0.3** | 1.4<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | - | **0.3** | 4.0<small>%</small> |
| [팬오션](/028670/) | P:운수창고업 | 7.5 | **0.3** | 3.2<small>%</small> |
| [컴투스](/078340/) | Q:출판매체복제 | - | **0.4** | <span style="color:tomato">4.2<small>%</small></span> |
| [GS건설](/006360/) | P:건설업 | <span style="color:tomato">6.5</span> | **0.4** | 1.6<small>%</small> |
| [에스디바이오센서](/137310/) | P:의료정밀 | - | **0.4** | 2.2<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | 12.6 | **0.4** | 3.5<small>%</small> |
| [GS](/078930/) | P:기타금융 | 9.9 | **0.4** | <span style="color:tomato">4.5<small>%</small></span> |
| [현대위아](/011210/) | P:운수장비 | 12.2 | **0.4** | 2.0<small>%</small> |
| [LX인터내셔널](/001120/) | P:유통업 | <span style="color:tomato">6.3</span> | **0.4** | <span style="color:tomato">6.5<small>%</small></span> |
| [POSCO홀딩스](/005490/) | P:철강금속 | 21.5 | **0.4** | 3.2<small>%</small> |
| [SK네트웍스](/001740/) | P:유통업 | 18.9 | **0.4** | <span style="color:tomato">6.7<small>%</small></span> |
| [BNK금융지주](/138930/) | P:기타금융 | 6.9 | **0.4** | <span style="color:tomato">4.4<small>%</small></span> |
| [CJ제일제당](/097950/) | P:음식료품 | 23.6 | **0.4** | 2.8<small>%</small> |
| [KG모빌리티](/003620/) | P:운수장비 | 18.5 | **0.5** | - |
| [LG](/003550/) | P:기타금융 | 21.4 | **0.5** | 3.9<small>%</small> |
| [매일유업](/267980/) | Q:음식료담배 | <span style="color:tomato">5.7</span> | **0.5** | 3.5<small>%</small> |
| [동화기업](/025900/) | Q:종이목재 | - | **0.5** | - |