<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [OCI홀딩스](/010060/) | P:기타금융 | **1.7** | <span style="color:tomato">0.3</span> | <span style="color:tomato">5.3<small>%</small></span> |
| [세아제강지주](/003030/) | P:기타금융 | **2.5** | <span style="color:tomato">0.4</span> | 1.2<small>%</small> |
| [영원무역홀딩스](/009970/) | P:기타금융 | **2.6** | 0.4 | 4.7<small>%</small> |
| [성우하이텍](/015750/) | Q:운송장비부품 | **2.6** | <span style="color:tomato">0.3</span> | 2.7<small>%</small> |
| [한화생명](/088350/) | P:보험 | **2.8** | <span style="color:tomato">0.1</span> | <span style="color:tomato">5.6<small>%</small></span> |
| [서부T&D](/006730/) | Q:숙박음식 | **2.8** | 0.5 | 0.8<small>%</small> |
| [KG스틸](/016380/) | P:철강금속 | **2.8** | <span style="color:tomato">0.3</span> | 3.0<small>%</small> |
| [대우건설](/047040/) | P:건설업 | **3.0** | <span style="color:tomato">0.4</span> | - |
| [GS](/078930/) | P:기타금융 | **3.0** | <span style="color:tomato">0.3</span> | <span style="color:tomato">6.0<small>%</small></span> |
| [KG이니시스](/035600/) | Q:출판매체복제 | **3.2** | 0.5 | 4.5<small>%</small> |
| [영원무역](/111770/) | P:유통업 | **3.4** | 0.5 | 3.2<small>%</small> |
| [현대해상](/001450/) | P:보험 | **3.5** | <span style="color:tomato">0.3</span> | <span style="color:tomato">7.6<small>%</small></span> |
| [DB손해보험](/005830/) | P:보험 | **3.6** | 0.6 | <span style="color:tomato">5.1<small>%</small></span> |
| [DGB금융지주](/139130/) | P:기타금융 | **4.0** | <span style="color:tomato">0.2</span> | <span style="color:tomato">6.4<small>%</small></span> |
| [명신산업](/009900/) | P:운수장비 | **4.2** | 1.2 | 0.8<small>%</small> |
| [두산밥캣](/241560/) | P:기계 | **4.2** | 0.7 | 4.1<small>%</small> |
| [에스엘](/005850/) | P:운수장비 | **4.3** | 0.8 | 2.8<small>%</small> |
| [기아](/000270/) | P:운수장비 | **4.4** | 0.8 | <span style="color:tomato">5.8<small>%</small></span> |
| [아난티](/025980/) | Q:숙박음식 | **4.6** | 0.7 | - |
| [F&F](/383220/) | P:섬유의복 | **4.6** | 1.5 | 3.3<small>%</small> |
| [기업은행](/024110/) | P:은행 | **4.7** | <span style="color:tomato">0.4</span> | <span style="color:tomato">6.7<small>%</small></span> |
| [삼성E&A](/028050/) | P:서비스업 | **4.8** | 1.1 | - |
| [현대차](/005380/) | P:운수장비 | **4.9** | 0.6 | <span style="color:tomato">5.1<small>%</small></span> |
| [매일유업](/267980/) | Q:음식료담배 | **4.9** | 0.5 | 3.2<small>%</small> |
| [한세실업](/105630/) | P:섬유의복 | **4.9** | 0.9 | 3.5<small>%</small> |
| [롯데정밀화학](/004000/) | P:화학 | **5.0** | <span style="color:tomato">0.4</span> | <span style="color:tomato">5.7<small>%</small></span> |
| [우리금융지주](/316140/) | P:기타금융 | **5.2** | 0.4 | <span style="color:tomato">6.0<small>%</small></span> |
| [메가스터디교육](/215200/) | Q:기타서비스 | **5.2** | 1.0 | 4.8<small>%</small> |
| [TKG휴켐스](/069260/) | P:화학 | **5.2** | 0.8 | <span style="color:tomato">5.4<small>%</small></span> |
| [덴티움](/145720/) | P:의료정밀 | **5.3** | 1.1 | 0.7<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | **5.3** | <span style="color:tomato">0.3</span> | <span style="color:tomato">5.1<small>%</small></span> |
| [골프존](/215000/) | Q:출판매체복제 | **5.3** | 1.0 | <span style="color:tomato">6.5<small>%</small></span> |
| [하나금융지주](/086790/) | P:기타금융 | **5.5** | 0.5 | <span style="color:tomato">5.5<small>%</small></span> |
| [대웅](/003090/) | P:의약품 | **5.5** | 0.9 | 0.5<small>%</small> |