<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [이마트](/139480/) | P:유통 | 14.8 | **0.2** | 3.3<small>%</small> |
| [태광산업](/003240/) | P:화학 | 9.4 | **0.2** | 0.2<small>%</small> |
| [롯데케미칼](/011170/) | P:화학 | - | **0.2** | 1.8<small>%</small> |
| [현대제철](/004020/) | P:금속 | - | **0.2** | 1.7<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통 | 57.6 | **0.2** | 3.8<small>%</small> |
| [세아제강지주](/003030/) | P:기타금융 | <span style="color:tomato">6.5</span> | **0.2** | 1.8<small>%</small> |
| [영풍](/000670/) | P:금속 | - | **0.2** | 0.0<small>%</small> |
| [CJ ENM](/035760/) | Q:오락문화 | 23.5 | **0.2** | - |
| [아세아](/002030/) | P:일반서비스 | 10.9 | **0.3** | 2.7<small>%</small> |
| [DL](/000210/) | P:화학 | - | **0.3** | - |
| [성우하이텍](/015750/) | Q:운송장비부품 | <span style="color:tomato">2.9</span> | **0.3** | 3.3<small>%</small> |
| [한화생명](/088350/) | P:보험 | 8.1 | **0.3** | - |
| [대한유화](/006650/) | P:화학 | 17.1 | **0.3** | 1.5<small>%</small> |
| [한국가스공사](/036460/) | P:전기가스 | 25.4 | **0.3** | 3.1<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | - | **0.3** | <span style="color:tomato">5.2<small>%</small></span> |
| [에스디바이오센서](/137310/) | P:의료정밀기기 | - | **0.3** | 3.2<small>%</small> |
| [하림지주](/003380/) | Q:금융 | <span style="color:tomato">4.6</span> | **0.3** | 1.1<small>%</small> |
| [CJ대한통운](/000120/) | P:운송창고 | <span style="color:tomato">6.6</span> | **0.4** | 1.1<small>%</small> |
| [지역난방공사](/071320/) | P:전기가스 | <span style="color:tomato">2.6</span> | **0.4** | <span style="color:tomato">8.2<small>%</small></span> |
| [컴투스](/078340/) | Q:IT서비스 | 10.7 | **0.4** | 3.8<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | <span style="color:cornflowerblue">233.8</span> | **0.4** | 2.5<small>%</small> |
| [동화기업](/025900/) | Q:종이목재 | - | **0.4** | - |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">5.9</span> | **0.4** | <span style="color:tomato">4.9<small>%</small></span> |
| [CJ제일제당](/097950/) | P:음식료담배 | - | **0.4** | 3.2<small>%</small> |
| [KCC](/002380/) | P:화학 | <span style="color:tomato">2.3</span> | **0.4** | 3.2<small>%</small> |
| [현대위아](/011210/) | P:운송장비부품 | 16.2 | **0.4** | 2.0<small>%</small> |
| [SK케미칼](/285130/) | P:화학 | 22.6 | **0.5** | 2.2<small>%</small> |
| [POSCO홀딩스](/005490/) | P:금속 | 37.7 | **0.5** | 3.0<small>%</small> |
| [현대백화점](/069960/) | P:유통 | 10.0 | **0.5** | 2.2<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">6.4</span> | **0.5** | <span style="color:tomato">5.2<small>%</small></span> |
| [웹젠](/069080/) | Q:IT서비스 | 13.3 | **0.5** | <span style="color:tomato">6.4<small>%</small></span> |
| [한국전력](/015760/) | P:전기가스 | <span style="color:tomato">2.6</span> | **0.5** | <span style="color:tomato">4.4<small>%</small></span> |
| [iM금융지주](/139130/) | P:기타금융 | <span style="color:tomato">7.0</span> | **0.5** | <span style="color:tomato">4.0<small>%</small></span> |
| [동원산업](/006040/) | P:기타금융 | <span style="color:tomato">4.4</span> | **0.5** | 3.0<small>%</small> |
| [다우데이타](/032190/) | Q:유통 | <span style="color:tomato">3.5</span> | **0.5** | 2.8<small>%</small> |