<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [현대해상](/001450/) | P:보험 | **2.5** | 0.5 | - |
| [한국가스공사](/036460/) | P:전기가스업 | **3.0** | <span style="color:tomato">0.3</span> | 3.7<small>%</small> |
| [한화생명](/088350/) | P:보험 | **3.3** | <span style="color:tomato">0.2</span> | - |
| [효성](/004800/) | P:기타금융 | **3.3** | 0.6 | 3.7<small>%</small> |
| [성우하이텍](/015750/) | Q:운송장비부품 | **3.5** | <span style="color:tomato">0.3</span> | 2.5<small>%</small> |
| [명신산업](/009900/) | P:운수장비 | **3.7** | 0.7 | 1.6<small>%</small> |
| [다우데이타](/032190/) | Q:유통 | **3.8** | 0.5 | 2.8<small>%</small> |
| [KG스틸](/016380/) | P:철강금속 | **4.0** | <span style="color:tomato">0.3</span> | <span style="color:tomato">4.7<small>%</small></span> |
| [기아](/000270/) | P:운수장비 | **4.2** | 0.7 | <span style="color:tomato">6.3<small>%</small></span> |
| [에스엘](/005850/) | P:운수장비 | **4.2** | 0.7 | 3.6<small>%</small> |
| [DB손해보험](/005830/) | P:보험 | **4.3** | 0.8 | <span style="color:tomato">5.2<small>%</small></span> |
| [영원무역홀딩스](/009970/) | P:기타금융 | **4.3** | 0.5 | 4.3<small>%</small> |
| [금호타이어](/073240/) | P:화학 | **4.4** | 0.8 | - |
| [HMM](/011200/) | P:운수창고업 | **4.4** | 0.7 | 2.7<small>%</small> |
| [한국타이어앤테크놀로지](/161390/) | P:화학 | **4.5** | 0.5 | <span style="color:tomato">4.9<small>%</small></span> |
| [한샘](/009240/) | P:유통업 | **4.6** | 2.0 | <span style="color:tomato">20.3<small>%</small></span> |
| [현대차](/005380/) | P:운수장비 | **4.6** | 0.5 | <span style="color:tomato">5.5<small>%</small></span> |
| [엘앤씨바이오](/290650/) | Q:제약 | **4.8** | 2.4 | 0.2<small>%</small> |
| [세방전지](/004490/) | P:전기전자 | **4.8** | 0.6 | 1.8<small>%</small> |
| [SK스퀘어](/402340/) | P:기타금융 | **5.0** | 1.0 | - |
| [위메이드](/112040/) | Q:출판매체복제 | **5.1** | 2.2 | - |
| [우리기술투자](/041190/) | Q:금융 | **5.4** | 1.2 | - |
| [더블유게임즈](/192080/) | P:서비스업 | **5.5** | 0.9 | 2.3<small>%</small> |
| [매일유업](/267980/) | Q:음식료담배 | **5.7** | 0.5 | 3.5<small>%</small> |
| [영원무역](/111770/) | P:유통업 | **5.8** | 0.7 | 2.5<small>%</small> |
| [바텍](/043150/) | Q:의료정밀기기 | **5.8** | 0.7 | 0.5<small>%</small> |
| [LX인터내셔널](/001120/) | P:유통업 | **6.1** | <span style="color:tomato">0.4</span> | <span style="color:tomato">6.7<small>%</small></span> |
| [기업은행](/024110/) | P:은행 | **6.2** | 0.5 | <span style="color:tomato">5.5<small>%</small></span> |
| [파트론](/091700/) | Q:일반전기전자 | **6.2** | 0.6 | <span style="color:tomato">4.7<small>%</small></span> |
| [한국앤컴퍼니](/000240/) | P:기타금융 | **6.2** | 0.5 | <span style="color:tomato">4.3<small>%</small></span> |
| [한세실업](/105630/) | P:섬유의복 | **6.3** | 0.5 | <span style="color:tomato">5.4<small>%</small></span> |
| [우리금융지주](/316140/) | P:기타금융 | **6.3** | 0.6 | <span style="color:tomato">4.8<small>%</small></span> |
| [피엔티](/137400/) | Q:기계장비 | **6.5** | 1.6 | 0.2<small>%</small> |
| [하나금융지주](/086790/) | P:기타금융 | **6.5** | 0.5 | <span style="color:tomato">4.4<small>%</small></span> |