| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-482730/) | <span style="color: tomato">15.5<small>%</small></span> | 17.6<small>%</small> | 0.88 | -16.2<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500타겟데일리커버드콜 | <span style="color: tomato">16.9<small>%</small></span> | 21.2<small>%</small> | 0.80 | -18.9<small>%</small> | -4.0<small>%</small> |