| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-482730/) | <span style="color: tomato">14.9<small>%</small></span> | 17.2<small>%</small> | 0.86 | -16.2<small>%</small> | -3.7<small>%</small> |
| TIGER 미국S&P500타겟데일리커버드콜 | <span style="color: tomato">16.5<small>%</small></span> | 20.7<small>%</small> | 0.80 | -18.9<small>%</small> | -3.8<small>%</small> |