| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-482730/) | <span style="color: tomato">2.7<small>%</small></span> | 19.9<small>%</small> | 0.13 | -16.2<small>%</small> | -5.2<small>%</small> |
| TIGER 미국S&P500타겟데일리커버드콜 | <span style="color: tomato">4.0<small>%</small></span> | 24.1<small>%</small> | 0.17 | -18.9<small>%</small> | -5.3<small>%</small> |