| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-379800/) | <span style="color: tomato">15.9<small>%</small></span> | 17.6<small>%</small> | 0.91 | -16.2<small>%</small> | -3.8<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">18.6<small>%</small></span> | 21.2<small>%</small> | 0.88 | -19.2<small>%</small> | -4.0<small>%</small> |