| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-379800/) | <span style="color: tomato">1.4<small>%</small></span> | 19.8<small>%</small> | 0.07 | -16.2<small>%</small> | -5.0<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">3.8<small>%</small></span> | 24.0<small>%</small> | 0.16 | -19.2<small>%</small> | -5.3<small>%</small> |