| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0005A0](/0005a0-vs-379800/) | <span style="color: tomato">5.9<small>%</small></span> | 18.4<small>%</small> | 0.32 | -16.2<small>%</small> | -4.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">9.2<small>%</small></span> | 22.4<small>%</small> | 0.41 | -19.2<small>%</small> | -4.5<small>%</small> |