| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458730/) | <span style="color: cornflowerblue">-14.0<small>%</small></span> | 20.9<small>%</small> | -0.67 | -13.3<small>%</small> | -7.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: cornflowerblue">-14.2<small>%</small></span> | 21.2<small>%</small> | -0.67 | -13.1<small>%</small> | -7.0<small>%</small> |