| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458760/) | <span style="color: tomato">2.3<small>%</small></span> | 17.3<small>%</small> | 0.13 | -13.3<small>%</small> | -6.4<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: cornflowerblue">-0.2<small>%</small></span> | 17.2<small>%</small> | -0.01 | -13.9<small>%</small> | -7.3<small>%</small> |