| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458730/) | <span style="color: cornflowerblue">-11.3<small>%</small></span> | 20.5<small>%</small> | -0.55 | -13.3<small>%</small> | -7.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: cornflowerblue">-11.5<small>%</small></span> | 20.8<small>%</small> | -0.55 | -13.1<small>%</small> | -7.1<small>%</small> |