| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-483290/) | <span style="color: cornflowerblue">-11.0<small>%</small></span> | 20.6<small>%</small> | -0.54 | -13.3<small>%</small> | -7.2<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: cornflowerblue">-17.0<small>%</small></span> | 20.2<small>%</small> | -0.85 | -14.6<small>%</small> | -8.1<small>%</small> |