| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458760/) | <span style="color: cornflowerblue">-5.2<small>%</small></span> | 19.9<small>%</small> | -0.26 | -13.3<small>%</small> | -7.2<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: cornflowerblue">-9.3<small>%</small></span> | 19.7<small>%</small> | -0.47 | -13.9<small>%</small> | -7.6<small>%</small> |