| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-483290/) | <span style="color: tomato">10.3<small>%</small></span> | 15.4<small>%</small> | 0.67 | -13.3<small>%</small> | -4.3<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: tomato">7.9<small>%</small></span> | 15.7<small>%</small> | 0.50 | -14.7<small>%</small> | -5.5<small>%</small> |