| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-483290/) | <span style="color: cornflowerblue">-12.5<small>%</small></span> | 20.9<small>%</small> | -0.59 | -13.3<small>%</small> | -7.1<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: cornflowerblue">-17.9<small>%</small></span> | 20.5<small>%</small> | -0.88 | -14.6<small>%</small> | -7.9<small>%</small> |