| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458760/) | <span style="color: tomato">11.1<small>%</small></span> | 15.4<small>%</small> | 0.72 | -13.3<small>%</small> | -4.3<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">9.7<small>%</small></span> | 15.5<small>%</small> | 0.62 | -13.9<small>%</small> | -4.8<small>%</small> |