| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458730/) | <span style="color: tomato">1.7<small>%</small></span> | 17.5<small>%</small> | 0.10 | -13.3<small>%</small> | -6.5<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">2.0<small>%</small></span> | 17.8<small>%</small> | 0.11 | -13.1<small>%</small> | -6.3<small>%</small> |