| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458750/) | <span style="color: tomato">11.1<small>%</small></span> | 15.4<small>%</small> | 0.72 | -13.3<small>%</small> | -4.3<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜1호 | <span style="color: tomato">10.7<small>%</small></span> | 15.6<small>%</small> | 0.68 | -13.7<small>%</small> | -4.6<small>%</small> |