| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0008S0](/0008s0-vs-458750/) | <span style="color: cornflowerblue">-1.7<small>%</small></span> | 17.8<small>%</small> | -0.09 | -13.3<small>%</small> | -6.9<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜1호 | <span style="color: cornflowerblue">-3.3<small>%</small></span> | 17.7<small>%</small> | -0.18 | -13.7<small>%</small> | -7.4<small>%</small> |