| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-489030/) | <span style="color: tomato">53.7<small>%</small></span> | 17.2<small>%</small> | 3.11 | -11.5<small>%</small> | -3.9<small>%</small> |
| PLUS 고배당주위클리커버드콜 | <span style="color: tomato">23.1<small>%</small></span> | 15.6<small>%</small> | 1.48 | -18.0<small>%</small> | -4.7<small>%</small> |