| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-489030/) | <span style="color: tomato">52.1<small>%</small></span> | 17.9<small>%</small> | 2.90 | -11.5<small>%</small> | -4.4<small>%</small> |
| PLUS 고배당주위클리커버드콜 | <span style="color: tomato">21.6<small>%</small></span> | 16.6<small>%</small> | 1.30 | -20.6<small>%</small> | -6.7<small>%</small> |