| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-489030/) | <span style="color: tomato">52.5<small>%</small></span> | 17.4<small>%</small> | 3.02 | -11.5<small>%</small> | -3.7<small>%</small> |
| PLUS 고배당주위클리커버드콜 | <span style="color: tomato">26.1<small>%</small></span> | 15.5<small>%</small> | 1.69 | -16.6<small>%</small> | -4.2<small>%</small> |