| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-161510/) | <span style="color: tomato">59.7<small>%</small></span> | 17.5<small>%</small> | 3.41 | -10.9<small>%</small> | -3.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">74.1<small>%</small></span> | 18.7<small>%</small> | 3.96 | -11.4<small>%</small> | -3.3<small>%</small> |