| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-161510/) | <span style="color: tomato">52.2<small>%</small></span> | 18.2<small>%</small> | 2.87 | -11.5<small>%</small> | -4.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">70.0<small>%</small></span> | 19.0<small>%</small> | 3.68 | -11.4<small>%</small> | -3.6<small>%</small> |