| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0018C0](/0018c0-vs-161510/) | <span style="color: tomato">49.6<small>%</small></span> | 17.3<small>%</small> | 2.86 | -11.5<small>%</small> | -4.3<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">69.9<small>%</small></span> | 18.4<small>%</small> | 3.79 | -11.4<small>%</small> | -3.7<small>%</small> |