| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성전자우](/005935-vs-005930/) | <span style="color: tomato">21.3<small>%</small></span> | 33.3<small>%</small> | 0.64 | -48.4<small>%</small> | -17.1<small>%</small> |
| 삼성전자 | <span style="color: tomato">21.6<small>%</small></span> | 33.3<small>%</small> | 0.65 | -45.2<small>%</small> | -16.5<small>%</small> |