| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성전자우](/005935-vs-005930/) | <span style="color: tomato">11.9<small>%</small></span> | 34.0<small>%</small> | 0.35 | -67.0<small>%</small> | -17.7<small>%</small> |
| 삼성전자 | <span style="color: tomato">8.7<small>%</small></span> | 33.2<small>%</small> | 0.26 | -64.8<small>%</small> | -17.8<small>%</small> |