| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성전자우](/005935-vs-005930/) | <span style="color: tomato">11.9<small>%</small></span> | 27.3<small>%</small> | 0.43 | -48.4<small>%</small> | -17.0<small>%</small> |
| 삼성전자 | <span style="color: tomato">10.7<small>%</small></span> | 26.4<small>%</small> | 0.40 | -45.2<small>%</small> | -16.6<small>%</small> |