| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0104N0](/0104n0-vs-102110/) | <span style="color: tomato">123.1<small>%</small></span> | 58.3<small>%</small> | 2.11 | -40.8<small>%</small> | -8.6<small>%</small> |
| TIGER 200 | <span style="color: tomato">131.3<small>%</small></span> | 61.6<small>%</small> | 2.13 | -40.6<small>%</small> | -8.5<small>%</small> |