| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [0104N0](/0104n0-vs-102110/) | <span style="color: tomato">126.6<small>%</small></span> | 57.5<small>%</small> | 2.20 | -40.8<small>%</small> | -9.5<small>%</small> |
| TIGER 200 | <span style="color: tomato">135.3<small>%</small></span> | 60.7<small>%</small> | 2.23 | -40.6<small>%</small> | -9.3<small>%</small> |