| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM KRX100](/100910-vs-292190/) | <span style="color: tomato">17.1<small>%</small></span> | 27.0<small>%</small> | 0.63 | -40.6<small>%</small> | -13.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">16.7<small>%</small></span> | 27.3<small>%</small> | 0.61 | -41.1<small>%</small> | -12.2<small>%</small> |