| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM KRX100](/100910-vs-292190/) | <span style="color: tomato">6.9<small>%</small></span> | 19.2<small>%</small> | 0.36 | -35.6<small>%</small> | -13.7<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">7.6<small>%</small></span> | 19.7<small>%</small> | 0.39 | -36.8<small>%</small> | -12.6<small>%</small> |