| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM KRX100](/100910-vs-292190/) | <span style="color: tomato">16.9<small>%</small></span> | 27.1<small>%</small> | 0.62 | -40.6<small>%</small> | -13.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">16.4<small>%</small></span> | 27.4<small>%</small> | 0.60 | -41.1<small>%</small> | -12.2<small>%</small> |