| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 고배당](/104530-vs-161510/) | <span style="color: tomato">11.4<small>%</small></span> | 17.2<small>%</small> | 0.67 | -49.4<small>%</small> | -8.3<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">9.9<small>%</small></span> | 16.9<small>%</small> | 0.59 | -51.6<small>%</small> | -8.2<small>%</small> |