| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 고배당](/104530-vs-161510/) | <span style="color: tomato">12.4<small>%</small></span> | 19.0<small>%</small> | 0.65 | -49.4<small>%</small> | -9.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.3<small>%</small></span> | 18.6<small>%</small> | 0.61 | -51.6<small>%</small> | -8.6<small>%</small> |