| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 고배당](/104530-vs-161510/) | <span style="color: tomato">8.6<small>%</small></span> | 16.5<small>%</small> | 0.52 | -49.3<small>%</small> | -8.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.7<small>%</small></span> | 16.3<small>%</small> | 0.47 | -51.6<small>%</small> | -8.1<small>%</small> |