| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 코스피50](/122090-vs-069500/) | <span style="color: tomato">4.9<small>%</small></span> | 18.5<small>%</small> | 0.26 | -36.6<small>%</small> | -12.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.8<small>%</small></span> | 17.3<small>%</small> | 0.28 | -38.1<small>%</small> | -11.5<small>%</small> |