| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 코스피50](/122090-vs-069500/) | <span style="color: tomato">9.1<small>%</small></span> | 17.7<small>%</small> | 0.52 | -36.6<small>%</small> | -11.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.6<small>%</small></span> | 16.9<small>%</small> | 0.51 | -38.1<small>%</small> | -10.6<small>%</small> |