| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-379810/) | <span style="color: tomato">20.1<small>%</small></span> | 21.2<small>%</small> | 0.95 | -31.0<small>%</small> | -7.4<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">20.2<small>%</small></span> | 21.1<small>%</small> | 0.96 | -31.0<small>%</small> | -7.4<small>%</small> |