| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-161510/) | <span style="color: tomato">21.9<small>%</small></span> | 19.5<small>%</small> | 1.13 | -31.0<small>%</small> | -4.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">10.6<small>%</small></span> | 16.9<small>%</small> | 0.63 | -51.6<small>%</small> | -8.2<small>%</small> |