| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-379810/) | <span style="color: tomato">20.8<small>%</small></span> | 20.2<small>%</small> | 1.03 | -31.0<small>%</small> | -7.8<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">20.9<small>%</small></span> | 20.1<small>%</small> | 1.04 | -31.0<small>%</small> | -7.8<small>%</small> |