| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-161510/) | <span style="color: tomato">20.2<small>%</small></span> | 18.6<small>%</small> | 1.09 | -31.0<small>%</small> | -4.9<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.7<small>%</small></span> | 16.3<small>%</small> | 0.47 | -51.6<small>%</small> | -8.1<small>%</small> |