| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-379810/) | <span style="color: tomato">18.8<small>%</small></span> | 21.3<small>%</small> | 0.88 | -31.0<small>%</small> | -7.5<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">18.9<small>%</small></span> | 21.2<small>%</small> | 0.89 | -31.0<small>%</small> | -7.5<small>%</small> |