| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">11.9<small>%</small></span> | 18.1<small>%</small> | 0.66 | -25.7<small>%</small> | -6.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.7<small>%</small></span> | 16.1<small>%</small> | 1.16 | -19.1<small>%</small> | -3.8<small>%</small> |