| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">12.4<small>%</small></span> | 17.4<small>%</small> | 0.71 | -25.7<small>%</small> | -5.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.4<small>%</small></span> | 15.6<small>%</small> | 1.17 | -19.2<small>%</small> | -3.5<small>%</small> |