| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">12.3<small>%</small></span> | 17.9<small>%</small> | 0.69 | -25.7<small>%</small> | -6.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.3<small>%</small></span> | 16.0<small>%</small> | 1.21 | -19.1<small>%</small> | -3.7<small>%</small> |