| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 모멘텀](/147970-vs-069500/) | <span style="color: tomato">10.4<small>%</small></span> | 18.3<small>%</small> | 0.57 | -53.8<small>%</small> | -11.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.1<small>%</small></span> | 17.0<small>%</small> | 0.53 | -38.1<small>%</small> | -10.6<small>%</small> |