| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 모멘텀](/147970-vs-069500/) | <span style="color: tomato">13.8<small>%</small></span> | 22.9<small>%</small> | 0.60 | -53.8<small>%</small> | -11.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.3<small>%</small></span> | 23.7<small>%</small> | 0.60 | -40.8<small>%</small> | -11.0<small>%</small> |