| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 모멘텀](/147970-vs-069500/) | <span style="color: tomato">10.0<small>%</small></span> | 18.4<small>%</small> | 0.54 | -53.8<small>%</small> | -11.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.6<small>%</small></span> | 17.1<small>%</small> | 0.50 | -38.1<small>%</small> | -10.6<small>%</small> |