| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주](/161510-vs-069500/) | <span style="color: tomato">9.1<small>%</small></span> | 16.9<small>%</small> | 0.54 | -51.6<small>%</small> | -8.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.6<small>%</small></span> | 16.8<small>%</small> | 0.39 | -38.1<small>%</small> | -10.6<small>%</small> |