| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주](/161510-vs-069500/) | <span style="color: tomato">7.6<small>%</small></span> | 16.3<small>%</small> | 0.46 | -51.6<small>%</small> | -8.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.2<small>%</small></span> | 16.4<small>%</small> | 0.25 | -38.1<small>%</small> | -10.3<small>%</small> |