| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주](/161510-vs-069500/) | <span style="color: tomato">11.9<small>%</small></span> | 18.6<small>%</small> | 0.64 | -51.6<small>%</small> | -8.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.2<small>%</small></span> | 23.7<small>%</small> | 0.60 | -40.8<small>%</small> | -11.0<small>%</small> |