| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜OTM](/166400-vs-069500/) | <span style="color: tomato">2.7<small>%</small></span> | 14.5<small>%</small> | 0.19 | -37.4<small>%</small> | -10.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.5<small>%</small></span> | 16.4<small>%</small> | 0.28 | -38.1<small>%</small> | -10.3<small>%</small> |