| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜OTM](/166400-vs-069500/) | <span style="color: tomato">5.1<small>%</small></span> | 14.8<small>%</small> | 0.35 | -37.4<small>%</small> | -10.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.0<small>%</small></span> | 17.1<small>%</small> | 0.53 | -38.1<small>%</small> | -10.6<small>%</small> |