| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 베타플러스](/170350-vs-069500/) | <span style="color: tomato">9.8<small>%</small></span> | 16.4<small>%</small> | 0.60 | -46.5<small>%</small> | -9.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.0<small>%</small></span> | 16.1<small>%</small> | 0.62 | -38.1<small>%</small> | -7.7<small>%</small> |