| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 베타플러스](/170350-vs-069500/) | <span style="color: tomato">8.4<small>%</small></span> | 16.3<small>%</small> | 0.51 | -46.5<small>%</small> | -10.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.5<small>%</small></span> | 16.1<small>%</small> | 0.53 | -38.1<small>%</small> | -7.9<small>%</small> |