| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 로우볼](/174350-vs-069500/) | <span style="color: tomato">8.2<small>%</small></span> | 15.7<small>%</small> | 0.52 | -49.6<small>%</small> | -8.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.3<small>%</small></span> | 23.7<small>%</small> | 0.60 | -40.8<small>%</small> | -11.0<small>%</small> |