| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 로우볼](/174350-vs-069500/) | <span style="color: tomato">7.5<small>%</small></span> | 14.1<small>%</small> | 0.53 | -49.6<small>%</small> | -8.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.3<small>%</small></span> | 17.1<small>%</small> | 0.55 | -38.1<small>%</small> | -10.6<small>%</small> |