| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 로우볼](/174350-vs-069500/) | <span style="color: tomato">7.1<small>%</small></span> | 14.2<small>%</small> | 0.50 | -49.6<small>%</small> | -8.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.6<small>%</small></span> | 17.2<small>%</small> | 0.50 | -38.1<small>%</small> | -10.7<small>%</small> |