| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [파워 고배당저변동성](/192720-vs-161510/) | <span style="color: tomato">5.9<small>%</small></span> | 15.6<small>%</small> | 0.38 | -49.8<small>%</small> | -7.9<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.2<small>%</small></span> | 17.0<small>%</small> | 0.42 | -51.6<small>%</small> | -8.6<small>%</small> |