| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [파워 고배당저변동성](/192720-vs-161510/) | <span style="color: tomato">10.3<small>%</small></span> | 17.4<small>%</small> | 0.59 | -49.8<small>%</small> | -7.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.3<small>%</small></span> | 18.6<small>%</small> | 0.61 | -51.6<small>%</small> | -8.6<small>%</small> |