| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [파워 고배당저변동성](/192720-vs-161510/) | <span style="color: tomato">8.4<small>%</small></span> | 15.8<small>%</small> | 0.53 | -49.8<small>%</small> | -7.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">9.6<small>%</small></span> | 17.0<small>%</small> | 0.56 | -51.6<small>%</small> | -8.4<small>%</small> |