| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 유로스탁스50(합성 H)](/195930-vs-379790/) | <span style="color: tomato">8.0<small>%</small></span> | 19.1<small>%</small> | 0.42 | -24.2<small>%</small> | -5.7<small>%</small> |
| RISE 유로스탁스50(H) | <span style="color: tomato">9.2<small>%</small></span> | 18.4<small>%</small> | 0.50 | -23.7<small>%</small> | -5.4<small>%</small> |