| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 유로스탁스50(합성 H)](/195930-vs-379790/) | <span style="color: tomato">9.4<small>%</small></span> | 19.4<small>%</small> | 0.48 | -24.2<small>%</small> | -5.4<small>%</small> |
| RISE 유로스탁스50(H) | <span style="color: tomato">10.2<small>%</small></span> | 18.7<small>%</small> | 0.54 | -23.7<small>%</small> | -5.1<small>%</small> |