| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">2.0<small>%</small></span> | 14.8<small>%</small> | 0.14 | -27.3<small>%</small> | -5.5<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">3.2<small>%</small></span> | 14.8<small>%</small> | 0.22 | -26.6<small>%</small> | -5.2<small>%</small> |