| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">22.4<small>%</small></span> | 13.1<small>%</small> | 1.71 | -6.4<small>%</small> | -1.6<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">23.8<small>%</small></span> | 13.8<small>%</small> | 1.73 | -6.3<small>%</small> | -1.6<small>%</small> |