| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">15.2<small>%</small></span> | 14.0<small>%</small> | 1.08 | -12.5<small>%</small> | -3.1<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">16.6<small>%</small></span> | 14.2<small>%</small> | 1.17 | -12.0<small>%</small> | -2.9<small>%</small> |