| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피고배당](/210780-vs-161510/) | <span style="color: tomato">7.3<small>%</small></span> | 15.1<small>%</small> | 0.49 | -48.0<small>%</small> | -9.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">8.2<small>%</small></span> | 17.3<small>%</small> | 0.47 | -51.6<small>%</small> | -8.8<small>%</small> |