| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피고배당](/210780-vs-161510/) | <span style="color: tomato">9.9<small>%</small></span> | 15.3<small>%</small> | 0.65 | -48.0<small>%</small> | -8.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.4<small>%</small></span> | 17.4<small>%</small> | 0.65 | -51.6<small>%</small> | -8.5<small>%</small> |