| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피고배당](/210780-vs-161510/) | <span style="color: tomato">9.2<small>%</small></span> | 15.2<small>%</small> | 0.60 | -48.0<small>%</small> | -8.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">10.4<small>%</small></span> | 17.4<small>%</small> | 0.60 | -51.6<small>%</small> | -8.5<small>%</small> |