| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 배당성장](/211560-vs-069500/) | <span style="color: tomato">9.3<small>%</small></span> | 17.2<small>%</small> | 0.54 | -50.4<small>%</small> | -10.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.3<small>%</small></span> | 17.6<small>%</small> | 0.59 | -38.1<small>%</small> | -11.3<small>%</small> |