| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 배당성장](/211560-vs-069500/) | <span style="color: tomato">6.2<small>%</small></span> | 17.0<small>%</small> | 0.37 | -50.4<small>%</small> | -10.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.0<small>%</small></span> | 17.2<small>%</small> | 0.29 | -38.1<small>%</small> | -11.4<small>%</small> |