| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 가격조정](/217790-vs-069500/) | <span style="color: cornflowerblue">-1.4<small>%</small></span> | 19.4<small>%</small> | -0.07 | -53.0<small>%</small> | -15.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.6<small>%</small></span> | 17.2<small>%</small> | 0.21 | -38.1<small>%</small> | -10.0<small>%</small> |