| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500선물(H)](/219480-vs-143850/) | <span style="color: tomato">11.0<small>%</small></span> | 21.4<small>%</small> | 0.51 | -34.8<small>%</small> | -7.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">10.7<small>%</small></span> | 17.7<small>%</small> | 0.61 | -35.0<small>%</small> | -5.2<small>%</small> |