| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500선물(H)](/219480-vs-143850/) | <span style="color: tomato">10.8<small>%</small></span> | 21.5<small>%</small> | 0.50 | -34.8<small>%</small> | -7.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">10.6<small>%</small></span> | 17.8<small>%</small> | 0.59 | -35.0<small>%</small> | -5.2<small>%</small> |