| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 스마트베타Value](/222180-vs-069500/) | <span style="color: cornflowerblue">-5.1<small>%</small></span> | 19.2<small>%</small> | -0.27 | -58.6<small>%</small> | -12.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.1<small>%</small></span> | 16.4<small>%</small> | 0.19 | -38.1<small>%</small> | -8.1<small>%</small> |