| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 스마트베타Momentum](/222190-vs-069500/) | <span style="color: cornflowerblue">-5.2<small>%</small></span> | 17.1<small>%</small> | -0.30 | -49.4<small>%</small> | -14.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.1<small>%</small></span> | 16.4<small>%</small> | 0.19 | -38.1<small>%</small> | -8.1<small>%</small> |