| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 스마트베타Quality](/222200-vs-069500/) | <span style="color: cornflowerblue">-3.7<small>%</small></span> | 16.5<small>%</small> | -0.23 | -47.8<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.1<small>%</small></span> | 16.4<small>%</small> | 0.19 | -38.1<small>%</small> | -8.1<small>%</small> |