| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500레버리지(합성 H)](/225040-vs-sso/) | <span style="color: tomato">17.8<small>%</small></span> | 35.1<small>%</small> | 0.51 | -58.8<small>%</small> | -11.7<small>%</small> |
| SSO | <span style="color: tomato">21.0<small>%</small></span> | 37.0<small>%</small> | 0.57 | -59.3<small>%</small> | -10.5<small>%</small> |