| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500레버리지(합성 H)](/225040-vs-sso/) | <span style="color: tomato">17.1<small>%</small></span> | 35.4<small>%</small> | 0.48 | -58.8<small>%</small> | -12.0<small>%</small> |
| SSO | <span style="color: tomato">20.1<small>%</small></span> | 37.3<small>%</small> | 0.54 | -59.3<small>%</small> | -10.8<small>%</small> |