| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피](/226490-vs-069500/) | <span style="color: tomato">10.1<small>%</small></span> | 17.0<small>%</small> | 0.60 | -41.3<small>%</small> | -10.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.8<small>%</small></span> | 18.0<small>%</small> | 0.66 | -38.1<small>%</small> | -10.9<small>%</small> |