| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피](/226490-vs-069500/) | <span style="color: tomato">14.7<small>%</small></span> | 22.7<small>%</small> | 0.65 | -41.3<small>%</small> | -10.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.5<small>%</small></span> | 24.7<small>%</small> | 0.71 | -40.8<small>%</small> | -10.8<small>%</small> |