| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피](/226490-vs-069500/) | <span style="color: tomato">8.3<small>%</small></span> | 16.7<small>%</small> | 0.50 | -41.3<small>%</small> | -11.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.6<small>%</small></span> | 17.8<small>%</small> | 0.54 | -38.1<small>%</small> | -11.1<small>%</small> |