| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200 중소형](/226980-vs-069500/) | <span style="color: tomato">7.3<small>%</small></span> | 20.3<small>%</small> | 0.36 | -56.6<small>%</small> | -14.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.5<small>%</small></span> | 18.1<small>%</small> | 0.63 | -38.1<small>%</small> | -10.9<small>%</small> |