| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200 중소형](/226980-vs-069500/) | <span style="color: tomato">3.1<small>%</small></span> | 20.1<small>%</small> | 0.15 | -56.6<small>%</small> | -15.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.8<small>%</small></span> | 17.5<small>%</small> | 0.39 | -38.1<small>%</small> | -11.0<small>%</small> |