| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우량가치](/227570-vs-069500/) | <span style="color: tomato">3.1<small>%</small></span> | 17.2<small>%</small> | 0.18 | -56.3<small>%</small> | -12.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.7<small>%</small></span> | 17.5<small>%</small> | 0.33 | -38.1<small>%</small> | -11.2<small>%</small> |