| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우량가치](/227570-vs-069500/) | <span style="color: tomato">8.8<small>%</small></span> | 19.1<small>%</small> | 0.46 | -56.3<small>%</small> | -11.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.0<small>%</small></span> | 24.8<small>%</small> | 0.69 | -40.8<small>%</small> | -10.9<small>%</small> |