| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우량가치](/227570-vs-069500/) | <span style="color: tomato">6.6<small>%</small></span> | 17.4<small>%</small> | 0.38 | -56.3<small>%</small> | -11.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.6<small>%</small></span> | 18.1<small>%</small> | 0.64 | -38.1<small>%</small> | -11.0<small>%</small> |