| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 스마트베타LowVOL](/236460-vs-069500/) | <span style="color: cornflowerblue">-4.1<small>%</small></span> | 14.9<small>%</small> | -0.28 | -51.2<small>%</small> | -11.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.1<small>%</small></span> | 16.7<small>%</small> | 0.31 | -38.1<small>%</small> | -8.2<small>%</small> |