| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피100](/237350-vs-069500/) | <span style="color: tomato">11.9<small>%</small></span> | 21.5<small>%</small> | 0.55 | -36.7<small>%</small> | -12.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.7<small>%</small></span> | 18.0<small>%</small> | 0.65 | -38.1<small>%</small> | -11.3<small>%</small> |