| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피100](/237350-vs-069500/) | <span style="color: tomato">8.9<small>%</small></span> | 21.5<small>%</small> | 0.41 | -36.7<small>%</small> | -12.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.8<small>%</small></span> | 17.9<small>%</small> | 0.49 | -38.1<small>%</small> | -11.5<small>%</small> |