| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 일본Nikkei225(H)](/238720-vs-1329/) | <span style="color: tomato">15.5<small>%</small></span> | 22.2<small>%</small> | 0.70 | -32.1<small>%</small> | -6.1<small>%</small> |
| 1329.T | <span style="color: tomato">15.7<small>%</small></span> | 21.8<small>%</small> | 0.72 | -31.2<small>%</small> | -5.8<small>%</small> |