| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 일본Nikkei225(H)](/238720-vs-1329/) | <span style="color: tomato">12.5<small>%</small></span> | 21.0<small>%</small> | 0.60 | -32.1<small>%</small> | -6.3<small>%</small> |
| 1329.T | <span style="color: tomato">11.7<small>%</small></span> | 20.8<small>%</small> | 0.56 | -31.6<small>%</small> | -6.4<small>%</small> |