| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 일본Nikkei225(H)](/238720-vs-1329/) | <span style="color: tomato">11.9<small>%</small></span> | 21.1<small>%</small> | 0.57 | -32.1<small>%</small> | -6.4<small>%</small> |
| 1329.T | <span style="color: tomato">11.2<small>%</small></span> | 20.9<small>%</small> | 0.54 | -31.2<small>%</small> | -6.5<small>%</small> |