| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 모멘텀Plus](/244620-vs-069500/) | <span style="color: tomato">7.9<small>%</small></span> | 26.6<small>%</small> | 0.30 | -49.9<small>%</small> | -13.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">18.1<small>%</small></span> | 25.3<small>%</small> | 0.72 | -40.8<small>%</small> | -11.3<small>%</small> |