| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 모멘텀Plus](/244620-vs-069500/) | <span style="color: tomato">2.1<small>%</small></span> | 21.8<small>%</small> | 0.10 | -49.9<small>%</small> | -14.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.8<small>%</small></span> | 17.9<small>%</small> | 0.32 | -38.1<small>%</small> | -11.7<small>%</small> |