| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 모멘텀Plus](/244620-vs-069500/) | <span style="color: tomato">5.4<small>%</small></span> | 21.6<small>%</small> | 0.25 | -49.9<small>%</small> | -13.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.9<small>%</small></span> | 18.2<small>%</small> | 0.65 | -38.1<small>%</small> | -11.5<small>%</small> |