| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 스마트베타4종결합](/244820-vs-069500/) | <span style="color: cornflowerblue">-1.8<small>%</small></span> | 27.2<small>%</small> | -0.06 | -26.6<small>%</small> | -12.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.0<small>%</small></span> | 12.3<small>%</small> | 0.57 | -22.0<small>%</small> | -4.0<small>%</small> |