| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">50.2<small>%</small></span> | 28.0<small>%</small> | 1.80 | -14.8<small>%</small> | -7.1<small>%</small> |
| 2828.HK | <span style="color: tomato">51.8<small>%</small></span> | 31.3<small>%</small> | 1.65 | -14.2<small>%</small> | -7.1<small>%</small> |