| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">40.3<small>%</small></span> | 26.4<small>%</small> | 1.53 | -20.5<small>%</small> | -7.2<small>%</small> |
| 2828.HK | <span style="color: tomato">41.4<small>%</small></span> | 28.9<small>%</small> | 1.43 | -21.0<small>%</small> | -7.2<small>%</small> |