| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">54.7<small>%</small></span> | 27.7<small>%</small> | 1.98 | -14.8<small>%</small> | -7.2<small>%</small> |
| 2828.HK | <span style="color: tomato">54.0<small>%</small></span> | 31.3<small>%</small> | 1.72 | -14.2<small>%</small> | -7.3<small>%</small> |