| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당저변동50](/251590-vs-161510/) | <span style="color: tomato">8.6<small>%</small></span> | 14.0<small>%</small> | 0.61 | -48.8<small>%</small> | -7.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.4<small>%</small></span> | 17.8<small>%</small> | 0.64 | -51.6<small>%</small> | -9.0<small>%</small> |