| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당저변동50](/251590-vs-161510/) | <span style="color: tomato">6.6<small>%</small></span> | 14.1<small>%</small> | 0.47 | -48.8<small>%</small> | -8.1<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">8.4<small>%</small></span> | 17.7<small>%</small> | 0.47 | -51.6<small>%</small> | -9.4<small>%</small> |