| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당저변동50](/251590-vs-161510/) | <span style="color: tomato">7.0<small>%</small></span> | 14.1<small>%</small> | 0.50 | -48.8<small>%</small> | -8.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">8.9<small>%</small></span> | 17.8<small>%</small> | 0.50 | -51.6<small>%</small> | -9.3<small>%</small> |