| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200동일가중](/252650-vs-069500/) | <span style="color: tomato">6.3<small>%</small></span> | 18.1<small>%</small> | 0.35 | -52.2<small>%</small> | -13.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.0<small>%</small></span> | 18.6<small>%</small> | 0.59 | -38.1<small>%</small> | -11.9<small>%</small> |