| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200동일가중](/252650-vs-069500/) | <span style="color: tomato">8.5<small>%</small></span> | 20.4<small>%</small> | 0.42 | -52.2<small>%</small> | -13.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.7<small>%</small></span> | 25.7<small>%</small> | 0.69 | -40.8<small>%</small> | -11.7<small>%</small> |