| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 모멘텀로우볼](/252730-vs-069500/) | <span style="color: tomato">9.2<small>%</small></span> | 17.6<small>%</small> | 0.52 | -40.1<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.6<small>%</small></span> | 17.7<small>%</small> | 0.43 | -38.1<small>%</small> | -12.2<small>%</small> |