| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우선주](/261140-vs-069500/) | <span style="color: tomato">8.5<small>%</small></span> | 18.7<small>%</small> | 0.46 | -40.5<small>%</small> | -15.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.7<small>%</small></span> | 18.4<small>%</small> | 0.47 | -38.1<small>%</small> | -12.5<small>%</small> |