| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국달러선물](/261240-vs-138230/) | <span style="color: tomato">4.6<small>%</small></span> | 12.6<small>%</small> | 0.36 | -19.7<small>%</small> | -7.9<small>%</small> |
| KIWOOM 미국달러선물 | <span style="color: tomato">4.5<small>%</small></span> | 8.3<small>%</small> | 0.53 | -15.6<small>%</small> | -5.4<small>%</small> |