| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국달러선물](/261240-vs-138230/) | <span style="color: tomato">4.4<small>%</small></span> | 12.7<small>%</small> | 0.35 | -19.7<small>%</small> | -8.0<small>%</small> |
| KIWOOM 미국달러선물 | <span style="color: tomato">4.3<small>%</small></span> | 8.4<small>%</small> | 0.51 | -15.6<small>%</small> | -5.4<small>%</small> |