| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국달러선물](/261240-vs-138230/) | <span style="color: tomato">3.5<small>%</small></span> | 12.5<small>%</small> | 0.28 | -19.7<small>%</small> | -7.5<small>%</small> |
| KIWOOM 미국달러선물 | <span style="color: tomato">3.5<small>%</small></span> | 8.6<small>%</small> | 0.40 | -15.6<small>%</small> | -5.2<small>%</small> |