| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-13.7<small>%</small></span> | 15.9<small>%</small> | -0.86 | -51.7<small>%</small> | -30.1<small>%</small> |
| TLT | <span style="color: cornflowerblue">-10.0<small>%</small></span> | 17.1<small>%</small> | -0.58 | -45.5<small>%</small> | -25.4<small>%</small> |