| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-12.1<small>%</small></span> | 15.7<small>%</small> | -0.77 | -52.8<small>%</small> | -33.5<small>%</small> |
| TLT | <span style="color: cornflowerblue">-7.9<small>%</small></span> | 16.6<small>%</small> | -0.48 | -45.5<small>%</small> | -27.6<small>%</small> |