| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-13.5<small>%</small></span> | 15.8<small>%</small> | -0.86 | -52.8<small>%</small> | -33.0<small>%</small> |
| TLT | <span style="color: cornflowerblue">-9.4<small>%</small></span> | 16.7<small>%</small> | -0.56 | -45.5<small>%</small> | -27.3<small>%</small> |