| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 지속배당](/266140-vs-069500/) | <span style="color: cornflowerblue">-2.5<small>%</small></span> | 18.1<small>%</small> | -0.14 | -49.5<small>%</small> | -13.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.1<small>%</small></span> | 19.0<small>%</small> | 0.22 | -38.1<small>%</small> | -10.7<small>%</small> |