| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 고배당](/266160-vs-161510/) | <span style="color: tomato">16.8<small>%</small></span> | 23.1<small>%</small> | 0.73 | -43.4<small>%</small> | -8.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">12.9<small>%</small></span> | 19.8<small>%</small> | 0.65 | -51.6<small>%</small> | -9.5<small>%</small> |