| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 고배당](/266160-vs-161510/) | <span style="color: tomato">11.7<small>%</small></span> | 17.8<small>%</small> | 0.65 | -43.4<small>%</small> | -8.3<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.4<small>%</small></span> | 18.2<small>%</small> | 0.62 | -51.6<small>%</small> | -9.6<small>%</small> |