| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX S&P글로벌인프라(합성)](/269420-vs-269530/) | <span style="color: tomato">8.3<small>%</small></span> | 15.8<small>%</small> | 0.53 | -38.4<small>%</small> | -7.7<small>%</small> |
| PLUS S&P글로벌인프라 | <span style="color: tomato">9.1<small>%</small></span> | 17.6<small>%</small> | 0.51 | -40.0<small>%</small> | -7.3<small>%</small> |