| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX S&P글로벌인프라(합성)](/269420-vs-269530/) | <span style="color: tomato">8.9<small>%</small></span> | 15.7<small>%</small> | 0.57 | -38.4<small>%</small> | -7.2<small>%</small> |
| PLUS S&P글로벌인프라 | <span style="color: tomato">9.3<small>%</small></span> | 17.5<small>%</small> | 0.53 | -40.0<small>%</small> | -6.9<small>%</small> |