| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX S&P글로벌인프라(합성)](/269420-vs-269530/) | <span style="color: tomato">9.6<small>%</small></span> | 15.5<small>%</small> | 0.62 | -38.4<small>%</small> | -6.9<small>%</small> |
| PLUS S&P글로벌인프라 | <span style="color: tomato">10.1<small>%</small></span> | 17.2<small>%</small> | 0.59 | -40.0<small>%</small> | -6.6<small>%</small> |