| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-448290/) | <span style="color: tomato">20.6<small>%</small></span> | 13.6<small>%</small> | 1.51 | -9.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">20.2<small>%</small></span> | 13.7<small>%</small> | 1.48 | -10.1<small>%</small> | -1.9<small>%</small> |