| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-spy/) | <span style="color: tomato">12.5<small>%</small></span> | 18.8<small>%</small> | 0.66 | -35.2<small>%</small> | -5.4<small>%</small> |
| SPY | <span style="color: tomato">14.6<small>%</small></span> | 19.4<small>%</small> | 0.75 | -33.7<small>%</small> | -5.0<small>%</small> |