| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-spy/) | <span style="color: tomato">13.0<small>%</small></span> | 18.7<small>%</small> | 0.69 | -35.2<small>%</small> | -5.2<small>%</small> |
| SPY | <span style="color: tomato">14.8<small>%</small></span> | 19.2<small>%</small> | 0.77 | -33.7<small>%</small> | -4.8<small>%</small> |