| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-143850/) | <span style="color: tomato">13.0<small>%</small></span> | 18.5<small>%</small> | 0.70 | -35.3<small>%</small> | -5.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">11.5<small>%</small></span> | 18.3<small>%</small> | 0.63 | -35.0<small>%</small> | -5.7<small>%</small> |