| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-spy/) | <span style="color: tomato">12.8<small>%</small></span> | 18.7<small>%</small> | 0.69 | -35.2<small>%</small> | -5.3<small>%</small> |
| SPY | <span style="color: tomato">14.9<small>%</small></span> | 19.3<small>%</small> | 0.77 | -33.7<small>%</small> | -4.9<small>%</small> |