| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-143850/) | <span style="color: tomato">12.6<small>%</small></span> | 18.2<small>%</small> | 0.69 | -35.3<small>%</small> | -5.6<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">11.4<small>%</small></span> | 18.0<small>%</small> | 0.63 | -35.0<small>%</small> | -6.1<small>%</small> |