| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-143850/) | <span style="color: tomato">12.4<small>%</small></span> | 18.7<small>%</small> | 0.67 | -35.3<small>%</small> | -5.4<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">11.2<small>%</small></span> | 18.5<small>%</small> | 0.60 | -35.0<small>%</small> | -5.9<small>%</small> |