| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE KQ고배당](/270800-vs-161510/) | <span style="color: tomato">2.3<small>%</small></span> | 22.1<small>%</small> | 0.11 | -48.0<small>%</small> | -17.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">6.6<small>%</small></span> | 18.4<small>%</small> | 0.36 | -51.6<small>%</small> | -10.4<small>%</small> |