| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE KQ고배당](/270800-vs-161510/) | <span style="color: tomato">2.9<small>%</small></span> | 22.0<small>%</small> | 0.13 | -48.0<small>%</small> | -17.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.4<small>%</small></span> | 18.4<small>%</small> | 0.40 | -51.6<small>%</small> | -10.3<small>%</small> |