| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE KQ고배당](/270800-vs-161510/) | <span style="color: tomato">5.6<small>%</small></span> | 21.7<small>%</small> | 0.26 | -48.0<small>%</small> | -18.1<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.2<small>%</small></span> | 18.4<small>%</small> | 0.61 | -51.6<small>%</small> | -9.8<small>%</small> |