| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 스마트모멘텀](/272220-vs-069500/) | <span style="color: tomato">5.1<small>%</small></span> | 18.1<small>%</small> | 0.28 | -37.6<small>%</small> | -13.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.0<small>%</small></span> | 18.3<small>%</small> | 0.27 | -38.1<small>%</small> | -13.3<small>%</small> |