| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">11.4<small>%</small></span> | 21.5<small>%</small> | 0.53 | -43.8<small>%</small> | -14.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.5<small>%</small></span> | 19.2<small>%</small> | 0.49 | -38.1<small>%</small> | -13.0<small>%</small> |