| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">17.9<small>%</small></span> | 28.6<small>%</small> | 0.62 | -44.0<small>%</small> | -14.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">16.4<small>%</small></span> | 26.6<small>%</small> | 0.62 | -40.8<small>%</small> | -12.7<small>%</small> |