| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">18.4<small>%</small></span> | 28.7<small>%</small> | 0.64 | -44.0<small>%</small> | -14.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">16.8<small>%</small></span> | 26.7<small>%</small> | 0.63 | -40.8<small>%</small> | -12.8<small>%</small> |