| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-spy/) | <span style="color: tomato">2.8<small>%</small></span> | 14.3<small>%</small> | 0.20 | -32.5<small>%</small> | -5.7<small>%</small> |
| SPY | <span style="color: tomato">14.7<small>%</small></span> | 19.7<small>%</small> | 0.75 | -33.7<small>%</small> | -5.1<small>%</small> |