| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-spy/) | <span style="color: tomato">2.6<small>%</small></span> | 14.4<small>%</small> | 0.18 | -32.5<small>%</small> | -5.6<small>%</small> |
| SPY | <span style="color: tomato">14.3<small>%</small></span> | 19.8<small>%</small> | 0.72 | -33.7<small>%</small> | -5.1<small>%</small> |