| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-nobl/) | <span style="color: tomato">2.6<small>%</small></span> | 14.2<small>%</small> | 0.19 | -32.5<small>%</small> | -5.9<small>%</small> |
| NOBL | <span style="color: tomato">9.8<small>%</small></span> | 18.1<small>%</small> | 0.54 | -35.4<small>%</small> | -4.3<small>%</small> |