| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-nobl/) | <span style="color: tomato">3.4<small>%</small></span> | 14.0<small>%</small> | 0.24 | -32.6<small>%</small> | -5.9<small>%</small> |
| NOBL | <span style="color: tomato">10.6<small>%</small></span> | 17.7<small>%</small> | 0.60 | -35.4<small>%</small> | -4.2<small>%</small> |