| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-161510/) | <span style="color: tomato">2.6<small>%</small></span> | 14.0<small>%</small> | 0.19 | -32.5<small>%</small> | -5.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">10.3<small>%</small></span> | 18.5<small>%</small> | 0.56 | -51.6<small>%</small> | -9.8<small>%</small> |