| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-spy/) | <span style="color: tomato">3.2<small>%</small></span> | 14.0<small>%</small> | 0.23 | -32.6<small>%</small> | -5.9<small>%</small> |
| SPY | <span style="color: tomato">15.3<small>%</small></span> | 19.1<small>%</small> | 0.80 | -33.7<small>%</small> | -4.7<small>%</small> |