| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피중형주](/277650-vs-226490/) | <span style="color: tomato">5.3<small>%</small></span> | 18.9<small>%</small> | 0.28 | -53.1<small>%</small> | -15.4<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">7.5<small>%</small></span> | 17.9<small>%</small> | 0.42 | -41.3<small>%</small> | -13.3<small>%</small> |