| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피중형주](/277650-vs-226490/) | <span style="color: tomato">1.3<small>%</small></span> | 19.0<small>%</small> | 0.07 | -53.1<small>%</small> | -15.9<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">2.4<small>%</small></span> | 17.8<small>%</small> | 0.13 | -41.3<small>%</small> | -13.7<small>%</small> |