| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피대형주](/277640-vs-069500/) | <span style="color: tomato">8.9<small>%</small></span> | 21.7<small>%</small> | 0.41 | -38.4<small>%</small> | -13.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.3<small>%</small></span> | 19.1<small>%</small> | 0.49 | -38.1<small>%</small> | -13.3<small>%</small> |