| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피대형주](/277640-vs-069500/) | <span style="color: tomato">15.6<small>%</small></span> | 28.0<small>%</small> | 0.56 | -39.7<small>%</small> | -13.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.0<small>%</small></span> | 26.8<small>%</small> | 0.63 | -40.8<small>%</small> | -12.8<small>%</small> |