| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피대형주](/277640-vs-069500/) | <span style="color: tomato">9.8<small>%</small></span> | 21.8<small>%</small> | 0.45 | -38.4<small>%</small> | -13.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.3<small>%</small></span> | 19.2<small>%</small> | 0.54 | -38.1<small>%</small> | -13.2<small>%</small> |