| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피중형주](/277650-vs-226490/) | <span style="color: tomato">6.4<small>%</small></span> | 21.3<small>%</small> | 0.30 | -53.1<small>%</small> | -14.7<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">15.1<small>%</small></span> | 24.6<small>%</small> | 0.62 | -41.3<small>%</small> | -12.9<small>%</small> |