| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 코스닥150선물레버리지](/278240-vs-233740/) | <span style="color: tomato">2.8<small>%</small></span> | 63.0<small>%</small> | 0.04 | -85.9<small>%</small> | -54.7<small>%</small> |
| KODEX 코스닥150레버리지 | <span style="color: tomato">0.7<small>%</small></span> | 56.3<small>%</small> | 0.01 | -86.0<small>%</small> | -57.1<small>%</small> |