| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 코스닥150선물레버리지](/278240-vs-233740/) | <span style="color: cornflowerblue">-0.0<small>%</small></span> | 63.5<small>%</small> | -0.00 | -85.9<small>%</small> | -54.6<small>%</small> |
| KODEX 코스닥150레버리지 | <span style="color: cornflowerblue">-2.1<small>%</small></span> | 56.7<small>%</small> | -0.04 | -86.0<small>%</small> | -56.8<small>%</small> |