| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200TR](/278530-vs-069500/) | <span style="color: tomato">9.7<small>%</small></span> | 19.1<small>%</small> | 0.51 | -38.1<small>%</small> | -13.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.6<small>%</small></span> | 19.3<small>%</small> | 0.50 | -38.1<small>%</small> | -13.5<small>%</small> |