| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200TR](/278530-vs-069500/) | <span style="color: tomato">5.5<small>%</small></span> | 18.9<small>%</small> | 0.29 | -38.1<small>%</small> | -13.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.4<small>%</small></span> | 19.2<small>%</small> | 0.28 | -38.1<small>%</small> | -13.8<small>%</small> |