| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200TR](/278530-vs-069500/) | <span style="color: tomato">9.5<small>%</small></span> | 19.2<small>%</small> | 0.49 | -38.1<small>%</small> | -13.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.4<small>%</small></span> | 19.4<small>%</small> | 0.48 | -38.1<small>%</small> | -13.5<small>%</small> |