| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 최소변동성](/279540-vs-292190/) | <span style="color: tomato">3.0<small>%</small></span> | 16.3<small>%</small> | 0.18 | -35.2<small>%</small> | -9.8<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">3.5<small>%</small></span> | 19.5<small>%</small> | 0.18 | -36.8<small>%</small> | -12.8<small>%</small> |