| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 최소변동성](/279540-vs-292190/) | <span style="color: tomato">11.2<small>%</small></span> | 21.2<small>%</small> | 0.53 | -35.2<small>%</small> | -9.4<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">16.7<small>%</small></span> | 27.3<small>%</small> | 0.61 | -41.1<small>%</small> | -12.2<small>%</small> |