| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 고배당](/279530-vs-161510/) | <span style="color: tomato">9.2<small>%</small></span> | 14.9<small>%</small> | 0.62 | -49.2<small>%</small> | -9.2<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.0<small>%</small></span> | 18.6<small>%</small> | 0.59 | -51.6<small>%</small> | -10.0<small>%</small> |