| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 중소형고배당](/281990-vs-161510/) | <span style="color: tomato">7.2<small>%</small></span> | 18.6<small>%</small> | 0.39 | -52.0<small>%</small> | -12.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">10.2<small>%</small></span> | 18.7<small>%</small> | 0.55 | -51.6<small>%</small> | -10.1<small>%</small> |