| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 중소형고배당](/281990-vs-161510/) | <span style="color: tomato">7.8<small>%</small></span> | 18.7<small>%</small> | 0.42 | -52.0<small>%</small> | -12.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">11.1<small>%</small></span> | 18.7<small>%</small> | 0.60 | -51.6<small>%</small> | -10.0<small>%</small> |