| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-069500/) | <span style="color: tomato">5.8<small>%</small></span> | 7.2<small>%</small> | 0.81 | -16.9<small>%</small> | -4.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.8<small>%</small></span> | 19.3<small>%</small> | 0.46 | -38.1<small>%</small> | -13.6<small>%</small> |