| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-305080/) | <span style="color: tomato">4.1<small>%</small></span> | 7.2<small>%</small> | 0.57 | -17.0<small>%</small> | -4.9<small>%</small> |
| TIGER 미국채10년선물 | <span style="color: tomato">3.3<small>%</small></span> | 9.5<small>%</small> | 0.35 | -17.2<small>%</small> | -8.4<small>%</small> |