| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-305080/) | <span style="color: tomato">7.3<small>%</small></span> | 7.5<small>%</small> | 0.98 | -17.0<small>%</small> | -4.6<small>%</small> |
| TIGER 미국채10년선물 | <span style="color: tomato">4.2<small>%</small></span> | 9.6<small>%</small> | 0.44 | -17.2<small>%</small> | -8.0<small>%</small> |