| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-069500/) | <span style="color: tomato">8.7<small>%</small></span> | 11.2<small>%</small> | 0.78 | -25.2<small>%</small> | -4.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.2<small>%</small></span> | 27.1<small>%</small> | 0.64 | -40.8<small>%</small> | -13.1<small>%</small> |