| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-069500/) | <span style="color: tomato">6.4<small>%</small></span> | 7.3<small>%</small> | 0.88 | -17.0<small>%</small> | -4.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.8<small>%</small></span> | 19.6<small>%</small> | 0.50 | -38.1<small>%</small> | -13.4<small>%</small> |