| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-305080/) | <span style="color: tomato">6.0<small>%</small></span> | 7.3<small>%</small> | 0.82 | -17.0<small>%</small> | -4.6<small>%</small> |
| TIGER 미국채10년선물 | <span style="color: tomato">3.6<small>%</small></span> | 9.6<small>%</small> | 0.38 | -17.2<small>%</small> | -8.1<small>%</small> |