| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜](/289480-vs-069500/) | <span style="color: tomato">8.1<small>%</small></span> | 17.9<small>%</small> | 0.46 | -31.5<small>%</small> | -8.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">18.6<small>%</small></span> | 27.4<small>%</small> | 0.68 | -40.8<small>%</small> | -12.4<small>%</small> |