| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜](/289480-vs-069500/) | <span style="color: tomato">2.4<small>%</small></span> | 14.1<small>%</small> | 0.17 | -31.4<small>%</small> | -9.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.2<small>%</small></span> | 19.3<small>%</small> | 0.37 | -35.6<small>%</small> | -13.1<small>%</small> |