| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜](/289480-vs-069500/) | <span style="color: tomato">2.8<small>%</small></span> | 14.1<small>%</small> | 0.20 | -31.4<small>%</small> | -8.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.9<small>%</small></span> | 19.6<small>%</small> | 0.50 | -35.6<small>%</small> | -12.6<small>%</small> |