| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜](/289480-vs-166400/) | <span style="color: tomato">3.2<small>%</small></span> | 14.0<small>%</small> | 0.23 | -31.4<small>%</small> | -9.0<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">4.3<small>%</small></span> | 16.5<small>%</small> | 0.26 | -35.2<small>%</small> | -13.4<small>%</small> |