| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜](/289480-vs-166400/) | <span style="color: tomato">3.8<small>%</small></span> | 14.1<small>%</small> | 0.27 | -31.4<small>%</small> | -8.8<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">5.0<small>%</small></span> | 16.7<small>%</small> | 0.30 | -35.2<small>%</small> | -13.1<small>%</small> |