| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200고배당커버드콜ATM](/290080-vs-210780/) | <span style="color: tomato">0.8<small>%</small></span> | 15.3<small>%</small> | 0.05 | -45.3<small>%</small> | -13.3<small>%</small> |
| TIGER 코스피고배당 | <span style="color: tomato">5.8<small>%</small></span> | 16.8<small>%</small> | 0.34 | -44.5<small>%</small> | -8.9<small>%</small> |