| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200고배당커버드콜ATM](/290080-vs-210780/) | <span style="color: tomato">3.2<small>%</small></span> | 15.2<small>%</small> | 0.21 | -45.4<small>%</small> | -12.2<small>%</small> |
| TIGER 코스피고배당 | <span style="color: tomato">9.9<small>%</small></span> | 16.8<small>%</small> | 0.59 | -44.5<small>%</small> | -8.4<small>%</small> |