| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200고배당커버드콜ATM](/290080-vs-210780/) | <span style="color: tomato">1.7<small>%</small></span> | 15.2<small>%</small> | 0.11 | -45.3<small>%</small> | -13.3<small>%</small> |
| TIGER 코스피고배당 | <span style="color: tomato">7.0<small>%</small></span> | 16.7<small>%</small> | 0.42 | -44.5<small>%</small> | -8.9<small>%</small> |