| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">6.9<small>%</small></span> | 19.7<small>%</small> | 0.35 | -36.8<small>%</small> | -12.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.2<small>%</small></span> | 19.3<small>%</small> | 0.37 | -35.6<small>%</small> | -13.1<small>%</small> |