| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 대형성장](/292100-vs-069500/) | <span style="color: tomato">10.9<small>%</small></span> | 21.0<small>%</small> | 0.52 | -31.7<small>%</small> | -9.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.6<small>%</small></span> | 20.8<small>%</small> | 0.60 | -35.6<small>%</small> | -9.0<small>%</small> |