| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">9.7<small>%</small></span> | 22.2<small>%</small> | 0.44 | -39.7<small>%</small> | -16.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.2<small>%</small></span> | 19.4<small>%</small> | 0.48 | -35.6<small>%</small> | -12.9<small>%</small> |