| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 중소형성장](/292130-vs-069500/) | <span style="color: tomato">4.6<small>%</small></span> | 24.8<small>%</small> | 0.18 | -48.1<small>%</small> | -16.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.6<small>%</small></span> | 20.8<small>%</small> | 0.60 | -35.6<small>%</small> | -9.0<small>%</small> |