| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">19.1<small>%</small></span> | 29.0<small>%</small> | 0.66 | -40.1<small>%</small> | -15.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.7<small>%</small></span> | 27.5<small>%</small> | 0.64 | -40.8<small>%</small> | -12.5<small>%</small> |