| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">5.9<small>%</small></span> | 22.1<small>%</small> | 0.26 | -39.7<small>%</small> | -16.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.4<small>%</small></span> | 19.4<small>%</small> | 0.33 | -35.6<small>%</small> | -13.2<small>%</small> |