| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 중소형](/292120-vs-069500/) | <span style="color: tomato">4.2<small>%</small></span> | 22.9<small>%</small> | 0.18 | -50.1<small>%</small> | -15.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.1<small>%</small></span> | 20.7<small>%</small> | 0.39 | -35.6<small>%</small> | -9.8<small>%</small> |