| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-292190/) | <span style="color: tomato">6.3<small>%</small></span> | 22.1<small>%</small> | 0.29 | -39.7<small>%</small> | -16.8<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">6.6<small>%</small></span> | 19.7<small>%</small> | 0.33 | -36.8<small>%</small> | -12.9<small>%</small> |