| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">9.2<small>%</small></span> | 20.0<small>%</small> | 0.46 | -36.8<small>%</small> | -12.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.6<small>%</small></span> | 19.7<small>%</small> | 0.49 | -35.6<small>%</small> | -12.8<small>%</small> |