| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">10.2<small>%</small></span> | 20.0<small>%</small> | 0.51 | -36.8<small>%</small> | -12.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.5<small>%</small></span> | 19.7<small>%</small> | 0.54 | -35.6<small>%</small> | -12.7<small>%</small> |