| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 대형가치](/292110-vs-069500/) | <span style="color: tomato">11.1<small>%</small></span> | 21.1<small>%</small> | 0.53 | -40.4<small>%</small> | -9.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.6<small>%</small></span> | 20.8<small>%</small> | 0.60 | -35.6<small>%</small> | -9.0<small>%</small> |