| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-292190/) | <span style="color: tomato">10.9<small>%</small></span> | 22.5<small>%</small> | 0.48 | -39.7<small>%</small> | -16.3<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">9.4<small>%</small></span> | 20.0<small>%</small> | 0.47 | -36.8<small>%</small> | -12.4<small>%</small> |