| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-292190/) | <span style="color: tomato">12.8<small>%</small></span> | 19.9<small>%</small> | 0.64 | -35.1<small>%</small> | -12.7<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">12.7<small>%</small></span> | 20.2<small>%</small> | 0.63 | -34.9<small>%</small> | -11.4<small>%</small> |