| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-069500/) | <span style="color: tomato">11.3<small>%</small></span> | 19.9<small>%</small> | 0.57 | -35.1<small>%</small> | -12.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.7<small>%</small></span> | 19.8<small>%</small> | 0.59 | -34.6<small>%</small> | -11.9<small>%</small> |