| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-069500/) | <span style="color: tomato">12.9<small>%</small></span> | 20.2<small>%</small> | 0.64 | -35.1<small>%</small> | -12.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">13.3<small>%</small></span> | 20.1<small>%</small> | 0.66 | -34.6<small>%</small> | -11.8<small>%</small> |