| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-292190/) | <span style="color: tomato">8.9<small>%</small></span> | 19.8<small>%</small> | 0.45 | -35.1<small>%</small> | -13.0<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">9.4<small>%</small></span> | 20.2<small>%</small> | 0.47 | -34.9<small>%</small> | -11.6<small>%</small> |