| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-292190/) | <span style="color: tomato">5.9<small>%</small></span> | 19.7<small>%</small> | 0.30 | -35.1<small>%</small> | -12.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">6.1<small>%</small></span> | 20.1<small>%</small> | 0.30 | -34.9<small>%</small> | -11.6<small>%</small> |