| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-069500/) | <span style="color: tomato">13.2<small>%</small></span> | 20.0<small>%</small> | 0.66 | -35.1<small>%</small> | -12.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">13.6<small>%</small></span> | 19.9<small>%</small> | 0.68 | -34.6<small>%</small> | -11.9<small>%</small> |