| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-381170/) | <span style="color: tomato">17.6<small>%</small></span> | 29.8<small>%</small> | 0.59 | -49.7<small>%</small> | -13.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">28.0<small>%</small></span> | 25.4<small>%</small> | 1.10 | -40.6<small>%</small> | -9.3<small>%</small> |