| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-472160/) | <span style="color: tomato">41.7<small>%</small></span> | 30.7<small>%</small> | 1.36 | -31.2<small>%</small> | -4.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX(H) | <span style="color: tomato">37.4<small>%</small></span> | 29.5<small>%</small> | 1.27 | -31.8<small>%</small> | -5.4<small>%</small> |