| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-381170/) | <span style="color: tomato">14.3<small>%</small></span> | 29.5<small>%</small> | 0.49 | -49.7<small>%</small> | -16.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">26.2<small>%</small></span> | 24.5<small>%</small> | 1.07 | -40.6<small>%</small> | -9.9<small>%</small> |