| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-381170/) | <span style="color: tomato">17.4<small>%</small></span> | 30.1<small>%</small> | 0.58 | -49.7<small>%</small> | -14.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">25.9<small>%</small></span> | 25.6<small>%</small> | 1.01 | -40.6<small>%</small> | -9.6<small>%</small> |