| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-472160/) | <span style="color: tomato">40.9<small>%</small></span> | 29.6<small>%</small> | 1.38 | -31.2<small>%</small> | -4.3<small>%</small> |
| TIGER 미국테크TOP10 INDXX(H) | <span style="color: tomato">36.9<small>%</small></span> | 28.6<small>%</small> | 1.29 | -31.8<small>%</small> | -5.0<small>%</small> |