| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-069500/) | <span style="color: tomato">18.9<small>%</small></span> | 23.5<small>%</small> | 0.80 | -36.6<small>%</small> | -10.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.8<small>%</small></span> | 19.9<small>%</small> | 0.64 | -34.6<small>%</small> | -12.1<small>%</small> |