| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-292150/) | <span style="color: tomato">19.2<small>%</small></span> | 23.5<small>%</small> | 0.81 | -36.6<small>%</small> | -10.2<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">14.5<small>%</small></span> | 22.7<small>%</small> | 0.64 | -39.7<small>%</small> | -15.9<small>%</small> |