| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-292150/) | <span style="color: tomato">20.8<small>%</small></span> | 23.8<small>%</small> | 0.87 | -36.6<small>%</small> | -10.1<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">16.0<small>%</small></span> | 23.0<small>%</small> | 0.70 | -39.7<small>%</small> | -15.7<small>%</small> |