| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-069500/) | <span style="color: tomato">15.7<small>%</small></span> | 23.4<small>%</small> | 0.67 | -36.6<small>%</small> | -10.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.6<small>%</small></span> | 19.9<small>%</small> | 0.53 | -34.6<small>%</small> | -12.3<small>%</small> |