| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-161510/) | <span style="color: tomato">20.1<small>%</small></span> | 23.9<small>%</small> | 0.84 | -36.6<small>%</small> | -10.1<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">13.9<small>%</small></span> | 19.4<small>%</small> | 0.72 | -47.5<small>%</small> | -7.8<small>%</small> |