| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-161510/) | <span style="color: tomato">11.7<small>%</small></span> | 23.2<small>%</small> | 0.50 | -36.6<small>%</small> | -9.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">9.4<small>%</small></span> | 19.6<small>%</small> | 0.48 | -47.4<small>%</small> | -8.3<small>%</small> |