| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-069500/) | <span style="color: tomato">11.5<small>%</small></span> | 23.2<small>%</small> | 0.49 | -36.6<small>%</small> | -9.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.7<small>%</small></span> | 19.8<small>%</small> | 0.29 | -34.6<small>%</small> | -12.3<small>%</small> |