| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-161510/) | <span style="color: tomato">21.1<small>%</small></span> | 23.7<small>%</small> | 0.89 | -36.6<small>%</small> | -10.2<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">14.1<small>%</small></span> | 19.4<small>%</small> | 0.73 | -47.5<small>%</small> | -7.9<small>%</small> |