| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-292150/) | <span style="color: tomato">13.6<small>%</small></span> | 23.4<small>%</small> | 0.58 | -36.6<small>%</small> | -10.5<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">9.2<small>%</small></span> | 22.6<small>%</small> | 0.41 | -39.7<small>%</small> | -16.2<small>%</small> |