| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KRX300미국달러선물혼합](/319870-vs-138230/) | <span style="color: tomato">13.5<small>%</small></span> | 17.1<small>%</small> | 0.79 | -28.3<small>%</small> | -6.5<small>%</small> |
| KIWOOM 미국달러선물 | <span style="color: tomato">6.0<small>%</small></span> | 8.8<small>%</small> | 0.68 | -15.6<small>%</small> | -5.7<small>%</small> |