| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">10.3<small>%</small></span> | 18.1<small>%</small> | 0.57 | -44.4<small>%</small> | -6.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">9.1<small>%</small></span> | 19.9<small>%</small> | 0.45 | -46.8<small>%</small> | -8.1<small>%</small> |