| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">14.9<small>%</small></span> | 18.0<small>%</small> | 0.83 | -44.4<small>%</small> | -6.2<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">14.4<small>%</small></span> | 19.7<small>%</small> | 0.73 | -46.8<small>%</small> | -7.8<small>%</small> |