| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">9.9<small>%</small></span> | 18.0<small>%</small> | 0.55 | -44.4<small>%</small> | -6.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">8.9<small>%</small></span> | 19.9<small>%</small> | 0.45 | -46.8<small>%</small> | -8.2<small>%</small> |