| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333960](/333960-vs-292190/) | <span style="color: tomato">7.5<small>%</small></span> | 21.3<small>%</small> | 0.35 | -35.0<small>%</small> | -13.5<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.7<small>%</small></span> | 21.0<small>%</small> | 0.42 | -34.9<small>%</small> | -12.4<small>%</small> |