| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333960](/333960-vs-069500/) | <span style="color: tomato">7.5<small>%</small></span> | 21.3<small>%</small> | 0.35 | -35.0<small>%</small> | -13.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.4<small>%</small></span> | 20.6<small>%</small> | 0.41 | -34.6<small>%</small> | -13.0<small>%</small> |