| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333940](/333940-vs-292190/) | <span style="color: tomato">6.1<small>%</small></span> | 18.6<small>%</small> | 0.33 | -37.7<small>%</small> | -10.1<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.7<small>%</small></span> | 21.0<small>%</small> | 0.42 | -34.9<small>%</small> | -12.4<small>%</small> |