| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333970](/333970-vs-292190/) | <span style="color: tomato">8.2<small>%</small></span> | 20.6<small>%</small> | 0.40 | -39.4<small>%</small> | -9.5<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.1<small>%</small></span> | 20.9<small>%</small> | 0.39 | -34.9<small>%</small> | -12.4<small>%</small> |