| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333950](/333950-vs-292190/) | <span style="color: tomato">7.8<small>%</small></span> | 20.9<small>%</small> | 0.37 | -39.7<small>%</small> | -11.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.1<small>%</small></span> | 20.9<small>%</small> | 0.39 | -34.9<small>%</small> | -12.4<small>%</small> |