| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333970](/333970-vs-069500/) | <span style="color: tomato">8.2<small>%</small></span> | 20.6<small>%</small> | 0.40 | -39.4<small>%</small> | -9.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.7<small>%</small></span> | 20.5<small>%</small> | 0.38 | -34.6<small>%</small> | -13.0<small>%</small> |