| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333940](/333940-vs-069500/) | <span style="color: tomato">6.1<small>%</small></span> | 18.6<small>%</small> | 0.33 | -37.7<small>%</small> | -10.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.4<small>%</small></span> | 20.6<small>%</small> | 0.41 | -34.6<small>%</small> | -13.0<small>%</small> |