| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [333950](/333950-vs-069500/) | <span style="color: tomato">7.8<small>%</small></span> | 20.9<small>%</small> | 0.37 | -39.7<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.7<small>%</small></span> | 20.5<small>%</small> | 0.38 | -34.6<small>%</small> | -13.0<small>%</small> |