| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS퀄리티가중TR](/333980-vs-069500/) | <span style="color: tomato">8.1<small>%</small></span> | 19.5<small>%</small> | 0.42 | -32.2<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.1<small>%</small></span> | 20.6<small>%</small> | 0.44 | -34.6<small>%</small> | -12.9<small>%</small> |