| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200exTOP](/337150-vs-069500/) | <span style="color: tomato">14.5<small>%</small></span> | 19.7<small>%</small> | 0.74 | -36.6<small>%</small> | -14.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.6<small>%</small></span> | 20.7<small>%</small> | 0.70 | -34.6<small>%</small> | -13.0<small>%</small> |