| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피대형주](/337140-vs-226490/) | <span style="color: tomato">22.4<small>%</small></span> | 28.5<small>%</small> | 0.79 | -40.4<small>%</small> | -12.0<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">20.8<small>%</small></span> | 27.2<small>%</small> | 0.76 | -38.5<small>%</small> | -12.1<small>%</small> |