| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피대형주](/337140-vs-226490/) | <span style="color: tomato">14.6<small>%</small></span> | 20.0<small>%</small> | 0.73 | -34.6<small>%</small> | -12.4<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">13.8<small>%</small></span> | 19.4<small>%</small> | 0.71 | -35.4<small>%</small> | -12.6<small>%</small> |