| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200exTOP](/337150-vs-069500/) | <span style="color: tomato">10.4<small>%</small></span> | 19.7<small>%</small> | 0.53 | -36.6<small>%</small> | -14.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.1<small>%</small></span> | 20.7<small>%</small> | 0.49 | -34.6<small>%</small> | -13.5<small>%</small> |