| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200exTOP](/337150-vs-069500/) | <span style="color: tomato">13.9<small>%</small></span> | 20.0<small>%</small> | 0.69 | -36.6<small>%</small> | -14.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.2<small>%</small></span> | 21.0<small>%</small> | 0.67 | -34.6<small>%</small> | -12.9<small>%</small> |