| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-329750/) | <span style="color: tomato">2.1<small>%</small></span> | 12.7<small>%</small> | 0.17 | -17.3<small>%</small> | -5.1<small>%</small> |
| TIGER 미국달러단기채권액티브 | <span style="color: tomato">4.5<small>%</small></span> | 8.9<small>%</small> | 0.50 | -14.5<small>%</small> | -4.5<small>%</small> |