| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-332620/) | <span style="color: tomato">0.4<small>%</small></span> | 12.8<small>%</small> | 0.03 | -20.7<small>%</small> | -5.3<small>%</small> |
| PLUS 미국장기우량회사채 | <span style="color: cornflowerblue">-3.0<small>%</small></span> | 12.4<small>%</small> | -0.24 | -31.8<small>%</small> | -16.3<small>%</small> |