| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-329750/) | <span style="color: tomato">3.9<small>%</small></span> | 12.1<small>%</small> | 0.32 | -17.3<small>%</small> | -5.5<small>%</small> |
| TIGER 미국달러단기채권액티브 | <span style="color: tomato">4.7<small>%</small></span> | 8.6<small>%</small> | 0.55 | -14.5<small>%</small> | -5.2<small>%</small> |