| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-332620/) | <span style="color: tomato">3.5<small>%</small></span> | 12.7<small>%</small> | 0.28 | -17.3<small>%</small> | -5.5<small>%</small> |
| PLUS 미국장기우량회사채 | <span style="color: cornflowerblue">-1.2<small>%</small></span> | 12.5<small>%</small> | -0.10 | -31.8<small>%</small> | -17.3<small>%</small> |