| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-332610/) | <span style="color: tomato">1.6<small>%</small></span> | 12.7<small>%</small> | 0.12 | -17.3<small>%</small> | -5.1<small>%</small> |
| PLUS 미국단기회사채(AAA~A) | <span style="color: tomato">3.8<small>%</small></span> | 9.8<small>%</small> | 0.39 | -13.8<small>%</small> | -4.8<small>%</small> |