| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-329750/) | <span style="color: tomato">0.8<small>%</small></span> | 12.8<small>%</small> | 0.06 | -19.0<small>%</small> | -5.3<small>%</small> |
| TIGER 미국달러단기채권액티브 | <span style="color: tomato">4.0<small>%</small></span> | 8.9<small>%</small> | 0.45 | -14.5<small>%</small> | -4.6<small>%</small> |