| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-332610/) | <span style="color: tomato">3.4<small>%</small></span> | 12.7<small>%</small> | 0.27 | -17.3<small>%</small> | -5.5<small>%</small> |
| PLUS 미국단기회사채(AAA~A) | <span style="color: tomato">4.4<small>%</small></span> | 9.7<small>%</small> | 0.45 | -13.8<small>%</small> | -5.1<small>%</small> |