| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국고정배당우선증권 TR](/354240-vs-332610/) | <span style="color: tomato">3.9<small>%</small></span> | 12.2<small>%</small> | 0.32 | -17.3<small>%</small> | -5.4<small>%</small> |
| PLUS 미국단기회사채(AAA~A) | <span style="color: tomato">4.2<small>%</small></span> | 8.6<small>%</small> | 0.49 | -13.8<small>%</small> | -4.9<small>%</small> |