| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-360140/) | <span style="color: cornflowerblue">-17.3<small>%</small></span> | 25.6<small>%</small> | -0.68 | -76.2<small>%</small> | -22.2<small>%</small> |
| KODEX 200롱코스닥150숏선물 | <span style="color: tomato">14.0<small>%</small></span> | 25.7<small>%</small> | 0.54 | -38.1<small>%</small> | -17.5<small>%</small> |