| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-069500/) | <span style="color: cornflowerblue">-6.1<small>%</small></span> | 19.1<small>%</small> | -0.32 | -38.1<small>%</small> | -16.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">15.2<small>%</small></span> | 18.6<small>%</small> | 0.82 | -34.3<small>%</small> | -13.7<small>%</small> |