| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-360140/) | <span style="color: cornflowerblue">-5.8<small>%</small></span> | 19.1<small>%</small> | -0.31 | -37.3<small>%</small> | -16.8<small>%</small> |
| KODEX 200롱코스닥150숏선물 | <span style="color: tomato">3.1<small>%</small></span> | 18.9<small>%</small> | 0.17 | -38.1<small>%</small> | -19.1<small>%</small> |