| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-069500/) | <span style="color: tomato">1.6<small>%</small></span> | 18.9<small>%</small> | 0.08 | -38.1<small>%</small> | -19.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.1<small>%</small></span> | 18.4<small>%</small> | 0.60 | -34.3<small>%</small> | -13.9<small>%</small> |