| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-229200/) | <span style="color: cornflowerblue">-5.7<small>%</small></span> | 19.3<small>%</small> | -0.30 | -39.7<small>%</small> | -17.2<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">3.5<small>%</small></span> | 27.8<small>%</small> | 0.13 | -39.3<small>%</small> | -15.2<small>%</small> |