| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-229200/) | <span style="color: tomato">1.6<small>%</small></span> | 18.9<small>%</small> | 0.08 | -38.1<small>%</small> | -19.2<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">2.3<small>%</small></span> | 27.8<small>%</small> | 0.08 | -39.3<small>%</small> | -15.5<small>%</small> |