| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-069500/) | <span style="color: cornflowerblue">-3.7<small>%</small></span> | 19.3<small>%</small> | -0.19 | -30.2<small>%</small> | -16.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.7<small>%</small></span> | 18.5<small>%</small> | 0.53 | -34.3<small>%</small> | -14.3<small>%</small> |