| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-069500/) | <span style="color: cornflowerblue">-4.9<small>%</small></span> | 19.1<small>%</small> | -0.26 | -33.8<small>%</small> | -16.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.2<small>%</small></span> | 18.4<small>%</small> | 0.66 | -34.3<small>%</small> | -13.9<small>%</small> |