| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-229200/) | <span style="color: tomato">12.8<small>%</small></span> | 25.8<small>%</small> | 0.50 | -38.1<small>%</small> | -17.5<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">3.6<small>%</small></span> | 34.0<small>%</small> | 0.11 | -49.7<small>%</small> | -15.3<small>%</small> |