| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-229200/) | <span style="color: cornflowerblue">-5.0<small>%</small></span> | 19.4<small>%</small> | -0.26 | -39.7<small>%</small> | -17.2<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">4.9<small>%</small></span> | 27.9<small>%</small> | 0.18 | -39.3<small>%</small> | -15.2<small>%</small> |