| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-069500/) | <span style="color: tomato">2.7<small>%</small></span> | 19.1<small>%</small> | 0.14 | -38.1<small>%</small> | -18.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.5<small>%</small></span> | 18.9<small>%</small> | 0.77 | -34.3<small>%</small> | -13.6<small>%</small> |