| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-229200/) | <span style="color: cornflowerblue">-2.6<small>%</small></span> | 19.5<small>%</small> | -0.13 | -38.1<small>%</small> | -18.4<small>%</small> |
| KODEX 코스닥150 | <span style="color: cornflowerblue">-1.3<small>%</small></span> | 28.3<small>%</small> | -0.05 | -39.3<small>%</small> | -14.5<small>%</small> |