| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">18.4<small>%</small></span> | 16.0<small>%</small> | 1.15 | -19.1<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.3<small>%</small></span> | 16.2<small>%</small> | 1.13 | -19.1<small>%</small> | -3.8<small>%</small> |