| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-379800/) | <span style="color: tomato">17.7<small>%</small></span> | 15.9<small>%</small> | 1.11 | -19.1<small>%</small> | -3.7<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">17.8<small>%</small></span> | 16.0<small>%</small> | 1.11 | -19.2<small>%</small> | -3.7<small>%</small> |