| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">18.5<small>%</small></span> | 15.4<small>%</small> | 1.20 | -19.1<small>%</small> | -3.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.4<small>%</small></span> | 15.6<small>%</small> | 1.17 | -19.2<small>%</small> | -3.5<small>%</small> |