| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">20.5<small>%</small></span> | 14.8<small>%</small> | 1.38 | -16.7<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">20.2<small>%</small></span> | 14.9<small>%</small> | 1.36 | -16.7<small>%</small> | -3.7<small>%</small> |