| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-161510/) | <span style="color: tomato">19.6<small>%</small></span> | 14.9<small>%</small> | 1.32 | -16.7<small>%</small> | -3.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">20.1<small>%</small></span> | 16.9<small>%</small> | 1.19 | -18.0<small>%</small> | -4.4<small>%</small> |