| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-379800/) | <span style="color: tomato">19.2<small>%</small></span> | 16.0<small>%</small> | 1.20 | -19.2<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">19.3<small>%</small></span> | 15.9<small>%</small> | 1.21 | -19.2<small>%</small> | -3.6<small>%</small> |