| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-161510/) | <span style="color: tomato">18.7<small>%</small></span> | 16.1<small>%</small> | 1.16 | -19.1<small>%</small> | -3.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">24.1<small>%</small></span> | 17.2<small>%</small> | 1.40 | -18.0<small>%</small> | -4.5<small>%</small> |