| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-161510/) | <span style="color: tomato">20.2<small>%</small></span> | 16.0<small>%</small> | 1.27 | -19.2<small>%</small> | -3.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">24.2<small>%</small></span> | 17.2<small>%</small> | 1.41 | -18.0<small>%</small> | -4.6<small>%</small> |