| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-379800/) | <span style="color: tomato">17.9<small>%</small></span> | 15.7<small>%</small> | 1.14 | -19.2<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">18.0<small>%</small></span> | 15.6<small>%</small> | 1.15 | -19.2<small>%</small> | -3.4<small>%</small> |