| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-379800/) | <span style="color: tomato">19.1<small>%</small></span> | 14.7<small>%</small> | 1.30 | -16.7<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">19.2<small>%</small></span> | 14.6<small>%</small> | 1.32 | -16.7<small>%</small> | -3.6<small>%</small> |