| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-379810/) | <span style="color: tomato">19.3<small>%</small></span> | 20.7<small>%</small> | 0.93 | -30.9<small>%</small> | -6.8<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">19.3<small>%</small></span> | 20.7<small>%</small> | 0.93 | -31.0<small>%</small> | -6.8<small>%</small> |