| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-133690/) | <span style="color: tomato">21.8<small>%</small></span> | 21.4<small>%</small> | 1.02 | -30.9<small>%</small> | -7.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.8<small>%</small></span> | 21.5<small>%</small> | 1.02 | -31.0<small>%</small> | -7.1<small>%</small> |