| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-379810/) | <span style="color: tomato">21.2<small>%</small></span> | 21.1<small>%</small> | 1.01 | -30.9<small>%</small> | -7.1<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">21.3<small>%</small></span> | 21.0<small>%</small> | 1.01 | -31.0<small>%</small> | -7.2<small>%</small> |