| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">21.4<small>%</small></span> | 20.2<small>%</small> | 1.06 | -31.1<small>%</small> | -7.3<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.5<small>%</small></span> | 20.2<small>%</small> | 1.07 | -31.0<small>%</small> | -7.3<small>%</small> |