| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">21.6<small>%</small></span> | 21.1<small>%</small> | 1.02 | -31.0<small>%</small> | -6.9<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.7<small>%</small></span> | 21.1<small>%</small> | 1.03 | -31.0<small>%</small> | -6.9<small>%</small> |