| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-379810/) | <span style="color: tomato">18.1<small>%</small></span> | 20.3<small>%</small> | 0.89 | -31.1<small>%</small> | -8.0<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">18.2<small>%</small></span> | 20.1<small>%</small> | 0.90 | -31.0<small>%</small> | -8.0<small>%</small> |