| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">20.1<small>%</small></span> | 20.3<small>%</small> | 0.99 | -31.1<small>%</small> | -7.4<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">20.2<small>%</small></span> | 20.3<small>%</small> | 1.00 | -31.0<small>%</small> | -7.4<small>%</small> |