| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-379810/) | <span style="color: tomato">21.9<small>%</small></span> | 21.1<small>%</small> | 1.04 | -31.0<small>%</small> | -7.2<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">21.9<small>%</small></span> | 20.9<small>%</small> | 1.05 | -31.0<small>%</small> | -7.2<small>%</small> |