| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">18.7<small>%</small></span> | 16.1<small>%</small> | 1.16 | -19.1<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.9<small>%</small></span> | 16.1<small>%</small> | 1.18 | -19.2<small>%</small> | -3.6<small>%</small> |