| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">18.2<small>%</small></span> | 14.7<small>%</small> | 1.24 | -16.8<small>%</small> | -3.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.3<small>%</small></span> | 14.7<small>%</small> | 1.25 | -16.7<small>%</small> | -3.7<small>%</small> |