| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500](/379780-vs-379800/) | <span style="color: tomato">17.7<small>%</small></span> | 14.7<small>%</small> | 1.21 | -16.8<small>%</small> | -3.7<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">18.1<small>%</small></span> | 14.5<small>%</small> | 1.25 | -16.7<small>%</small> | -3.6<small>%</small> |