| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500](/379780-vs-379800/) | <span style="color: tomato">19.7<small>%</small></span> | 14.7<small>%</small> | 1.34 | -16.8<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">20.0<small>%</small></span> | 14.5<small>%</small> | 1.38 | -16.7<small>%</small> | -3.5<small>%</small> |