| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">19.1<small>%</small></span> | 14.7<small>%</small> | 1.29 | -16.8<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.3<small>%</small></span> | 14.7<small>%</small> | 1.31 | -16.7<small>%</small> | -3.6<small>%</small> |