| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100](/379810-vs-133690/) | <span style="color: tomato">22.0<small>%</small></span> | 21.0<small>%</small> | 1.05 | -31.0<small>%</small> | -7.3<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.9<small>%</small></span> | 21.1<small>%</small> | 1.03 | -31.0<small>%</small> | -7.3<small>%</small> |