| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500TR](/379800-vs-360750/) | <span style="color: tomato">18.5<small>%</small></span> | 14.5<small>%</small> | 1.27 | -16.7<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.3<small>%</small></span> | 14.7<small>%</small> | 1.25 | -16.7<small>%</small> | -3.7<small>%</small> |