| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500](/379800-vs-360750/) | <span style="color: tomato">17.8<small>%</small></span> | 15.6<small>%</small> | 1.15 | -19.2<small>%</small> | -3.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.7<small>%</small></span> | 15.7<small>%</small> | 1.13 | -19.2<small>%</small> | -3.5<small>%</small> |