| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100](/379810-vs-133690/) | <span style="color: tomato">19.5<small>%</small></span> | 21.2<small>%</small> | 0.92 | -31.0<small>%</small> | -7.5<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">19.3<small>%</small></span> | 21.3<small>%</small> | 0.91 | -31.0<small>%</small> | -7.5<small>%</small> |