| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500](/379800-vs-360750/) | <span style="color: tomato">17.8<small>%</small></span> | 16.2<small>%</small> | 1.10 | -19.2<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.7<small>%</small></span> | 16.3<small>%</small> | 1.09 | -19.1<small>%</small> | -3.8<small>%</small> |