| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-226490/) | <span style="color: cornflowerblue">-1.9<small>%</small></span> | 18.5<small>%</small> | -0.10 | -31.0<small>%</small> | -14.3<small>%</small> |
| KODEX 코스피 | <span style="color: cornflowerblue">-3.6<small>%</small></span> | 16.5<small>%</small> | -0.22 | -32.7<small>%</small> | -16.5<small>%</small> |