| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-069500/) | <span style="color: tomato">18.7<small>%</small></span> | 30.8<small>%</small> | 0.61 | -40.5<small>%</small> | -12.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">20.9<small>%</small></span> | 30.8<small>%</small> | 0.68 | -40.8<small>%</small> | -14.7<small>%</small> |