| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-069500/) | <span style="color: tomato">4.9<small>%</small></span> | 19.0<small>%</small> | 0.26 | -31.0<small>%</small> | -13.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.3<small>%</small></span> | 18.2<small>%</small> | 0.24 | -34.3<small>%</small> | -16.1<small>%</small> |