| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-226490/) | <span style="color: tomato">8.0<small>%</small></span> | 19.4<small>%</small> | 0.41 | -31.0<small>%</small> | -12.7<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">7.4<small>%</small></span> | 17.3<small>%</small> | 0.43 | -32.8<small>%</small> | -15.1<small>%</small> |