| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-069500/) | <span style="color: tomato">8.5<small>%</small></span> | 19.7<small>%</small> | 0.43 | -31.0<small>%</small> | -12.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.8<small>%</small></span> | 18.8<small>%</small> | 0.47 | -34.3<small>%</small> | -15.5<small>%</small> |