| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-226490/) | <span style="color: tomato">18.9<small>%</small></span> | 30.8<small>%</small> | 0.62 | -40.5<small>%</small> | -12.3<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">17.7<small>%</small></span> | 27.9<small>%</small> | 0.63 | -38.5<small>%</small> | -14.1<small>%</small> |