| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX Top10동일가중](/395170-vs-292150/) | <span style="color: tomato">2.6<small>%</small></span> | 21.0<small>%</small> | 0.12 | -33.7<small>%</small> | -20.6<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">6.4<small>%</small></span> | 22.1<small>%</small> | 0.29 | -37.9<small>%</small> | -20.4<small>%</small> |