| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX Top10동일가중](/395170-vs-292150/) | <span style="color: tomato">2.9<small>%</small></span> | 21.4<small>%</small> | 0.13 | -33.7<small>%</small> | -20.2<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">7.5<small>%</small></span> | 22.8<small>%</small> | 0.33 | -37.9<small>%</small> | -20.0<small>%</small> |