| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX Top10동일가중](/395170-vs-292150/) | <span style="color: cornflowerblue">-7.3<small>%</small></span> | 21.2<small>%</small> | -0.34 | -33.7<small>%</small> | -20.8<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-8.1<small>%</small></span> | 21.4<small>%</small> | -0.38 | -37.9<small>%</small> | -21.3<small>%</small> |