| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국배당다우존스](/402970-vs-458730/) | <span style="color: tomato">12.0<small>%</small></span> | 14.6<small>%</small> | 0.83 | -13.2<small>%</small> | -3.1<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">11.9<small>%</small></span> | 14.7<small>%</small> | 0.81 | -13.1<small>%</small> | -3.1<small>%</small> |