| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국배당다우존스](/402970-vs-458730/) | <span style="color: tomato">18.6<small>%</small></span> | 13.9<small>%</small> | 1.34 | -13.2<small>%</small> | -2.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">18.5<small>%</small></span> | 13.9<small>%</small> | 1.33 | -13.1<small>%</small> | -2.9<small>%</small> |