| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국배당다우존스](/402970-vs-458730/) | <span style="color: tomato">25.8<small>%</small></span> | 11.6<small>%</small> | 2.22 | -7.8<small>%</small> | -1.7<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">25.7<small>%</small></span> | 11.9<small>%</small> | 2.15 | -7.6<small>%</small> | -1.8<small>%</small> |