| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-226490/) | <span style="color: tomato">13.3<small>%</small></span> | 17.8<small>%</small> | 0.75 | -25.0<small>%</small> | -8.5<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">10.9<small>%</small></span> | 18.0<small>%</small> | 0.60 | -27.4<small>%</small> | -10.4<small>%</small> |