| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-069500/) | <span style="color: tomato">13.1<small>%</small></span> | 17.4<small>%</small> | 0.75 | -25.0<small>%</small> | -8.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.8<small>%</small></span> | 18.8<small>%</small> | 0.68 | -28.4<small>%</small> | -11.2<small>%</small> |