| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-069500/) | <span style="color: tomato">23.7<small>%</small></span> | 28.8<small>%</small> | 0.82 | -37.0<small>%</small> | -8.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">26.0<small>%</small></span> | 31.8<small>%</small> | 0.82 | -40.8<small>%</small> | -11.0<small>%</small> |