| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-226490/) | <span style="color: tomato">7.5<small>%</small></span> | 17.3<small>%</small> | 0.44 | -25.0<small>%</small> | -9.1<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">4.8<small>%</small></span> | 17.5<small>%</small> | 0.28 | -27.4<small>%</small> | -11.1<small>%</small> |