| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-069500/) | <span style="color: tomato">23.3<small>%</small></span> | 28.8<small>%</small> | 0.81 | -37.0<small>%</small> | -8.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">25.4<small>%</small></span> | 31.7<small>%</small> | 0.80 | -40.8<small>%</small> | -10.9<small>%</small> |