| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이다스 코스피액티브](/403790-vs-226490/) | <span style="color: tomato">11.6<small>%</small></span> | 17.3<small>%</small> | 0.67 | -25.0<small>%</small> | -8.7<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">9.4<small>%</small></span> | 17.5<small>%</small> | 0.54 | -27.4<small>%</small> | -10.7<small>%</small> |