| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: tomato">7.4<small>%</small></span> | 49.2<small>%</small> | 0.15 | -63.2<small>%</small> | -30.7<small>%</small> |
| QLD | <span style="color: tomato">8.7<small>%</small></span> | 48.3<small>%</small> | 0.18 | -63.4<small>%</small> | -30.4<small>%</small> |