| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: tomato">5.8<small>%</small></span> | 48.9<small>%</small> | 0.12 | -63.2<small>%</small> | -30.4<small>%</small> |
| QLD | <span style="color: tomato">7.3<small>%</small></span> | 48.1<small>%</small> | 0.15 | -63.4<small>%</small> | -30.0<small>%</small> |