| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: tomato">14.8<small>%</small></span> | 48.3<small>%</small> | 0.31 | -63.2<small>%</small> | -22.2<small>%</small> |
| QLD | <span style="color: tomato">16.2<small>%</small></span> | 47.0<small>%</small> | 0.34 | -63.4<small>%</small> | -22.0<small>%</small> |