| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-395170/) | <span style="color: tomato">5.0<small>%</small></span> | 21.6<small>%</small> | 0.23 | -29.1<small>%</small> | -14.6<small>%</small> |
| KODEX Top10동일가중 | <span style="color: tomato">5.2<small>%</small></span> | 21.6<small>%</small> | 0.24 | -27.4<small>%</small> | -14.2<small>%</small> |