| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-292150/) | <span style="color: tomato">4.5<small>%</small></span> | 21.3<small>%</small> | 0.21 | -29.1<small>%</small> | -14.9<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">8.7<small>%</small></span> | 22.5<small>%</small> | 0.39 | -32.3<small>%</small> | -15.7<small>%</small> |