| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-395170/) | <span style="color: tomato">5.7<small>%</small></span> | 21.4<small>%</small> | 0.27 | -29.1<small>%</small> | -14.9<small>%</small> |
| KODEX Top10동일가중 | <span style="color: tomato">6.6<small>%</small></span> | 21.3<small>%</small> | 0.31 | -27.4<small>%</small> | -14.4<small>%</small> |