| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-292150/) | <span style="color: cornflowerblue">-6.9<small>%</small></span> | 21.4<small>%</small> | -0.32 | -29.1<small>%</small> | -15.6<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-6.9<small>%</small></span> | 21.8<small>%</small> | -0.32 | -32.3<small>%</small> | -16.4<small>%</small> |