| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-292150/) | <span style="color: tomato">6.2<small>%</small></span> | 21.6<small>%</small> | 0.29 | -29.1<small>%</small> | -14.5<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">11.2<small>%</small></span> | 23.2<small>%</small> | 0.48 | -32.3<small>%</small> | -15.2<small>%</small> |