| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 차이나과창판STAR50(합성)](/414780-vs-416090/) | <span style="color: cornflowerblue">-7.0<small>%</small></span> | 31.2<small>%</small> | -0.22 | -51.3<small>%</small> | -29.4<small>%</small> |
| ACE 중국과창판STAR50 | <span style="color: cornflowerblue">-9.2<small>%</small></span> | 30.6<small>%</small> | -0.30 | -53.8<small>%</small> | -31.8<small>%</small> |