| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 차이나과창판STAR50(합성)](/414780-vs-416090/) | <span style="color: cornflowerblue">-7.6<small>%</small></span> | 31.3<small>%</small> | -0.24 | -51.3<small>%</small> | -29.3<small>%</small> |
| ACE 중국과창판STAR50 | <span style="color: cornflowerblue">-8.1<small>%</small></span> | 30.5<small>%</small> | -0.26 | -53.8<small>%</small> | -31.7<small>%</small> |