| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">47.5<small>%</small></span> | 25.1<small>%</small> | 1.89 | -24.6<small>%</small> | -5.5<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">30.1<small>%</small></span> | 20.0<small>%</small> | 1.51 | -23.8<small>%</small> | -4.7<small>%</small> |