| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국S&P500액티브](/426020-vs-360750/) | <span style="color: tomato">32.8<small>%</small></span> | 21.9<small>%</small> | 1.49 | -27.9<small>%</small> | -4.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">21.7<small>%</small></span> | 16.5<small>%</small> | 1.32 | -19.2<small>%</small> | -3.3<small>%</small> |