| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국S&P500액티브](/426020-vs-360750/) | <span style="color: tomato">30.4<small>%</small></span> | 21.5<small>%</small> | 1.41 | -27.9<small>%</small> | -4.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.1<small>%</small></span> | 15.9<small>%</small> | 1.20 | -19.2<small>%</small> | -3.2<small>%</small> |