| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">42.6<small>%</small></span> | 24.8<small>%</small> | 1.72 | -24.6<small>%</small> | -5.6<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">28.3<small>%</small></span> | 20.2<small>%</small> | 1.40 | -23.8<small>%</small> | -4.8<small>%</small> |