| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">40.5<small>%</small></span> | 28.4<small>%</small> | 1.42 | -35.0<small>%</small> | -6.4<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">24.5<small>%</small></span> | 21.6<small>%</small> | 1.13 | -24.3<small>%</small> | -4.9<small>%</small> |