| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-360750/) | <span style="color: tomato">21.3<small>%</small></span> | 16.5<small>%</small> | 1.29 | -19.3<small>%</small> | -3.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.1<small>%</small></span> | 16.4<small>%</small> | 1.35 | -19.2<small>%</small> | -3.3<small>%</small> |