| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-379800/) | <span style="color: tomato">21.0<small>%</small></span> | 14.8<small>%</small> | 1.42 | -16.2<small>%</small> | -3.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">22.3<small>%</small></span> | 14.5<small>%</small> | 1.54 | -15.0<small>%</small> | -3.1<small>%</small> |