| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-379800/) | <span style="color: tomato">17.9<small>%</small></span> | 15.8<small>%</small> | 1.14 | -19.3<small>%</small> | -3.5<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">18.8<small>%</small></span> | 15.6<small>%</small> | 1.20 | -19.2<small>%</small> | -3.3<small>%</small> |