| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-360750/) | <span style="color: tomato">17.8<small>%</small></span> | 15.9<small>%</small> | 1.12 | -19.3<small>%</small> | -3.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.5<small>%</small></span> | 15.8<small>%</small> | 1.17 | -19.2<small>%</small> | -3.2<small>%</small> |