| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-379800/) | <span style="color: tomato">19.5<small>%</small></span> | 16.5<small>%</small> | 1.18 | -19.3<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">20.6<small>%</small></span> | 16.3<small>%</small> | 1.27 | -19.2<small>%</small> | -3.3<small>%</small> |