| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-360750/) | <span style="color: tomato">22.0<small>%</small></span> | 14.7<small>%</small> | 1.49 | -16.2<small>%</small> | -3.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">23.2<small>%</small></span> | 14.7<small>%</small> | 1.59 | -15.2<small>%</small> | -3.2<small>%</small> |