| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">21.9<small>%</small></span> | 15.9<small>%</small> | 1.38 | -15.1<small>%</small> | -3.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.9<small>%</small></span> | 14.7<small>%</small> | 1.56 | -15.2<small>%</small> | -3.2<small>%</small> |