| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-379800/) | <span style="color: tomato">18.2<small>%</small></span> | 17.7<small>%</small> | 1.03 | -19.4<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">19.4<small>%</small></span> | 16.7<small>%</small> | 1.16 | -19.2<small>%</small> | -3.5<small>%</small> |