| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-379800/) | <span style="color: tomato">20.0<small>%</small></span> | 17.2<small>%</small> | 1.16 | -19.4<small>%</small> | -3.3<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">21.0<small>%</small></span> | 16.3<small>%</small> | 1.29 | -19.2<small>%</small> | -3.3<small>%</small> |