| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">20.0<small>%</small></span> | 17.2<small>%</small> | 1.16 | -19.4<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">20.8<small>%</small></span> | 16.4<small>%</small> | 1.26 | -19.2<small>%</small> | -3.3<small>%</small> |