| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">17.9<small>%</small></span> | 17.7<small>%</small> | 1.01 | -19.4<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.7<small>%</small></span> | 16.8<small>%</small> | 1.11 | -19.1<small>%</small> | -3.6<small>%</small> |