| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-379800/) | <span style="color: tomato">20.7<small>%</small></span> | 17.2<small>%</small> | 1.20 | -19.4<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">21.8<small>%</small></span> | 16.3<small>%</small> | 1.34 | -19.2<small>%</small> | -3.3<small>%</small> |