| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-379800/) | <span style="color: tomato">22.0<small>%</small></span> | 16.7<small>%</small> | 1.32 | -19.2<small>%</small> | -3.5<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.6<small>%</small></span> | 16.5<small>%</small> | 1.37 | -19.2<small>%</small> | -3.4<small>%</small> |