| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-379800/) | <span style="color: tomato">24.4<small>%</small></span> | 16.3<small>%</small> | 1.50 | -19.2<small>%</small> | -3.2<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">25.0<small>%</small></span> | 16.2<small>%</small> | 1.54 | -19.2<small>%</small> | -3.1<small>%</small> |