| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-379800/) | <span style="color: tomato">21.5<small>%</small></span> | 15.8<small>%</small> | 1.36 | -19.3<small>%</small> | -3.1<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.1<small>%</small></span> | 15.7<small>%</small> | 1.41 | -19.2<small>%</small> | -3.0<small>%</small> |