| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">24.2<small>%</small></span> | 16.3<small>%</small> | 1.49 | -19.2<small>%</small> | -3.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">24.6<small>%</small></span> | 16.3<small>%</small> | 1.51 | -19.2<small>%</small> | -3.2<small>%</small> |