| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">24.5<small>%</small></span> | 16.3<small>%</small> | 1.50 | -19.2<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">24.9<small>%</small></span> | 16.3<small>%</small> | 1.53 | -19.1<small>%</small> | -3.3<small>%</small> |