| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">22.0<small>%</small></span> | 16.6<small>%</small> | 1.33 | -19.2<small>%</small> | -3.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.4<small>%</small></span> | 16.6<small>%</small> | 1.35 | -19.1<small>%</small> | -3.4<small>%</small> |