| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">12.8<small>%</small></span> | 15.8<small>%</small> | 0.81 | -21.1<small>%</small> | -3.7<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">27.5<small>%</small></span> | 20.9<small>%</small> | 1.32 | -24.3<small>%</small> | -3.6<small>%</small> |