| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-402970/) | <span style="color: tomato">14.4<small>%</small></span> | 13.5<small>%</small> | 1.07 | -13.7<small>%</small> | -3.6<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">8.3<small>%</small></span> | 15.0<small>%</small> | 0.55 | -13.2<small>%</small> | -4.9<small>%</small> |