| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-161510/) | <span style="color: tomato">15.3<small>%</small></span> | 13.2<small>%</small> | 1.16 | -13.7<small>%</small> | -3.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">29.5<small>%</small></span> | 17.0<small>%</small> | 1.74 | -13.4<small>%</small> | -4.0<small>%</small> |