| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">12.7<small>%</small></span> | 16.1<small>%</small> | 0.79 | -21.1<small>%</small> | -3.5<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">27.5<small>%</small></span> | 21.1<small>%</small> | 1.30 | -24.3<small>%</small> | -3.8<small>%</small> |