| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-446720/) | <span style="color: tomato">13.9<small>%</small></span> | 13.2<small>%</small> | 1.06 | -13.7<small>%</small> | -2.8<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">7.4<small>%</small></span> | 14.5<small>%</small> | 0.51 | -13.3<small>%</small> | -5.3<small>%</small> |