| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-276970/) | <span style="color: tomato">14.3<small>%</small></span> | 13.3<small>%</small> | 1.08 | -13.7<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500배당귀족커버드콜(합성 H) | <span style="color: tomato">3.0<small>%</small></span> | 12.2<small>%</small> | 0.24 | -13.7<small>%</small> | -4.3<small>%</small> |