| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-379800/) | <span style="color: tomato">14.9<small>%</small></span> | 13.3<small>%</small> | 1.12 | -13.7<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.2<small>%</small></span> | 16.1<small>%</small> | 1.38 | -19.2<small>%</small> | -2.9<small>%</small> |