| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-402970/) | <span style="color: tomato">16.6<small>%</small></span> | 13.1<small>%</small> | 1.26 | -13.7<small>%</small> | -3.2<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">10.3<small>%</small></span> | 14.6<small>%</small> | 0.71 | -13.2<small>%</small> | -4.9<small>%</small> |