| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-379800/) | <span style="color: tomato">14.8<small>%</small></span> | 12.8<small>%</small> | 1.15 | -13.7<small>%</small> | -3.0<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">20.4<small>%</small></span> | 15.4<small>%</small> | 1.32 | -19.2<small>%</small> | -2.7<small>%</small> |