| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-276970/) | <span style="color: tomato">14.8<small>%</small></span> | 12.8<small>%</small> | 1.15 | -13.7<small>%</small> | -3.0<small>%</small> |
| KODEX 미국S&P500배당귀족커버드콜(합성 H) | <span style="color: tomato">4.1<small>%</small></span> | 11.9<small>%</small> | 0.35 | -13.7<small>%</small> | -4.9<small>%</small> |