| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-458730/) | <span style="color: tomato">18.9<small>%</small></span> | 13.3<small>%</small> | 1.42 | -13.7<small>%</small> | -2.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">12.2<small>%</small></span> | 14.7<small>%</small> | 0.83 | -13.1<small>%</small> | -3.1<small>%</small> |