| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-446720/) | <span style="color: tomato">16.6<small>%</small></span> | 12.8<small>%</small> | 1.29 | -13.7<small>%</small> | -2.7<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">8.2<small>%</small></span> | 14.1<small>%</small> | 0.58 | -13.3<small>%</small> | -5.4<small>%</small> |