| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-458750/) | <span style="color: tomato">21.6<small>%</small></span> | 12.8<small>%</small> | 1.69 | -13.7<small>%</small> | -2.0<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜1호 | <span style="color: tomato">11.4<small>%</small></span> | 13.7<small>%</small> | 0.83 | -13.7<small>%</small> | -3.7<small>%</small> |