| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-161510/) | <span style="color: tomato">13.4<small>%</small></span> | 11.4<small>%</small> | 1.18 | -12.4<small>%</small> | -3.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">25.1<small>%</small></span> | 16.6<small>%</small> | 1.51 | -10.8<small>%</small> | -3.3<small>%</small> |