| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-379800/) | <span style="color: tomato">16.3<small>%</small></span> | 11.7<small>%</small> | 1.39 | -12.4<small>%</small> | -3.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">26.0<small>%</small></span> | 13.7<small>%</small> | 1.89 | -13.0<small>%</small> | -2.4<small>%</small> |