| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-161510/) | <span style="color: tomato">15.2<small>%</small></span> | 12.8<small>%</small> | 1.18 | -13.7<small>%</small> | -3.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">30.9<small>%</small></span> | 21.1<small>%</small> | 1.46 | -20.7<small>%</small> | -4.8<small>%</small> |