| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-276970/) | <span style="color: tomato">16.3<small>%</small></span> | 11.7<small>%</small> | 1.39 | -12.4<small>%</small> | -3.5<small>%</small> |
| KODEX 미국S&P500배당귀족커버드콜(합성 H) | <span style="color: tomato">8.1<small>%</small></span> | 11.1<small>%</small> | 0.73 | -11.1<small>%</small> | -3.3<small>%</small> |