| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-458730/) | <span style="color: tomato">18.4<small>%</small></span> | 12.6<small>%</small> | 1.47 | -13.7<small>%</small> | -2.0<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">18.5<small>%</small></span> | 13.9<small>%</small> | 1.33 | -13.1<small>%</small> | -2.9<small>%</small> |