| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-446720/) | <span style="color: tomato">13.0<small>%</small></span> | 10.8<small>%</small> | 1.20 | -10.0<small>%</small> | -2.6<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">10.4<small>%</small></span> | 12.2<small>%</small> | 0.85 | -13.3<small>%</small> | -5.2<small>%</small> |