| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">17.4<small>%</small></span> | 13.1<small>%</small> | 1.32 | -12.0<small>%</small> | -2.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">31.9<small>%</small></span> | 19.0<small>%</small> | 1.68 | -17.2<small>%</small> | -3.1<small>%</small> |