| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-458730/) | <span style="color: tomato">20.8<small>%</small></span> | 12.9<small>%</small> | 1.61 | -13.7<small>%</small> | -2.0<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">14.3<small>%</small></span> | 14.2<small>%</small> | 1.00 | -13.1<small>%</small> | -3.4<small>%</small> |