| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-402970/) | <span style="color: tomato">17.5<small>%</small></span> | 11.6<small>%</small> | 1.50 | -12.4<small>%</small> | -3.4<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">14.8<small>%</small></span> | 13.3<small>%</small> | 1.11 | -12.9<small>%</small> | -4.5<small>%</small> |