| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당커버드콜액티브](/441640-vs-458750/) | <span style="color: tomato">26.1<small>%</small></span> | 10.2<small>%</small> | 2.55 | -6.2<small>%</small> | -1.4<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜1호 | <span style="color: tomato">21.9<small>%</small></span> | 11.1<small>%</small> | 1.96 | -7.9<small>%</small> | -1.8<small>%</small> |