| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-315960/) | <span style="color: tomato">34.5<small>%</small></span> | 19.5<small>%</small> | 1.77 | -17.4<small>%</small> | -3.5<small>%</small> |
| RISE 대형고배당10TR | <span style="color: tomato">40.5<small>%</small></span> | 23.7<small>%</small> | 1.71 | -28.0<small>%</small> | -7.1<small>%</small> |