| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">26.9<small>%</small></span> | 19.2<small>%</small> | 1.40 | -17.4<small>%</small> | -3.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">16.4<small>%</small></span> | 18.8<small>%</small> | 0.87 | -21.6<small>%</small> | -5.7<small>%</small> |