| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-315960/) | <span style="color: tomato">33.1<small>%</small></span> | 19.8<small>%</small> | 1.67 | -17.4<small>%</small> | -3.5<small>%</small> |
| RISE 대형고배당10TR | <span style="color: tomato">38.3<small>%</small></span> | 24.0<small>%</small> | 1.60 | -28.0<small>%</small> | -7.1<small>%</small> |