| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-315960/) | <span style="color: tomato">29.1<small>%</small></span> | 19.1<small>%</small> | 1.52 | -17.4<small>%</small> | -3.4<small>%</small> |
| RISE 대형고배당10TR | <span style="color: tomato">25.3<small>%</small></span> | 22.8<small>%</small> | 1.11 | -28.0<small>%</small> | -7.6<small>%</small> |