| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">22.9<small>%</small></span> | 18.6<small>%</small> | 1.23 | -13.3<small>%</small> | -3.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">23.9<small>%</small></span> | 16.9<small>%</small> | 1.41 | -10.8<small>%</small> | -3.4<small>%</small> |