| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">34.6<small>%</small></span> | 19.6<small>%</small> | 1.77 | -17.4<small>%</small> | -3.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">31.7<small>%</small></span> | 17.1<small>%</small> | 1.85 | -13.4<small>%</small> | -4.1<small>%</small> |