| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">27.9<small>%</small></span> | 19.3<small>%</small> | 1.45 | -17.4<small>%</small> | -3.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">30.7<small>%</small></span> | 17.3<small>%</small> | 1.78 | -13.4<small>%</small> | -3.8<small>%</small> |