| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">35.5<small>%</small></span> | 19.6<small>%</small> | 1.82 | -17.4<small>%</small> | -3.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">28.2<small>%</small></span> | 19.3<small>%</small> | 1.46 | -21.6<small>%</small> | -5.4<small>%</small> |