| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">24.9<small>%</small></span> | 18.3<small>%</small> | 1.36 | -13.3<small>%</small> | -2.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.4<small>%</small></span> | 18.3<small>%</small> | 0.46 | -19.7<small>%</small> | -4.2<small>%</small> |