| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">22.5<small>%</small></span> | 18.9<small>%</small> | 1.19 | -22.9<small>%</small> | -5.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">21.2<small>%</small></span> | 18.7<small>%</small> | 1.13 | -21.6<small>%</small> | -5.7<small>%</small> |