| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">28.0<small>%</small></span> | 20.0<small>%</small> | 1.40 | -22.9<small>%</small> | -5.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">27.5<small>%</small></span> | 19.7<small>%</small> | 1.40 | -21.6<small>%</small> | -5.6<small>%</small> |