| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">42.6<small>%</small></span> | 34.7<small>%</small> | 1.23 | -41.9<small>%</small> | -6.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">42.0<small>%</small></span> | 34.4<small>%</small> | 1.22 | -40.8<small>%</small> | -6.8<small>%</small> |