| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WON 미국S&P500](/444490-vs-379800/) | <span style="color: tomato">20.8<small>%</small></span> | 17.4<small>%</small> | 1.20 | -19.4<small>%</small> | -3.0<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">21.3<small>%</small></span> | 16.2<small>%</small> | 1.31 | -19.2<small>%</small> | -3.0<small>%</small> |