| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WON 미국S&P500](/444490-vs-360750/) | <span style="color: tomato">22.1<small>%</small></span> | 17.1<small>%</small> | 1.29 | -19.4<small>%</small> | -2.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.4<small>%</small></span> | 16.0<small>%</small> | 1.40 | -19.2<small>%</small> | -2.9<small>%</small> |