| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WON 미국S&P500](/444490-vs-379800/) | <span style="color: tomato">21.6<small>%</small></span> | 17.3<small>%</small> | 1.25 | -19.4<small>%</small> | -2.9<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.0<small>%</small></span> | 16.1<small>%</small> | 1.37 | -19.2<small>%</small> | -2.9<small>%</small> |