| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WON 미국S&P500](/444490-vs-360750/) | <span style="color: tomato">20.3<small>%</small></span> | 17.6<small>%</small> | 1.16 | -19.4<small>%</small> | -3.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">20.6<small>%</small></span> | 16.4<small>%</small> | 1.25 | -19.1<small>%</small> | -3.1<small>%</small> |