| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">12.7<small>%</small></span> | 12.4<small>%</small> | 1.03 | -13.3<small>%</small> | -4.9<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">13.3<small>%</small></span> | 12.7<small>%</small> | 1.04 | -12.9<small>%</small> | -4.6<small>%</small> |