| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-458730/) | <span style="color: tomato">12.4<small>%</small></span> | 14.5<small>%</small> | 0.86 | -13.3<small>%</small> | -3.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">12.4<small>%</small></span> | 14.7<small>%</small> | 0.84 | -13.1<small>%</small> | -3.2<small>%</small> |