| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">11.9<small>%</small></span> | 14.0<small>%</small> | 0.85 | -13.3<small>%</small> | -4.6<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">12.3<small>%</small></span> | 14.2<small>%</small> | 0.87 | -13.2<small>%</small> | -4.4<small>%</small> |