| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-458730/) | <span style="color: tomato">12.9<small>%</small></span> | 14.1<small>%</small> | 0.91 | -13.3<small>%</small> | -3.4<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">12.8<small>%</small></span> | 14.3<small>%</small> | 0.90 | -13.1<small>%</small> | -3.4<small>%</small> |