| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">11.3<small>%</small></span> | 12.3<small>%</small> | 0.92 | -13.3<small>%</small> | -5.2<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">11.9<small>%</small></span> | 12.6<small>%</small> | 0.94 | -12.9<small>%</small> | -4.9<small>%</small> |