| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-458730/) | <span style="color: tomato">26.0<small>%</small></span> | 11.6<small>%</small> | 2.25 | -7.8<small>%</small> | -1.7<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">25.9<small>%</small></span> | 11.9<small>%</small> | 2.16 | -7.6<small>%</small> | -1.8<small>%</small> |