| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">16.6<small>%</small></span> | 14.9<small>%</small> | 1.12 | -13.9<small>%</small> | -2.9<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">18.7<small>%</small></span> | 19.1<small>%</small> | 0.98 | -21.7<small>%</small> | -5.8<small>%</small> |