| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">19.1<small>%</small></span> | 15.0<small>%</small> | 1.28 | -12.3<small>%</small> | -2.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">13.4<small>%</small></span> | 19.0<small>%</small> | 0.70 | -21.7<small>%</small> | -6.0<small>%</small> |