| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-161510/) | <span style="color: tomato">18.2<small>%</small></span> | 15.1<small>%</small> | 1.21 | -14.1<small>%</small> | -3.2<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">31.6<small>%</small></span> | 17.3<small>%</small> | 1.83 | -13.4<small>%</small> | -4.2<small>%</small> |