| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">14.0<small>%</small></span> | 13.2<small>%</small> | 1.06 | -12.0<small>%</small> | -2.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.9<small>%</small></span> | 18.0<small>%</small> | 0.33 | -16.5<small>%</small> | -4.0<small>%</small> |