| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">17.0<small>%</small></span> | 18.0<small>%</small> | 0.95 | -21.7<small>%</small> | -4.4<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">38.2<small>%</small></span> | 34.2<small>%</small> | 1.11 | -41.1<small>%</small> | -6.3<small>%</small> |