| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">17.1<small>%</small></span> | 14.9<small>%</small> | 1.15 | -13.9<small>%</small> | -3.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">21.6<small>%</small></span> | 18.8<small>%</small> | 1.15 | -21.6<small>%</small> | -5.7<small>%</small> |