| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-441800/) | <span style="color: tomato">20.0<small>%</small></span> | 15.1<small>%</small> | 1.33 | -12.0<small>%</small> | -2.4<small>%</small> |
| TIMEFOLIO Korea플러스배당액티브 | <span style="color: tomato">26.2<small>%</small></span> | 19.5<small>%</small> | 1.34 | -17.4<small>%</small> | -3.6<small>%</small> |