| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">18.2<small>%</small></span> | 15.1<small>%</small> | 1.20 | -14.1<small>%</small> | -3.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">23.1<small>%</small></span> | 19.4<small>%</small> | 1.19 | -21.6<small>%</small> | -5.6<small>%</small> |