| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-441800/) | <span style="color: tomato">18.0<small>%</small></span> | 14.9<small>%</small> | 1.21 | -12.3<small>%</small> | -2.8<small>%</small> |
| TIMEFOLIO Korea플러스배당액티브 | <span style="color: tomato">28.2<small>%</small></span> | 19.3<small>%</small> | 1.46 | -17.4<small>%</small> | -3.7<small>%</small> |