| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-161510/) | <span style="color: tomato">17.1<small>%</small></span> | 14.9<small>%</small> | 1.15 | -13.9<small>%</small> | -2.9<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">28.5<small>%</small></span> | 17.1<small>%</small> | 1.67 | -13.4<small>%</small> | -4.2<small>%</small> |