| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500TR(H)](/448290-vs-269540/) | <span style="color: tomato">17.7<small>%</small></span> | 16.7<small>%</small> | 1.06 | -20.9<small>%</small> | -2.3<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">18.4<small>%</small></span> | 16.4<small>%</small> | 1.12 | -20.8<small>%</small> | -2.3<small>%</small> |