| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500TR(H)](/448290-vs-269540/) | <span style="color: tomato">20.7<small>%</small></span> | 13.6<small>%</small> | 1.52 | -10.1<small>%</small> | -1.9<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">21.2<small>%</small></span> | 13.5<small>%</small> | 1.57 | -9.7<small>%</small> | -1.9<small>%</small> |