| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500TR(H)](/448290-vs-269540/) | <span style="color: tomato">17.8<small>%</small></span> | 13.7<small>%</small> | 1.30 | -10.1<small>%</small> | -2.0<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">18.3<small>%</small></span> | 13.6<small>%</small> | 1.34 | -9.7<small>%</small> | -1.9<small>%</small> |