| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-304940/) | <span style="color: tomato">30.0<small>%</small></span> | 20.0<small>%</small> | 1.50 | -15.8<small>%</small> | -2.9<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">28.3<small>%</small></span> | 19.4<small>%</small> | 1.46 | -15.9<small>%</small> | -3.0<small>%</small> |