| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-qqq/) | <span style="color: tomato">26.3<small>%</small></span> | 23.0<small>%</small> | 1.14 | -25.7<small>%</small> | -3.5<small>%</small> |
| QQQ | <span style="color: tomato">29.9<small>%</small></span> | 21.3<small>%</small> | 1.41 | -22.8<small>%</small> | -3.3<small>%</small> |