| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-qqq/) | <span style="color: tomato">27.3<small>%</small></span> | 22.5<small>%</small> | 1.21 | -25.7<small>%</small> | -3.4<small>%</small> |
| QQQ | <span style="color: tomato">29.3<small>%</small></span> | 20.8<small>%</small> | 1.41 | -22.8<small>%</small> | -3.1<small>%</small> |