| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-304940/) | <span style="color: tomato">26.0<small>%</small></span> | 22.0<small>%</small> | 1.18 | -25.7<small>%</small> | -3.3<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">24.4<small>%</small></span> | 21.8<small>%</small> | 1.12 | -26.1<small>%</small> | -3.4<small>%</small> |