| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-269540/) | <span style="color: tomato">16.8<small>%</small></span> | 17.8<small>%</small> | 0.94 | -20.8<small>%</small> | -2.6<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">17.1<small>%</small></span> | 16.8<small>%</small> | 1.02 | -20.8<small>%</small> | -2.4<small>%</small> |