| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-448290/) | <span style="color: tomato">19.9<small>%</small></span> | 15.1<small>%</small> | 1.32 | -10.8<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">20.1<small>%</small></span> | 13.5<small>%</small> | 1.48 | -10.1<small>%</small> | -1.9<small>%</small> |