| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-448300/) | <span style="color: tomato">30.1<small>%</small></span> | 19.2<small>%</small> | 1.57 | -15.9<small>%</small> | -2.8<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">30.2<small>%</small></span> | 19.5<small>%</small> | 1.54 | -15.8<small>%</small> | -2.9<small>%</small> |