| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-448300/) | <span style="color: tomato">26.7<small>%</small></span> | 21.7<small>%</small> | 1.23 | -25.8<small>%</small> | -3.3<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">26.9<small>%</small></span> | 21.8<small>%</small> | 1.23 | -25.7<small>%</small> | -3.3<small>%</small> |