| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-269540/) | <span style="color: tomato">16.5<small>%</small></span> | 16.8<small>%</small> | 0.98 | -20.8<small>%</small> | -2.3<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">16.7<small>%</small></span> | 16.0<small>%</small> | 1.04 | -20.8<small>%</small> | -2.1<small>%</small> |