| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-269540/) | <span style="color: tomato">19.5<small>%</small></span> | 15.1<small>%</small> | 1.28 | -10.8<small>%</small> | -2.2<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">20.0<small>%</small></span> | 13.6<small>%</small> | 1.47 | -9.7<small>%</small> | -1.9<small>%</small> |