| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">24.7<small>%</small></span> | 22.2<small>%</small> | 1.11 | -25.8<small>%</small> | -3.5<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">23.2<small>%</small></span> | 22.1<small>%</small> | 1.05 | -26.1<small>%</small> | -3.6<small>%</small> |