| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-143850/) | <span style="color: tomato">19.2<small>%</small></span> | 15.1<small>%</small> | 1.27 | -10.8<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">16.7<small>%</small></span> | 13.5<small>%</small> | 1.23 | -10.6<small>%</small> | -2.1<small>%</small> |