| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER KOFR금리액티브(합성)](/449170-vs-423160/) | <span style="color: tomato">3.4<small>%</small></span> | 0.2<small>%</small> | 22.55 | -0.0<small>%</small> | -0.0<small>%</small> |
| KODEX KOFR금리액티브(합성) | <span style="color: tomato">3.4<small>%</small></span> | 0.1<small>%</small> | 24.06 | -0.0<small>%</small> | -0.0<small>%</small> |