| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">28.0<small>%</small></span> | 21.8<small>%</small> | 1.28 | -25.8<small>%</small> | -3.3<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">26.5<small>%</small></span> | 21.7<small>%</small> | 1.22 | -26.1<small>%</small> | -3.4<small>%</small> |