| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-143850/) | <span style="color: tomato">16.2<small>%</small></span> | 17.4<small>%</small> | 0.93 | -20.8<small>%</small> | -2.5<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">13.7<small>%</small></span> | 16.4<small>%</small> | 0.84 | -21.0<small>%</small> | -2.5<small>%</small> |