| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-143850/) | <span style="color: tomato">15.8<small>%</small></span> | 17.9<small>%</small> | 0.88 | -20.8<small>%</small> | -2.7<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">13.4<small>%</small></span> | 16.9<small>%</small> | 0.80 | -21.0<small>%</small> | -2.7<small>%</small> |