| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">29.5<small>%</small></span> | 19.4<small>%</small> | 1.52 | -15.9<small>%</small> | -2.9<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">28.0<small>%</small></span> | 19.1<small>%</small> | 1.47 | -15.9<small>%</small> | -3.0<small>%</small> |