| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-448290/) | <span style="color: tomato">16.4<small>%</small></span> | 17.4<small>%</small> | 0.94 | -20.8<small>%</small> | -2.5<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">16.5<small>%</small></span> | 16.6<small>%</small> | 0.99 | -20.9<small>%</small> | -2.3<small>%</small> |