| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-448290/) | <span style="color: tomato">16.2<small>%</small></span> | 17.8<small>%</small> | 0.91 | -20.8<small>%</small> | -2.6<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">16.3<small>%</small></span> | 17.0<small>%</small> | 0.96 | -20.9<small>%</small> | -2.4<small>%</small> |