| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-448300/) | <span style="color: tomato">26.1<small>%</small></span> | 22.3<small>%</small> | 1.17 | -25.8<small>%</small> | -3.5<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">26.3<small>%</small></span> | 22.4<small>%</small> | 1.17 | -25.7<small>%</small> | -3.5<small>%</small> |