| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-448290/) | <span style="color: tomato">20.8<small>%</small></span> | 16.5<small>%</small> | 1.26 | -20.9<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">20.4<small>%</small></span> | 16.5<small>%</small> | 1.23 | -20.9<small>%</small> | -2.2<small>%</small> |