| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-379800/) | <span style="color: tomato">34.7<small>%</small></span> | 12.8<small>%</small> | 2.71 | -8.8<small>%</small> | -1.4<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">34.7<small>%</small></span> | 12.6<small>%</small> | 2.75 | -8.9<small>%</small> | -1.4<small>%</small> |