| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-448290/) | <span style="color: tomato">20.5<small>%</small></span> | 17.0<small>%</small> | 1.21 | -20.9<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">19.9<small>%</small></span> | 17.0<small>%</small> | 1.17 | -20.9<small>%</small> | -2.3<small>%</small> |