| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500](/449770-vs-360750/) | <span style="color: tomato">26.3<small>%</small></span> | 16.0<small>%</small> | 1.64 | -19.2<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">26.2<small>%</small></span> | 16.0<small>%</small> | 1.64 | -19.1<small>%</small> | -2.3<small>%</small> |