| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-448290/) | <span style="color: tomato">21.4<small>%</small></span> | 16.7<small>%</small> | 1.29 | -20.9<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">20.9<small>%</small></span> | 16.7<small>%</small> | 1.25 | -20.9<small>%</small> | -2.2<small>%</small> |