| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-143850/) | <span style="color: tomato">21.0<small>%</small></span> | 16.6<small>%</small> | 1.27 | -20.9<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">17.9<small>%</small></span> | 16.4<small>%</small> | 1.09 | -21.0<small>%</small> | -2.4<small>%</small> |