| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-269540/) | <span style="color: tomato">20.1<small>%</small></span> | 16.1<small>%</small> | 1.25 | -20.9<small>%</small> | -2.1<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">19.9<small>%</small></span> | 15.9<small>%</small> | 1.25 | -20.8<small>%</small> | -2.0<small>%</small> |