| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500](/449770-vs-360750/) | <span style="color: tomato">28.7<small>%</small></span> | 15.7<small>%</small> | 1.83 | -19.2<small>%</small> | -2.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">28.7<small>%</small></span> | 15.7<small>%</small> | 1.83 | -19.2<small>%</small> | -2.1<small>%</small> |