| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-269540/) | <span style="color: tomato">21.6<small>%</small></span> | 16.4<small>%</small> | 1.32 | -20.9<small>%</small> | -2.2<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">21.8<small>%</small></span> | 16.2<small>%</small> | 1.34 | -20.8<small>%</small> | -2.1<small>%</small> |