| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-269540/) | <span style="color: tomato">25.2<small>%</small></span> | 13.3<small>%</small> | 1.90 | -10.1<small>%</small> | -1.7<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">25.0<small>%</small></span> | 13.2<small>%</small> | 1.89 | -9.7<small>%</small> | -1.7<small>%</small> |