| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500(H)](/449780-vs-143850/) | <span style="color: tomato">20.7<small>%</small></span> | 16.9<small>%</small> | 1.22 | -20.9<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">17.6<small>%</small></span> | 16.8<small>%</small> | 1.05 | -21.0<small>%</small> | -2.5<small>%</small> |