| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국S&P500](/449770-vs-379800/) | <span style="color: tomato">25.8<small>%</small></span> | 16.0<small>%</small> | 1.61 | -19.2<small>%</small> | -2.3<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">25.8<small>%</small></span> | 15.9<small>%</small> | 1.62 | -19.2<small>%</small> | -2.3<small>%</small> |