| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-379800/) | <span style="color: tomato">32.7<small>%</small></span> | 12.8<small>%</small> | 2.55 | -8.8<small>%</small> | -1.4<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">32.5<small>%</small></span> | 12.7<small>%</small> | 2.57 | -8.9<small>%</small> | -1.4<small>%</small> |