| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [1Q K200액티브](/451060-vs-069500/) | <span style="color: tomato">42.2<small>%</small></span> | 34.5<small>%</small> | 1.22 | -41.3<small>%</small> | -6.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">42.9<small>%</small></span> | 35.4<small>%</small> | 1.21 | -40.8<small>%</small> | -6.6<small>%</small> |