| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [1Q K200액티브](/451060-vs-069500/) | <span style="color: tomato">22.1<small>%</small></span> | 18.8<small>%</small> | 1.17 | -21.9<small>%</small> | -6.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">22.7<small>%</small></span> | 19.0<small>%</small> | 1.20 | -21.6<small>%</small> | -5.9<small>%</small> |