| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [1Q K200액티브](/451060-vs-069500/) | <span style="color: tomato">5.3<small>%</small></span> | 17.9<small>%</small> | 0.30 | -16.4<small>%</small> | -4.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.9<small>%</small></span> | 18.1<small>%</small> | 0.32 | -16.5<small>%</small> | -4.1<small>%</small> |