| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스(H)](/452360-vs-446720/) | <span style="color: tomato">12.4<small>%</small></span> | 11.6<small>%</small> | 1.06 | -11.0<small>%</small> | -2.6<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">19.0<small>%</small></span> | 11.7<small>%</small> | 1.62 | -7.8<small>%</small> | -2.1<small>%</small> |