| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스(H)](/452360-vs-446720/) | <span style="color: tomato">6.4<small>%</small></span> | 14.1<small>%</small> | 0.46 | -17.6<small>%</small> | -4.1<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">11.7<small>%</small></span> | 14.3<small>%</small> | 0.82 | -13.3<small>%</small> | -3.4<small>%</small> |