| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스(H)](/452360-vs-446720/) | <span style="color: tomato">6.8<small>%</small></span> | 13.9<small>%</small> | 0.49 | -17.6<small>%</small> | -4.4<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">14.0<small>%</small></span> | 14.0<small>%</small> | 1.00 | -13.3<small>%</small> | -3.4<small>%</small> |