| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국나스닥100(H)](/453080-vs-304940/) | <span style="color: tomato">30.0<small>%</small></span> | 21.5<small>%</small> | 1.39 | -25.7<small>%</small> | -3.2<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">27.2<small>%</small></span> | 21.5<small>%</small> | 1.27 | -26.1<small>%</small> | -3.3<small>%</small> |