| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국나스닥100(H)](/453080-vs-448300/) | <span style="color: tomato">29.0<small>%</small></span> | 22.1<small>%</small> | 1.32 | -25.7<small>%</small> | -3.3<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">29.0<small>%</small></span> | 22.2<small>%</small> | 1.30 | -25.7<small>%</small> | -3.4<small>%</small> |