| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-304940/) | <span style="color: tomato">37.4<small>%</small></span> | 18.5<small>%</small> | 2.03 | -16.0<small>%</small> | -2.5<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">33.6<small>%</small></span> | 18.1<small>%</small> | 1.86 | -15.9<small>%</small> | -2.7<small>%</small> |