| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-448300/) | <span style="color: tomato">38.1<small>%</small></span> | 18.2<small>%</small> | 2.10 | -16.0<small>%</small> | -2.4<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">37.7<small>%</small></span> | 18.5<small>%</small> | 2.03 | -15.8<small>%</small> | -2.5<small>%</small> |