| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-143850/) | <span style="color: tomato">27.2<small>%</small></span> | 12.5<small>%</small> | 2.18 | -10.4<small>%</small> | -1.7<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">23.9<small>%</small></span> | 12.4<small>%</small> | 1.92 | -10.6<small>%</small> | -1.8<small>%</small> |