| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-448290/) | <span style="color: tomato">20.4<small>%</small></span> | 16.4<small>%</small> | 1.24 | -20.7<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">20.1<small>%</small></span> | 16.4<small>%</small> | 1.23 | -20.9<small>%</small> | -2.2<small>%</small> |