| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-269540/) | <span style="color: tomato">25.7<small>%</small></span> | 12.3<small>%</small> | 2.09 | -10.4<small>%</small> | -1.7<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">25.8<small>%</small></span> | 12.2<small>%</small> | 2.12 | -9.7<small>%</small> | -1.6<small>%</small> |