| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-143850/) | <span style="color: tomato">20.6<small>%</small></span> | 16.7<small>%</small> | 1.24 | -20.7<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">17.6<small>%</small></span> | 16.4<small>%</small> | 1.07 | -21.0<small>%</small> | -2.4<small>%</small> |