| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-143850/) | <span style="color: tomato">20.8<small>%</small></span> | 16.3<small>%</small> | 1.28 | -20.7<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">17.9<small>%</small></span> | 16.1<small>%</small> | 1.11 | -21.0<small>%</small> | -2.3<small>%</small> |