| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-269540/) | <span style="color: tomato">20.5<small>%</small></span> | 16.7<small>%</small> | 1.22 | -20.7<small>%</small> | -2.3<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">20.5<small>%</small></span> | 16.5<small>%</small> | 1.24 | -20.8<small>%</small> | -2.2<small>%</small> |