| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-448290/) | <span style="color: tomato">26.6<small>%</small></span> | 12.5<small>%</small> | 2.13 | -10.4<small>%</small> | -1.7<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">26.4<small>%</small></span> | 12.4<small>%</small> | 2.14 | -10.1<small>%</small> | -1.6<small>%</small> |