| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 인도Nifty50](/453810-vs-200250/) | <span style="color: tomato">3.4<small>%</small></span> | 14.8<small>%</small> | 0.23 | -26.1<small>%</small> | -5.1<small>%</small> |
| KIWOOM 인도Nifty50(합성) | <span style="color: tomato">2.2<small>%</small></span> | 14.8<small>%</small> | 0.15 | -26.9<small>%</small> | -5.4<small>%</small> |