| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 인도Nifty50](/453810-vs-200250/) | <span style="color: tomato">2.8<small>%</small></span> | 14.8<small>%</small> | 0.19 | -27.5<small>%</small> | -5.2<small>%</small> |
| KIWOOM 인도Nifty50(합성) | <span style="color: tomato">1.6<small>%</small></span> | 14.8<small>%</small> | 0.11 | -28.2<small>%</small> | -5.5<small>%</small> |