| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-200250/) | <span style="color: tomato">6.6<small>%</small></span> | 15.2<small>%</small> | 0.43 | -19.8<small>%</small> | -4.5<small>%</small> |
| KIWOOM 인도Nifty50(합성) | <span style="color: tomato">5.3<small>%</small></span> | 14.7<small>%</small> | 0.36 | -20.4<small>%</small> | -4.9<small>%</small> |