| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 인도Nifty50](/453810-vs-200250/) | <span style="color: tomato">5.0<small>%</small></span> | 14.8<small>%</small> | 0.34 | -24.7<small>%</small> | -5.0<small>%</small> |
| KIWOOM 인도Nifty50(합성) | <span style="color: tomato">3.7<small>%</small></span> | 14.7<small>%</small> | 0.25 | -25.1<small>%</small> | -5.3<small>%</small> |