| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-200250/) | <span style="color: tomato">16.3<small>%</small></span> | 14.4<small>%</small> | 1.14 | -12.0<small>%</small> | -2.8<small>%</small> |
| KIWOOM 인도Nifty50(합성) | <span style="color: tomato">15.0<small>%</small></span> | 14.0<small>%</small> | 1.07 | -12.5<small>%</small> | -3.2<small>%</small> |