| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-453810/) | <span style="color: tomato">24.2<small>%</small></span> | 13.9<small>%</small> | 1.74 | -6.8<small>%</small> | -1.7<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">24.5<small>%</small></span> | 14.0<small>%</small> | 1.75 | -6.9<small>%</small> | -1.7<small>%</small> |