| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 머니마켓액티브](/455890-vs-423160/) | <span style="color: tomato">3.9<small>%</small></span> | 0.2<small>%</small> | 17.78 | -0.0<small>%</small> | -0.0<small>%</small> |
| KODEX KOFR금리액티브(합성) | <span style="color: tomato">3.4<small>%</small></span> | 0.1<small>%</small> | 23.15 | -0.0<small>%</small> | -0.0<small>%</small> |