| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 머니마켓액티브](/455890-vs-357870/) | <span style="color: tomato">4.2<small>%</small></span> | 0.2<small>%</small> | 18.71 | -0.0<small>%</small> | -0.0<small>%</small> |
| TIGER CD금리투자KIS(합성) | <span style="color: tomato">3.6<small>%</small></span> | 0.2<small>%</small> | 19.54 | -0.0<small>%</small> | -0.0<small>%</small> |