| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국달러SOFR금리액티브(합성)](/456200-vs-456610/) | <span style="color: tomato">5.3<small>%</small></span> | 9.1<small>%</small> | 0.59 | -13.5<small>%</small> | -2.4<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">5.4<small>%</small></span> | 9.2<small>%</small> | 0.59 | -13.4<small>%</small> | -2.4<small>%</small> |