| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국달러SOFR금리액티브(합성)](/456200-vs-456610/) | <span style="color: tomato">4.9<small>%</small></span> | 9.0<small>%</small> | 0.54 | -13.5<small>%</small> | -2.4<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">5.1<small>%</small></span> | 9.1<small>%</small> | 0.56 | -13.4<small>%</small> | -2.3<small>%</small> |