| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국달러SOFR금리액티브(합성)](/456610-vs-138230/) | <span style="color: tomato">6.0<small>%</small></span> | 9.2<small>%</small> | 0.65 | -13.4<small>%</small> | -2.4<small>%</small> |
| KIWOOM 미국달러선물 | <span style="color: tomato">5.5<small>%</small></span> | 9.1<small>%</small> | 0.60 | -13.6<small>%</small> | -2.4<small>%</small> |