| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국달러SOFR금리액티브(합성)](/456610-vs-138230/) | <span style="color: tomato">9.2<small>%</small></span> | 8.3<small>%</small> | 1.11 | -5.0<small>%</small> | -1.5<small>%</small> |
| KOSEF 미국달러선물 | <span style="color: tomato">8.6<small>%</small></span> | 8.3<small>%</small> | 1.03 | -5.1<small>%</small> | -1.5<small>%</small> |