| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-458730/) | <span style="color: tomato">19.8<small>%</small></span> | 10.8<small>%</small> | 1.83 | -7.9<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">22.7<small>%</small></span> | 11.5<small>%</small> | 1.96 | -7.7<small>%</small> | -1.8<small>%</small> |