| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-360750/) | <span style="color: tomato">10.2<small>%</small></span> | 14.2<small>%</small> | 0.72 | -13.7<small>%</small> | -3.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.1<small>%</small></span> | 16.3<small>%</small> | 1.53 | -19.1<small>%</small> | -2.5<small>%</small> |