| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-458730/) | <span style="color: tomato">11.4<small>%</small></span> | 13.8<small>%</small> | 0.83 | -13.7<small>%</small> | -3.6<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">13.5<small>%</small></span> | 14.3<small>%</small> | 0.94 | -13.1<small>%</small> | -3.4<small>%</small> |