| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-446720/) | <span style="color: tomato">13.0<small>%</small></span> | 14.5<small>%</small> | 0.90 | -13.1<small>%</small> | -3.3<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">13.0<small>%</small></span> | 14.3<small>%</small> | 0.91 | -13.3<small>%</small> | -3.3<small>%</small> |