| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-360750/) | <span style="color: tomato">16.0<small>%</small></span> | 10.5<small>%</small> | 1.53 | -8.1<small>%</small> | -2.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">30.5<small>%</small></span> | 11.8<small>%</small> | 2.58 | -9.1<small>%</small> | -1.5<small>%</small> |