| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-379800/) | <span style="color: tomato">19.6<small>%</small></span> | 10.8<small>%</small> | 1.82 | -8.1<small>%</small> | -2.0<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">33.1<small>%</small></span> | 12.0<small>%</small> | 2.75 | -8.9<small>%</small> | -1.4<small>%</small> |