| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-360750/) | <span style="color: tomato">20.1<small>%</small></span> | 10.8<small>%</small> | 1.87 | -8.1<small>%</small> | -2.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">33.2<small>%</small></span> | 12.2<small>%</small> | 2.71 | -9.1<small>%</small> | -1.5<small>%</small> |