| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-446720/) | <span style="color: tomato">18.6<small>%</small></span> | 13.9<small>%</small> | 1.34 | -13.1<small>%</small> | -2.9<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">18.7<small>%</small></span> | 13.9<small>%</small> | 1.34 | -13.3<small>%</small> | -3.0<small>%</small> |