| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">20.9<small>%</small></span> | 11.6<small>%</small> | 1.81 | -7.6<small>%</small> | -1.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">28.8<small>%</small></span> | 11.7<small>%</small> | 2.47 | -8.9<small>%</small> | -1.4<small>%</small> |