| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">12.3<small>%</small></span> | 14.3<small>%</small> | 0.86 | -13.1<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">27.5<small>%</small></span> | 15.8<small>%</small> | 1.74 | -19.2<small>%</small> | -2.3<small>%</small> |