| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-360750/) | <span style="color: tomato">22.7<small>%</small></span> | 11.2<small>%</small> | 2.02 | -7.9<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">33.2<small>%</small></span> | 12.2<small>%</small> | 2.71 | -9.1<small>%</small> | -1.5<small>%</small> |