| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-379800/) | <span style="color: tomato">18.3<small>%</small></span> | 10.7<small>%</small> | 1.71 | -8.1<small>%</small> | -2.1<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">33.4<small>%</small></span> | 12.1<small>%</small> | 2.77 | -8.9<small>%</small> | -1.4<small>%</small> |