| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">25.2<small>%</small></span> | 11.9<small>%</small> | 2.12 | -7.6<small>%</small> | -1.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">34.4<small>%</small></span> | 12.0<small>%</small> | 2.86 | -8.9<small>%</small> | -1.4<small>%</small> |