| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-360750/) | <span style="color: tomato">10.1<small>%</small></span> | 13.8<small>%</small> | 0.73 | -13.7<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.6<small>%</small></span> | 15.9<small>%</small> | 1.61 | -19.1<small>%</small> | -2.4<small>%</small> |