| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-360750/) | <span style="color: tomato">12.5<small>%</small></span> | 14.3<small>%</small> | 0.88 | -13.1<small>%</small> | -3.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">27.4<small>%</small></span> | 15.8<small>%</small> | 1.73 | -19.2<small>%</small> | -2.3<small>%</small> |