| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-458730/) | <span style="color: tomato">11.5<small>%</small></span> | 13.3<small>%</small> | 0.86 | -13.9<small>%</small> | -3.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">15.4<small>%</small></span> | 14.2<small>%</small> | 1.09 | -13.1<small>%</small> | -3.3<small>%</small> |