| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-446720/) | <span style="color: tomato">14.5<small>%</small></span> | 14.2<small>%</small> | 1.03 | -13.1<small>%</small> | -3.4<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">14.5<small>%</small></span> | 14.0<small>%</small> | 1.04 | -13.3<small>%</small> | -3.4<small>%</small> |