| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-379800/) | <span style="color: tomato">8.6<small>%</small></span> | 13.7<small>%</small> | 0.63 | -13.9<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">25.5<small>%</small></span> | 16.0<small>%</small> | 1.59 | -19.2<small>%</small> | -2.4<small>%</small> |