| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-458730/) | <span style="color: tomato">8.8<small>%</small></span> | 13.7<small>%</small> | 0.64 | -13.9<small>%</small> | -3.6<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">13.0<small>%</small></span> | 14.5<small>%</small> | 0.90 | -13.1<small>%</small> | -3.3<small>%</small> |