| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜1호](/458750-vs-458730/) | <span style="color: tomato">10.1<small>%</small></span> | 13.8<small>%</small> | 0.73 | -13.7<small>%</small> | -3.6<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">12.1<small>%</small></span> | 14.3<small>%</small> | 0.85 | -13.1<small>%</small> | -3.4<small>%</small> |