| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스타겟커버드콜2호](/458760-vs-360750/) | <span style="color: tomato">9.0<small>%</small></span> | 13.4<small>%</small> | 0.67 | -13.9<small>%</small> | -3.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">27.5<small>%</small></span> | 15.8<small>%</small> | 1.74 | -19.2<small>%</small> | -2.3<small>%</small> |