| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-360750/) | <span style="color: tomato">13.0<small>%</small></span> | 14.5<small>%</small> | 0.90 | -13.1<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.5<small>%</small></span> | 16.1<small>%</small> | 1.59 | -19.1<small>%</small> | -2.4<small>%</small> |