| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-402970/) | <span style="color: tomato">25.0<small>%</small></span> | 11.9<small>%</small> | 2.10 | -7.6<small>%</small> | -1.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">25.3<small>%</small></span> | 11.6<small>%</small> | 2.18 | -7.8<small>%</small> | -1.8<small>%</small> |