| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX CD금리액티브(합성)](/459580-vs-357870/) | <span style="color: tomato">3.3<small>%</small></span> | 0.1<small>%</small> | 23.81 | 0.0<small>%</small> | 0.0<small>%</small> |
| TIGER CD금리투자KIS(합성) | <span style="color: tomato">3.3<small>%</small></span> | 0.2<small>%</small> | 18.00 | -0.0<small>%</small> | -0.0<small>%</small> |