| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [히어로즈 미국달러SOFR금리액티브(합성)](/460270-vs-456610/) | <span style="color: tomato">11.9<small>%</small></span> | 8.8<small>%</small> | 1.36 | -5.1<small>%</small> | -1.3<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">12.0<small>%</small></span> | 8.3<small>%</small> | 1.45 | -4.9<small>%</small> | -1.4<small>%</small> |