| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국달러SOFR금리액티브(합성)](/460270-vs-456200/) | <span style="color: tomato">8.9<small>%</small></span> | 9.2<small>%</small> | 0.97 | -8.0<small>%</small> | -1.9<small>%</small> |
| PLUS 미국달러SOFR금리액티브(합성) | <span style="color: tomato">8.8<small>%</small></span> | 8.9<small>%</small> | 0.99 | -8.5<small>%</small> | -2.0<small>%</small> |