| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [히어로즈 미국달러SOFR금리액티브(합성)](/460270-vs-456200/) | <span style="color: tomato">10.5<small>%</small></span> | 8.8<small>%</small> | 1.18 | -5.1<small>%</small> | -1.4<small>%</small> |
| PLUS 미국달러SOFR금리액티브(합성) | <span style="color: tomato">11.1<small>%</small></span> | 8.3<small>%</small> | 1.34 | -4.8<small>%</small> | -1.4<small>%</small> |