| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국달러SOFR금리액티브(합성)](/460270-vs-456610/) | <span style="color: tomato">8.8<small>%</small></span> | 9.0<small>%</small> | 0.97 | -8.0<small>%</small> | -2.0<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">8.8<small>%</small></span> | 8.7<small>%</small> | 1.00 | -8.1<small>%</small> | -2.1<small>%</small> |