| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KIWOOM 미국달러SOFR금리액티브(합성)](/460270-vs-456610/) | <span style="color: tomato">9.3<small>%</small></span> | 9.1<small>%</small> | 1.02 | -8.0<small>%</small> | -2.0<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">9.2<small>%</small></span> | 8.8<small>%</small> | 1.05 | -8.1<small>%</small> | -2.0<small>%</small> |