| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">51.3<small>%</small></span> | 21.6<small>%</small> | 2.37 | -20.5<small>%</small> | -3.1<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">51.3<small>%</small></span> | 23.3<small>%</small> | 2.20 | -22.6<small>%</small> | -3.1<small>%</small> |