| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">41.7<small>%</small></span> | 24.9<small>%</small> | 1.67 | -30.8<small>%</small> | -4.8<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">43.0<small>%</small></span> | 25.9<small>%</small> | 1.66 | -31.4<small>%</small> | -4.8<small>%</small> |