| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">41.0<small>%</small></span> | 25.2<small>%</small> | 1.63 | -30.8<small>%</small> | -5.1<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">41.6<small>%</small></span> | 26.2<small>%</small> | 1.58 | -31.4<small>%</small> | -5.1<small>%</small> |