| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크TOP7 Plus](/465580-vs-381170/) | <span style="color: tomato">58.6<small>%</small></span> | 25.3<small>%</small> | 2.31 | -23.2<small>%</small> | -3.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">54.6<small>%</small></span> | 23.9<small>%</small> | 2.29 | -22.6<small>%</small> | -3.3<small>%</small> |