| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크TOP7 Plus](/465580-vs-381170/) | <span style="color: tomato">46.3<small>%</small></span> | 27.1<small>%</small> | 1.71 | -30.1<small>%</small> | -5.1<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">43.0<small>%</small></span> | 26.4<small>%</small> | 1.63 | -31.4<small>%</small> | -5.1<small>%</small> |