| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">36.5<small>%</small></span> | 29.2<small>%</small> | 1.25 | -31.8<small>%</small> | -5.3<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">44.8<small>%</small></span> | 28.1<small>%</small> | 1.59 | -31.4<small>%</small> | -6.0<small>%</small> |