| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">39.0<small>%</small></span> | 28.2<small>%</small> | 1.38 | -31.8<small>%</small> | -4.9<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">50.1<small>%</small></span> | 27.1<small>%</small> | 1.85 | -31.4<small>%</small> | -5.5<small>%</small> |