| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">38.4<small>%</small></span> | 28.1<small>%</small> | 1.36 | -31.8<small>%</small> | -4.9<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">50.4<small>%</small></span> | 27.0<small>%</small> | 1.87 | -31.4<small>%</small> | -5.4<small>%</small> |