| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-461900/) | <span style="color: tomato">47.3<small>%</small></span> | 23.3<small>%</small> | 2.03 | -20.1<small>%</small> | -3.4<small>%</small> |
| PLUS 미국테크TOP10 | <span style="color: tomato">51.8<small>%</small></span> | 24.4<small>%</small> | 2.12 | -20.5<small>%</small> | -4.2<small>%</small> |