| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-381170/) | <span style="color: tomato">51.5<small>%</small></span> | 23.3<small>%</small> | 2.21 | -20.1<small>%</small> | -3.4<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">55.6<small>%</small></span> | 26.7<small>%</small> | 2.09 | -22.6<small>%</small> | -4.2<small>%</small> |