| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-461900/) | <span style="color: tomato">26.7<small>%</small></span> | 23.2<small>%</small> | 1.15 | -30.0<small>%</small> | -5.2<small>%</small> |
| PLUS 미국테크TOP10 | <span style="color: tomato">27.7<small>%</small></span> | 25.0<small>%</small> | 1.11 | -30.8<small>%</small> | -6.0<small>%</small> |