| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-461900/) | <span style="color: tomato">40.3<small>%</small></span> | 25.3<small>%</small> | 1.59 | -30.0<small>%</small> | -5.5<small>%</small> |
| PLUS 미국테크TOP10 | <span style="color: tomato">43.4<small>%</small></span> | 26.9<small>%</small> | 1.61 | -30.8<small>%</small> | -5.9<small>%</small> |