| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-381170/) | <span style="color: tomato">52.0<small>%</small></span> | 22.9<small>%</small> | 2.27 | -20.1<small>%</small> | -3.2<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">54.7<small>%</small></span> | 26.2<small>%</small> | 2.09 | -22.6<small>%</small> | -4.0<small>%</small> |