| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10타겟커버드콜](/474220-vs-381170/) | <span style="color: tomato">38.9<small>%</small></span> | 26.3<small>%</small> | 1.48 | -30.0<small>%</small> | -6.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">42.4<small>%</small></span> | 29.0<small>%</small> | 1.46 | -31.4<small>%</small> | -6.5<small>%</small> |