| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-379800/) | <span style="color: tomato">20.1<small>%</small></span> | 19.6<small>%</small> | 1.02 | -15.6<small>%</small> | -4.1<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.7<small>%</small></span> | 18.3<small>%</small> | 1.24 | -19.2<small>%</small> | -3.0<small>%</small> |