| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-379800/) | <span style="color: tomato">21.0<small>%</small></span> | 19.1<small>%</small> | 1.10 | -15.6<small>%</small> | -4.0<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">26.4<small>%</small></span> | 17.7<small>%</small> | 1.50 | -19.2<small>%</small> | -2.8<small>%</small> |