| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-289480/) | <span style="color: tomato">22.8<small>%</small></span> | 17.0<small>%</small> | 1.34 | -22.4<small>%</small> | -6.9<small>%</small> |
| TIGER 200커버드콜 | <span style="color: tomato">12.1<small>%</small></span> | 14.5<small>%</small> | 0.84 | -14.6<small>%</small> | -4.2<small>%</small> |