| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-148020/) | <span style="color: tomato">19.1<small>%</small></span> | 18.0<small>%</small> | 1.06 | -22.4<small>%</small> | -6.7<small>%</small> |
| RISE 200 | <span style="color: tomato">30.4<small>%</small></span> | 21.9<small>%</small> | 1.39 | -21.8<small>%</small> | -7.4<small>%</small> |