| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: tomato">10.2<small>%</small></span> | 17.0<small>%</small> | 0.60 | -22.4<small>%</small> | -7.5<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">11.0<small>%</small></span> | 18.6<small>%</small> | 0.59 | -18.7<small>%</small> | -6.9<small>%</small> |