| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: tomato">28.3<small>%</small></span> | 29.4<small>%</small> | 0.96 | -31.6<small>%</small> | -7.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">55.9<small>%</small></span> | 41.2<small>%</small> | 1.36 | -40.8<small>%</small> | -8.3<small>%</small> |