| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: tomato">14.6<small>%</small></span> | 16.9<small>%</small> | 0.86 | -22.4<small>%</small> | -7.1<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">17.5<small>%</small></span> | 18.4<small>%</small> | 0.95 | -18.7<small>%</small> | -6.6<small>%</small> |