| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-148020/) | <span style="color: tomato">20.1<small>%</small></span> | 17.0<small>%</small> | 1.18 | -22.4<small>%</small> | -6.9<small>%</small> |
| RISE 200 | <span style="color: tomato">31.1<small>%</small></span> | 20.8<small>%</small> | 1.49 | -21.8<small>%</small> | -7.6<small>%</small> |