| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: tomato">20.7<small>%</small></span> | 17.8<small>%</small> | 1.16 | -22.4<small>%</small> | -6.7<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">17.9<small>%</small></span> | 18.4<small>%</small> | 0.97 | -18.7<small>%</small> | -6.2<small>%</small> |