| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-289480/) | <span style="color: cornflowerblue">-8.6<small>%</small></span> | 17.1<small>%</small> | -0.51 | -15.1<small>%</small> | -5.0<small>%</small> |
| TIGER 200커버드콜 | <span style="color: cornflowerblue">-4.9<small>%</small></span> | 15.8<small>%</small> | -0.31 | -14.6<small>%</small> | -4.4<small>%</small> |