| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: tomato">12.6<small>%</small></span> | 17.0<small>%</small> | 0.74 | -22.4<small>%</small> | -7.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">18.4<small>%</small></span> | 20.7<small>%</small> | 0.88 | -21.6<small>%</small> | -8.5<small>%</small> |