| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: tomato">23.6<small>%</small></span> | 17.4<small>%</small> | 1.36 | -22.4<small>%</small> | -6.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">36.9<small>%</small></span> | 21.3<small>%</small> | 1.73 | -21.6<small>%</small> | -7.4<small>%</small> |