| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-379810/) | <span style="color: tomato">26.0<small>%</small></span> | 23.4<small>%</small> | 1.11 | -24.2<small>%</small> | -4.7<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">26.2<small>%</small></span> | 23.4<small>%</small> | 1.12 | -24.3<small>%</small> | -4.7<small>%</small> |