| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-379810/) | <span style="color: tomato">34.2<small>%</small></span> | 19.9<small>%</small> | 1.72 | -15.9<small>%</small> | -3.5<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">34.5<small>%</small></span> | 19.9<small>%</small> | 1.74 | -15.9<small>%</small> | -3.5<small>%</small> |