| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">25.7<small>%</small></span> | 23.0<small>%</small> | 1.12 | -24.2<small>%</small> | -4.5<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">25.7<small>%</small></span> | 23.3<small>%</small> | 1.10 | -24.3<small>%</small> | -4.5<small>%</small> |