| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">32.7<small>%</small></span> | 19.9<small>%</small> | 1.64 | -15.9<small>%</small> | -3.8<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">32.6<small>%</small></span> | 20.4<small>%</small> | 1.60 | -16.4<small>%</small> | -3.8<small>%</small> |