| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">40.7<small>%</small></span> | 19.7<small>%</small> | 2.07 | -15.9<small>%</small> | -3.4<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">40.8<small>%</small></span> | 20.1<small>%</small> | 2.03 | -16.4<small>%</small> | -3.4<small>%</small> |