| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크7+데일리타겟커버드콜(합성)](/480020-vs-465580/) | <span style="color: tomato">50.5<small>%</small></span> | 29.7<small>%</small> | 1.70 | -23.2<small>%</small> | -6.0<small>%</small> |
| ACE 미국빅테크TOP7 Plus | <span style="color: tomato">63.0<small>%</small></span> | 30.8<small>%</small> | 2.05 | -23.2<small>%</small> | -5.6<small>%</small> |