| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500데일리타겟커버드콜(합성)](/480030-vs-379800/) | <span style="color: tomato">17.5<small>%</small></span> | 17.0<small>%</small> | 1.03 | -17.1<small>%</small> | -4.0<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">22.1<small>%</small></span> | 19.4<small>%</small> | 1.14 | -19.2<small>%</small> | -3.4<small>%</small> |