| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500데일리타겟커버드콜(합성)](/480030-vs-360200/) | <span style="color: tomato">17.9<small>%</small></span> | 16.7<small>%</small> | 1.08 | -17.1<small>%</small> | -3.9<small>%</small> |
| ACE 미국S&P500 | <span style="color: tomato">23.2<small>%</small></span> | 18.5<small>%</small> | 1.25 | -19.1<small>%</small> | -3.3<small>%</small> |