| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500데일리타겟커버드콜(합성)](/480030-vs-360200/) | <span style="color: tomato">34.3<small>%</small></span> | 13.9<small>%</small> | 2.47 | -9.5<small>%</small> | -2.0<small>%</small> |
| ACE 미국S&P500 | <span style="color: tomato">40.5<small>%</small></span> | 14.5<small>%</small> | 2.79 | -9.2<small>%</small> | -1.7<small>%</small> |