| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크7+데일리타겟커버드콜(합성)](/480020-vs-465580/) | <span style="color: tomato">30.0<small>%</small></span> | 26.8<small>%</small> | 1.12 | -29.3<small>%</small> | -8.9<small>%</small> |
| ACE 미국빅테크TOP7 Plus | <span style="color: tomato">41.3<small>%</small></span> | 30.9<small>%</small> | 1.34 | -30.1<small>%</small> | -7.4<small>%</small> |