| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">68.6<small>%</small></span> | 27.4<small>%</small> | 2.51 | -21.7<small>%</small> | -5.4<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">68.3<small>%</small></span> | 28.4<small>%</small> | 2.40 | -22.6<small>%</small> | -5.4<small>%</small> |