| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">43.5<small>%</small></span> | 28.8<small>%</small> | 1.51 | -31.4<small>%</small> | -7.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">42.9<small>%</small></span> | 29.2<small>%</small> | 1.47 | -31.4<small>%</small> | -7.0<small>%</small> |