| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">45.6<small>%</small></span> | 28.6<small>%</small> | 1.59 | -21.7<small>%</small> | -6.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">45.7<small>%</small></span> | 29.7<small>%</small> | 1.54 | -22.6<small>%</small> | -6.0<small>%</small> |