| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-360750/) | <span style="color: tomato">37.5<small>%</small></span> | 13.9<small>%</small> | 2.70 | -8.8<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">39.0<small>%</small></span> | 14.4<small>%</small> | 2.72 | -9.1<small>%</small> | -1.8<small>%</small> |