| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-480030/) | <span style="color: tomato">18.3<small>%</small></span> | 19.5<small>%</small> | 0.94 | -19.2<small>%</small> | -3.7<small>%</small> |
| ACE 미국500데일리타겟커버드콜(합성) | <span style="color: tomato">15.8<small>%</small></span> | 17.2<small>%</small> | 0.92 | -17.1<small>%</small> | -4.2<small>%</small> |