| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-480030/) | <span style="color: tomato">28.3<small>%</small></span> | 13.7<small>%</small> | 2.08 | -8.8<small>%</small> | -2.1<small>%</small> |
| ACE 미국500데일리타겟커버드콜(합성) | <span style="color: tomato">25.2<small>%</small></span> | 13.9<small>%</small> | 1.81 | -9.5<small>%</small> | -2.5<small>%</small> |