| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-379800/) | <span style="color: tomato">37.5<small>%</small></span> | 13.9<small>%</small> | 2.70 | -8.8<small>%</small> | -1.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">39.1<small>%</small></span> | 14.2<small>%</small> | 2.76 | -8.9<small>%</small> | -1.8<small>%</small> |