| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-379800/) | <span style="color: tomato">18.7<small>%</small></span> | 16.7<small>%</small> | 1.12 | -19.2<small>%</small> | -2.8<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">19.6<small>%</small></span> | 16.9<small>%</small> | 1.16 | -19.2<small>%</small> | -2.8<small>%</small> |