| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-360750/) | <span style="color: tomato">20.1<small>%</small></span> | 18.5<small>%</small> | 1.09 | -19.2<small>%</small> | -3.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">21.1<small>%</small></span> | 18.6<small>%</small> | 1.13 | -19.1<small>%</small> | -3.1<small>%</small> |