| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-379800/) | <span style="color: tomato">36.5<small>%</small></span> | 14.4<small>%</small> | 2.54 | -8.8<small>%</small> | -2.0<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">38.5<small>%</small></span> | 14.7<small>%</small> | 2.61 | -8.9<small>%</small> | -2.0<small>%</small> |