| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-480030/) | <span style="color: tomato">23.3<small>%</small></span> | 18.2<small>%</small> | 1.28 | -19.2<small>%</small> | -3.1<small>%</small> |
| ACE 미국500데일리타겟커버드콜(합성) | <span style="color: tomato">20.3<small>%</small></span> | 16.2<small>%</small> | 1.25 | -17.1<small>%</small> | -3.6<small>%</small> |