| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458760/) | <span style="color: tomato">7.9<small>%</small></span> | 15.4<small>%</small> | 0.51 | -14.7<small>%</small> | -5.5<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">9.1<small>%</small></span> | 15.4<small>%</small> | 0.59 | -13.9<small>%</small> | -5.0<small>%</small> |