| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-360750/) | <span style="color: tomato">8.4<small>%</small></span> | 15.3<small>%</small> | 0.55 | -14.7<small>%</small> | -5.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">24.3<small>%</small></span> | 18.6<small>%</small> | 1.31 | -19.2<small>%</small> | -3.0<small>%</small> |