| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458760/) | <span style="color: tomato">28.5<small>%</small></span> | 12.5<small>%</small> | 2.27 | -4.7<small>%</small> | -1.5<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">30.3<small>%</small></span> | 12.2<small>%</small> | 2.48 | -4.9<small>%</small> | -1.5<small>%</small> |