| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458760/) | <span style="color: tomato">34.5<small>%</small></span> | 12.8<small>%</small> | 2.69 | -4.7<small>%</small> | -1.6<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">36.0<small>%</small></span> | 12.5<small>%</small> | 2.88 | -4.9<small>%</small> | -1.5<small>%</small> |