| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458730/) | <span style="color: tomato">4.4<small>%</small></span> | 16.4<small>%</small> | 0.27 | -14.6<small>%</small> | -4.5<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">7.9<small>%</small></span> | 17.2<small>%</small> | 0.46 | -13.1<small>%</small> | -4.1<small>%</small> |