| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: tomato">24.9<small>%</small></span> | 32.9<small>%</small> | 0.76 | -22.9<small>%</small> | -7.5<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: tomato">24.2<small>%</small></span> | 34.4<small>%</small> | 0.70 | -24.4<small>%</small> | -8.4<small>%</small> |