| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: tomato">12.2<small>%</small></span> | 33.8<small>%</small> | 0.36 | -22.9<small>%</small> | -8.2<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: tomato">9.2<small>%</small></span> | 35.4<small>%</small> | 0.26 | -24.4<small>%</small> | -9.1<small>%</small> |