| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-360750/) | <span style="color: tomato">23.9<small>%</small></span> | 12.3<small>%</small> | 1.94 | -4.7<small>%</small> | -1.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">28.0<small>%</small></span> | 14.3<small>%</small> | 1.96 | -9.1<small>%</small> | -2.1<small>%</small> |