| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458730/) | <span style="color: tomato">6.6<small>%</small></span> | 15.5<small>%</small> | 0.43 | -14.7<small>%</small> | -5.3<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">10.4<small>%</small></span> | 16.3<small>%</small> | 0.64 | -13.1<small>%</small> | -4.4<small>%</small> |