| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-360750/) | <span style="color: tomato">5.1<small>%</small></span> | 15.7<small>%</small> | 0.32 | -14.7<small>%</small> | -5.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.2<small>%</small></span> | 18.8<small>%</small> | 1.18 | -19.1<small>%</small> | -3.2<small>%</small> |