| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: tomato">30.9<small>%</small></span> | 33.5<small>%</small> | 0.92 | -22.9<small>%</small> | -7.8<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: tomato">31.8<small>%</small></span> | 35.0<small>%</small> | 0.91 | -24.4<small>%</small> | -8.7<small>%</small> |