| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458730/) | <span style="color: tomato">31.6<small>%</small></span> | 12.7<small>%</small> | 2.49 | -4.7<small>%</small> | -1.6<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">37.3<small>%</small></span> | 13.8<small>%</small> | 2.70 | -5.1<small>%</small> | -1.6<small>%</small> |