| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">16.7<small>%</small></span> | 24.8<small>%</small> | 0.67 | -24.3<small>%</small> | -5.3<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">18.3<small>%</small></span> | 24.7<small>%</small> | 0.74 | -24.3<small>%</small> | -5.3<small>%</small> |