| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">18.3<small>%</small></span> | 22.0<small>%</small> | 0.83 | -24.3<small>%</small> | -4.4<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">19.9<small>%</small></span> | 22.1<small>%</small> | 0.90 | -24.3<small>%</small> | -4.5<small>%</small> |