| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">17.0<small>%</small></span> | 25.1<small>%</small> | 0.68 | -24.3<small>%</small> | -5.5<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">18.5<small>%</small></span> | 25.0<small>%</small> | 0.74 | -24.3<small>%</small> | -5.4<small>%</small> |