| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500동일가중](/488500-vs-379800/) | <span style="color: tomato">15.2<small>%</small></span> | 17.0<small>%</small> | 0.89 | -15.9<small>%</small> | -2.8<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">17.8<small>%</small></span> | 17.5<small>%</small> | 1.02 | -19.2<small>%</small> | -2.8<small>%</small> |