| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500동일가중](/488500-vs-379800/) | <span style="color: tomato">37.2<small>%</small></span> | 16.0<small>%</small> | 2.32 | -6.5<small>%</small> | -1.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">37.2<small>%</small></span> | 16.6<small>%</small> | 2.24 | -7.5<small>%</small> | -1.8<small>%</small> |