| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500동일가중](/488500-vs-379800/) | <span style="color: tomato">13.9<small>%</small></span> | 19.0<small>%</small> | 0.73 | -15.9<small>%</small> | -3.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">21.6<small>%</small></span> | 19.7<small>%</small> | 1.10 | -19.2<small>%</small> | -3.2<small>%</small> |