| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-161510/) | <span style="color: tomato">39.1<small>%</small></span> | 15.4<small>%</small> | 2.54 | -5.4<small>%</small> | -1.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">27.5<small>%</small></span> | 16.9<small>%</small> | 1.63 | -7.7<small>%</small> | -3.9<small>%</small> |