| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-069500/) | <span style="color: tomato">19.7<small>%</small></span> | 16.0<small>%</small> | 1.23 | -17.1<small>%</small> | -5.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">20.6<small>%</small></span> | 19.7<small>%</small> | 1.05 | -15.5<small>%</small> | -5.5<small>%</small> |