| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-161510/) | <span style="color: tomato">21.8<small>%</small></span> | 15.4<small>%</small> | 1.42 | -5.4<small>%</small> | -1.9<small>%</small> |
| PLUS 고배당주 | <span style="color: cornflowerblue">-2.7<small>%</small></span> | 16.8<small>%</small> | -0.16 | -7.7<small>%</small> | -4.2<small>%</small> |