| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-161510/) | <span style="color: tomato">28.2<small>%</small></span> | 15.1<small>%</small> | 1.87 | -5.4<small>%</small> | -1.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">15.2<small>%</small></span> | 16.3<small>%</small> | 0.93 | -7.7<small>%</small> | -4.0<small>%</small> |