| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-069500/) | <span style="color: tomato">10.2<small>%</small></span> | 16.9<small>%</small> | 0.61 | -7.4<small>%</small> | -2.0<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-20.5<small>%</small></span> | 19.0<small>%</small> | -1.08 | -14.3<small>%</small> | -6.6<small>%</small> |