| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 고배당주위클리커버드콜](/489030-vs-069500/) | <span style="color: tomato">10.2<small>%</small></span> | 16.4<small>%</small> | 0.62 | -20.6<small>%</small> | -7.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">47.2<small>%</small></span> | 21.1<small>%</small> | 2.24 | -15.5<small>%</small> | -4.8<small>%</small> |