| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스](/489250-vs-458730/) | <span style="color: tomato">8.0<small>%</small></span> | 17.3<small>%</small> | 0.46 | -13.3<small>%</small> | -4.7<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">7.8<small>%</small></span> | 17.2<small>%</small> | 0.45 | -13.1<small>%</small> | -4.7<small>%</small> |