| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스](/489250-vs-458730/) | <span style="color: tomato">51.5<small>%</small></span> | 13.3<small>%</small> | 3.88 | -3.0<small>%</small> | -0.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">50.1<small>%</small></span> | 13.4<small>%</small> | 3.75 | -2.8<small>%</small> | -0.8<small>%</small> |