| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스](/489250-vs-458730/) | <span style="color: tomato">10.7<small>%</small></span> | 16.5<small>%</small> | 0.65 | -13.3<small>%</small> | -4.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">10.5<small>%</small></span> | 16.4<small>%</small> | 0.64 | -13.1<small>%</small> | -4.7<small>%</small> |