| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-483290/) | <span style="color: tomato">9.8<small>%</small></span> | 14.1<small>%</small> | 0.69 | -12.6<small>%</small> | -3.3<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: tomato">11.6<small>%</small></span> | 15.1<small>%</small> | 0.77 | -14.7<small>%</small> | -4.8<small>%</small> |