| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-458760/) | <span style="color: tomato">10.6<small>%</small></span> | 14.1<small>%</small> | 0.75 | -12.6<small>%</small> | -3.4<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">13.4<small>%</small></span> | 14.9<small>%</small> | 0.90 | -13.9<small>%</small> | -4.2<small>%</small> |