| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-360750/) | <span style="color: tomato">4.4<small>%</small></span> | 15.6<small>%</small> | 0.28 | -12.6<small>%</small> | -4.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">24.0<small>%</small></span> | 19.5<small>%</small> | 1.23 | -19.2<small>%</small> | -3.1<small>%</small> |