| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-458730/) | <span style="color: tomato">2.3<small>%</small></span> | 16.4<small>%</small> | 0.14 | -12.6<small>%</small> | -4.7<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">3.1<small>%</small></span> | 17.6<small>%</small> | 0.18 | -13.1<small>%</small> | -5.1<small>%</small> |