| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-483290/) | <span style="color: tomato">6.4<small>%</small></span> | 15.4<small>%</small> | 0.42 | -12.6<small>%</small> | -4.4<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: tomato">6.9<small>%</small></span> | 15.8<small>%</small> | 0.43 | -14.7<small>%</small> | -6.3<small>%</small> |