| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-458730/) | <span style="color: tomato">5.7<small>%</small></span> | 15.5<small>%</small> | 0.37 | -12.6<small>%</small> | -4.4<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">9.1<small>%</small></span> | 16.7<small>%</small> | 0.54 | -13.1<small>%</small> | -5.0<small>%</small> |