| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-458760/) | <span style="color: tomato">6.8<small>%</small></span> | 15.4<small>%</small> | 0.44 | -12.6<small>%</small> | -4.4<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">8.3<small>%</small></span> | 15.9<small>%</small> | 0.52 | -13.9<small>%</small> | -5.7<small>%</small> |