| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-458760/) | <span style="color: cornflowerblue">-0.5<small>%</small></span> | 16.9<small>%</small> | -0.03 | -12.6<small>%</small> | -4.7<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: cornflowerblue">-0.1<small>%</small></span> | 17.6<small>%</small> | -0.00 | -13.9<small>%</small> | -5.2<small>%</small> |