| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-360750/) | <span style="color: cornflowerblue">-1.8<small>%</small></span> | 17.1<small>%</small> | -0.11 | -12.6<small>%</small> | -4.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.9<small>%</small></span> | 21.6<small>%</small> | 0.88 | -19.1<small>%</small> | -4.0<small>%</small> |