| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-483290/) | <span style="color: tomato">2.5<small>%</small></span> | 16.8<small>%</small> | 0.15 | -12.6<small>%</small> | -4.7<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: tomato">1.5<small>%</small></span> | 17.3<small>%</small> | 0.08 | -14.6<small>%</small> | -5.7<small>%</small> |