| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국배당100데일리고정커버드콜](/490600-vs-360750/) | <span style="color: tomato">3.0<small>%</small></span> | 16.0<small>%</small> | 0.19 | -12.6<small>%</small> | -4.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">23.7<small>%</small></span> | 20.0<small>%</small> | 1.19 | -19.1<small>%</small> | -3.4<small>%</small> |