| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국테크100데일리고정커버드콜](/491620-vs-486290/) | <span style="color: tomato">28.2<small>%</small></span> | 25.6<small>%</small> | 1.10 | -26.1<small>%</small> | -5.4<small>%</small> |
| TIGER 미국나스닥100타겟데일리커버드콜 | <span style="color: tomato">28.0<small>%</small></span> | 25.0<small>%</small> | 1.12 | -24.3<small>%</small> | -4.9<small>%</small> |