| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국테크100데일리고정커버드콜](/491620-vs-379810/) | <span style="color: tomato">39.3<small>%</small></span> | 24.0<small>%</small> | 1.64 | -26.1<small>%</small> | -4.6<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">39.4<small>%</small></span> | 23.4<small>%</small> | 1.68 | -24.3<small>%</small> | -4.1<small>%</small> |