| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국테크100데일리고정커버드콜](/491620-vs-486290/) | <span style="color: tomato">30.5<small>%</small></span> | 26.2<small>%</small> | 1.16 | -26.1<small>%</small> | -5.8<small>%</small> |
| TIGER 미국나스닥100타겟데일리커버드콜 | <span style="color: tomato">31.5<small>%</small></span> | 25.6<small>%</small> | 1.23 | -24.3<small>%</small> | -5.2<small>%</small> |