| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국테크100데일리고정커버드콜](/491620-vs-486290/) | <span style="color: tomato">34.3<small>%</small></span> | 24.6<small>%</small> | 1.39 | -26.1<small>%</small> | -5.0<small>%</small> |
| TIGER 미국나스닥100타겟데일리커버드콜 | <span style="color: tomato">32.4<small>%</small></span> | 24.0<small>%</small> | 1.35 | -24.3<small>%</small> | -4.5<small>%</small> |