| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국테크100데일리고정커버드콜](/491620-vs-379810/) | <span style="color: tomato">26.4<small>%</small></span> | 21.8<small>%</small> | 1.21 | -26.1<small>%</small> | -4.5<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">27.6<small>%</small></span> | 21.4<small>%</small> | 1.29 | -24.3<small>%</small> | -4.3<small>%</small> |