| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스TR](/493420-vs-446720/) | <span style="color: tomato">10.0<small>%</small></span> | 16.8<small>%</small> | 0.59 | -13.0<small>%</small> | -5.0<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">9.9<small>%</small></span> | 16.6<small>%</small> | 0.60 | -13.3<small>%</small> | -5.0<small>%</small> |