| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스TR](/493420-vs-446720/) | <span style="color: tomato">6.8<small>%</small></span> | 17.2<small>%</small> | 0.40 | -13.0<small>%</small> | -5.3<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">7.2<small>%</small></span> | 17.0<small>%</small> | 0.42 | -13.3<small>%</small> | -5.4<small>%</small> |