| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스TR](/493420-vs-446720/) | <span style="color: tomato">11.4<small>%</small></span> | 15.6<small>%</small> | 0.73 | -13.0<small>%</small> | -3.9<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">11.2<small>%</small></span> | 15.4<small>%</small> | 0.73 | -13.3<small>%</small> | -3.9<small>%</small> |