| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국AI빅테크10타겟데일리커버드콜](/493810-vs-490090/) | <span style="color: tomato">38.3<small>%</small></span> | 27.3<small>%</small> | 1.41 | -30.9<small>%</small> | -6.4<small>%</small> |
| TIGER 미국AI빅테크10 | <span style="color: tomato">39.0<small>%</small></span> | 28.5<small>%</small> | 1.37 | -31.5<small>%</small> | -6.2<small>%</small> |