| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국AI빅테크10타겟데일리커버드콜](/493810-vs-490090/) | <span style="color: tomato">22.5<small>%</small></span> | 24.7<small>%</small> | 0.91 | -30.9<small>%</small> | -5.9<small>%</small> |
| TIGER 미국AI빅테크10 | <span style="color: tomato">23.8<small>%</small></span> | 25.8<small>%</small> | 0.92 | -31.5<small>%</small> | -5.7<small>%</small> |