| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국AI빅테크10타겟데일리커버드콜](/493810-vs-490090/) | <span style="color: tomato">23.5<small>%</small></span> | 24.4<small>%</small> | 0.96 | -30.9<small>%</small> | -6.1<small>%</small> |
| TIGER 미국AI빅테크10 | <span style="color: tomato">24.8<small>%</small></span> | 25.6<small>%</small> | 0.97 | -31.5<small>%</small> | -5.9<small>%</small> |