| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100데일리커버드콜OTM](/494300-vs-486290/) | <span style="color: tomato">13.5<small>%</small></span> | 20.9<small>%</small> | 0.65 | -21.0<small>%</small> | -5.4<small>%</small> |
| TIGER 미국나스닥100타겟데일리커버드콜 | <span style="color: tomato">19.9<small>%</small></span> | 24.8<small>%</small> | 0.80 | -24.3<small>%</small> | -4.9<small>%</small> |