| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100데일리커버드콜OTM](/494300-vs-379810/) | <span style="color: tomato">23.9<small>%</small></span> | 20.1<small>%</small> | 1.19 | -21.0<small>%</small> | -4.8<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">32.4<small>%</small></span> | 23.8<small>%</small> | 1.36 | -24.3<small>%</small> | -4.4<small>%</small> |