| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100데일리커버드콜OTM](/494300-vs-486290/) | <span style="color: tomato">22.0<small>%</small></span> | 20.0<small>%</small> | 1.10 | -21.0<small>%</small> | -4.6<small>%</small> |
| TIGER 미국나스닥100타겟데일리커버드콜 | <span style="color: tomato">27.1<small>%</small></span> | 23.7<small>%</small> | 1.14 | -24.3<small>%</small> | -4.2<small>%</small> |