| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100데일리커버드콜OTM](/494300-vs-379810/) | <span style="color: tomato">13.5<small>%</small></span> | 21.7<small>%</small> | 0.62 | -21.0<small>%</small> | -5.7<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">22.5<small>%</small></span> | 25.7<small>%</small> | 0.87 | -24.3<small>%</small> | -5.3<small>%</small> |