| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-458760/) | <span style="color: tomato">13.9<small>%</small></span> | 15.5<small>%</small> | 0.90 | -12.9<small>%</small> | -2.6<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">4.0<small>%</small></span> | 16.1<small>%</small> | 0.25 | -13.9<small>%</small> | -6.0<small>%</small> |