| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-483290/) | <span style="color: tomato">7.0<small>%</small></span> | 16.6<small>%</small> | 0.42 | -12.9<small>%</small> | -3.1<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: cornflowerblue">-5.5<small>%</small></span> | 17.1<small>%</small> | -0.32 | -14.7<small>%</small> | -6.4<small>%</small> |