| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-458730/) | <span style="color: tomato">6.4<small>%</small></span> | 14.6<small>%</small> | 0.44 | -14.7<small>%</small> | -2.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">11.3<small>%</small></span> | 15.3<small>%</small> | 0.74 | -13.1<small>%</small> | -3.8<small>%</small> |