| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-360750/) | <span style="color: tomato">4.4<small>%</small></span> | 17.5<small>%</small> | 0.25 | -12.9<small>%</small> | -3.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">13.6<small>%</small></span> | 21.9<small>%</small> | 0.62 | -19.1<small>%</small> | -4.2<small>%</small> |