| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-458730/) | <span style="color: tomato">8.1<small>%</small></span> | 16.4<small>%</small> | 0.50 | -12.9<small>%</small> | -3.0<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">0.3<small>%</small></span> | 17.6<small>%</small> | 0.02 | -13.1<small>%</small> | -5.5<small>%</small> |