| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-483290/) | <span style="color: tomato">13.5<small>%</small></span> | 15.7<small>%</small> | 0.86 | -12.9<small>%</small> | -2.7<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: tomato">2.7<small>%</small></span> | 16.2<small>%</small> | 0.17 | -14.7<small>%</small> | -6.8<small>%</small> |