| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-490600/) | <span style="color: tomato">11.6<small>%</small></span> | 15.8<small>%</small> | 0.74 | -12.9<small>%</small> | -2.8<small>%</small> |
| RISE 미국배당100데일리고정커버드콜 | 0.0<small>%</small> | 15.9<small>%</small> | 0.00 | -12.6<small>%</small> | -4.8<small>%</small> |