| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-483290/) | <span style="color: tomato">11.1<small>%</small></span> | 16.1<small>%</small> | 0.69 | -12.9<small>%</small> | -2.9<small>%</small> |
| KODEX 미국배당다우존스타겟커버드콜 | <span style="color: cornflowerblue">-1.6<small>%</small></span> | 16.6<small>%</small> | -0.10 | -14.7<small>%</small> | -6.7<small>%</small> |