| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-490600/) | <span style="color: tomato">12.5<small>%</small></span> | 16.0<small>%</small> | 0.78 | -12.9<small>%</small> | -2.9<small>%</small> |
| RISE 미국배당100데일리고정커버드콜 | <span style="color: tomato">2.4<small>%</small></span> | 16.0<small>%</small> | 0.15 | -12.6<small>%</small> | -4.8<small>%</small> |