| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-458760/) | <span style="color: tomato">11.5<small>%</small></span> | 16.1<small>%</small> | 0.72 | -12.9<small>%</small> | -2.9<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: cornflowerblue">-0.3<small>%</small></span> | 16.8<small>%</small> | -0.02 | -13.9<small>%</small> | -6.1<small>%</small> |