| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-360750/) | <span style="color: tomato">12.7<small>%</small></span> | 15.8<small>%</small> | 0.81 | -12.9<small>%</small> | -2.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">23.7<small>%</small></span> | 19.7<small>%</small> | 1.20 | -19.2<small>%</small> | -3.3<small>%</small> |