| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국배당증가성장주데일리커버드콜](/494420-vs-360750/) | <span style="color: tomato">8.0<small>%</small></span> | 16.3<small>%</small> | 0.49 | -12.9<small>%</small> | -3.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.1<small>%</small></span> | 20.4<small>%</small> | 0.89 | -19.1<small>%</small> | -3.6<small>%</small> |