| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-475720/) | <span style="color: tomato">57.6<small>%</small></span> | 18.4<small>%</small> | 3.13 | -13.0<small>%</small> | -1.6<small>%</small> |
| RISE 200위클리커버드콜 | <span style="color: tomato">48.6<small>%</small></span> | 16.9<small>%</small> | 2.88 | -12.6<small>%</small> | -1.5<small>%</small> |