| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-475720/) | <span style="color: tomato">67.5<small>%</small></span> | 19.2<small>%</small> | 3.51 | -13.0<small>%</small> | -1.6<small>%</small> |
| RISE 200위클리커버드콜 | <span style="color: tomato">56.9<small>%</small></span> | 17.5<small>%</small> | 3.25 | -12.6<small>%</small> | -1.5<small>%</small> |