| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-166400/) | <span style="color: tomato">36.3<small>%</small></span> | 18.1<small>%</small> | 2.00 | -13.0<small>%</small> | -1.8<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">31.3<small>%</small></span> | 17.3<small>%</small> | 1.81 | -12.9<small>%</small> | -1.6<small>%</small> |