| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-069500/) | <span style="color: tomato">45.0<small>%</small></span> | 18.0<small>%</small> | 2.50 | -13.0<small>%</small> | -1.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">61.0<small>%</small></span> | 19.9<small>%</small> | 3.06 | -13.5<small>%</small> | -2.0<small>%</small> |