| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-289480/) | <span style="color: tomato">38.3<small>%</small></span> | 18.7<small>%</small> | 2.05 | -13.0<small>%</small> | -1.8<small>%</small> |
| TIGER 200커버드콜 | <span style="color: tomato">21.3<small>%</small></span> | 14.3<small>%</small> | 1.49 | -10.8<small>%</small> | -1.0<small>%</small> |