| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-289480/) | <span style="color: tomato">58.9<small>%</small></span> | 20.0<small>%</small> | 2.94 | -13.0<small>%</small> | -1.7<small>%</small> |
| TIGER 200커버드콜 | <span style="color: tomato">24.2<small>%</small></span> | 13.6<small>%</small> | 1.78 | -10.8<small>%</small> | -0.8<small>%</small> |