| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-166400/) | <span style="color: tomato">76.0<small>%</small></span> | 42.8<small>%</small> | 1.77 | -39.8<small>%</small> | -6.0<small>%</small> |
| TIGER 200커버드콜OTM | <span style="color: tomato">55.0<small>%</small></span> | 34.2<small>%</small> | 1.61 | -22.5<small>%</small> | -2.3<small>%</small> |