| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-069500/) | <span style="color: tomato">55.4<small>%</small></span> | 18.4<small>%</small> | 3.01 | -13.0<small>%</small> | -1.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">74.2<small>%</small></span> | 20.4<small>%</small> | 3.64 | -13.5<small>%</small> | -1.9<small>%</small> |