| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-475720/) | <span style="color: tomato">40.8<small>%</small></span> | 18.1<small>%</small> | 2.26 | -13.0<small>%</small> | -1.8<small>%</small> |
| RISE 200위클리커버드콜 | <span style="color: tomato">34.9<small>%</small></span> | 16.7<small>%</small> | 2.09 | -12.6<small>%</small> | -1.7<small>%</small> |