| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200타겟위클리커버드콜](/498400-vs-069500/) | <span style="color: tomato">36.3<small>%</small></span> | 18.1<small>%</small> | 2.00 | -13.0<small>%</small> | -1.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">46.9<small>%</small></span> | 19.9<small>%</small> | 2.36 | -13.5<small>%</small> | -2.1<small>%</small> |