| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-069500/) | <span style="color: tomato">17.9<small>%</small></span> | 20.9<small>%</small> | 0.86 | -22.1<small>%</small> | -8.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.7<small>%</small></span> | 20.6<small>%</small> | 0.86 | -21.6<small>%</small> | -7.9<small>%</small> |