| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스닥 150 TR ETN](/530118-vs-229200/) | <span style="color: cornflowerblue">-17.1<small>%</small></span> | 27.9<small>%</small> | -0.61 | -30.8<small>%</small> | -12.0<small>%</small> |
| KODEX 코스닥150 | <span style="color: cornflowerblue">-18.4<small>%</small></span> | 28.0<small>%</small> | -0.66 | -30.5<small>%</small> | -11.9<small>%</small> |