| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-278530/) | <span style="color: cornflowerblue">-4.6<small>%</small></span> | 20.6<small>%</small> | -0.22 | -21.0<small>%</small> | -6.4<small>%</small> |
| KODEX 200TR | <span style="color: cornflowerblue">-4.7<small>%</small></span> | 20.3<small>%</small> | -0.23 | -20.4<small>%</small> | -6.3<small>%</small> |