| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 나스닥 100 ETN](/530120-vs-379810/) | <span style="color: tomato">31.9<small>%</small></span> | 23.1<small>%</small> | 1.38 | -16.0<small>%</small> | -4.5<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">31.9<small>%</small></span> | 21.8<small>%</small> | 1.46 | -15.9<small>%</small> | -4.4<small>%</small> |