| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 나스닥 100 ETN](/530120-vs-379810/) | <span style="color: tomato">26.2<small>%</small></span> | 25.2<small>%</small> | 1.04 | -24.3<small>%</small> | -4.8<small>%</small> |
| KODEX 미국나스닥100 | <span style="color: tomato">26.6<small>%</small></span> | 23.7<small>%</small> | 1.12 | -24.3<small>%</small> | -4.8<small>%</small> |