| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-278530/) | <span style="color: tomato">57.2<small>%</small></span> | 39.3<small>%</small> | 1.45 | -40.9<small>%</small> | -8.0<small>%</small> |
| KODEX 200TR | <span style="color: tomato">57.1<small>%</small></span> | 39.2<small>%</small> | 1.46 | -40.6<small>%</small> | -7.8<small>%</small> |