| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 S&P500 ETN](/530112-vs-379800/) | <span style="color: tomato">25.3<small>%</small></span> | 16.2<small>%</small> | 1.56 | -19.1<small>%</small> | -2.4<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">25.0<small>%</small></span> | 16.1<small>%</small> | 1.55 | -19.2<small>%</small> | -2.4<small>%</small> |