| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-278530/) | <span style="color: tomato">20.0<small>%</small></span> | 20.6<small>%</small> | 0.97 | -22.1<small>%</small> | -7.7<small>%</small> |
| KODEX 200TR | <span style="color: tomato">19.8<small>%</small></span> | 20.0<small>%</small> | 0.99 | -21.4<small>%</small> | -7.4<small>%</small> |