| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 S&P500 ETN](/530112-vs-379800/) | <span style="color: tomato">28.7<small>%</small></span> | 15.9<small>%</small> | 1.81 | -19.1<small>%</small> | -2.3<small>%</small> |
| KODEX 미국S&P500 | <span style="color: tomato">28.3<small>%</small></span> | 15.8<small>%</small> | 1.79 | -19.2<small>%</small> | -2.3<small>%</small> |