| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-069500/) | <span style="color: tomato">27.2<small>%</small></span> | 20.7<small>%</small> | 1.31 | -22.1<small>%</small> | -7.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">26.8<small>%</small></span> | 20.4<small>%</small> | 1.31 | -21.6<small>%</small> | -7.2<small>%</small> |