| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스닥 150 TR ETN](/530118-vs-229200/) | <span style="color: tomato">4.3<small>%</small></span> | 26.7<small>%</small> | 0.16 | -32.0<small>%</small> | -15.3<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">2.9<small>%</small></span> | 26.3<small>%</small> | 0.11 | -31.5<small>%</small> | -15.2<small>%</small> |