| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 S&P500 ETN](/530112-vs-379800/) | <span style="color: tomato">34.9<small>%</small></span> | 11.9<small>%</small> | 2.93 | -8.5<small>%</small> | -1.4<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">34.4<small>%</small></span> | 12.0<small>%</small> | 2.87 | -8.9<small>%</small> | -1.4<small>%</small> |