| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-069500/) | <span style="color: tomato">0.7<small>%</small></span> | 20.6<small>%</small> | 0.03 | -16.9<small>%</small> | -5.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">0.3<small>%</small></span> | 20.7<small>%</small> | 0.02 | -16.5<small>%</small> | -4.9<small>%</small> |