| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [키움 INDXX 미국테크탑10 ETN](/760005-vs-381170/) | <span style="color: tomato">42.4<small>%</small></span> | 24.3<small>%</small> | 1.74 | -31.5<small>%</small> | -4.9<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">41.6<small>%</small></span> | 24.1<small>%</small> | 1.72 | -31.4<small>%</small> | -4.7<small>%</small> |