| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [키움 INDXX 미국테크탑10 ETN](/760005-vs-381170/) | <span style="color: tomato">70.6<small>%</small></span> | 21.6<small>%</small> | 3.27 | -17.8<small>%</small> | -2.7<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">69.5<small>%</small></span> | 22.8<small>%</small> | 3.04 | -22.6<small>%</small> | -2.6<small>%</small> |