| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AAPW](/aapw-vs-aapl/) | <span style="color: tomato">20.2<small>%</small></span> | 34.9<small>%</small> | 0.58 | -36.3<small>%</small> | -10.3<small>%</small> |
| AAPL | <span style="color: tomato">21.7<small>%</small></span> | 30.4<small>%</small> | 0.71 | -30.2<small>%</small> | -7.9<small>%</small> |