| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AAPW](/aapw-vs-aapl/) | <span style="color: tomato">16.0<small>%</small></span> | 38.3<small>%</small> | 0.42 | -36.3<small>%</small> | -13.0<small>%</small> |
| AAPL | <span style="color: tomato">18.9<small>%</small></span> | 34.3<small>%</small> | 0.55 | -30.2<small>%</small> | -9.8<small>%</small> |