| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AAPW](/aapw-vs-aapl/) | <span style="color: tomato">9.0<small>%</small></span> | 39.1<small>%</small> | 0.23 | -36.3<small>%</small> | -13.7<small>%</small> |
| AAPL | <span style="color: tomato">12.5<small>%</small></span> | 35.0<small>%</small> | 0.36 | -30.2<small>%</small> | -10.3<small>%</small> |