| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-15.1<small>%</small></span> | 32.3<small>%</small> | -0.47 | -31.6<small>%</small> | -14.8<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-15.3<small>%</small></span> | 39.0<small>%</small> | -0.39 | -34.5<small>%</small> | -16.9<small>%</small> |