| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-12.4<small>%</small></span> | 33.2<small>%</small> | -0.37 | -31.6<small>%</small> | -13.8<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-12.2<small>%</small></span> | 40.1<small>%</small> | -0.30 | -34.5<small>%</small> | -16.0<small>%</small> |