| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-16.1<small>%</small></span> | 31.2<small>%</small> | -0.51 | -31.6<small>%</small> | -15.6<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-17.9<small>%</small></span> | 37.7<small>%</small> | -0.48 | -34.5<small>%</small> | -17.6<small>%</small> |