| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIEQ](/aieq-vs-spy/) | <span style="color: tomato">9.0<small>%</small></span> | 23.0<small>%</small> | 0.39 | -39.0<small>%</small> | -11.8<small>%</small> |
| SPY | <span style="color: tomato">14.4<small>%</small></span> | 19.3<small>%</small> | 0.75 | -33.7<small>%</small> | -5.1<small>%</small> |