| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIEQ](/aieq-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 23.2<small>%</small> | 0.40 | -39.0<small>%</small> | -12.0<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 19.4<small>%</small> | 0.75 | -33.7<small>%</small> | -5.2<small>%</small> |