| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIEQ](/aieq-vs-spy/) | <span style="color: tomato">8.3<small>%</small></span> | 23.0<small>%</small> | 0.36 | -39.0<small>%</small> | -12.7<small>%</small> |
| SPY | <span style="color: tomato">14.2<small>%</small></span> | 19.3<small>%</small> | 0.74 | -33.7<small>%</small> | -5.4<small>%</small> |