| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-36.7<small>%</small></span> | 50.0<small>%</small> | -0.73 | -62.6<small>%</small> | -29.7<small>%</small> |
| AI | <span style="color: cornflowerblue">-24.1<small>%</small></span> | 67.4<small>%</small> | -0.36 | -64.0<small>%</small> | -31.2<small>%</small> |