| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-36.6<small>%</small></span> | 49.7<small>%</small> | -0.74 | -62.6<small>%</small> | -30.3<small>%</small> |
| AI | <span style="color: cornflowerblue">-24.9<small>%</small></span> | 66.9<small>%</small> | -0.37 | -64.0<small>%</small> | -31.7<small>%</small> |