| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-42.1<small>%</small></span> | 49.3<small>%</small> | -0.86 | -80.3<small>%</small> | -44.1<small>%</small> |
| AI | <span style="color: cornflowerblue">-33.5<small>%</small></span> | 64.9<small>%</small> | -0.52 | -81.9<small>%</small> | -45.3<small>%</small> |