| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">31.8<small>%</small></span> | 42.6<small>%</small> | 0.75 | -53.9<small>%</small> | -19.2<small>%</small> |
| AMD | <span style="color: tomato">51.4<small>%</small></span> | 53.4<small>%</small> | 0.96 | -63.0<small>%</small> | -24.6<small>%</small> |