| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">17.5<small>%</small></span> | 38.1<small>%</small> | 0.46 | -32.0<small>%</small> | -12.0<small>%</small> |
| AMD | <span style="color: tomato">36.9<small>%</small></span> | 47.9<small>%</small> | 0.77 | -39.1<small>%</small> | -15.6<small>%</small> |