| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">17.2<small>%</small></span> | 40.0<small>%</small> | 0.43 | -53.9<small>%</small> | -20.2<small>%</small> |
| AMD | <span style="color: tomato">34.0<small>%</small></span> | 50.3<small>%</small> | 0.68 | -63.0<small>%</small> | -26.0<small>%</small> |