| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMOM](/amom-vs-spy/) | <span style="color: tomato">17.0<small>%</small></span> | 25.5<small>%</small> | 0.67 | -40.0<small>%</small> | -10.8<small>%</small> |
| SPY | <span style="color: tomato">16.2<small>%</small></span> | 19.5<small>%</small> | 0.83 | -33.7<small>%</small> | -4.9<small>%</small> |