| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMOM](/amom-vs-spy/) | <span style="color: tomato">15.2<small>%</small></span> | 24.9<small>%</small> | 0.61 | -40.0<small>%</small> | -11.6<small>%</small> |
| SPY | <span style="color: tomato">15.5<small>%</small></span> | 20.2<small>%</small> | 0.77 | -33.7<small>%</small> | -5.3<small>%</small> |