| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">23.6<small>%</small></span> | 25.9<small>%</small> | 0.91 | -23.7<small>%</small> | -5.5<small>%</small> |
| AMZN | <span style="color: tomato">26.4<small>%</small></span> | 32.3<small>%</small> | 0.82 | -30.9<small>%</small> | -7.5<small>%</small> |