| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">21.7<small>%</small></span> | 25.7<small>%</small> | 0.85 | -23.7<small>%</small> | -5.6<small>%</small> |
| AMZN | <span style="color: tomato">23.2<small>%</small></span> | 32.0<small>%</small> | 0.72 | -30.9<small>%</small> | -7.6<small>%</small> |