| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">24.5<small>%</small></span> | 25.5<small>%</small> | 0.96 | -23.7<small>%</small> | -4.6<small>%</small> |
| AMZN | <span style="color: tomato">25.1<small>%</small></span> | 31.7<small>%</small> | 0.79 | -30.9<small>%</small> | -6.7<small>%</small> |