| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">14.3<small>%</small></span> | 16.6<small>%</small> | 0.86 | -15.9<small>%</small> | -5.7<small>%</small> |
| AAPL | <span style="color: tomato">21.8<small>%</small></span> | 21.4<small>%</small> | 1.02 | -16.6<small>%</small> | -5.4<small>%</small> |