| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">11.1<small>%</small></span> | 21.7<small>%</small> | 0.51 | -31.1<small>%</small> | -7.8<small>%</small> |
| AAPL | <span style="color: tomato">19.5<small>%</small></span> | 26.5<small>%</small> | 0.74 | -33.4<small>%</small> | -8.1<small>%</small> |