| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">14.1<small>%</small></span> | 21.4<small>%</small> | 0.66 | -31.1<small>%</small> | -7.5<small>%</small> |
| AAPL | <span style="color: tomato">23.1<small>%</small></span> | 26.1<small>%</small> | 0.88 | -33.4<small>%</small> | -7.6<small>%</small> |