| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKG](/arkg-vs-xbi/) | <span style="color: tomato">2.7<small>%</small></span> | 39.1<small>%</small> | 0.07 | -83.6<small>%</small> | -33.1<small>%</small> |
| XBI | <span style="color: tomato">4.5<small>%</small></span> | 33.1<small>%</small> | 0.14 | -63.9<small>%</small> | -27.8<small>%</small> |