| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">14.3<small>%</small></span> | 38.2<small>%</small> | 0.37 | -80.9<small>%</small> | -28.8<small>%</small> |
| QQQ | <span style="color: tomato">18.4<small>%</small></span> | 21.9<small>%</small> | 0.84 | -35.1<small>%</small> | -6.1<small>%</small> |