| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">13.7<small>%</small></span> | 38.2<small>%</small> | 0.36 | -80.9<small>%</small> | -28.7<small>%</small> |
| QLD | <span style="color: tomato">28.5<small>%</small></span> | 43.9<small>%</small> | 0.65 | -63.7<small>%</small> | -13.9<small>%</small> |