| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">11.1<small>%</small></span> | 37.5<small>%</small> | 0.30 | -80.9<small>%</small> | -26.2<small>%</small> |
| QQQ | <span style="color: tomato">18.5<small>%</small></span> | 21.7<small>%</small> | 0.85 | -35.1<small>%</small> | -6.2<small>%</small> |