| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">14.5<small>%</small></span> | 38.1<small>%</small> | 0.38 | -80.9<small>%</small> | -30.6<small>%</small> |
| QLD | <span style="color: tomato">30.8<small>%</small></span> | 43.3<small>%</small> | 0.71 | -63.7<small>%</small> | -13.2<small>%</small> |