| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">9.7<small>%</small></span> | 37.4<small>%</small> | 0.26 | -80.9<small>%</small> | -26.1<small>%</small> |
| QQQ | <span style="color: tomato">17.9<small>%</small></span> | 21.7<small>%</small> | 0.83 | -35.1<small>%</small> | -6.2<small>%</small> |