| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">11.9<small>%</small></span> | 37.5<small>%</small> | 0.32 | -80.9<small>%</small> | -26.4<small>%</small> |
| QLD | <span style="color: tomato">29.1<small>%</small></span> | 43.3<small>%</small> | 0.67 | -63.7<small>%</small> | -14.1<small>%</small> |