| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BABO](/babo-vs-baba/) | <span style="color: tomato">49.4<small>%</small></span> | 38.1<small>%</small> | 1.30 | -29.3<small>%</small> | -12.1<small>%</small> |
| BABA | <span style="color: tomato">92.7<small>%</small></span> | 48.5<small>%</small> | 1.91 | -32.7<small>%</small> | -14.0<small>%</small> |