| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BABO](/babo-vs-baba/) | <span style="color: tomato">22.3<small>%</small></span> | 36.3<small>%</small> | 0.61 | -29.3<small>%</small> | -13.2<small>%</small> |
| BABA | <span style="color: tomato">47.5<small>%</small></span> | 46.3<small>%</small> | 1.03 | -32.7<small>%</small> | -15.3<small>%</small> |