| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">21.9<small>%</small></span> | 13.4<small>%</small> | 1.63 | -16.6<small>%</small> | -1.8<small>%</small> |
| SPYI | <span style="color: tomato">19.1<small>%</small></span> | 13.1<small>%</small> | 1.46 | -16.5<small>%</small> | -1.4<small>%</small> |