| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">22.3<small>%</small></span> | 13.7<small>%</small> | 1.63 | -16.6<small>%</small> | -1.9<small>%</small> |
| QQQ | <span style="color: tomato">29.4<small>%</small></span> | 20.8<small>%</small> | 1.41 | -22.8<small>%</small> | -3.2<small>%</small> |