| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepi/) | <span style="color: tomato">32.0<small>%</small></span> | 10.2<small>%</small> | 3.13 | -7.7<small>%</small> | -0.9<small>%</small> |
| JEPI | <span style="color: tomato">18.8<small>%</small></span> | 7.5<small>%</small> | 2.51 | -4.7<small>%</small> | -0.6<small>%</small> |