| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">38.5<small>%</small></span> | 10.2<small>%</small> | 3.77 | -7.7<small>%</small> | -0.9<small>%</small> |
| GPIQ | <span style="color: tomato">37.9<small>%</small></span> | 14.6<small>%</small> | 2.59 | -11.7<small>%</small> | -1.6<small>%</small> |