| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-wdte/) | <span style="color: tomato">21.1<small>%</small></span> | 12.6<small>%</small> | 1.67 | -16.6<small>%</small> | -1.6<small>%</small> |
| WDTE | <span style="color: tomato">14.8<small>%</small></span> | 11.2<small>%</small> | 1.32 | -15.8<small>%</small> | -1.8<small>%</small> |