| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">26.8<small>%</small></span> | 10.3<small>%</small> | 2.60 | -7.7<small>%</small> | -1.0<small>%</small> |
| SPY | <span style="color: tomato">31.1<small>%</small></span> | 12.2<small>%</small> | 2.54 | -8.4<small>%</small> | -1.1<small>%</small> |