| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">30.5<small>%</small></span> | 10.2<small>%</small> | 2.99 | -7.7<small>%</small> | -0.9<small>%</small> |
| SPY | <span style="color: tomato">34.3<small>%</small></span> | 12.1<small>%</small> | 2.83 | -8.4<small>%</small> | -1.1<small>%</small> |