| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">21.7<small>%</small></span> | 13.8<small>%</small> | 1.57 | -16.6<small>%</small> | -1.9<small>%</small> |
| SPYI | <span style="color: tomato">18.4<small>%</small></span> | 13.5<small>%</small> | 1.36 | -16.5<small>%</small> | -1.5<small>%</small> |