| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-wdte/) | <span style="color: tomato">21.0<small>%</small></span> | 12.7<small>%</small> | 1.66 | -16.6<small>%</small> | -1.6<small>%</small> |
| WDTE | <span style="color: tomato">14.9<small>%</small></span> | 11.3<small>%</small> | 1.32 | -15.8<small>%</small> | -1.8<small>%</small> |