| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpix/) | <span style="color: tomato">38.8<small>%</small></span> | 10.3<small>%</small> | 3.78 | -7.7<small>%</small> | -0.9<small>%</small> |
| GPIX | <span style="color: tomato">37.4<small>%</small></span> | 10.6<small>%</small> | 3.53 | -7.0<small>%</small> | -0.8<small>%</small> |