| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">31.6<small>%</small></span> | 10.5<small>%</small> | 3.01 | -7.7<small>%</small> | -1.0<small>%</small> |
| QQQ | <span style="color: tomato">39.2<small>%</small></span> | 17.5<small>%</small> | 2.24 | -13.6<small>%</small> | -2.3<small>%</small> |