| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpix/) | <span style="color: tomato">23.4<small>%</small></span> | 14.0<small>%</small> | 1.67 | -16.6<small>%</small> | -2.0<small>%</small> |
| GPIX | <span style="color: tomato">24.4<small>%</small></span> | 15.0<small>%</small> | 1.63 | -17.5<small>%</small> | -1.7<small>%</small> |