| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">29.7<small>%</small></span> | 10.1<small>%</small> | 2.94 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPY | <span style="color: tomato">567.4<small>%</small></span> | 193.6<small>%</small> | 2.93 | -4.3<small>%</small> | -0.6<small>%</small> |