| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">22.3<small>%</small></span> | 13.5<small>%</small> | 1.65 | -16.6<small>%</small> | -1.8<small>%</small> |
| JEPQ | <span style="color: tomato">24.2<small>%</small></span> | 15.8<small>%</small> | 1.53 | -20.1<small>%</small> | -2.4<small>%</small> |