| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">25.8<small>%</small></span> | 13.6<small>%</small> | 1.89 | -16.6<small>%</small> | -1.9<small>%</small> |
| GPIQ | <span style="color: tomato">29.7<small>%</small></span> | 18.2<small>%</small> | 1.63 | -21.1<small>%</small> | -2.5<small>%</small> |