| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">21.6<small>%</small></span> | 12.8<small>%</small> | 1.69 | -16.6<small>%</small> | -1.6<small>%</small> |
| JEPQ | <span style="color: tomato">21.1<small>%</small></span> | 15.7<small>%</small> | 1.34 | -20.1<small>%</small> | -2.2<small>%</small> |