| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepi/) | <span style="color: tomato">21.5<small>%</small></span> | 13.7<small>%</small> | 1.57 | -16.6<small>%</small> | -1.9<small>%</small> |
| JEPI | <span style="color: tomato">11.1<small>%</small></span> | 11.1<small>%</small> | 1.00 | -13.3<small>%</small> | -1.5<small>%</small> |