| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">21.4<small>%</small></span> | 13.9<small>%</small> | 1.54 | -16.6<small>%</small> | -2.0<small>%</small> |
| SPY | <span style="color: tomato">25.0<small>%</small></span> | 16.7<small>%</small> | 1.50 | -18.8<small>%</small> | -2.1<small>%</small> |