| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepi/) | <span style="color: tomato">20.9<small>%</small></span> | 12.7<small>%</small> | 1.64 | -16.6<small>%</small> | -1.6<small>%</small> |
| JEPI | <span style="color: tomato">10.1<small>%</small></span> | 10.1<small>%</small> | 1.00 | -13.3<small>%</small> | -1.6<small>%</small> |