| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-wdte/) | <span style="color: tomato">20.8<small>%</small></span> | 12.6<small>%</small> | 1.65 | -16.6<small>%</small> | -1.6<small>%</small> |
| WDTE | <span style="color: tomato">14.7<small>%</small></span> | 11.3<small>%</small> | 1.30 | -15.8<small>%</small> | -1.8<small>%</small> |