| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpix/) | <span style="color: tomato">23.9<small>%</small></span> | 13.6<small>%</small> | 1.76 | -16.6<small>%</small> | -1.8<small>%</small> |
| GPIX | <span style="color: tomato">25.1<small>%</small></span> | 14.5<small>%</small> | 1.74 | -17.5<small>%</small> | -1.6<small>%</small> |