| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">22.4<small>%</small></span> | 13.5<small>%</small> | 1.66 | -16.6<small>%</small> | -1.8<small>%</small> |
| JEPY | <span style="color: tomato">193.8<small>%</small></span> | 143.1<small>%</small> | 1.35 | -15.8<small>%</small> | -1.8<small>%</small> |