| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">20.6<small>%</small></span> | 12.6<small>%</small> | 1.63 | -16.6<small>%</small> | -1.6<small>%</small> |
| SPYI | <span style="color: tomato">17.6<small>%</small></span> | 12.5<small>%</small> | 1.41 | -16.5<small>%</small> | -1.3<small>%</small> |