| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">21.8<small>%</small></span> | 13.8<small>%</small> | 1.58 | -16.6<small>%</small> | -1.9<small>%</small> |
| JEPQ | <span style="color: tomato">21.8<small>%</small></span> | 16.3<small>%</small> | 1.33 | -20.1<small>%</small> | -2.6<small>%</small> |