| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">29.6<small>%</small></span> | 10.4<small>%</small> | 2.84 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPY | <span style="color: tomato">518.0<small>%</small></span> | 189.6<small>%</small> | 2.73 | -4.3<small>%</small> | -0.6<small>%</small> |