| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">24.8<small>%</small></span> | 13.6<small>%</small> | 1.82 | -16.6<small>%</small> | -1.8<small>%</small> |
| GPIQ | <span style="color: tomato">29.5<small>%</small></span> | 18.1<small>%</small> | 1.63 | -21.1<small>%</small> | -2.4<small>%</small> |