| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">20.0<small>%</small></span> | 13.4<small>%</small> | 1.50 | -16.6<small>%</small> | -1.8<small>%</small> |
| QQQ | <span style="color: tomato">26.9<small>%</small></span> | 20.6<small>%</small> | 1.31 | -22.8<small>%</small> | -3.0<small>%</small> |