| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">3.6<small>%</small></span> | 6.1<small>%</small> | 0.59 | -7.0<small>%</small> | -1.7<small>%</small> |
| BND | <span style="color: tomato">2.6<small>%</small></span> | 5.9<small>%</small> | 0.45 | -7.2<small>%</small> | -1.8<small>%</small> |