| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">2.4<small>%</small></span> | 7.0<small>%</small> | 0.34 | -7.0<small>%</small> | -2.1<small>%</small> |
| BND | <span style="color: tomato">1.9<small>%</small></span> | 6.9<small>%</small> | 0.27 | -7.2<small>%</small> | -2.2<small>%</small> |