| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">3.9<small>%</small></span> | 6.4<small>%</small> | 0.61 | -7.0<small>%</small> | -1.9<small>%</small> |
| BND | <span style="color: tomato">3.2<small>%</small></span> | 6.2<small>%</small> | 0.51 | -7.2<small>%</small> | -1.9<small>%</small> |