| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDW](/bndw-vs-bnd/) | <span style="color: tomato">1.4<small>%</small></span> | 4.8<small>%</small> | 0.30 | -17.2<small>%</small> | -4.8<small>%</small> |
| BND | <span style="color: tomato">1.5<small>%</small></span> | 6.0<small>%</small> | 0.25 | -18.6<small>%</small> | -5.7<small>%</small> |