| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDW](/bndw-vs-bnd/) | <span style="color: tomato">1.4<small>%</small></span> | 5.1<small>%</small> | 0.28 | -17.2<small>%</small> | -5.4<small>%</small> |
| BND | <span style="color: tomato">1.4<small>%</small></span> | 6.4<small>%</small> | 0.22 | -18.6<small>%</small> | -6.0<small>%</small> |