| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-us500/) | <span style="color: tomato">18.5<small>%</small></span> | 22.3<small>%</small> | 0.83 | -51.5<small>%</small> | -9.5<small>%</small> |
| US500 | <span style="color: tomato">9.8<small>%</small></span> | 17.7<small>%</small> | 0.55 | -56.8<small>%</small> | -9.6<small>%</small> |