| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-B](/brk-b-vs-spy/) | <span style="color: tomato">11.1<small>%</small></span> | 22.3<small>%</small> | 0.50 | -53.9<small>%</small> | -11.3<small>%</small> |
| SPY | <span style="color: tomato">10.0<small>%</small></span> | 19.3<small>%</small> | 0.52 | -55.2<small>%</small> | -10.3<small>%</small> |