| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-B](/brk-b-vs-brk-a/) | <span style="color: tomato">11.1<small>%</small></span> | 22.3<small>%</small> | 0.50 | -53.9<small>%</small> | -11.3<small>%</small> |
| BRK-A | <span style="color: tomato">11.0<small>%</small></span> | 22.4<small>%</small> | 0.49 | -51.5<small>%</small> | -10.9<small>%</small> |