| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-B](/brk-b-vs-brk-a/) | <span style="color: tomato">10.6<small>%</small></span> | 22.0<small>%</small> | 0.48 | -53.9<small>%</small> | -11.0<small>%</small> |
| BRK-A | <span style="color: tomato">10.6<small>%</small></span> | 22.1<small>%</small> | 0.48 | -51.5<small>%</small> | -10.7<small>%</small> |