| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-spy/) | <span style="color: tomato">13.1<small>%</small></span> | 22.1<small>%</small> | 0.59 | -51.5<small>%</small> | -10.3<small>%</small> |
| SPY | <span style="color: tomato">10.9<small>%</small></span> | 18.5<small>%</small> | 0.59 | -55.2<small>%</small> | -9.0<small>%</small> |