| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-us500/) | <span style="color: tomato">19.1<small>%</small></span> | 22.5<small>%</small> | 0.85 | -51.5<small>%</small> | -9.6<small>%</small> |
| US500 | <span style="color: tomato">9.5<small>%</small></span> | 17.8<small>%</small> | 0.53 | -56.8<small>%</small> | -9.9<small>%</small> |