| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-B](/brk-b-vs-spy/) | <span style="color: tomato">10.7<small>%</small></span> | 22.0<small>%</small> | 0.48 | -53.9<small>%</small> | -11.0<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 19.2<small>%</small> | 0.54 | -55.2<small>%</small> | -9.8<small>%</small> |