| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRKC](/brkc-vs-brk-b/) | <span style="color: tomato">0.5<small>%</small></span> | 12.2<small>%</small> | 0.04 | -6.1<small>%</small> | -2.0<small>%</small> |
| BRK-B | <span style="color: tomato">4.0<small>%</small></span> | 14.2<small>%</small> | 0.28 | -7.0<small>%</small> | -2.4<small>%</small> |