| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRKC](/brkc-vs-brk-b/) | <span style="color: tomato">2.6<small>%</small></span> | 11.5<small>%</small> | 0.23 | -6.1<small>%</small> | -2.0<small>%</small> |
| BRK-B | <span style="color: tomato">6.7<small>%</small></span> | 13.8<small>%</small> | 0.48 | -7.0<small>%</small> | -2.5<small>%</small> |