| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRKC](/brkc-vs-brk-b/) | <span style="color: tomato">0.4<small>%</small></span> | 12.3<small>%</small> | 0.03 | -7.6<small>%</small> | -3.1<small>%</small> |
| BRK-B | <span style="color: tomato">2.2<small>%</small></span> | 14.5<small>%</small> | 0.15 | -9.4<small>%</small> | -3.8<small>%</small> |