| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [COIW](/coiw-vs-coin/) | <span style="color: tomato">40.9<small>%</small></span> | 92.9<small>%</small> | 0.44 | -48.9<small>%</small> | -21.1<small>%</small> |
| COIN | <span style="color: tomato">48.9<small>%</small></span> | 76.1<small>%</small> | 0.64 | -41.4<small>%</small> | -17.2<small>%</small> |