| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [COIW](/coiw-vs-coin/) | <span style="color: cornflowerblue">-3.7<small>%</small></span> | 90.9<small>%</small> | -0.04 | -51.5<small>%</small> | -23.9<small>%</small> |
| COIN | <span style="color: tomato">7.9<small>%</small></span> | 74.7<small>%</small> | 0.11 | -43.3<small>%</small> | -19.4<small>%</small> |