| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [COIW](/coiw-vs-coin/) | <span style="color: tomato">20.0<small>%</small></span> | 98.0<small>%</small> | 0.20 | -48.9<small>%</small> | -20.4<small>%</small> |
| COIN | <span style="color: tomato">30.7<small>%</small></span> | 80.1<small>%</small> | 0.38 | -41.4<small>%</small> | -16.8<small>%</small> |