| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CONY](/cony-vs-coin/) | <span style="color: tomato">42.3<small>%</small></span> | 59.4<small>%</small> | 0.71 | -50.3<small>%</small> | -15.6<small>%</small> |
| COIN | <span style="color: tomato">93.1<small>%</small></span> | 78.3<small>%</small> | 1.19 | -55.9<small>%</small> | -19.5<small>%</small> |