| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CONY](/cony-vs-coin/) | <span style="color: tomato">255.0<small>%</small></span> | 605.4<small>%</small> | 0.42 | -50.3<small>%</small> | -16.2<small>%</small> |
| COIN | <span style="color: tomato">68.6<small>%</small></span> | 78.0<small>%</small> | 0.88 | -55.9<small>%</small> | -20.0<small>%</small> |