| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CSHI](/cshi-vs-bil/) | <span style="color: tomato">5.4<small>%</small></span> | 1.3<small>%</small> | 4.21 | -1.7<small>%</small> | -0.0<small>%</small> |
| BIL | <span style="color: tomato">4.4<small>%</small></span> | 0.2<small>%</small> | 18.04 | -0.0<small>%</small> | -0.0<small>%</small> |