| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CSHI](/cshi-vs-bil/) | <span style="color: tomato">5.5<small>%</small></span> | 1.4<small>%</small> | 3.97 | -1.7<small>%</small> | -0.0<small>%</small> |
| BIL | <span style="color: tomato">4.6<small>%</small></span> | 0.3<small>%</small> | 18.10 | -0.0<small>%</small> | -0.0<small>%</small> |