| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CVNY](/cvny-vs-cvna/) | <span style="color: tomato">52.8<small>%</small></span> | 64.6<small>%</small> | 0.82 | -43.3<small>%</small> | -11.5<small>%</small> |
| CVNA | <span style="color: tomato">79.9<small>%</small></span> | 77.8<small>%</small> | 1.03 | -43.0<small>%</small> | -12.1<small>%</small> |