| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CVNY](/cvny-vs-cvna/) | <span style="color: tomato">75.6<small>%</small></span> | 70.3<small>%</small> | 1.08 | -43.3<small>%</small> | -12.6<small>%</small> |
| CVNA | <span style="color: tomato">121.5<small>%</small></span> | 84.5<small>%</small> | 1.44 | -43.0<small>%</small> | -13.0<small>%</small> |