| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CVNY](/cvny-vs-cvna/) | <span style="color: tomato">57.4<small>%</small></span> | 64.5<small>%</small> | 0.89 | -43.3<small>%</small> | -11.4<small>%</small> |
| CVNA | <span style="color: tomato">85.7<small>%</small></span> | 77.6<small>%</small> | 1.10 | -43.0<small>%</small> | -12.1<small>%</small> |