| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DBC](/dbc-vs-spy/) | <span style="color: tomato">0.6<small>%</small></span> | 19.2<small>%</small> | 0.03 | -76.4<small>%</small> | -46.6<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 19.5<small>%</small> | 0.54 | -55.2<small>%</small> | -7.6<small>%</small> |