| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DBC](/dbc-vs-spy/) | <span style="color: tomato">2.5<small>%</small></span> | 19.2<small>%</small> | 0.13 | -76.4<small>%</small> | -45.9<small>%</small> |
| SPY | <span style="color: tomato">11.2<small>%</small></span> | 19.2<small>%</small> | 0.58 | -55.2<small>%</small> | -7.3<small>%</small> |