| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-divo/) | <span style="color: tomato">12.7<small>%</small></span> | 17.2<small>%</small> | 0.74 | -35.1<small>%</small> | -3.9<small>%</small> |
| DIVO | <span style="color: tomato">12.7<small>%</small></span> | 15.0<small>%</small> | 0.84 | -30.0<small>%</small> | -2.7<small>%</small> |