| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">12.1<small>%</small></span> | 16.4<small>%</small> | 0.74 | -35.1<small>%</small> | -3.6<small>%</small> |
| SCHD | <span style="color: tomato">14.8<small>%</small></span> | 16.4<small>%</small> | 0.90 | -33.4<small>%</small> | -3.3<small>%</small> |