| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-divo/) | <span style="color: tomato">12.9<small>%</small></span> | 16.6<small>%</small> | 0.77 | -35.1<small>%</small> | -3.7<small>%</small> |
| DIVO | <span style="color: tomato">12.5<small>%</small></span> | 14.6<small>%</small> | 0.85 | -30.0<small>%</small> | -2.6<small>%</small> |