| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">12.0<small>%</small></span> | 16.4<small>%</small> | 0.73 | -35.1<small>%</small> | -3.6<small>%</small> |
| SCHD | <span style="color: tomato">9.7<small>%</small></span> | 16.4<small>%</small> | 0.59 | -33.4<small>%</small> | -4.3<small>%</small> |