| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-divo/) | <span style="color: tomato">13.1<small>%</small></span> | 17.4<small>%</small> | 0.75 | -35.1<small>%</small> | -4.1<small>%</small> |
| DIVO | <span style="color: tomato">12.6<small>%</small></span> | 15.2<small>%</small> | 0.83 | -30.0<small>%</small> | -2.8<small>%</small> |