| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-vig/) | <span style="color: tomato">11.8<small>%</small></span> | 16.3<small>%</small> | 0.72 | -35.1<small>%</small> | -3.5<small>%</small> |
| VIG | <span style="color: tomato">11.6<small>%</small></span> | 15.7<small>%</small> | 0.74 | -31.7<small>%</small> | -3.6<small>%</small> |