| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">12.1<small>%</small></span> | 16.5<small>%</small> | 0.74 | -35.1<small>%</small> | -3.7<small>%</small> |
| SCHD | <span style="color: tomato">15.6<small>%</small></span> | 16.5<small>%</small> | 0.95 | -33.4<small>%</small> | -3.2<small>%</small> |