| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-vig/) | <span style="color: tomato">12.0<small>%</small></span> | 15.9<small>%</small> | 0.75 | -35.1<small>%</small> | -3.4<small>%</small> |
| VIG | <span style="color: tomato">11.6<small>%</small></span> | 15.4<small>%</small> | 0.75 | -31.7<small>%</small> | -3.4<small>%</small> |