| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-divo/) | <span style="color: tomato">13.6<small>%</small></span> | 16.9<small>%</small> | 0.81 | -32.0<small>%</small> | -3.5<small>%</small> |
| DIVO | <span style="color: tomato">12.1<small>%</small></span> | 15.2<small>%</small> | 0.80 | -30.0<small>%</small> | -2.7<small>%</small> |