| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-vig/) | <span style="color: tomato">13.2<small>%</small></span> | 15.4<small>%</small> | 0.86 | -32.0<small>%</small> | -3.0<small>%</small> |
| VIG | <span style="color: tomato">12.1<small>%</small></span> | 15.1<small>%</small> | 0.80 | -31.7<small>%</small> | -3.3<small>%</small> |