| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-divo/) | <span style="color: tomato">14.3<small>%</small></span> | 16.8<small>%</small> | 0.85 | -32.0<small>%</small> | -3.5<small>%</small> |
| DIVO | <span style="color: tomato">12.0<small>%</small></span> | 15.2<small>%</small> | 0.79 | -30.0<small>%</small> | -2.8<small>%</small> |