| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-vig/) | <span style="color: tomato">12.9<small>%</small></span> | 15.3<small>%</small> | 0.84 | -32.0<small>%</small> | -3.0<small>%</small> |
| VIG | <span style="color: tomato">11.8<small>%</small></span> | 15.1<small>%</small> | 0.78 | -31.7<small>%</small> | -3.3<small>%</small> |