| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-vig/) | <span style="color: tomato">12.9<small>%</small></span> | 15.6<small>%</small> | 0.83 | -32.0<small>%</small> | -3.1<small>%</small> |
| VIG | <span style="color: tomato">11.9<small>%</small></span> | 15.4<small>%</small> | 0.78 | -31.7<small>%</small> | -3.4<small>%</small> |