| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRW](/dgrw-vs-divo/) | <span style="color: tomato">14.1<small>%</small></span> | 16.3<small>%</small> | 0.86 | -32.0<small>%</small> | -3.3<small>%</small> |
| DIVO | <span style="color: tomato">13.0<small>%</small></span> | 14.7<small>%</small> | 0.89 | -30.0<small>%</small> | -2.6<small>%</small> |