| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">7.2<small>%</small></span> | 21.2<small>%</small> | 0.34 | -26.6<small>%</small> | -7.4<small>%</small> |
| DIS | <span style="color: tomato">10.8<small>%</small></span> | 27.5<small>%</small> | 0.39 | -32.9<small>%</small> | -10.6<small>%</small> |