| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">12.4<small>%</small></span> | 18.7<small>%</small> | 0.66 | -22.9<small>%</small> | -8.0<small>%</small> |
| DIS | <span style="color: tomato">17.8<small>%</small></span> | 25.1<small>%</small> | 0.71 | -30.0<small>%</small> | -11.1<small>%</small> |