| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">11.1<small>%</small></span> | 18.8<small>%</small> | 0.59 | -22.9<small>%</small> | -8.0<small>%</small> |
| DIS | <span style="color: tomato">16.0<small>%</small></span> | 25.2<small>%</small> | 0.64 | -30.0<small>%</small> | -11.1<small>%</small> |