| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-idvo/) | <span style="color: tomato">14.9<small>%</small></span> | 10.6<small>%</small> | 1.41 | -8.9<small>%</small> | -1.9<small>%</small> |
| IDVO | <span style="color: tomato">16.6<small>%</small></span> | 15.2<small>%</small> | 1.09 | -11.0<small>%</small> | -2.6<small>%</small> |