| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-idvo/) | <span style="color: tomato">12.5<small>%</small></span> | 10.5<small>%</small> | 1.19 | -8.9<small>%</small> | -2.0<small>%</small> |
| IDVO | <span style="color: tomato">16.3<small>%</small></span> | 15.4<small>%</small> | 1.06 | -11.0<small>%</small> | -2.7<small>%</small> |