| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-schd/) | <span style="color: tomato">12.5<small>%</small></span> | 14.6<small>%</small> | 0.85 | -30.0<small>%</small> | -2.6<small>%</small> |
| SCHD | <span style="color: tomato">12.4<small>%</small></span> | 16.8<small>%</small> | 0.74 | -33.4<small>%</small> | -4.1<small>%</small> |