| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-idvo/) | <span style="color: tomato">14.8<small>%</small></span> | 10.6<small>%</small> | 1.40 | -8.9<small>%</small> | -2.0<small>%</small> |
| IDVO | <span style="color: tomato">15.8<small>%</small></span> | 15.3<small>%</small> | 1.04 | -11.0<small>%</small> | -2.6<small>%</small> |