| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-schd/) | <span style="color: tomato">11.9<small>%</small></span> | 15.2<small>%</small> | 0.78 | -30.0<small>%</small> | -2.8<small>%</small> |
| SCHD | <span style="color: tomato">15.9<small>%</small></span> | 17.5<small>%</small> | 0.90 | -33.4<small>%</small> | -3.5<small>%</small> |