| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-schd/) | <span style="color: tomato">12.2<small>%</small></span> | 15.2<small>%</small> | 0.81 | -30.0<small>%</small> | -2.7<small>%</small> |
| SCHD | <span style="color: tomato">11.1<small>%</small></span> | 17.4<small>%</small> | 0.64 | -33.4<small>%</small> | -4.3<small>%</small> |