| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">8.6<small>%</small></span> | 10.9<small>%</small> | 0.78 | -16.9<small>%</small> | -3.4<small>%</small> |
| DIA | <span style="color: tomato">12.8<small>%</small></span> | 14.9<small>%</small> | 0.86 | -17.8<small>%</small> | -3.3<small>%</small> |