| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">7.1<small>%</small></span> | 10.8<small>%</small> | 0.66 | -16.9<small>%</small> | -4.4<small>%</small> |
| DIA | <span style="color: tomato">12.8<small>%</small></span> | 14.8<small>%</small> | 0.87 | -17.8<small>%</small> | -3.7<small>%</small> |