| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">6.7<small>%</small></span> | 11.6<small>%</small> | 0.58 | -16.9<small>%</small> | -4.0<small>%</small> |
| DIA | <span style="color: tomato">11.9<small>%</small></span> | 15.4<small>%</small> | 0.78 | -17.8<small>%</small> | -3.7<small>%</small> |