| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.4<small>%</small></span> | 18.3<small>%</small> | 0.57 | -33.7<small>%</small> | -4.5<small>%</small> |
| DIA | <span style="color: tomato">11.6<small>%</small></span> | 18.9<small>%</small> | 0.62 | -36.7<small>%</small> | -4.6<small>%</small> |