| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.6<small>%</small></span> | 18.2<small>%</small> | 0.58 | -33.7<small>%</small> | -4.3<small>%</small> |
| DIA | <span style="color: tomato">11.2<small>%</small></span> | 18.8<small>%</small> | 0.59 | -36.7<small>%</small> | -4.6<small>%</small> |