| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.6<small>%</small></span> | 18.1<small>%</small> | 0.59 | -33.7<small>%</small> | -4.2<small>%</small> |
| DIA | <span style="color: tomato">11.4<small>%</small></span> | 18.7<small>%</small> | 0.61 | -36.7<small>%</small> | -4.5<small>%</small> |