| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EQWS](/eqws-vs-iwm/) | <span style="color: tomato">4.5<small>%</small></span> | 22.4<small>%</small> | 0.20 | -61.0<small>%</small> | -14.2<small>%</small> |
| IWM | <span style="color: tomato">7.4<small>%</small></span> | 24.2<small>%</small> | 0.31 | -58.6<small>%</small> | -10.2<small>%</small> |