| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJ](/ewj-vs-idvo/) | <span style="color: tomato">17.6<small>%</small></span> | 18.2<small>%</small> | 0.96 | -14.7<small>%</small> | -3.2<small>%</small> |
| IDVO | <span style="color: tomato">19.1<small>%</small></span> | 16.3<small>%</small> | 1.18 | -15.5<small>%</small> | -2.5<small>%</small> |