| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJ](/ewj-vs-idvo/) | <span style="color: tomato">17.6<small>%</small></span> | 18.1<small>%</small> | 0.97 | -14.7<small>%</small> | -3.1<small>%</small> |
| IDVO | <span style="color: tomato">20.8<small>%</small></span> | 16.0<small>%</small> | 1.30 | -15.5<small>%</small> | -2.4<small>%</small> |