| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJV](/ewjv-vs-idvo/) | <span style="color: tomato">24.6<small>%</small></span> | 18.5<small>%</small> | 1.33 | -14.7<small>%</small> | -3.0<small>%</small> |
| IDVO | <span style="color: tomato">21.7<small>%</small></span> | 16.3<small>%</small> | 1.33 | -15.5<small>%</small> | -2.3<small>%</small> |