| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJV](/ewjv-vs-idvo/) | <span style="color: tomato">22.4<small>%</small></span> | 18.1<small>%</small> | 1.24 | -14.6<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">21.0<small>%</small></span> | 15.9<small>%</small> | 1.31 | -15.5<small>%</small> | -2.3<small>%</small> |