| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">12.2<small>%</small></span> | 29.4<small>%</small> | 0.41 | -31.5<small>%</small> | -8.9<small>%</small> |
| META | <span style="color: tomato">19.0<small>%</small></span> | 37.2<small>%</small> | 0.51 | -34.2<small>%</small> | -10.0<small>%</small> |