| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">33.6<small>%</small></span> | 27.4<small>%</small> | 1.23 | -31.5<small>%</small> | -5.4<small>%</small> |
| META | <span style="color: tomato">45.1<small>%</small></span> | 35.6<small>%</small> | 1.26 | -34.2<small>%</small> | -6.1<small>%</small> |