| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">22.1<small>%</small></span> | 27.9<small>%</small> | 0.79 | -31.5<small>%</small> | -5.7<small>%</small> |
| META | <span style="color: tomato">30.9<small>%</small></span> | 36.0<small>%</small> | 0.86 | -34.2<small>%</small> | -6.5<small>%</small> |