| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-spy/) | <span style="color: tomato">11.7<small>%</small></span> | 19.9<small>%</small> | 0.59 | -32.9<small>%</small> | -9.4<small>%</small> |
| SPY | <span style="color: tomato">14.2<small>%</small></span> | 17.1<small>%</small> | 0.83 | -24.5<small>%</small> | -5.6<small>%</small> |