| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-qqq/) | <span style="color: tomato">11.7<small>%</small></span> | 19.9<small>%</small> | 0.59 | -32.9<small>%</small> | -9.4<small>%</small> |
| QQQ | <span style="color: tomato">14.8<small>%</small></span> | 22.7<small>%</small> | 0.66 | -35.1<small>%</small> | -9.2<small>%</small> |