| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-qqq/) | <span style="color: tomato">12.7<small>%</small></span> | 19.7<small>%</small> | 0.64 | -32.9<small>%</small> | -11.1<small>%</small> |
| QQQ | <span style="color: tomato">12.5<small>%</small></span> | 22.5<small>%</small> | 0.56 | -35.1<small>%</small> | -10.7<small>%</small> |