| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-spy/) | <span style="color: tomato">11.7<small>%</small></span> | 19.7<small>%</small> | 0.59 | -32.9<small>%</small> | -11.2<small>%</small> |
| SPY | <span style="color: tomato">12.5<small>%</small></span> | 16.5<small>%</small> | 0.76 | -24.5<small>%</small> | -6.5<small>%</small> |