| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-qqq/) | <span style="color: tomato">13.0<small>%</small></span> | 20.1<small>%</small> | 0.65 | -32.9<small>%</small> | -9.7<small>%</small> |
| QQQ | <span style="color: tomato">14.8<small>%</small></span> | 22.8<small>%</small> | 0.65 | -35.1<small>%</small> | -9.5<small>%</small> |