| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-spy/) | <span style="color: tomato">12.5<small>%</small></span> | 20.1<small>%</small> | 0.62 | -32.9<small>%</small> | -9.7<small>%</small> |
| SPY | <span style="color: tomato">13.9<small>%</small></span> | 17.3<small>%</small> | 0.80 | -24.5<small>%</small> | -5.8<small>%</small> |