| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">42.0<small>%</small></span> | 62.9<small>%</small> | 0.67 | -78.4<small>%</small> | -24.5<small>%</small> |
| TQQQ | <span style="color: tomato">30.6<small>%</small></span> | 72.5<small>%</small> | 0.42 | -81.7<small>%</small> | -29.3<small>%</small> |