| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">40.1<small>%</small></span> | 61.1<small>%</small> | 0.66 | -78.4<small>%</small> | -23.3<small>%</small> |
| TQQQ | <span style="color: tomato">32.7<small>%</small></span> | 71.1<small>%</small> | 0.46 | -81.7<small>%</small> | -27.3<small>%</small> |