| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-qld/) | <span style="color: tomato">38.6<small>%</small></span> | 63.3<small>%</small> | 0.61 | -78.4<small>%</small> | -26.7<small>%</small> |
| QLD | <span style="color: tomato">26.5<small>%</small></span> | 49.3<small>%</small> | 0.54 | -63.7<small>%</small> | -19.4<small>%</small> |