| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-qld/) | <span style="color: tomato">41.6<small>%</small></span> | 63.2<small>%</small> | 0.66 | -78.4<small>%</small> | -24.8<small>%</small> |
| QLD | <span style="color: tomato">27.0<small>%</small></span> | 49.3<small>%</small> | 0.55 | -63.7<small>%</small> | -18.3<small>%</small> |