| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">39.1<small>%</small></span> | 63.4<small>%</small> | 0.62 | -78.4<small>%</small> | -26.7<small>%</small> |
| TQQQ | <span style="color: tomato">29.0<small>%</small></span> | 72.8<small>%</small> | 0.40 | -81.7<small>%</small> | -31.4<small>%</small> |