| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">24.5<small>%</small></span> | 87.7<small>%</small> | 0.28 | -60.8<small>%</small> | -16.2<small>%</small> |
| BULZ | <span style="color: tomato">36.7<small>%</small></span> | 101.1<small>%</small> | 0.36 | -65.2<small>%</small> | -19.4<small>%</small> |