| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">36.3<small>%</small></span> | 92.1<small>%</small> | 0.39 | -92.3<small>%</small> | -42.6<small>%</small> |
| TQQQ | <span style="color: tomato">26.6<small>%</small></span> | 71.6<small>%</small> | 0.37 | -81.7<small>%</small> | -29.5<small>%</small> |