| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">28.5<small>%</small></span> | 86.2<small>%</small> | 0.33 | -60.8<small>%</small> | -16.1<small>%</small> |
| BULZ | <span style="color: tomato">59.7<small>%</small></span> | 99.7<small>%</small> | 0.60 | -65.2<small>%</small> | -19.5<small>%</small> |