| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">24.1<small>%</small></span> | 78.9<small>%</small> | 0.31 | -60.8<small>%</small> | -21.8<small>%</small> |
| TQQQ | <span style="color: tomato">37.9<small>%</small></span> | 68.1<small>%</small> | 0.56 | -56.3<small>%</small> | -14.2<small>%</small> |