| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">34.7<small>%</small></span> | 95.6<small>%</small> | 0.36 | -60.8<small>%</small> | -19.4<small>%</small> |
| BULZ | <span style="color: tomato">35.8<small>%</small></span> | 105.8<small>%</small> | 0.34 | -65.2<small>%</small> | -23.3<small>%</small> |