| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">35.7<small>%</small></span> | 92.9<small>%</small> | 0.38 | -60.8<small>%</small> | -18.3<small>%</small> |
| TQQQ | <span style="color: tomato">24.8<small>%</small></span> | 79.3<small>%</small> | 0.31 | -56.3<small>%</small> | -17.5<small>%</small> |