| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: tomato">25.7<small>%</small></span> | 33.0<small>%</small> | 0.78 | -37.0<small>%</small> | -8.8<small>%</small> |
| GDX | <span style="color: tomato">54.3<small>%</small></span> | 41.9<small>%</small> | 1.30 | -38.9<small>%</small> | -10.0<small>%</small> |