| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: cornflowerblue">-13.1<small>%</small></span> | 23.3<small>%</small> | -0.56 | -15.1<small>%</small> | -4.5<small>%</small> |
| GDX | <span style="color: cornflowerblue">-0.5<small>%</small></span> | 31.7<small>%</small> | -0.02 | -19.5<small>%</small> | -6.0<small>%</small> |