| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: tomato">24.6<small>%</small></span> | 25.1<small>%</small> | 0.98 | -17.8<small>%</small> | -4.7<small>%</small> |
| GDX | <span style="color: tomato">50.5<small>%</small></span> | 33.6<small>%</small> | 1.50 | -22.5<small>%</small> | -6.3<small>%</small> |