| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GLD](/gld-vs-spy/) | <span style="color: tomato">10.3<small>%</small></span> | 17.5<small>%</small> | 0.59 | -45.6<small>%</small> | -16.4<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 19.0<small>%</small> | 0.56 | -55.2<small>%</small> | -7.3<small>%</small> |