| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GLD](/gld-vs-spy/) | <span style="color: tomato">10.7<small>%</small></span> | 18.2<small>%</small> | 0.59 | -45.6<small>%</small> | -16.2<small>%</small> |
| SPY | <span style="color: tomato">11.0<small>%</small></span> | 18.8<small>%</small> | 0.58 | -55.2<small>%</small> | -7.0<small>%</small> |