| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GLD](/gld-vs-spy/) | <span style="color: tomato">10.2<small>%</small></span> | 17.5<small>%</small> | 0.58 | -45.6<small>%</small> | -16.5<small>%</small> |
| SPY | <span style="color: tomato">10.5<small>%</small></span> | 19.0<small>%</small> | 0.55 | -55.2<small>%</small> | -7.3<small>%</small> |