| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-spy/) | <span style="color: tomato">8.2<small>%</small></span> | 21.5<small>%</small> | 0.38 | -54.7<small>%</small> | -7.2<small>%</small> |
| SPY | <span style="color: tomato">11.1<small>%</small></span> | 19.7<small>%</small> | 0.57 | -55.2<small>%</small> | -7.7<small>%</small> |