| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-spy/) | <span style="color: tomato">10.0<small>%</small></span> | 21.6<small>%</small> | 0.46 | -54.7<small>%</small> | -6.8<small>%</small> |
| SPY | <span style="color: tomato">10.9<small>%</small></span> | 19.9<small>%</small> | 0.55 | -55.2<small>%</small> | -8.0<small>%</small> |