| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-hyt/) | <span style="color: tomato">10.6<small>%</small></span> | 21.7<small>%</small> | 0.49 | -54.7<small>%</small> | -7.0<small>%</small> |
| HYT | <span style="color: tomato">8.7<small>%</small></span> | 19.9<small>%</small> | 0.44 | -55.2<small>%</small> | -6.4<small>%</small> |