| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-shy/) | <span style="color: tomato">8.3<small>%</small></span> | 21.5<small>%</small> | 0.39 | -54.7<small>%</small> | -7.2<small>%</small> |
| SHY | <span style="color: tomato">1.8<small>%</small></span> | 1.5<small>%</small> | 1.18 | -5.7<small>%</small> | -0.6<small>%</small> |