| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-shy/) | <span style="color: tomato">10.5<small>%</small></span> | 21.8<small>%</small> | 0.48 | -54.7<small>%</small> | -7.0<small>%</small> |
| SHY | <span style="color: tomato">1.6<small>%</small></span> | 1.5<small>%</small> | 1.05 | -5.7<small>%</small> | -0.6<small>%</small> |