| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-hyt/) | <span style="color: tomato">8.4<small>%</small></span> | 21.5<small>%</small> | 0.39 | -54.7<small>%</small> | -7.2<small>%</small> |
| HYT | <span style="color: tomato">7.7<small>%</small></span> | 19.4<small>%</small> | 0.40 | -55.2<small>%</small> | -6.1<small>%</small> |