| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: tomato">1.8<small>%</small></span> | 20.2<small>%</small> | 0.09 | -17.5<small>%</small> | -6.5<small>%</small> |
| GOOGL | <span style="color: tomato">21.7<small>%</small></span> | 26.7<small>%</small> | 0.81 | -22.1<small>%</small> | -6.0<small>%</small> |