| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: tomato">19.8<small>%</small></span> | 22.8<small>%</small> | 0.87 | -24.4<small>%</small> | -6.8<small>%</small> |
| GOOGL | <span style="color: tomato">38.1<small>%</small></span> | 29.4<small>%</small> | 1.29 | -29.8<small>%</small> | -7.6<small>%</small> |