| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: tomato">21.4<small>%</small></span> | 23.7<small>%</small> | 0.90 | -24.4<small>%</small> | -6.7<small>%</small> |
| GOOGL | <span style="color: tomato">36.5<small>%</small></span> | 30.1<small>%</small> | 1.21 | -29.8<small>%</small> | -7.7<small>%</small> |