| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-qqq/) | <span style="color: tomato">37.0<small>%</small></span> | 14.6<small>%</small> | 2.54 | -11.7<small>%</small> | -1.6<small>%</small> |
| QQQ | <span style="color: tomato">43.6<small>%</small></span> | 17.2<small>%</small> | 2.53 | -13.6<small>%</small> | -2.2<small>%</small> |