| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">39.4<small>%</small></span> | 14.4<small>%</small> | 2.74 | -11.7<small>%</small> | -1.5<small>%</small> |
| JEPQ | <span style="color: tomato">37.0<small>%</small></span> | 12.0<small>%</small> | 3.07 | -10.7<small>%</small> | -1.2<small>%</small> |