| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">29.1<small>%</small></span> | 18.2<small>%</small> | 1.60 | -21.1<small>%</small> | -2.5<small>%</small> |
| JEPQ | <span style="color: tomato">25.5<small>%</small></span> | 16.0<small>%</small> | 1.59 | -20.1<small>%</small> | -2.5<small>%</small> |