| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">37.4<small>%</small></span> | 14.7<small>%</small> | 2.54 | -11.7<small>%</small> | -1.7<small>%</small> |
| JEPQ | <span style="color: tomato">34.0<small>%</small></span> | 12.4<small>%</small> | 2.73 | -10.7<small>%</small> | -1.3<small>%</small> |