| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-qqq/) | <span style="color: tomato">29.0<small>%</small></span> | 18.2<small>%</small> | 1.60 | -21.1<small>%</small> | -2.4<small>%</small> |
| QQQ | <span style="color: tomato">33.6<small>%</small></span> | 20.8<small>%</small> | 1.62 | -22.8<small>%</small> | -3.1<small>%</small> |