| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">24.9<small>%</small></span> | 15.0<small>%</small> | 1.66 | -17.5<small>%</small> | -1.7<small>%</small> |
| SPY | <span style="color: tomato">28.7<small>%</small></span> | 16.9<small>%</small> | 1.70 | -18.8<small>%</small> | -2.1<small>%</small> |