| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">25.4<small>%</small></span> | 14.3<small>%</small> | 1.78 | -17.5<small>%</small> | -1.6<small>%</small> |
| JEPI | <span style="color: tomato">14.2<small>%</small></span> | 10.7<small>%</small> | 1.33 | -13.3<small>%</small> | -1.4<small>%</small> |