| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">37.3<small>%</small></span> | 10.6<small>%</small> | 3.53 | -7.0<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">44.8<small>%</small></span> | 12.2<small>%</small> | 3.66 | -8.4<small>%</small> | -1.0<small>%</small> |