| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">23.9<small>%</small></span> | 15.1<small>%</small> | 1.59 | -17.5<small>%</small> | -1.8<small>%</small> |
| JEPI | <span style="color: tomato">13.0<small>%</small></span> | 11.3<small>%</small> | 1.15 | -13.3<small>%</small> | -1.6<small>%</small> |