| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">22.8<small>%</small></span> | 13.5<small>%</small> | 1.69 | -17.5<small>%</small> | -1.4<small>%</small> |
| JEPI | <span style="color: tomato">11.9<small>%</small></span> | 10.0<small>%</small> | 1.19 | -13.3<small>%</small> | -1.6<small>%</small> |