| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">36.1<small>%</small></span> | 10.5<small>%</small> | 3.43 | -7.0<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">42.3<small>%</small></span> | 12.2<small>%</small> | 3.46 | -8.4<small>%</small> | -1.0<small>%</small> |