| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HDIV](/hdiv-vs-spy/) | <span style="color: tomato">9.7<small>%</small></span> | 20.9<small>%</small> | 0.46 | -28.3<small>%</small> | -5.0<small>%</small> |
| SPY | <span style="color: tomato">11.2<small>%</small></span> | 25.1<small>%</small> | 0.45 | -28.3<small>%</small> | -6.9<small>%</small> |