| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HOOY](/hooy-vs-hood/) | <span style="color: tomato">194.7<small>%</small></span> | 49.6<small>%</small> | 3.93 | -28.3<small>%</small> | -4.6<small>%</small> |
| HOOD | <span style="color: tomato">376.4<small>%</small></span> | 64.4<small>%</small> | 5.84 | -30.3<small>%</small> | -5.3<small>%</small> |