| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HOOY](/hooy-vs-hood/) | <span style="color: tomato">53.8<small>%</small></span> | 55.2<small>%</small> | 0.97 | -51.5<small>%</small> | -22.4<small>%</small> |
| HOOD | <span style="color: tomato">88.1<small>%</small></span> | 69.1<small>%</small> | 1.27 | -57.3<small>%</small> | -24.3<small>%</small> |