| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HOOY](/hooy-vs-hood/) | <span style="color: tomato">247.6<small>%</small></span> | 46.5<small>%</small> | 5.33 | -16.0<small>%</small> | -2.9<small>%</small> |
| HOOD | <span style="color: tomato">455.6<small>%</small></span> | 61.3<small>%</small> | 7.43 | -16.6<small>%</small> | -3.7<small>%</small> |