| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HYT](/hyt-vs-shy/) | <span style="color: tomato">7.6<small>%</small></span> | 18.4<small>%</small> | 0.42 | -56.9<small>%</small> | -6.1<small>%</small> |
| SHY | <span style="color: tomato">1.9<small>%</small></span> | 1.5<small>%</small> | 1.25 | -5.7<small>%</small> | -0.5<small>%</small> |