| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HYT](/hyt-vs-shy/) | <span style="color: tomato">7.5<small>%</small></span> | 18.3<small>%</small> | 0.41 | -56.9<small>%</small> | -6.1<small>%</small> |
| SHY | <span style="color: tomato">1.9<small>%</small></span> | 1.5<small>%</small> | 1.26 | -5.7<small>%</small> | -0.5<small>%</small> |