| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HYT](/hyt-vs-spy/) | <span style="color: tomato">7.8<small>%</small></span> | 18.4<small>%</small> | 0.42 | -56.9<small>%</small> | -6.3<small>%</small> |
| SPY | <span style="color: tomato">11.1<small>%</small></span> | 18.5<small>%</small> | 0.60 | -55.2<small>%</small> | -7.0<small>%</small> |