| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HYT](/hyt-vs-shy/) | <span style="color: tomato">6.8<small>%</small></span> | 18.1<small>%</small> | 0.38 | -57.0<small>%</small> | -6.1<small>%</small> |
| SHY | <span style="color: tomato">1.9<small>%</small></span> | 1.5<small>%</small> | 1.24 | -5.7<small>%</small> | -0.5<small>%</small> |