| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IEF](/ief-vs-tlt/) | <span style="color: tomato">3.5<small>%</small></span> | 6.8<small>%</small> | 0.52 | -23.9<small>%</small> | -5.4<small>%</small> |
| TLT | <span style="color: tomato">3.5<small>%</small></span> | 14.2<small>%</small> | 0.25 | -48.4<small>%</small> | -14.1<small>%</small> |