| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IEF](/ief-vs-tlt/) | <span style="color: tomato">3.5<small>%</small></span> | 6.9<small>%</small> | 0.51 | -23.9<small>%</small> | -4.8<small>%</small> |
| TLT | <span style="color: tomato">3.9<small>%</small></span> | 14.4<small>%</small> | 0.27 | -48.4<small>%</small> | -12.0<small>%</small> |