| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IEF](/ief-vs-tlt/) | <span style="color: tomato">3.6<small>%</small></span> | 6.8<small>%</small> | 0.53 | -23.9<small>%</small> | -5.1<small>%</small> |
| TLT | <span style="color: tomato">3.8<small>%</small></span> | 14.4<small>%</small> | 0.26 | -48.4<small>%</small> | -12.9<small>%</small> |