| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">17.5<small>%</small></span> | 19.3<small>%</small> | 0.91 | -20.4<small>%</small> | -4.0<small>%</small> |
| QQQ | <span style="color: tomato">21.6<small>%</small></span> | 22.1<small>%</small> | 0.97 | -22.8<small>%</small> | -3.8<small>%</small> |