| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">15.5<small>%</small></span> | 19.6<small>%</small> | 0.79 | -20.4<small>%</small> | -4.2<small>%</small> |
| QQQ | <span style="color: tomato">19.8<small>%</small></span> | 22.5<small>%</small> | 0.88 | -22.8<small>%</small> | -4.0<small>%</small> |