| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">16.9<small>%</small></span> | 19.4<small>%</small> | 0.87 | -20.4<small>%</small> | -4.1<small>%</small> |
| QQQ | <span style="color: tomato">21.0<small>%</small></span> | 22.2<small>%</small> | 0.94 | -22.8<small>%</small> | -3.9<small>%</small> |