| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xylg/) | <span style="color: tomato">19.4<small>%</small></span> | 13.8<small>%</small> | 1.40 | -16.9<small>%</small> | -2.3<small>%</small> |
| XYLG | <span style="color: tomato">17.8<small>%</small></span> | 14.0<small>%</small> | 1.27 | -17.4<small>%</small> | -1.9<small>%</small> |