| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">26.7<small>%</small></span> | 11.1<small>%</small> | 2.40 | -7.9<small>%</small> | -1.1<small>%</small> |
| XYLD | <span style="color: tomato">17.6<small>%</small></span> | 6.9<small>%</small> | 2.55 | -5.2<small>%</small> | -0.4<small>%</small> |