| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">25.7<small>%</small></span> | 11.4<small>%</small> | 2.26 | -7.9<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">29.6<small>%</small></span> | 12.4<small>%</small> | 2.39 | -8.4<small>%</small> | -1.1<small>%</small> |