| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spyi/) | <span style="color: tomato">18.4<small>%</small></span> | 13.8<small>%</small> | 1.33 | -16.9<small>%</small> | -2.2<small>%</small> |
| SPYI | <span style="color: tomato">18.2<small>%</small></span> | 13.5<small>%</small> | 1.35 | -16.5<small>%</small> | -1.5<small>%</small> |