| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xylg/) | <span style="color: tomato">17.0<small>%</small></span> | 14.4<small>%</small> | 1.18 | -16.9<small>%</small> | -2.5<small>%</small> |
| XYLG | <span style="color: tomato">16.4<small>%</small></span> | 14.6<small>%</small> | 1.13 | -17.4<small>%</small> | -2.1<small>%</small> |