| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">19.2<small>%</small></span> | 13.9<small>%</small> | 1.38 | -16.9<small>%</small> | -2.2<small>%</small> |
| JEPY | <span style="color: tomato">164.6<small>%</small></span> | 147.9<small>%</small> | 1.11 | -15.8<small>%</small> | -1.9<small>%</small> |