| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">27.2<small>%</small></span> | 11.2<small>%</small> | 2.43 | -7.9<small>%</small> | -1.1<small>%</small> |
| BALI | <span style="color: tomato">27.2<small>%</small></span> | 10.0<small>%</small> | 2.72 | -7.7<small>%</small> | -1.0<small>%</small> |