| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-gpix/) | <span style="color: tomato">16.5<small>%</small></span> | 13.9<small>%</small> | 1.19 | -16.9<small>%</small> | -2.2<small>%</small> |
| GPIX | <span style="color: tomato">18.2<small>%</small></span> | 14.6<small>%</small> | 1.24 | -17.5<small>%</small> | -1.7<small>%</small> |