| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">26.9<small>%</small></span> | 11.3<small>%</small> | 2.38 | -7.9<small>%</small> | -1.1<small>%</small> |
| XYLD | <span style="color: tomato">18.8<small>%</small></span> | 7.1<small>%</small> | 2.65 | -5.2<small>%</small> | -0.4<small>%</small> |