| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-wdte/) | <span style="color: tomato">16.4<small>%</small></span> | 13.4<small>%</small> | 1.22 | -16.9<small>%</small> | -2.0<small>%</small> |
| WDTE | <span style="color: tomato">13.3<small>%</small></span> | 11.5<small>%</small> | 1.16 | -15.8<small>%</small> | -1.9<small>%</small> |