| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-gpix/) | <span style="color: tomato">18.5<small>%</small></span> | 13.8<small>%</small> | 1.34 | -16.9<small>%</small> | -2.2<small>%</small> |
| GPIX | <span style="color: tomato">19.7<small>%</small></span> | 14.5<small>%</small> | 1.36 | -17.5<small>%</small> | -1.7<small>%</small> |