| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">27.3<small>%</small></span> | 11.5<small>%</small> | 2.38 | -7.9<small>%</small> | -1.1<small>%</small> |
| JEPI | <span style="color: tomato">17.9<small>%</small></span> | 7.3<small>%</small> | 2.46 | -3.9<small>%</small> | -0.7<small>%</small> |