| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">27.3<small>%</small></span> | 11.1<small>%</small> | 2.46 | -7.9<small>%</small> | -1.0<small>%</small> |
| SPY | <span style="color: tomato">30.8<small>%</small></span> | 12.1<small>%</small> | 2.55 | -8.4<small>%</small> | -1.1<small>%</small> |