| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-wdte/) | <span style="color: tomato">17.0<small>%</small></span> | 13.4<small>%</small> | 1.27 | -16.9<small>%</small> | -2.0<small>%</small> |
| WDTE | <span style="color: tomato">13.7<small>%</small></span> | 11.5<small>%</small> | 1.20 | -15.8<small>%</small> | -1.9<small>%</small> |