| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">17.2<small>%</small></span> | 14.2<small>%</small> | 1.21 | -16.9<small>%</small> | -2.4<small>%</small> |
| JEPI | <span style="color: tomato">10.0<small>%</small></span> | 11.3<small>%</small> | 0.88 | -13.3<small>%</small> | -1.7<small>%</small> |