| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">16.0<small>%</small></span> | 13.9<small>%</small> | 1.15 | -16.9<small>%</small> | -2.2<small>%</small> |
| JEPY | <span style="color: tomato">155.8<small>%</small></span> | 146.2<small>%</small> | 1.07 | -15.8<small>%</small> | -1.9<small>%</small> |