| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">28.2<small>%</small></span> | 11.2<small>%</small> | 2.52 | -7.9<small>%</small> | -1.0<small>%</small> |
| JEPI | <span style="color: tomato">19.9<small>%</small></span> | 7.2<small>%</small> | 2.78 | -3.9<small>%</small> | -0.6<small>%</small> |