| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">17.7<small>%</small></span> | 13.5<small>%</small> | 1.30 | -16.9<small>%</small> | -2.0<small>%</small> |
| XYLD | <span style="color: tomato">14.3<small>%</small></span> | 10.5<small>%</small> | 1.37 | -15.5<small>%</small> | -1.6<small>%</small> |