| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spyi/) | <span style="color: tomato">17.4<small>%</small></span> | 13.6<small>%</small> | 1.28 | -16.9<small>%</small> | -2.0<small>%</small> |
| SPYI | <span style="color: tomato">17.6<small>%</small></span> | 12.9<small>%</small> | 1.36 | -16.5<small>%</small> | -1.4<small>%</small> |