| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">17.3<small>%</small></span> | 13.5<small>%</small> | 1.27 | -16.9<small>%</small> | -2.0<small>%</small> |
| BALI | <span style="color: tomato">20.0<small>%</small></span> | 12.9<small>%</small> | 1.55 | -16.6<small>%</small> | -1.6<small>%</small> |