| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">18.1<small>%</small></span> | 13.9<small>%</small> | 1.30 | -16.9<small>%</small> | -2.2<small>%</small> |
| JEPY | <span style="color: tomato">160.0<small>%</small></span> | 146.9<small>%</small> | 1.09 | -15.8<small>%</small> | -1.9<small>%</small> |