| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">18.1<small>%</small></span> | 14.3<small>%</small> | 1.27 | -16.9<small>%</small> | -2.4<small>%</small> |
| BALI | <span style="color: tomato">19.5<small>%</small></span> | 14.3<small>%</small> | 1.37 | -16.6<small>%</small> | -2.1<small>%</small> |