| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">27.3<small>%</small></span> | 11.5<small>%</small> | 2.38 | -7.9<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">32.7<small>%</small></span> | 12.5<small>%</small> | 2.62 | -8.4<small>%</small> | -1.1<small>%</small> |