| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IVV](/ivv-vs-spy/) | <span style="color: tomato">8.6<small>%</small></span> | 18.9<small>%</small> | 0.46 | -55.3<small>%</small> | -10.7<small>%</small> |
| SPY | <span style="color: tomato">8.6<small>%</small></span> | 19.0<small>%</small> | 0.45 | -55.2<small>%</small> | -10.7<small>%</small> |