| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IVV](/ivv-vs-spy/) | <span style="color: tomato">8.2<small>%</small></span> | 19.0<small>%</small> | 0.43 | -55.3<small>%</small> | -10.9<small>%</small> |
| SPY | <span style="color: tomato">8.2<small>%</small></span> | 19.2<small>%</small> | 0.43 | -55.2<small>%</small> | -11.0<small>%</small> |