| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IVV](/ivv-vs-spy/) | <span style="color: tomato">8.0<small>%</small></span> | 19.1<small>%</small> | 0.42 | -55.2<small>%</small> | -11.3<small>%</small> |
| SPY | <span style="color: tomato">7.9<small>%</small></span> | 19.2<small>%</small> | 0.41 | -55.2<small>%</small> | -11.3<small>%</small> |