| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWF](/iwf-vs-brk-b/) | <span style="color: tomato">7.8<small>%</small></span> | 20.7<small>%</small> | 0.38 | -64.2<small>%</small> | -23.2<small>%</small> |
| BRK-B | <span style="color: tomato">10.7<small>%</small></span> | 21.3<small>%</small> | 0.50 | -53.9<small>%</small> | -9.6<small>%</small> |