| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWF](/iwf-vs-brk-b/) | <span style="color: tomato">8.4<small>%</small></span> | 20.9<small>%</small> | 0.40 | -64.2<small>%</small> | -22.5<small>%</small> |
| BRK-B | <span style="color: tomato">10.8<small>%</small></span> | 21.3<small>%</small> | 0.51 | -53.9<small>%</small> | -9.5<small>%</small> |