| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">13.5<small>%</small></span> | 15.1<small>%</small> | 0.90 | -18.7<small>%</small> | -2.8<small>%</small> |
| RYLD | <span style="color: tomato">10.1<small>%</small></span> | 13.5<small>%</small> | 0.74 | -19.0<small>%</small> | -3.1<small>%</small> |