| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-iwm/) | <span style="color: tomato">15.0<small>%</small></span> | 13.4<small>%</small> | 1.12 | -7.1<small>%</small> | -2.1<small>%</small> |
| IWM | <span style="color: tomato">43.8<small>%</small></span> | 21.5<small>%</small> | 2.04 | -10.1<small>%</small> | -2.9<small>%</small> |