| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">15.6<small>%</small></span> | 15.0<small>%</small> | 1.04 | -18.7<small>%</small> | -2.8<small>%</small> |
| RYLD | <span style="color: tomato">9.5<small>%</small></span> | 13.6<small>%</small> | 0.70 | -19.0<small>%</small> | -3.2<small>%</small> |