| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-iwm/) | <span style="color: tomato">14.6<small>%</small></span> | 13.3<small>%</small> | 1.10 | -7.1<small>%</small> | -2.0<small>%</small> |
| IWM | <span style="color: tomato">33.9<small>%</small></span> | 21.0<small>%</small> | 1.61 | -10.1<small>%</small> | -3.0<small>%</small> |