| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">13.0<small>%</small></span> | 15.2<small>%</small> | 0.86 | -18.7<small>%</small> | -2.8<small>%</small> |
| RYLD | <span style="color: tomato">9.8<small>%</small></span> | 13.6<small>%</small> | 0.72 | -19.0<small>%</small> | -3.1<small>%</small> |