| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-spy/) | <span style="color: tomato">11.8<small>%</small></span> | 11.0<small>%</small> | 1.07 | -13.7<small>%</small> | -2.2<small>%</small> |
| SPY | <span style="color: tomato">18.0<small>%</small></span> | 17.5<small>%</small> | 1.03 | -24.5<small>%</small> | -5.4<small>%</small> |