| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">10.2<small>%</small></span> | 14.4<small>%</small> | 0.71 | -32.6<small>%</small> | -2.9<small>%</small> |
| SPY | <span style="color: tomato">17.5<small>%</small></span> | 19.2<small>%</small> | 0.91 | -33.7<small>%</small> | -4.7<small>%</small> |