| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-jepix/) | <span style="color: tomato">11.6<small>%</small></span> | 11.0<small>%</small> | 1.05 | -13.7<small>%</small> | -2.2<small>%</small> |
| JEPIX | <span style="color: tomato">11.6<small>%</small></span> | 11.4<small>%</small> | 1.01 | -13.7<small>%</small> | -2.3<small>%</small> |