| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">13.8<small>%</small></span> | 10.3<small>%</small> | 1.34 | -13.7<small>%</small> | -2.1<small>%</small> |
| SCHD | <span style="color: tomato">14.3<small>%</small></span> | 15.6<small>%</small> | 0.91 | -18.9<small>%</small> | -5.1<small>%</small> |