| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-schd/) | <span style="color: tomato">11.3<small>%</small></span> | 15.1<small>%</small> | 0.75 | -32.6<small>%</small> | -3.1<small>%</small> |
| SCHD | <span style="color: tomato">18.5<small>%</small></span> | 19.1<small>%</small> | 0.97 | -33.4<small>%</small> | -3.6<small>%</small> |