| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-jepix/) | <span style="color: tomato">11.2<small>%</small></span> | 10.9<small>%</small> | 1.02 | -13.7<small>%</small> | -2.1<small>%</small> |
| JEPIX | <span style="color: tomato">11.1<small>%</small></span> | 11.4<small>%</small> | 0.98 | -13.7<small>%</small> | -2.3<small>%</small> |