| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-divo/) | <span style="color: tomato">13.2<small>%</small></span> | 10.3<small>%</small> | 1.28 | -13.7<small>%</small> | -2.1<small>%</small> |
| DIVO | <span style="color: tomato">14.4<small>%</small></span> | 12.3<small>%</small> | 1.17 | -13.7<small>%</small> | -2.4<small>%</small> |