| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">10.3<small>%</small></span> | 15.1<small>%</small> | 0.68 | -32.6<small>%</small> | -3.1<small>%</small> |
| SPY | <span style="color: tomato">16.8<small>%</small></span> | 20.1<small>%</small> | 0.84 | -33.7<small>%</small> | -5.3<small>%</small> |