| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-spy/) | <span style="color: tomato">11.7<small>%</small></span> | 11.0<small>%</small> | 1.06 | -13.7<small>%</small> | -2.1<small>%</small> |
| SPY | <span style="color: tomato">18.5<small>%</small></span> | 17.3<small>%</small> | 1.07 | -24.5<small>%</small> | -5.2<small>%</small> |