| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-idvo/) | <span style="color: tomato">9.4<small>%</small></span> | 11.1<small>%</small> | 0.85 | -13.3<small>%</small> | -1.7<small>%</small> |
| IDVO | <span style="color: tomato">19.5<small>%</small></span> | 16.1<small>%</small> | 1.21 | -15.5<small>%</small> | -2.4<small>%</small> |