| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">11.3<small>%</small></span> | 11.0<small>%</small> | 1.03 | -13.7<small>%</small> | -2.2<small>%</small> |
| SCHD | <span style="color: tomato">12.7<small>%</small></span> | 15.7<small>%</small> | 0.81 | -16.8<small>%</small> | -4.2<small>%</small> |