| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-schd/) | <span style="color: tomato">11.5<small>%</small></span> | 15.0<small>%</small> | 0.76 | -32.6<small>%</small> | -3.0<small>%</small> |
| SCHD | <span style="color: tomato">13.0<small>%</small></span> | 19.0<small>%</small> | 0.69 | -33.4<small>%</small> | -4.9<small>%</small> |