| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-jepix/) | <span style="color: tomato">13.4<small>%</small></span> | 10.3<small>%</small> | 1.30 | -13.7<small>%</small> | -2.1<small>%</small> |
| JEPIX | <span style="color: tomato">13.3<small>%</small></span> | 10.7<small>%</small> | 1.24 | -13.7<small>%</small> | -2.2<small>%</small> |