| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">11.7<small>%</small></span> | 11.0<small>%</small> | 1.06 | -13.7<small>%</small> | -2.1<small>%</small> |
| SCHD | <span style="color: tomato">13.0<small>%</small></span> | 15.6<small>%</small> | 0.83 | -16.8<small>%</small> | -4.2<small>%</small> |