| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-divo/) | <span style="color: tomato">11.8<small>%</small></span> | 11.0<small>%</small> | 1.08 | -13.7<small>%</small> | -2.1<small>%</small> |
| DIVO | <span style="color: tomato">15.0<small>%</small></span> | 12.5<small>%</small> | 1.19 | -13.7<small>%</small> | -2.3<small>%</small> |