| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">11.7<small>%</small></span> | 15.1<small>%</small> | 0.78 | -32.6<small>%</small> | -3.0<small>%</small> |
| SPY | <span style="color: tomato">17.8<small>%</small></span> | 19.8<small>%</small> | 0.90 | -33.7<small>%</small> | -5.5<small>%</small> |