| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-idvo/) | <span style="color: tomato">9.4<small>%</small></span> | 11.0<small>%</small> | 0.86 | -13.3<small>%</small> | -1.7<small>%</small> |
| IDVO | <span style="color: tomato">20.6<small>%</small></span> | 16.0<small>%</small> | 1.28 | -15.5<small>%</small> | -2.4<small>%</small> |