| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">16.2<small>%</small></span> | 17.0<small>%</small> | 0.95 | -20.1<small>%</small> | -3.7<small>%</small> |
| JEPI | <span style="color: tomato">7.6<small>%</small></span> | 11.4<small>%</small> | 0.66 | -13.3<small>%</small> | -1.9<small>%</small> |