| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">14.1<small>%</small></span> | 17.4<small>%</small> | 0.81 | -20.1<small>%</small> | -4.0<small>%</small> |
| QQQ | <span style="color: tomato">18.4<small>%</small></span> | 23.2<small>%</small> | 0.79 | -22.8<small>%</small> | -5.7<small>%</small> |