| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">14.2<small>%</small></span> | 17.3<small>%</small> | 0.82 | -20.1<small>%</small> | -3.9<small>%</small> |
| JEPI | <span style="color: tomato">7.5<small>%</small></span> | 11.7<small>%</small> | 0.65 | -13.3<small>%</small> | -2.0<small>%</small> |