| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">15.7<small>%</small></span> | 16.1<small>%</small> | 0.97 | -16.8<small>%</small> | -3.7<small>%</small> |
| QQQ | <span style="color: tomato">18.9<small>%</small></span> | 22.4<small>%</small> | 0.84 | -21.6<small>%</small> | -6.0<small>%</small> |