| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">16.5<small>%</small></span> | 16.1<small>%</small> | 1.03 | -16.8<small>%</small> | -3.7<small>%</small> |
| JEPI | <span style="color: tomato">9.8<small>%</small></span> | 10.5<small>%</small> | 0.94 | -10.5<small>%</small> | -1.7<small>%</small> |