| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">14.2<small>%</small></span> | 16.3<small>%</small> | 0.87 | -16.8<small>%</small> | -3.8<small>%</small> |
| QQQ | <span style="color: tomato">18.2<small>%</small></span> | 22.5<small>%</small> | 0.81 | -21.6<small>%</small> | -6.1<small>%</small> |