| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">15.2<small>%</small></span> | 17.2<small>%</small> | 0.88 | -20.1<small>%</small> | -3.9<small>%</small> |
| SPY | <span style="color: tomato">15.3<small>%</small></span> | 17.9<small>%</small> | 0.86 | -18.8<small>%</small> | -3.8<small>%</small> |