| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">16.3<small>%</small></span> | 16.6<small>%</small> | 0.98 | -20.1<small>%</small> | -3.3<small>%</small> |
| SPY | <span style="color: tomato">15.7<small>%</small></span> | 16.8<small>%</small> | 0.94 | -18.8<small>%</small> | -3.2<small>%</small> |