| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">15.8<small>%</small></span> | 16.2<small>%</small> | 0.97 | -16.8<small>%</small> | -3.8<small>%</small> |
| SPY | <span style="color: tomato">15.4<small>%</small></span> | 16.8<small>%</small> | 0.91 | -16.7<small>%</small> | -4.0<small>%</small> |