| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">179.7<small>%</small></span> | 140.5<small>%</small> | 1.28 | -15.8<small>%</small> | -1.8<small>%</small> |
| XYLD | <span style="color: tomato">11.5<small>%</small></span> | 11.4<small>%</small> | 1.01 | -15.5<small>%</small> | -2.0<small>%</small> |