| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">472.6<small>%</small></span> | 185.4<small>%</small> | 2.55 | -4.3<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">29.8<small>%</small></span> | 12.4<small>%</small> | 2.41 | -8.4<small>%</small> | -1.3<small>%</small> |