| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">439.5<small>%</small></span> | 182.4<small>%</small> | 2.41 | -4.3<small>%</small> | -0.6<small>%</small> |
| XYLD | <span style="color: tomato">15.3<small>%</small></span> | 7.3<small>%</small> | 2.10 | -5.2<small>%</small> | -0.6<small>%</small> |