| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">166.8<small>%</small></span> | 137.1<small>%</small> | 1.22 | -15.8<small>%</small> | -1.7<small>%</small> |
| SPY | <span style="color: tomato">22.9<small>%</small></span> | 16.1<small>%</small> | 1.42 | -18.8<small>%</small> | -2.0<small>%</small> |