| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">186.8<small>%</small></span> | 142.0<small>%</small> | 1.32 | -15.8<small>%</small> | -1.8<small>%</small> |
| XYLD | <span style="color: tomato">10.9<small>%</small></span> | 11.4<small>%</small> | 0.95 | -15.5<small>%</small> | -2.0<small>%</small> |