| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">165.3<small>%</small></span> | 136.9<small>%</small> | 1.21 | -15.8<small>%</small> | -1.7<small>%</small> |
| SPY | <span style="color: tomato">22.8<small>%</small></span> | 16.1<small>%</small> | 1.42 | -18.8<small>%</small> | -2.0<small>%</small> |