| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPMO](/jpmo-vs-jpm/) | <span style="color: tomato">18.2<small>%</small></span> | 18.4<small>%</small> | 0.99 | -24.8<small>%</small> | -4.2<small>%</small> |
| JPM | <span style="color: tomato">46.2<small>%</small></span> | 23.1<small>%</small> | 2.00 | -24.4<small>%</small> | -3.4<small>%</small> |