| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPMO](/jpmo-vs-jpm/) | <span style="color: tomato">15.9<small>%</small></span> | 18.4<small>%</small> | 0.86 | -24.8<small>%</small> | -4.1<small>%</small> |
| JPM | <span style="color: tomato">42.4<small>%</small></span> | 23.0<small>%</small> | 1.84 | -24.4<small>%</small> | -3.3<small>%</small> |