| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPO](/jpo-vs-jpm/) | <span style="color: tomato">17.2<small>%</small></span> | 18.8<small>%</small> | 0.92 | -24.8<small>%</small> | -4.4<small>%</small> |
| JPM | <span style="color: tomato">38.1<small>%</small></span> | 23.0<small>%</small> | 1.66 | -24.4<small>%</small> | -4.0<small>%</small> |