| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPO](/jpo-vs-jpm/) | <span style="color: tomato">14.3<small>%</small></span> | 18.8<small>%</small> | 0.76 | -24.8<small>%</small> | -4.4<small>%</small> |
| JPM | <span style="color: tomato">34.1<small>%</small></span> | 22.9<small>%</small> | 1.49 | -24.4<small>%</small> | -4.0<small>%</small> |