| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KNG](/kng-vs-nobl/) | <span style="color: tomato">8.8<small>%</small></span> | 17.6<small>%</small> | 0.50 | -35.1<small>%</small> | -4.2<small>%</small> |
| NOBL | <span style="color: tomato">9.6<small>%</small></span> | 18.1<small>%</small> | 0.53 | -35.4<small>%</small> | -4.3<small>%</small> |