| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KNG](/kng-vs-nobl/) | <span style="color: tomato">8.5<small>%</small></span> | 16.9<small>%</small> | 0.50 | -35.1<small>%</small> | -4.1<small>%</small> |
| NOBL | <span style="color: tomato">9.4<small>%</small></span> | 17.5<small>%</small> | 0.54 | -35.4<small>%</small> | -4.1<small>%</small> |