| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KNG](/kng-vs-nobl/) | <span style="color: tomato">9.3<small>%</small></span> | 17.0<small>%</small> | 0.55 | -35.1<small>%</small> | -4.1<small>%</small> |
| NOBL | <span style="color: tomato">10.3<small>%</small></span> | 17.5<small>%</small> | 0.59 | -35.4<small>%</small> | -4.1<small>%</small> |