| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOMP](/komp-vs-spy/) | <span style="color: tomato">10.4<small>%</small></span> | 27.3<small>%</small> | 0.38 | -50.1<small>%</small> | -22.2<small>%</small> |
| SPY | <span style="color: tomato">15.2<small>%</small></span> | 20.1<small>%</small> | 0.76 | -33.7<small>%</small> | -5.6<small>%</small> |