| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOMP](/komp-vs-spy/) | <span style="color: tomato">11.5<small>%</small></span> | 27.1<small>%</small> | 0.42 | -50.1<small>%</small> | -22.9<small>%</small> |
| SPY | <span style="color: tomato">15.2<small>%</small></span> | 20.2<small>%</small> | 0.75 | -33.7<small>%</small> | -5.3<small>%</small> |