| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOMP](/komp-vs-spy/) | <span style="color: tomato">11.2<small>%</small></span> | 27.2<small>%</small> | 0.41 | -50.1<small>%</small> | -22.9<small>%</small> |
| SPY | <span style="color: tomato">15.0<small>%</small></span> | 20.2<small>%</small> | 0.74 | -33.7<small>%</small> | -5.4<small>%</small> |