| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">47.3<small>%</small></span> | 26.9<small>%</small> | 1.76 | -29.9<small>%</small> | -4.6<small>%</small> |
| QQQ | <span style="color: tomato">30.1<small>%</small></span> | 19.9<small>%</small> | 1.51 | -22.8<small>%</small> | -3.1<small>%</small> |