| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">44.7<small>%</small></span> | 26.8<small>%</small> | 1.67 | -29.9<small>%</small> | -4.5<small>%</small> |
| TQQQ | <span style="color: tomato">64.1<small>%</small></span> | 59.2<small>%</small> | 1.08 | -58.0<small>%</small> | -11.3<small>%</small> |