| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">50.0<small>%</small></span> | 27.1<small>%</small> | 1.85 | -29.9<small>%</small> | -4.7<small>%</small> |
| QQQ | <span style="color: tomato">30.7<small>%</small></span> | 20.0<small>%</small> | 1.54 | -22.8<small>%</small> | -3.1<small>%</small> |