| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">46.7<small>%</small></span> | 26.7<small>%</small> | 1.75 | -29.9<small>%</small> | -4.5<small>%</small> |
| QLD | <span style="color: tomato">52.4<small>%</small></span> | 39.5<small>%</small> | 1.33 | -42.3<small>%</small> | -6.9<small>%</small> |