| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">46.2<small>%</small></span> | 27.3<small>%</small> | 1.69 | -29.9<small>%</small> | -4.8<small>%</small> |
| QLD | <span style="color: tomato">49.6<small>%</small></span> | 40.2<small>%</small> | 1.23 | -42.3<small>%</small> | -7.3<small>%</small> |