| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-spy/) | <span style="color: tomato">58.2<small>%</small></span> | 23.8<small>%</small> | 2.45 | -18.1<small>%</small> | -3.1<small>%</small> |
| SPY | <span style="color: tomato">27.4<small>%</small></span> | 12.1<small>%</small> | 2.26 | -10.0<small>%</small> | -1.6<small>%</small> |