| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-spy/) | <span style="color: tomato">48.9<small>%</small></span> | 26.9<small>%</small> | 1.82 | -29.9<small>%</small> | -4.6<small>%</small> |
| SPY | <span style="color: tomato">23.6<small>%</small></span> | 15.4<small>%</small> | 1.53 | -18.8<small>%</small> | -2.1<small>%</small> |