| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-spy/) | <span style="color: tomato">36.6<small>%</small></span> | 25.8<small>%</small> | 1.42 | -29.9<small>%</small> | -4.8<small>%</small> |
| SPY | <span style="color: tomato">21.2<small>%</small></span> | 14.8<small>%</small> | 1.43 | -18.8<small>%</small> | -1.9<small>%</small> |