| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">53.3<small>%</small></span> | 23.7<small>%</small> | 2.25 | -18.1<small>%</small> | -3.2<small>%</small> |
| TQQQ | <span style="color: tomato">87.3<small>%</small></span> | 51.0<small>%</small> | 1.71 | -37.4<small>%</small> | -9.2<small>%</small> |