| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">61.4<small>%</small></span> | 23.9<small>%</small> | 2.57 | -18.1<small>%</small> | -3.2<small>%</small> |
| TQQQ | <span style="color: tomato">106.8<small>%</small></span> | 51.3<small>%</small> | 2.08 | -37.4<small>%</small> | -9.2<small>%</small> |