| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">38.2<small>%</small></span> | 25.6<small>%</small> | 1.49 | -29.9<small>%</small> | -4.7<small>%</small> |
| QQQ | <span style="color: tomato">29.2<small>%</small></span> | 19.9<small>%</small> | 1.47 | -22.8<small>%</small> | -3.1<small>%</small> |