| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">48.1<small>%</small></span> | 27.4<small>%</small> | 1.75 | -29.9<small>%</small> | -4.8<small>%</small> |
| QLD | <span style="color: tomato">53.0<small>%</small></span> | 40.4<small>%</small> | 1.31 | -42.3<small>%</small> | -7.4<small>%</small> |