| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MARO](/maro-vs-mara/) | <span style="color: cornflowerblue">-34.4<small>%</small></span> | 63.7<small>%</small> | -0.54 | -54.1<small>%</small> | -31.4<small>%</small> |
| MARA | <span style="color: cornflowerblue">-32.9<small>%</small></span> | 80.2<small>%</small> | -0.41 | -57.2<small>%</small> | -33.0<small>%</small> |