| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MARO](/maro-vs-mara/) | <span style="color: cornflowerblue">-34.3<small>%</small></span> | 66.4<small>%</small> | -0.52 | -71.7<small>%</small> | -44.6<small>%</small> |
| MARA | <span style="color: cornflowerblue">-26.4<small>%</small></span> | 83.8<small>%</small> | -0.32 | -72.6<small>%</small> | -43.7<small>%</small> |