| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MARO](/maro-vs-mara/) | <span style="color: cornflowerblue">-38.7<small>%</small></span> | 66.3<small>%</small> | -0.58 | -71.7<small>%</small> | -44.3<small>%</small> |
| MARA | <span style="color: cornflowerblue">-33.3<small>%</small></span> | 83.6<small>%</small> | -0.40 | -72.6<small>%</small> | -43.5<small>%</small> |