| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-brk-b/) | <span style="color: tomato">14.5<small>%</small></span> | 17.5<small>%</small> | 0.83 | -33.3<small>%</small> | -3.8<small>%</small> |
| BRK-B | <span style="color: tomato">15.0<small>%</small></span> | 18.2<small>%</small> | 0.82 | -29.6<small>%</small> | -5.8<small>%</small> |