| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-schd/) | <span style="color: tomato">14.6<small>%</small></span> | 17.4<small>%</small> | 0.84 | -33.3<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">15.5<small>%</small></span> | 15.5<small>%</small> | 1.00 | -33.4<small>%</small> | -2.8<small>%</small> |