| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-schd/) | <span style="color: tomato">14.1<small>%</small></span> | 17.6<small>%</small> | 0.80 | -33.3<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">11.9<small>%</small></span> | 15.5<small>%</small> | 0.77 | -33.4<small>%</small> | -3.5<small>%</small> |