| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-spy/) | <span style="color: tomato">13.8<small>%</small></span> | 17.6<small>%</small> | 0.78 | -33.3<small>%</small> | -3.8<small>%</small> |
| SPY | <span style="color: tomato">14.3<small>%</small></span> | 16.8<small>%</small> | 0.85 | -33.7<small>%</small> | -3.8<small>%</small> |