| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-schd/) | <span style="color: tomato">14.1<small>%</small></span> | 17.4<small>%</small> | 0.81 | -33.3<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">13.3<small>%</small></span> | 15.3<small>%</small> | 0.87 | -33.4<small>%</small> | -3.4<small>%</small> |