| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-brk-b/) | <span style="color: tomato">13.9<small>%</small></span> | 17.6<small>%</small> | 0.79 | -33.3<small>%</small> | -3.8<small>%</small> |
| BRK-B | <span style="color: tomato">14.3<small>%</small></span> | 18.3<small>%</small> | 0.78 | -29.6<small>%</small> | -5.8<small>%</small> |