| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-brk-b/) | <span style="color: tomato">14.1<small>%</small></span> | 17.4<small>%</small> | 0.81 | -33.3<small>%</small> | -3.8<small>%</small> |
| BRK-B | <span style="color: tomato">13.7<small>%</small></span> | 18.1<small>%</small> | 0.76 | -29.6<small>%</small> | -6.0<small>%</small> |