| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: cornflowerblue">-47.0<small>%</small></span> | 49.6<small>%</small> | -0.95 | -81.5<small>%</small> | -45.1<small>%</small> |
| MRNA | <span style="color: cornflowerblue">-44.4<small>%</small></span> | 63.0<small>%</small> | -0.70 | -85.9<small>%</small> | -49.6<small>%</small> |