| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: tomato">19.1<small>%</small></span> | 112.2<small>%</small> | 0.17 | -82.1<small>%</small> | -51.4<small>%</small> |
| MRNA | <span style="color: tomato">37.3<small>%</small></span> | 123.5<small>%</small> | 0.30 | -86.6<small>%</small> | -55.1<small>%</small> |