| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: tomato">6.9<small>%</small></span> | 113.7<small>%</small> | 0.06 | -82.1<small>%</small> | -52.9<small>%</small> |
| MRNA | <span style="color: tomato">21.3<small>%</small></span> | 124.8<small>%</small> | 0.17 | -86.6<small>%</small> | -56.7<small>%</small> |