| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSFO](/msfo-vs-msft/) | <span style="color: tomato">26.9<small>%</small></span> | 16.1<small>%</small> | 1.67 | -13.2<small>%</small> | -3.2<small>%</small> |
| MSFT | <span style="color: tomato">28.8<small>%</small></span> | 19.9<small>%</small> | 1.45 | -15.5<small>%</small> | -4.5<small>%</small> |