| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSFO](/msfo-vs-msft/) | <span style="color: tomato">20.0<small>%</small></span> | 17.7<small>%</small> | 1.13 | -19.1<small>%</small> | -4.2<small>%</small> |
| MSFT | <span style="color: tomato">20.7<small>%</small></span> | 21.9<small>%</small> | 0.94 | -23.7<small>%</small> | -5.6<small>%</small> |