| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: tomato">74.2<small>%</small></span> | 72.5<small>%</small> | 1.02 | -41.7<small>%</small> | -14.7<small>%</small> |
| MSTR | <span style="color: tomato">112.7<small>%</small></span> | 96.8<small>%</small> | 1.16 | -49.8<small>%</small> | -22.7<small>%</small> |