| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: tomato">44.2<small>%</small></span> | 71.9<small>%</small> | 0.61 | -58.3<small>%</small> | -17.1<small>%</small> |
| MSTR | <span style="color: tomato">65.2<small>%</small></span> | 95.2<small>%</small> | 0.68 | -64.0<small>%</small> | -25.0<small>%</small> |