| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: tomato">341.0<small>%</small></span> | 82.6<small>%</small> | 4.13 | -33.2<small>%</small> | -11.1<small>%</small> |
| MSTR | <span style="color: tomato">760.8<small>%</small></span> | 113.1<small>%</small> | 6.73 | -46.4<small>%</small> | -18.3<small>%</small> |