| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">45.8<small>%</small></span> | 27.6<small>%</small> | 1.66 | -21.4<small>%</small> | -3.7<small>%</small> |
| NFLX | <span style="color: tomato">63.6<small>%</small></span> | 32.7<small>%</small> | 1.95 | -22.8<small>%</small> | -4.5<small>%</small> |