| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">47.3<small>%</small></span> | 27.8<small>%</small> | 1.70 | -21.4<small>%</small> | -3.3<small>%</small> |
| NFLX | <span style="color: tomato">64.0<small>%</small></span> | 32.4<small>%</small> | 1.97 | -22.8<small>%</small> | -4.1<small>%</small> |