| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">43.9<small>%</small></span> | 27.6<small>%</small> | 1.59 | -21.4<small>%</small> | -3.7<small>%</small> |
| NFLX | <span style="color: tomato">61.5<small>%</small></span> | 32.6<small>%</small> | 1.89 | -22.8<small>%</small> | -4.6<small>%</small> |