| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-idvo/) | <span style="color: tomato">7.4<small>%</small></span> | 13.8<small>%</small> | 0.54 | -15.4<small>%</small> | -3.7<small>%</small> |
| IDVO | <span style="color: tomato">19.9<small>%</small></span> | 16.2<small>%</small> | 1.23 | -15.5<small>%</small> | -2.2<small>%</small> |