| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">10.1<small>%</small></span> | 15.7<small>%</small> | 0.65 | -35.4<small>%</small> | -3.5<small>%</small> |
| SCHD | <span style="color: tomato">12.2<small>%</small></span> | 15.7<small>%</small> | 0.77 | -33.4<small>%</small> | -3.6<small>%</small> |