| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">10.4<small>%</small></span> | 15.9<small>%</small> | 0.65 | -35.4<small>%</small> | -3.5<small>%</small> |
| SCHD | <span style="color: tomato">11.2<small>%</small></span> | 16.0<small>%</small> | 0.70 | -33.4<small>%</small> | -3.7<small>%</small> |