| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-idvo/) | <span style="color: tomato">6.9<small>%</small></span> | 14.5<small>%</small> | 0.48 | -15.4<small>%</small> | -3.8<small>%</small> |
| IDVO | <span style="color: tomato">20.6<small>%</small></span> | 16.1<small>%</small> | 1.28 | -15.5<small>%</small> | -2.4<small>%</small> |