| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-spy/) | <span style="color: tomato">10.3<small>%</small></span> | 16.0<small>%</small> | 0.64 | -35.4<small>%</small> | -3.5<small>%</small> |
| SPY | <span style="color: tomato">13.7<small>%</small></span> | 17.3<small>%</small> | 0.79 | -33.7<small>%</small> | -4.0<small>%</small> |