| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-spy/) | <span style="color: tomato">11.1<small>%</small></span> | 16.0<small>%</small> | 0.70 | -35.4<small>%</small> | -3.3<small>%</small> |
| SPY | <span style="color: tomato">13.9<small>%</small></span> | 17.0<small>%</small> | 0.82 | -33.7<small>%</small> | -4.0<small>%</small> |