| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">11.0<small>%</small></span> | 16.0<small>%</small> | 0.69 | -35.4<small>%</small> | -3.4<small>%</small> |
| SCHD | <span style="color: tomato">16.8<small>%</small></span> | 16.2<small>%</small> | 1.03 | -33.4<small>%</small> | -2.9<small>%</small> |