| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-spy/) | <span style="color: tomato">11.0<small>%</small></span> | 16.0<small>%</small> | 0.68 | -35.4<small>%</small> | -3.4<small>%</small> |
| SPY | <span style="color: tomato">13.6<small>%</small></span> | 17.0<small>%</small> | 0.80 | -33.7<small>%</small> | -4.1<small>%</small> |