| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvdy/) | <span style="color: tomato">55.6<small>%</small></span> | 60.7<small>%</small> | 0.92 | -38.6<small>%</small> | -11.0<small>%</small> |
| NVDY | <span style="color: tomato">39.4<small>%</small></span> | 39.7<small>%</small> | 0.99 | -29.3<small>%</small> | -8.2<small>%</small> |