| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvda/) | <span style="color: tomato">69.7<small>%</small></span> | 57.1<small>%</small> | 1.22 | -38.6<small>%</small> | -9.4<small>%</small> |
| NVDA | <span style="color: tomato">65.5<small>%</small></span> | 47.5<small>%</small> | 1.38 | -32.7<small>%</small> | -7.5<small>%</small> |