| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvdy/) | <span style="color: tomato">51.4<small>%</small></span> | 58.0<small>%</small> | 0.89 | -38.6<small>%</small> | -9.9<small>%</small> |
| NVDY | <span style="color: tomato">34.7<small>%</small></span> | 38.1<small>%</small> | 0.91 | -29.3<small>%</small> | -7.2<small>%</small> |