| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvda/) | <span style="color: tomato">39.6<small>%</small></span> | 56.1<small>%</small> | 0.71 | -38.6<small>%</small> | -9.8<small>%</small> |
| NVDA | <span style="color: tomato">40.7<small>%</small></span> | 46.7<small>%</small> | 0.87 | -32.7<small>%</small> | -7.9<small>%</small> |