| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvda/) | <span style="color: tomato">36.4<small>%</small></span> | 50.8<small>%</small> | 0.72 | -38.6<small>%</small> | -11.2<small>%</small> |
| NVDA | <span style="color: tomato">36.5<small>%</small></span> | 42.3<small>%</small> | 0.86 | -32.7<small>%</small> | -8.8<small>%</small> |