| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDW](/nvdw-vs-nvdy/) | <span style="color: tomato">78.0<small>%</small></span> | 57.2<small>%</small> | 1.36 | -38.6<small>%</small> | -9.5<small>%</small> |
| NVDY | <span style="color: tomato">50.7<small>%</small></span> | 37.6<small>%</small> | 1.35 | -29.3<small>%</small> | -7.0<small>%</small> |