| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">68.4<small>%</small></span> | 39.7<small>%</small> | 1.72 | -34.1<small>%</small> | -6.2<small>%</small> |
| NVDA | <span style="color: tomato">107.5<small>%</small></span> | 50.8<small>%</small> | 2.12 | -36.9<small>%</small> | -7.4<small>%</small> |