| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">67.3<small>%</small></span> | 39.4<small>%</small> | 1.71 | -34.1<small>%</small> | -6.3<small>%</small> |
| NVDA | <span style="color: tomato">104.1<small>%</small></span> | 50.4<small>%</small> | 2.07 | -36.9<small>%</small> | -7.5<small>%</small> |