| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">75.0<small>%</small></span> | 40.7<small>%</small> | 1.84 | -34.1<small>%</small> | -6.6<small>%</small> |
| NVDA | <span style="color: tomato">121.4<small>%</small></span> | 52.2<small>%</small> | 2.33 | -36.9<small>%</small> | -7.7<small>%</small> |