| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVQ](/nvq-vs-spy/) | <span style="color: tomato">11.0<small>%</small></span> | 18.6<small>%</small> | 0.59 | -15.4<small>%</small> | -5.3<small>%</small> |
| SPY | <span style="color: tomato">11.6<small>%</small></span> | 17.1<small>%</small> | 0.68 | -24.5<small>%</small> | -7.3<small>%</small> |