| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: tomato">17.6<small>%</small></span> | 31.0<small>%</small> | 0.57 | -35.5<small>%</small> | -10.5<small>%</small> |
| ARKK | <span style="color: tomato">38.9<small>%</small></span> | 40.6<small>%</small> | 0.96 | -39.6<small>%</small> | -11.8<small>%</small> |