| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: tomato">90.6<small>%</small></span> | 234.6<small>%</small> | 0.39 | -35.5<small>%</small> | -10.3<small>%</small> |
| ARKK | <span style="color: tomato">29.7<small>%</small></span> | 40.8<small>%</small> | 0.73 | -39.6<small>%</small> | -11.7<small>%</small> |