| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: tomato">13.1<small>%</small></span> | 31.1<small>%</small> | 0.42 | -35.5<small>%</small> | -10.8<small>%</small> |
| ARKK | <span style="color: tomato">31.5<small>%</small></span> | 40.8<small>%</small> | 0.77 | -39.6<small>%</small> | -12.1<small>%</small> |