| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwb/) | <span style="color: tomato">10.5<small>%</small></span> | 17.1<small>%</small> | 0.61 | -39.7<small>%</small> | -4.1<small>%</small> |
| IWB | <span style="color: tomato">14.1<small>%</small></span> | 18.2<small>%</small> | 0.77 | -34.6<small>%</small> | -4.7<small>%</small> |