| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwb/) | <span style="color: tomato">11.3<small>%</small></span> | 16.8<small>%</small> | 0.68 | -39.7<small>%</small> | -3.9<small>%</small> |
| IWB | <span style="color: tomato">14.7<small>%</small></span> | 17.9<small>%</small> | 0.82 | -34.6<small>%</small> | -4.4<small>%</small> |