| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwb/) | <span style="color: tomato">10.7<small>%</small></span> | 17.1<small>%</small> | 0.62 | -39.7<small>%</small> | -4.1<small>%</small> |
| IWB | <span style="color: tomato">14.3<small>%</small></span> | 18.2<small>%</small> | 0.78 | -34.6<small>%</small> | -4.7<small>%</small> |