| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-shy/) | <span style="color: tomato">9.6<small>%</small></span> | 17.2<small>%</small> | 0.56 | -46.5<small>%</small> | -6.2<small>%</small> |
| SHY | <span style="color: tomato">1.4<small>%</small></span> | 1.4<small>%</small> | 0.98 | -5.7<small>%</small> | -0.7<small>%</small> |