| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-hyt/) | <span style="color: tomato">8.9<small>%</small></span> | 17.2<small>%</small> | 0.52 | -46.5<small>%</small> | -6.3<small>%</small> |
| HYT | <span style="color: tomato">6.0<small>%</small></span> | 15.3<small>%</small> | 0.39 | -42.6<small>%</small> | -5.2<small>%</small> |