| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-hyt/) | <span style="color: tomato">10.3<small>%</small></span> | 17.4<small>%</small> | 0.59 | -46.5<small>%</small> | -6.2<small>%</small> |
| HYT | <span style="color: tomato">7.0<small>%</small></span> | 15.6<small>%</small> | 0.45 | -42.6<small>%</small> | -5.1<small>%</small> |