| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-spy/) | <span style="color: tomato">10.5<small>%</small></span> | 17.5<small>%</small> | 0.60 | -46.5<small>%</small> | -6.2<small>%</small> |
| SPY | <span style="color: tomato">14.9<small>%</small></span> | 16.8<small>%</small> | 0.89 | -33.7<small>%</small> | -3.7<small>%</small> |