| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-shy/) | <span style="color: tomato">10.7<small>%</small></span> | 17.4<small>%</small> | 0.61 | -46.5<small>%</small> | -6.5<small>%</small> |
| SHY | <span style="color: tomato">1.0<small>%</small></span> | 1.4<small>%</small> | 0.75 | -5.7<small>%</small> | -0.7<small>%</small> |