| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">6.8<small>%</small></span> | 22.2<small>%</small> | 0.31 | -72.8<small>%</small> | -12.7<small>%</small> |
| SPY | <span style="color: tomato">11.0<small>%</small></span> | 18.8<small>%</small> | 0.58 | -55.2<small>%</small> | -7.0<small>%</small> |