| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">6.5<small>%</small></span> | 22.6<small>%</small> | 0.29 | -72.8<small>%</small> | -13.4<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 18.9<small>%</small> | 0.56 | -55.2<small>%</small> | -7.4<small>%</small> |