| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">6.3<small>%</small></span> | 22.6<small>%</small> | 0.28 | -72.8<small>%</small> | -13.4<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 19.0<small>%</small> | 0.55 | -55.2<small>%</small> | -7.5<small>%</small> |