| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aom/) | <span style="color: tomato">6.5<small>%</small></span> | 16.1<small>%</small> | 0.40 | -52.5<small>%</small> | -3.9<small>%</small> |
| AOM | <span style="color: tomato">6.6<small>%</small></span> | 9.7<small>%</small> | 0.68 | -20.0<small>%</small> | -2.7<small>%</small> |