| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-lqd/) | <span style="color: tomato">3.9<small>%</small></span> | 18.9<small>%</small> | 0.21 | -65.5<small>%</small> | -5.9<small>%</small> |
| LQD | <span style="color: tomato">4.3<small>%</small></span> | 8.9<small>%</small> | 0.48 | -25.0<small>%</small> | -4.5<small>%</small> |