| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aor/) | <span style="color: tomato">8.6<small>%</small></span> | 16.5<small>%</small> | 0.52 | -52.5<small>%</small> | -4.1<small>%</small> |
| AOR | <span style="color: tomato">8.4<small>%</small></span> | 12.7<small>%</small> | 0.66 | -24.4<small>%</small> | -3.7<small>%</small> |