| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aor/) | <span style="color: tomato">8.3<small>%</small></span> | 16.1<small>%</small> | 0.52 | -52.5<small>%</small> | -4.0<small>%</small> |
| AOR | <span style="color: tomato">8.9<small>%</small></span> | 12.6<small>%</small> | 0.71 | -24.4<small>%</small> | -3.6<small>%</small> |