| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-lqd/) | <span style="color: tomato">3.6<small>%</small></span> | 18.8<small>%</small> | 0.19 | -65.5<small>%</small> | -5.9<small>%</small> |
| LQD | <span style="color: tomato">4.2<small>%</small></span> | 8.9<small>%</small> | 0.47 | -25.0<small>%</small> | -4.5<small>%</small> |