| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aor/) | <span style="color: tomato">8.2<small>%</small></span> | 16.1<small>%</small> | 0.51 | -52.5<small>%</small> | -4.0<small>%</small> |
| AOR | <span style="color: tomato">8.8<small>%</small></span> | 12.5<small>%</small> | 0.70 | -24.4<small>%</small> | -3.5<small>%</small> |