| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-tlt/) | <span style="color: tomato">3.8<small>%</small></span> | 18.8<small>%</small> | 0.20 | -65.5<small>%</small> | -5.9<small>%</small> |
| TLT | <span style="color: tomato">3.1<small>%</small></span> | 15.2<small>%</small> | 0.21 | -48.4<small>%</small> | -15.4<small>%</small> |