| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aok/) | <span style="color: tomato">7.9<small>%</small></span> | 15.8<small>%</small> | 0.50 | -52.5<small>%</small> | -3.9<small>%</small> |
| AOK | <span style="color: tomato">5.5<small>%</small></span> | 7.5<small>%</small> | 0.73 | -18.9<small>%</small> | -2.4<small>%</small> |