| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-tlt/) | <span style="color: tomato">3.7<small>%</small></span> | 18.9<small>%</small> | 0.20 | -65.5<small>%</small> | -6.0<small>%</small> |
| TLT | <span style="color: tomato">3.1<small>%</small></span> | 15.3<small>%</small> | 0.20 | -48.4<small>%</small> | -14.9<small>%</small> |