| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aom/) | <span style="color: tomato">6.8<small>%</small></span> | 16.5<small>%</small> | 0.41 | -52.5<small>%</small> | -4.0<small>%</small> |
| AOM | <span style="color: tomato">6.6<small>%</small></span> | 9.8<small>%</small> | 0.67 | -20.0<small>%</small> | -2.8<small>%</small> |