| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-tlt/) | <span style="color: tomato">3.7<small>%</small></span> | 18.5<small>%</small> | 0.20 | -65.5<small>%</small> | -5.7<small>%</small> |
| TLT | <span style="color: tomato">2.8<small>%</small></span> | 15.0<small>%</small> | 0.19 | -48.4<small>%</small> | -16.4<small>%</small> |