| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-spy/) | <span style="color: tomato">3.9<small>%</small></span> | 18.9<small>%</small> | 0.21 | -65.5<small>%</small> | -5.9<small>%</small> |
| SPY | <span style="color: tomato">10.7<small>%</small></span> | 19.9<small>%</small> | 0.54 | -55.2<small>%</small> | -8.0<small>%</small> |