| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-spy/) | <span style="color: tomato">3.7<small>%</small></span> | 19.2<small>%</small> | 0.19 | -65.5<small>%</small> | -6.1<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 19.8<small>%</small> | 0.54 | -55.2<small>%</small> | -8.1<small>%</small> |