| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-lqd/) | <span style="color: tomato">2.2<small>%</small></span> | 13.0<small>%</small> | 0.17 | -30.9<small>%</small> | -6.7<small>%</small> |
| LQD | <span style="color: tomato">2.4<small>%</small></span> | 9.3<small>%</small> | 0.26 | -25.0<small>%</small> | -7.3<small>%</small> |