| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pff/) | <span style="color: tomato">1.9<small>%</small></span> | 12.6<small>%</small> | 0.15 | -30.9<small>%</small> | -6.5<small>%</small> |
| PFF | <span style="color: tomato">2.6<small>%</small></span> | 13.2<small>%</small> | 0.20 | -34.1<small>%</small> | -5.2<small>%</small> |