| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aok/) | <span style="color: tomato">2.9<small>%</small></span> | 13.5<small>%</small> | 0.21 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOK | <span style="color: tomato">4.0<small>%</small></span> | 7.1<small>%</small> | 0.56 | -18.9<small>%</small> | -4.2<small>%</small> |