| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-lqd/) | <span style="color: tomato">2.5<small>%</small></span> | 13.1<small>%</small> | 0.19 | -30.9<small>%</small> | -6.8<small>%</small> |
| LQD | <span style="color: tomato">2.3<small>%</small></span> | 9.4<small>%</small> | 0.25 | -25.0<small>%</small> | -7.4<small>%</small> |