| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aom/) | <span style="color: tomato">2.3<small>%</small></span> | 13.2<small>%</small> | 0.18 | -30.9<small>%</small> | -6.8<small>%</small> |
| AOM | <span style="color: tomato">5.2<small>%</small></span> | 8.4<small>%</small> | 0.62 | -20.0<small>%</small> | -4.0<small>%</small> |