| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-agg/) | <span style="color: tomato">2.7<small>%</small></span> | 13.6<small>%</small> | 0.20 | -30.9<small>%</small> | -6.6<small>%</small> |
| AGG | <span style="color: tomato">1.4<small>%</small></span> | 5.9<small>%</small> | 0.24 | -18.4<small>%</small> | -5.3<small>%</small> |