| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-spy/) | <span style="color: tomato">2.4<small>%</small></span> | 13.0<small>%</small> | 0.18 | -30.9<small>%</small> | -6.7<small>%</small> |
| SPY | <span style="color: tomato">14.9<small>%</small></span> | 19.1<small>%</small> | 0.78 | -33.7<small>%</small> | -5.0<small>%</small> |