| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aok/) | <span style="color: tomato">2.1<small>%</small></span> | 13.0<small>%</small> | 0.16 | -30.9<small>%</small> | -6.7<small>%</small> |
| AOK | <span style="color: tomato">4.5<small>%</small></span> | 7.0<small>%</small> | 0.65 | -18.9<small>%</small> | -3.8<small>%</small> |