| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aor/) | <span style="color: tomato">2.5<small>%</small></span> | 12.9<small>%</small> | 0.19 | -30.9<small>%</small> | -6.7<small>%</small> |
| AOR | <span style="color: tomato">7.5<small>%</small></span> | 11.2<small>%</small> | 0.67 | -22.9<small>%</small> | -4.3<small>%</small> |