| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-spy/) | <span style="color: tomato">3.0<small>%</small></span> | 13.4<small>%</small> | 0.22 | -30.9<small>%</small> | -6.6<small>%</small> |
| SPY | <span style="color: tomato">14.3<small>%</small></span> | 19.1<small>%</small> | 0.75 | -33.7<small>%</small> | -5.4<small>%</small> |