| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pgx/) | <span style="color: tomato">2.6<small>%</small></span> | 13.4<small>%</small> | 0.20 | -30.9<small>%</small> | -6.6<small>%</small> |
| PGX | <span style="color: tomato">2.1<small>%</small></span> | 14.7<small>%</small> | 0.14 | -34.1<small>%</small> | -6.5<small>%</small> |