| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-tlt/) | <span style="color: tomato">2.3<small>%</small></span> | 12.6<small>%</small> | 0.18 | -30.9<small>%</small> | -6.5<small>%</small> |
| TLT | <span style="color: cornflowerblue">-1.9<small>%</small></span> | 15.1<small>%</small> | -0.13 | -48.4<small>%</small> | -22.8<small>%</small> |