| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pff/) | <span style="color: tomato">2.5<small>%</small></span> | 12.9<small>%</small> | 0.19 | -30.9<small>%</small> | -6.7<small>%</small> |
| PFF | <span style="color: tomato">3.1<small>%</small></span> | 13.6<small>%</small> | 0.22 | -34.1<small>%</small> | -5.5<small>%</small> |