| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aom/) | <span style="color: tomato">2.4<small>%</small></span> | 13.0<small>%</small> | 0.18 | -30.9<small>%</small> | -6.7<small>%</small> |
| AOM | <span style="color: tomato">5.6<small>%</small></span> | 8.3<small>%</small> | 0.67 | -20.0<small>%</small> | -3.9<small>%</small> |