| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pgx/) | <span style="color: tomato">2.5<small>%</small></span> | 13.1<small>%</small> | 0.19 | -30.9<small>%</small> | -6.8<small>%</small> |
| PGX | <span style="color: tomato">2.1<small>%</small></span> | 14.3<small>%</small> | 0.15 | -34.1<small>%</small> | -6.7<small>%</small> |