| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-tlt/) | <span style="color: tomato">2.7<small>%</small></span> | 13.0<small>%</small> | 0.21 | -30.9<small>%</small> | -6.7<small>%</small> |
| TLT | <span style="color: cornflowerblue">-1.7<small>%</small></span> | 15.7<small>%</small> | -0.11 | -48.4<small>%</small> | -20.8<small>%</small> |