| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aok/) | <span style="color: tomato">2.8<small>%</small></span> | 13.1<small>%</small> | 0.21 | -30.9<small>%</small> | -6.8<small>%</small> |
| AOK | <span style="color: tomato">4.6<small>%</small></span> | 7.1<small>%</small> | 0.66 | -18.9<small>%</small> | -3.8<small>%</small> |