| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aor/) | <span style="color: tomato">2.1<small>%</small></span> | 12.6<small>%</small> | 0.17 | -30.9<small>%</small> | -6.5<small>%</small> |
| AOR | <span style="color: tomato">7.7<small>%</small></span> | 11.1<small>%</small> | 0.69 | -22.9<small>%</small> | -4.0<small>%</small> |