| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-spy/) | <span style="color: tomato">2.3<small>%</small></span> | 12.6<small>%</small> | 0.18 | -30.9<small>%</small> | -6.5<small>%</small> |
| SPY | <span style="color: tomato">15.2<small>%</small></span> | 18.7<small>%</small> | 0.81 | -33.7<small>%</small> | -4.7<small>%</small> |