| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pff/) | <span style="color: tomato">2.2<small>%</small></span> | 13.2<small>%</small> | 0.17 | -30.9<small>%</small> | -6.8<small>%</small> |
| PFF | <span style="color: tomato">2.7<small>%</small></span> | 13.9<small>%</small> | 0.19 | -34.1<small>%</small> | -5.8<small>%</small> |