| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-tlt/) | <span style="color: tomato">2.8<small>%</small></span> | 20.5<small>%</small> | 0.14 | -66.4<small>%</small> | -8.3<small>%</small> |
| TLT | <span style="color: tomato">2.7<small>%</small></span> | 15.4<small>%</small> | 0.18 | -48.4<small>%</small> | -16.0<small>%</small> |