| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aok/) | <span style="color: tomato">6.2<small>%</small></span> | 16.1<small>%</small> | 0.38 | -53.5<small>%</small> | -4.5<small>%</small> |
| AOK | <span style="color: tomato">5.4<small>%</small></span> | 7.5<small>%</small> | 0.72 | -18.9<small>%</small> | -2.3<small>%</small> |