| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-pff/) | <span style="color: tomato">2.6<small>%</small></span> | 20.1<small>%</small> | 0.13 | -66.4<small>%</small> | -8.1<small>%</small> |
| PFF | <span style="color: tomato">4.1<small>%</small></span> | 18.5<small>%</small> | 0.22 | -64.4<small>%</small> | -5.4<small>%</small> |