| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aok/) | <span style="color: tomato">7.2<small>%</small></span> | 16.8<small>%</small> | 0.43 | -53.5<small>%</small> | -4.3<small>%</small> |
| AOK | <span style="color: tomato">5.1<small>%</small></span> | 7.7<small>%</small> | 0.67 | -18.9<small>%</small> | -2.5<small>%</small> |