| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-agg/) | <span style="color: tomato">3.1<small>%</small></span> | 21.1<small>%</small> | 0.15 | -66.4<small>%</small> | -8.4<small>%</small> |
| AGG | <span style="color: tomato">2.8<small>%</small></span> | 5.5<small>%</small> | 0.50 | -18.4<small>%</small> | -3.0<small>%</small> |