| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-lqd/) | <span style="color: tomato">2.6<small>%</small></span> | 20.1<small>%</small> | 0.13 | -66.4<small>%</small> | -8.1<small>%</small> |
| LQD | <span style="color: tomato">3.9<small>%</small></span> | 8.9<small>%</small> | 0.44 | -25.0<small>%</small> | -4.6<small>%</small> |