| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: tomato">3.0<small>%</small></span> | 20.5<small>%</small> | 0.15 | -66.4<small>%</small> | -8.3<small>%</small> |
| SPY | <span style="color: tomato">11.4<small>%</small></span> | 19.9<small>%</small> | 0.57 | -51.5<small>%</small> | -6.7<small>%</small> |