| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: tomato">3.1<small>%</small></span> | 21.0<small>%</small> | 0.15 | -66.4<small>%</small> | -8.3<small>%</small> |
| SPY | <span style="color: tomato">10.9<small>%</small></span> | 19.9<small>%</small> | 0.55 | -51.5<small>%</small> | -6.9<small>%</small> |