| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-tlt/) | <span style="color: tomato">3.1<small>%</small></span> | 20.6<small>%</small> | 0.15 | -66.4<small>%</small> | -8.3<small>%</small> |
| TLT | <span style="color: tomato">2.6<small>%</small></span> | 15.5<small>%</small> | 0.17 | -48.4<small>%</small> | -15.7<small>%</small> |