| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: tomato">3.1<small>%</small></span> | 20.6<small>%</small> | 0.15 | -66.4<small>%</small> | -8.3<small>%</small> |
| SPY | <span style="color: tomato">11.3<small>%</small></span> | 20.0<small>%</small> | 0.56 | -51.5<small>%</small> | -6.7<small>%</small> |