| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-pff/) | <span style="color: tomato">2.8<small>%</small></span> | 20.6<small>%</small> | 0.14 | -66.4<small>%</small> | -8.3<small>%</small> |
| PFF | <span style="color: tomato">4.1<small>%</small></span> | 19.0<small>%</small> | 0.22 | -64.4<small>%</small> | -5.7<small>%</small> |