| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aor/) | <span style="color: tomato">7.3<small>%</small></span> | 16.8<small>%</small> | 0.43 | -53.5<small>%</small> | -4.3<small>%</small> |
| AOR | <span style="color: tomato">8.5<small>%</small></span> | 12.7<small>%</small> | 0.67 | -24.4<small>%</small> | -3.7<small>%</small> |