| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aor/) | <span style="color: tomato">6.9<small>%</small></span> | 16.5<small>%</small> | 0.42 | -53.5<small>%</small> | -4.5<small>%</small> |
| AOR | <span style="color: tomato">8.7<small>%</small></span> | 12.6<small>%</small> | 0.69 | -24.4<small>%</small> | -3.6<small>%</small> |