| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-tlt/) | <span style="color: tomato">2.6<small>%</small></span> | 20.1<small>%</small> | 0.13 | -66.4<small>%</small> | -8.1<small>%</small> |
| TLT | <span style="color: tomato">2.3<small>%</small></span> | 15.2<small>%</small> | 0.15 | -48.4<small>%</small> | -17.0<small>%</small> |