| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-lqd/) | <span style="color: tomato">3.0<small>%</small></span> | 20.5<small>%</small> | 0.15 | -66.4<small>%</small> | -8.3<small>%</small> |
| LQD | <span style="color: tomato">4.2<small>%</small></span> | 9.0<small>%</small> | 0.47 | -25.0<small>%</small> | -4.7<small>%</small> |