| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aom/) | <span style="color: tomato">5.1<small>%</small></span> | 16.3<small>%</small> | 0.32 | -53.5<small>%</small> | -4.6<small>%</small> |
| AOM | <span style="color: tomato">6.7<small>%</small></span> | 9.7<small>%</small> | 0.69 | -20.0<small>%</small> | -2.7<small>%</small> |