| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-aom/) | <span style="color: tomato">5.8<small>%</small></span> | 17.0<small>%</small> | 0.34 | -53.5<small>%</small> | -4.4<small>%</small> |
| AOM | <span style="color: tomato">6.4<small>%</small></span> | 9.9<small>%</small> | 0.65 | -20.0<small>%</small> | -2.9<small>%</small> |