| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTW](/pltw-vs-pltr/) | <span style="color: tomato">84.6<small>%</small></span> | 83.5<small>%</small> | 1.01 | -40.0<small>%</small> | -11.9<small>%</small> |
| PLTR | <span style="color: tomato">82.6<small>%</small></span> | 69.0<small>%</small> | 1.20 | -34.0<small>%</small> | -9.8<small>%</small> |