| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTW](/pltw-vs-pltr/) | <span style="color: tomato">94.1<small>%</small></span> | 76.0<small>%</small> | 1.24 | -40.0<small>%</small> | -11.8<small>%</small> |
| PLTR | <span style="color: tomato">89.2<small>%</small></span> | 63.1<small>%</small> | 1.41 | -34.0<small>%</small> | -9.5<small>%</small> |