| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTW](/pltw-vs-pltr/) | <span style="color: tomato">118.6<small>%</small></span> | 77.3<small>%</small> | 1.53 | -40.0<small>%</small> | -10.7<small>%</small> |
| PLTR | <span style="color: tomato">107.3<small>%</small></span> | 64.2<small>%</small> | 1.67 | -34.0<small>%</small> | -8.6<small>%</small> |