| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTY](/plty-vs-pltr/) | <span style="color: tomato">163.8<small>%</small></span> | 56.0<small>%</small> | 2.93 | -36.6<small>%</small> | -8.2<small>%</small> |
| PLTR | <span style="color: tomato">304.9<small>%</small></span> | 70.1<small>%</small> | 4.35 | -40.6<small>%</small> | -8.5<small>%</small> |