| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTY](/plty-vs-pltr/) | <span style="color: tomato">183.8<small>%</small></span> | 57.5<small>%</small> | 3.20 | -36.6<small>%</small> | -8.7<small>%</small> |
| PLTR | <span style="color: tomato">369.8<small>%</small></span> | 72.2<small>%</small> | 5.12 | -40.6<small>%</small> | -9.1<small>%</small> |