| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLTY](/plty-vs-pltr/) | <span style="color: tomato">181.3<small>%</small></span> | 60.1<small>%</small> | 3.02 | -36.6<small>%</small> | -8.4<small>%</small> |
| PLTR | <span style="color: tomato">371.0<small>%</small></span> | 75.3<small>%</small> | 4.92 | -40.6<small>%</small> | -8.8<small>%</small> |