| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwm/) | <span style="color: tomato">10.0<small>%</small></span> | 22.8<small>%</small> | 0.44 | -55.8<small>%</small> | -14.0<small>%</small> |
| IWM | <span style="color: tomato">7.8<small>%</small></span> | 23.9<small>%</small> | 0.33 | -58.6<small>%</small> | -10.9<small>%</small> |