| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwo/) | <span style="color: tomato">17.8<small>%</small></span> | 24.9<small>%</small> | 0.71 | -53.0<small>%</small> | -10.1<small>%</small> |
| IWO | <span style="color: tomato">6.8<small>%</small></span> | 25.1<small>%</small> | 0.27 | -60.1<small>%</small> | -16.9<small>%</small> |