| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-qqq/) | <span style="color: tomato">10.7<small>%</small></span> | 23.0<small>%</small> | 0.47 | -55.8<small>%</small> | -14.3<small>%</small> |
| QQQ | <span style="color: tomato">10.3<small>%</small></span> | 27.1<small>%</small> | 0.38 | -83.0<small>%</small> | -33.7<small>%</small> |