| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwm/) | <span style="color: tomato">18.4<small>%</small></span> | 24.9<small>%</small> | 0.74 | -53.0<small>%</small> | -10.0<small>%</small> |
| IWM | <span style="color: tomato">8.0<small>%</small></span> | 23.9<small>%</small> | 0.33 | -58.6<small>%</small> | -10.8<small>%</small> |