| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwm/) | <span style="color: tomato">10.3<small>%</small></span> | 22.7<small>%</small> | 0.45 | -55.8<small>%</small> | -14.1<small>%</small> |
| IWM | <span style="color: tomato">8.2<small>%</small></span> | 23.9<small>%</small> | 0.34 | -58.6<small>%</small> | -10.9<small>%</small> |