| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-qqq/) | <span style="color: tomato">19.3<small>%</small></span> | 25.1<small>%</small> | 0.77 | -53.0<small>%</small> | -10.4<small>%</small> |
| QQQ | <span style="color: tomato">10.4<small>%</small></span> | 27.0<small>%</small> | 0.39 | -83.0<small>%</small> | -33.3<small>%</small> |