| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-spy/) | <span style="color: tomato">20.9<small>%</small></span> | 24.4<small>%</small> | 0.86 | -53.0<small>%</small> | -9.5<small>%</small> |
| SPY | <span style="color: tomato">10.7<small>%</small></span> | 18.6<small>%</small> | 0.58 | -55.2<small>%</small> | -9.2<small>%</small> |