| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-spy/) | <span style="color: tomato">11.6<small>%</small></span> | 21.9<small>%</small> | 0.53 | -55.8<small>%</small> | -12.8<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 18.6<small>%</small> | 0.57 | -55.2<small>%</small> | -9.2<small>%</small> |