| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwo/) | <span style="color: tomato">10.0<small>%</small></span> | 22.7<small>%</small> | 0.44 | -55.8<small>%</small> | -14.4<small>%</small> |
| IWO | <span style="color: tomato">7.2<small>%</small></span> | 25.0<small>%</small> | 0.29 | -60.1<small>%</small> | -16.6<small>%</small> |