| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwo/) | <span style="color: tomato">9.7<small>%</small></span> | 22.7<small>%</small> | 0.43 | -55.8<small>%</small> | -14.2<small>%</small> |
| IWO | <span style="color: tomato">6.6<small>%</small></span> | 25.1<small>%</small> | 0.26 | -60.1<small>%</small> | -17.0<small>%</small> |