| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-spy/) | <span style="color: tomato">12.0<small>%</small></span> | 21.8<small>%</small> | 0.55 | -55.8<small>%</small> | -12.3<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 18.6<small>%</small> | 0.56 | -55.2<small>%</small> | -9.4<small>%</small> |