| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: cornflowerblue">-1.6<small>%</small></span> | 32.4<small>%</small> | -0.05 | -53.6<small>%</small> | -18.8<small>%</small> |
| PYPL | <span style="color: cornflowerblue">-3.1<small>%</small></span> | 38.5<small>%</small> | -0.08 | -57.3<small>%</small> | -21.0<small>%</small> |