| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: cornflowerblue">-0.8<small>%</small></span> | 32.5<small>%</small> | -0.02 | -53.6<small>%</small> | -18.9<small>%</small> |
| PYPL | <span style="color: cornflowerblue">-2.2<small>%</small></span> | 38.5<small>%</small> | -0.06 | -57.3<small>%</small> | -21.1<small>%</small> |