| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: tomato">11.0<small>%</small></span> | 29.0<small>%</small> | 0.38 | -32.3<small>%</small> | -8.9<small>%</small> |
| PYPL | <span style="color: tomato">7.9<small>%</small></span> | 36.0<small>%</small> | 0.22 | -37.5<small>%</small> | -11.1<small>%</small> |