| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">18.3<small>%</small></span> | 19.8<small>%</small> | 0.93 | -22.9<small>%</small> | -3.9<small>%</small> |
| IQQQ | <span style="color: tomato">15.7<small>%</small></span> | 19.6<small>%</small> | 0.80 | -20.4<small>%</small> | -4.2<small>%</small> |