| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">26.5<small>%</small></span> | 16.7<small>%</small> | 1.59 | -10.7<small>%</small> | -1.8<small>%</small> |
| QQQ | <span style="color: tomato">24.1<small>%</small></span> | 17.9<small>%</small> | 1.34 | -13.6<small>%</small> | -2.9<small>%</small> |