| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">19.9<small>%</small></span> | 19.2<small>%</small> | 1.03 | -22.9<small>%</small> | -3.6<small>%</small> |
| QQQ | <span style="color: tomato">21.8<small>%</small></span> | 21.9<small>%</small> | 0.99 | -22.8<small>%</small> | -3.7<small>%</small> |