| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">27.7<small>%</small></span> | 16.8<small>%</small> | 1.65 | -10.7<small>%</small> | -1.9<small>%</small> |
| IQQQ | <span style="color: tomato">21.8<small>%</small></span> | 16.9<small>%</small> | 1.29 | -13.1<small>%</small> | -3.1<small>%</small> |