| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">18.9<small>%</small></span> | 19.7<small>%</small> | 0.96 | -22.9<small>%</small> | -3.8<small>%</small> |
| IQQQ | <span style="color: tomato">16.4<small>%</small></span> | 19.5<small>%</small> | 0.84 | -20.4<small>%</small> | -4.2<small>%</small> |