| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">19.0<small>%</small></span> | 17.0<small>%</small> | 1.12 | -10.7<small>%</small> | -2.0<small>%</small> |
| QQQ | <span style="color: tomato">14.8<small>%</small></span> | 18.2<small>%</small> | 0.81 | -13.6<small>%</small> | -3.2<small>%</small> |