| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTY](/qdty-vs-qqq/) | <span style="color: tomato">9.6<small>%</small></span> | 33.5<small>%</small> | 0.29 | -23.5<small>%</small> | -6.9<small>%</small> |
| QQQ | <span style="color: tomato">19.9<small>%</small></span> | 26.9<small>%</small> | 0.74 | -22.8<small>%</small> | -5.1<small>%</small> |