| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTY](/qdty-vs-qqq/) | <span style="color: tomato">16.2<small>%</small></span> | 25.4<small>%</small> | 0.64 | -23.5<small>%</small> | -4.4<small>%</small> |
| QQQ | <span style="color: tomato">21.4<small>%</small></span> | 22.8<small>%</small> | 0.94 | -22.8<small>%</small> | -3.9<small>%</small> |