| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTY](/qdty-vs-qqq/) | <span style="color: tomato">3.3<small>%</small></span> | 37.2<small>%</small> | 0.09 | -23.5<small>%</small> | -8.5<small>%</small> |
| QQQ | <span style="color: tomato">13.3<small>%</small></span> | 29.7<small>%</small> | 0.45 | -22.8<small>%</small> | -6.2<small>%</small> |