| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDVO](/qdvo-vs-qqq/) | <span style="color: tomato">28.1<small>%</small></span> | 19.1<small>%</small> | 1.47 | -17.8<small>%</small> | -2.3<small>%</small> |
| QQQ | <span style="color: tomato">25.7<small>%</small></span> | 22.7<small>%</small> | 1.13 | -22.8<small>%</small> | -3.3<small>%</small> |