| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDVO](/qdvo-vs-qqq/) | <span style="color: tomato">26.2<small>%</small></span> | 18.9<small>%</small> | 1.39 | -17.8<small>%</small> | -2.3<small>%</small> |
| QQQ | <span style="color: tomato">24.5<small>%</small></span> | 22.4<small>%</small> | 1.09 | -22.8<small>%</small> | -3.3<small>%</small> |