| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDVO](/qdvo-vs-qqq/) | <span style="color: tomato">25.0<small>%</small></span> | 19.0<small>%</small> | 1.32 | -17.8<small>%</small> | -2.3<small>%</small> |
| QQQ | <span style="color: tomato">21.3<small>%</small></span> | 22.6<small>%</small> | 0.95 | -22.8<small>%</small> | -3.3<small>%</small> |