| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QLD](/qld-vs-qqq/) | <span style="color: tomato">24.7<small>%</small></span> | 43.9<small>%</small> | 0.56 | -83.1<small>%</small> | -18.5<small>%</small> |
| QQQ | <span style="color: tomato">16.2<small>%</small></span> | 22.1<small>%</small> | 0.74 | -53.4<small>%</small> | -7.8<small>%</small> |