| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QLD](/qld-vs-qqq/) | <span style="color: tomato">24.4<small>%</small></span> | 43.7<small>%</small> | 0.56 | -83.1<small>%</small> | -19.0<small>%</small> |
| QQQ | <span style="color: tomato">16.0<small>%</small></span> | 22.0<small>%</small> | 0.73 | -53.4<small>%</small> | -8.0<small>%</small> |