| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QLD](/qld-vs-qqq/) | <span style="color: tomato">25.1<small>%</small></span> | 43.9<small>%</small> | 0.57 | -83.1<small>%</small> | -18.5<small>%</small> |
| QQQ | <span style="color: tomato">16.4<small>%</small></span> | 22.0<small>%</small> | 0.75 | -53.4<small>%</small> | -7.8<small>%</small> |