| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQEW](/qqew-vs-qqq/) | <span style="color: tomato">11.2<small>%</small></span> | 21.6<small>%</small> | 0.52 | -58.2<small>%</small> | -8.5<small>%</small> |
| QQQ | <span style="color: tomato">15.4<small>%</small></span> | 22.1<small>%</small> | 0.70 | -53.4<small>%</small> | -7.9<small>%</small> |