| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQEW](/qqew-vs-qqq/) | <span style="color: tomato">11.3<small>%</small></span> | 21.5<small>%</small> | 0.52 | -58.2<small>%</small> | -8.4<small>%</small> |
| QQQ | <span style="color: tomato">15.7<small>%</small></span> | 22.0<small>%</small> | 0.72 | -53.4<small>%</small> | -7.8<small>%</small> |