| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQ](/qqq-vs-spy/) | <span style="color: tomato">9.9<small>%</small></span> | 27.1<small>%</small> | 0.36 | -83.0<small>%</small> | -34.5<small>%</small> |
| SPY | <span style="color: tomato">7.9<small>%</small></span> | 19.3<small>%</small> | 0.41 | -55.2<small>%</small> | -11.1<small>%</small> |