| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQ](/qqq-vs-spy/) | <span style="color: tomato">10.8<small>%</small></span> | 26.8<small>%</small> | 0.40 | -83.0<small>%</small> | -32.5<small>%</small> |
| SPY | <span style="color: tomato">8.6<small>%</small></span> | 19.1<small>%</small> | 0.45 | -55.2<small>%</small> | -10.5<small>%</small> |