| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQ](/qqq-vs-spy/) | <span style="color: tomato">10.2<small>%</small></span> | 27.0<small>%</small> | 0.38 | -83.0<small>%</small> | -33.6<small>%</small> |
| SPY | <span style="color: tomato">8.1<small>%</small></span> | 19.3<small>%</small> | 0.42 | -55.2<small>%</small> | -10.8<small>%</small> |