| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQI](/qqqi-vs-qqq/) | <span style="color: tomato">20.9<small>%</small></span> | 18.1<small>%</small> | 1.16 | -20.0<small>%</small> | -2.4<small>%</small> |
| QQQ | <span style="color: tomato">22.9<small>%</small></span> | 21.8<small>%</small> | 1.05 | -22.8<small>%</small> | -3.6<small>%</small> |