| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQI](/qqqi-vs-qqq/) | <span style="color: tomato">21.4<small>%</small></span> | 17.6<small>%</small> | 1.21 | -20.0<small>%</small> | -2.3<small>%</small> |
| QQQ | <span style="color: tomato">23.6<small>%</small></span> | 21.2<small>%</small> | 1.11 | -22.8<small>%</small> | -3.4<small>%</small> |