| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQI](/qqqi-vs-qqq/) | <span style="color: tomato">20.4<small>%</small></span> | 17.8<small>%</small> | 1.14 | -20.0<small>%</small> | -2.3<small>%</small> |
| QQQ | <span style="color: tomato">23.4<small>%</small></span> | 21.5<small>%</small> | 1.09 | -22.8<small>%</small> | -3.4<small>%</small> |