| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQM](/qqqm-vs-qqq/) | <span style="color: tomato">17.1<small>%</small></span> | 22.2<small>%</small> | 0.77 | -35.0<small>%</small> | -8.1<small>%</small> |
| QQQ | <span style="color: tomato">17.0<small>%</small></span> | 22.3<small>%</small> | 0.76 | -35.1<small>%</small> | -8.1<small>%</small> |