| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQM](/qqqm-vs-qqq/) | <span style="color: tomato">15.0<small>%</small></span> | 22.3<small>%</small> | 0.67 | -35.0<small>%</small> | -10.1<small>%</small> |
| QQQ | <span style="color: tomato">14.9<small>%</small></span> | 22.4<small>%</small> | 0.67 | -35.1<small>%</small> | -10.1<small>%</small> |