| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qqq/) | <span style="color: tomato">12.0<small>%</small></span> | 14.4<small>%</small> | 0.83 | -19.0<small>%</small> | -3.1<small>%</small> |
| QQQ | <span style="color: tomato">23.5<small>%</small></span> | 20.5<small>%</small> | 1.14 | -22.8<small>%</small> | -3.2<small>%</small> |