| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qyld/) | <span style="color: tomato">13.5<small>%</small></span> | 14.4<small>%</small> | 0.94 | -19.0<small>%</small> | -3.1<small>%</small> |
| QYLD | <span style="color: tomato">12.5<small>%</small></span> | 14.3<small>%</small> | 0.88 | -19.1<small>%</small> | -2.8<small>%</small> |