| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qyld/) | <span style="color: tomato">15.4<small>%</small></span> | 12.0<small>%</small> | 1.29 | -10.1<small>%</small> | -2.1<small>%</small> |
| QYLD | <span style="color: tomato">16.8<small>%</small></span> | 10.4<small>%</small> | 1.61 | -7.8<small>%</small> | -0.9<small>%</small> |