| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">16.1<small>%</small></span> | 20.7<small>%</small> | 0.77 | -30.2<small>%</small> | -7.5<small>%</small> |
| SPY | <span style="color: tomato">15.5<small>%</small></span> | 20.5<small>%</small> | 0.76 | -33.7<small>%</small> | -5.6<small>%</small> |