| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">16.1<small>%</small></span> | 20.4<small>%</small> | 0.79 | -30.2<small>%</small> | -7.2<small>%</small> |
| SPY | <span style="color: tomato">15.6<small>%</small></span> | 20.2<small>%</small> | 0.78 | -33.7<small>%</small> | -5.3<small>%</small> |