| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">16.5<small>%</small></span> | 20.5<small>%</small> | 0.80 | -30.2<small>%</small> | -7.3<small>%</small> |
| SPY | <span style="color: tomato">16.0<small>%</small></span> | 20.2<small>%</small> | 0.79 | -33.7<small>%</small> | -5.4<small>%</small> |