| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-xyld/) | <span style="color: tomato">7.3<small>%</small></span> | 15.0<small>%</small> | 0.48 | -24.8<small>%</small> | -4.2<small>%</small> |
| XYLD | <span style="color: tomato">7.0<small>%</small></span> | 14.1<small>%</small> | 0.50 | -33.5<small>%</small> | -4.0<small>%</small> |