| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-xyld/) | <span style="color: tomato">8.6<small>%</small></span> | 14.7<small>%</small> | 0.58 | -24.8<small>%</small> | -3.9<small>%</small> |
| XYLD | <span style="color: tomato">7.9<small>%</small></span> | 13.6<small>%</small> | 0.58 | -33.5<small>%</small> | -3.8<small>%</small> |