| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-qqq/) | <span style="color: tomato">7.8<small>%</small></span> | 14.9<small>%</small> | 0.52 | -24.8<small>%</small> | -4.1<small>%</small> |
| QQQ | <span style="color: tomato">19.5<small>%</small></span> | 21.3<small>%</small> | 0.91 | -35.1<small>%</small> | -5.7<small>%</small> |