| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-qqq/) | <span style="color: tomato">7.7<small>%</small></span> | 14.6<small>%</small> | 0.53 | -24.8<small>%</small> | -4.1<small>%</small> |
| QQQ | <span style="color: tomato">18.6<small>%</small></span> | 21.1<small>%</small> | 0.88 | -35.1<small>%</small> | -5.9<small>%</small> |