| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-qqq/) | <span style="color: tomato">7.6<small>%</small></span> | 14.9<small>%</small> | 0.51 | -24.8<small>%</small> | -4.2<small>%</small> |
| QQQ | <span style="color: tomato">19.1<small>%</small></span> | 21.4<small>%</small> | 0.90 | -35.1<small>%</small> | -5.7<small>%</small> |