| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTE](/rdte-vs-iwm/) | <span style="color: tomato">18.8<small>%</small></span> | 18.6<small>%</small> | 1.01 | -24.3<small>%</small> | -4.2<small>%</small> |
| IWM | <span style="color: tomato">19.5<small>%</small></span> | 21.0<small>%</small> | 0.93 | -27.5<small>%</small> | -5.4<small>%</small> |