| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTE](/rdte-vs-iwm/) | <span style="color: tomato">18.8<small>%</small></span> | 20.1<small>%</small> | 0.94 | -24.3<small>%</small> | -6.4<small>%</small> |
| IWM | <span style="color: tomato">18.8<small>%</small></span> | 23.0<small>%</small> | 0.82 | -27.5<small>%</small> | -8.3<small>%</small> |