| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTE](/rdte-vs-iwm/) | <span style="color: tomato">12.4<small>%</small></span> | 20.6<small>%</small> | 0.60 | -24.3<small>%</small> | -6.8<small>%</small> |
| IWM | <span style="color: tomato">10.1<small>%</small></span> | 23.3<small>%</small> | 0.43 | -27.5<small>%</small> | -8.9<small>%</small> |