| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTY](/rdty-vs-iwm/) | <span style="color: tomato">17.4<small>%</small></span> | 28.6<small>%</small> | 0.61 | -17.3<small>%</small> | -4.0<small>%</small> |
| IWM | <span style="color: tomato">27.2<small>%</small></span> | 27.2<small>%</small> | 1.00 | -16.3<small>%</small> | -3.2<small>%</small> |