| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTY](/rdty-vs-iwm/) | <span style="color: tomato">19.2<small>%</small></span> | 26.5<small>%</small> | 0.73 | -17.3<small>%</small> | -3.4<small>%</small> |
| IWM | <span style="color: tomato">35.0<small>%</small></span> | 25.8<small>%</small> | 1.35 | -16.3<small>%</small> | -2.8<small>%</small> |