| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RDTY](/rdty-vs-iwm/) | <span style="color: tomato">23.0<small>%</small></span> | 21.2<small>%</small> | 1.09 | -17.3<small>%</small> | -2.4<small>%</small> |
| IWM | <span style="color: tomato">31.1<small>%</small></span> | 21.7<small>%</small> | 1.43 | -16.3<small>%</small> | -2.4<small>%</small> |