| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RSP](/rsp-vs-spy/) | <span style="color: tomato">11.2<small>%</small></span> | 20.0<small>%</small> | 0.56 | -59.9<small>%</small> | -6.9<small>%</small> |
| SPY | <span style="color: tomato">11.1<small>%</small></span> | 18.5<small>%</small> | 0.60 | -55.2<small>%</small> | -7.0<small>%</small> |