| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RSP](/rsp-vs-spy/) | <span style="color: tomato">11.3<small>%</small></span> | 19.6<small>%</small> | 0.58 | -59.9<small>%</small> | -6.6<small>%</small> |
| SPY | <span style="color: tomato">11.5<small>%</small></span> | 18.4<small>%</small> | 0.63 | -55.2<small>%</small> | -6.7<small>%</small> |