| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RSP](/rsp-vs-spy/) | <span style="color: tomato">11.0<small>%</small></span> | 19.9<small>%</small> | 0.55 | -59.9<small>%</small> | -6.8<small>%</small> |
| SPY | <span style="color: tomato">11.3<small>%</small></span> | 18.6<small>%</small> | 0.61 | -55.2<small>%</small> | -6.9<small>%</small> |