| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RYLD](/ryld-vs-iwm/) | <span style="color: tomato">3.5<small>%</small></span> | 17.7<small>%</small> | 0.20 | -41.5<small>%</small> | -9.9<small>%</small> |
| IWM | <span style="color: tomato">7.7<small>%</small></span> | 26.2<small>%</small> | 0.29 | -41.1<small>%</small> | -13.2<small>%</small> |