| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RYLD](/ryld-vs-iwm/) | <span style="color: tomato">6.0<small>%</small></span> | 16.9<small>%</small> | 0.36 | -41.5<small>%</small> | -8.9<small>%</small> |
| IWM | <span style="color: tomato">10.7<small>%</small></span> | 25.1<small>%</small> | 0.43 | -41.1<small>%</small> | -11.4<small>%</small> |