| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RYLD](/ryld-vs-iwm/) | <span style="color: tomato">3.7<small>%</small></span> | 17.7<small>%</small> | 0.21 | -41.5<small>%</small> | -9.9<small>%</small> |
| IWM | <span style="color: tomato">8.1<small>%</small></span> | 26.0<small>%</small> | 0.31 | -41.1<small>%</small> | -12.9<small>%</small> |