| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-vig/) | <span style="color: tomato">13.6<small>%</small></span> | 15.3<small>%</small> | 0.89 | -33.4<small>%</small> | -3.3<small>%</small> |
| VIG | <span style="color: tomato">13.1<small>%</small></span> | 14.9<small>%</small> | 0.88 | -31.7<small>%</small> | -3.1<small>%</small> |