| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-divo/) | <span style="color: tomato">11.2<small>%</small></span> | 17.4<small>%</small> | 0.64 | -33.4<small>%</small> | -4.3<small>%</small> |
| DIVO | <span style="color: tomato">12.3<small>%</small></span> | 15.1<small>%</small> | 0.82 | -30.0<small>%</small> | -2.7<small>%</small> |