| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-brk-b/) | <span style="color: tomato">13.6<small>%</small></span> | 15.3<small>%</small> | 0.89 | -33.4<small>%</small> | -3.3<small>%</small> |
| BRK-B | <span style="color: tomato">13.6<small>%</small></span> | 18.2<small>%</small> | 0.75 | -29.6<small>%</small> | -5.9<small>%</small> |