| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">14.8<small>%</small></span> | 13.8<small>%</small> | 1.07 | -11.0<small>%</small> | -3.2<small>%</small> |
| IDVO | <span style="color: tomato">16.0<small>%</small></span> | 15.4<small>%</small> | 1.04 | -11.0<small>%</small> | -2.7<small>%</small> |