| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-brk-b/) | <span style="color: tomato">16.6<small>%</small></span> | 15.6<small>%</small> | 1.07 | -33.4<small>%</small> | -2.8<small>%</small> |
| BRK-B | <span style="color: tomato">14.8<small>%</small></span> | 18.3<small>%</small> | 0.81 | -29.6<small>%</small> | -5.7<small>%</small> |