| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-spy/) | <span style="color: tomato">12.3<small>%</small></span> | 15.5<small>%</small> | 0.80 | -33.4<small>%</small> | -3.4<small>%</small> |
| SPY | <span style="color: tomato">15.0<small>%</small></span> | 16.8<small>%</small> | 0.89 | -33.7<small>%</small> | -3.7<small>%</small> |