| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">15.0<small>%</small></span> | 13.8<small>%</small> | 1.08 | -12.0<small>%</small> | -3.4<small>%</small> |
| IDVO | <span style="color: tomato">15.6<small>%</small></span> | 15.3<small>%</small> | 1.02 | -11.0<small>%</small> | -2.7<small>%</small> |