| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">15.9<small>%</small></span> | 13.7<small>%</small> | 1.16 | -10.8<small>%</small> | -2.9<small>%</small> |
| IDVO | <span style="color: tomato">16.2<small>%</small></span> | 15.4<small>%</small> | 1.05 | -11.0<small>%</small> | -2.7<small>%</small> |