| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-divo/) | <span style="color: tomato">15.5<small>%</small></span> | 17.4<small>%</small> | 0.89 | -33.4<small>%</small> | -3.4<small>%</small> |
| DIVO | <span style="color: tomato">12.3<small>%</small></span> | 15.2<small>%</small> | 0.81 | -30.0<small>%</small> | -2.8<small>%</small> |