| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-spy/) | <span style="color: tomato">16.6<small>%</small></span> | 15.6<small>%</small> | 1.07 | -33.4<small>%</small> | -2.8<small>%</small> |
| SPY | <span style="color: tomato">14.8<small>%</small></span> | 16.6<small>%</small> | 0.89 | -33.7<small>%</small> | -3.7<small>%</small> |