| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">17.4<small>%</small></span> | 19.5<small>%</small> | 0.89 | -33.8<small>%</small> | -5.1<small>%</small> |
| SPY | <span style="color: tomato">13.6<small>%</small></span> | 17.0<small>%</small> | 0.80 | -33.7<small>%</small> | -4.0<small>%</small> |