| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-qqq/) | <span style="color: tomato">16.3<small>%</small></span> | 19.7<small>%</small> | 0.83 | -34.6<small>%</small> | -5.2<small>%</small> |
| QQQ | <span style="color: tomato">18.9<small>%</small></span> | 20.6<small>%</small> | 0.92 | -35.1<small>%</small> | -5.1<small>%</small> |