| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">16.6<small>%</small></span> | 19.8<small>%</small> | 0.84 | -34.6<small>%</small> | -5.2<small>%</small> |
| SPY | <span style="color: tomato">14.0<small>%</small></span> | 17.2<small>%</small> | 0.82 | -33.7<small>%</small> | -3.9<small>%</small> |