| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-qqq/) | <span style="color: tomato">18.0<small>%</small></span> | 19.5<small>%</small> | 0.92 | -33.8<small>%</small> | -5.1<small>%</small> |
| QQQ | <span style="color: tomato">18.4<small>%</small></span> | 20.4<small>%</small> | 0.91 | -35.1<small>%</small> | -5.3<small>%</small> |