| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">16.2<small>%</small></span> | 19.9<small>%</small> | 0.82 | -34.6<small>%</small> | -5.3<small>%</small> |
| SPY | <span style="color: tomato">13.7<small>%</small></span> | 17.3<small>%</small> | 0.80 | -33.7<small>%</small> | -3.9<small>%</small> |