| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDTY](/sdty-vs-spy/) | <span style="color: tomato">10.0<small>%</small></span> | 20.2<small>%</small> | 0.49 | -18.6<small>%</small> | -4.6<small>%</small> |
| SPY | <span style="color: tomato">18.2<small>%</small></span> | 22.0<small>%</small> | 0.83 | -18.8<small>%</small> | -3.6<small>%</small> |