| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDTY](/sdty-vs-spy/) | <span style="color: tomato">9.4<small>%</small></span> | 19.9<small>%</small> | 0.47 | -18.6<small>%</small> | -4.3<small>%</small> |
| SPY | <span style="color: tomato">17.0<small>%</small></span> | 21.6<small>%</small> | 0.79 | -18.8<small>%</small> | -3.4<small>%</small> |