| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDTY](/sdty-vs-spy/) | <span style="color: tomato">10.8<small>%</small></span> | 18.8<small>%</small> | 0.58 | -18.6<small>%</small> | -3.7<small>%</small> |
| SPY | <span style="color: tomato">16.1<small>%</small></span> | 20.4<small>%</small> | 0.79 | -18.8<small>%</small> | -3.1<small>%</small> |