| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDY](/sdy-vs-schd/) | <span style="color: tomato">11.0<small>%</small></span> | 15.6<small>%</small> | 0.70 | -36.7<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">13.2<small>%</small></span> | 15.3<small>%</small> | 0.86 | -33.4<small>%</small> | -3.3<small>%</small> |