| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDY](/sdy-vs-schd/) | <span style="color: tomato">11.8<small>%</small></span> | 16.0<small>%</small> | 0.74 | -36.7<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">16.6<small>%</small></span> | 15.6<small>%</small> | 1.07 | -33.4<small>%</small> | -2.8<small>%</small> |