| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SHY](/shy-vs-tlt/) | <span style="color: tomato">2.0<small>%</small></span> | 1.5<small>%</small> | 1.29 | -5.7<small>%</small> | -0.5<small>%</small> |
| TLT | <span style="color: tomato">3.7<small>%</small></span> | 14.4<small>%</small> | 0.26 | -48.4<small>%</small> | -13.0<small>%</small> |