| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SLV](/slv-vs-gld/) | <span style="color: tomato">6.7<small>%</small></span> | 31.0<small>%</small> | 0.22 | -76.3<small>%</small> | -45.5<small>%</small> |
| GLD | <span style="color: tomato">9.7<small>%</small></span> | 17.6<small>%</small> | 0.55 | -45.6<small>%</small> | -17.3<small>%</small> |