| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SLV](/slv-vs-gld/) | <span style="color: tomato">6.6<small>%</small></span> | 31.0<small>%</small> | 0.21 | -76.3<small>%</small> | -45.4<small>%</small> |
| GLD | <span style="color: tomato">9.8<small>%</small></span> | 17.6<small>%</small> | 0.56 | -45.6<small>%</small> | -17.3<small>%</small> |