| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SLV](/slv-vs-spy/) | <span style="color: tomato">6.1<small>%</small></span> | 31.0<small>%</small> | 0.20 | -76.3<small>%</small> | -45.4<small>%</small> |
| SPY | <span style="color: tomato">10.9<small>%</small></span> | 19.5<small>%</small> | 0.56 | -55.2<small>%</small> | -7.6<small>%</small> |