| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SLV](/slv-vs-spy/) | <span style="color: tomato">5.2<small>%</small></span> | 31.0<small>%</small> | 0.17 | -76.3<small>%</small> | -45.6<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 19.5<small>%</small> | 0.55 | -55.2<small>%</small> | -7.7<small>%</small> |