| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SLV](/slv-vs-gld/) | <span style="color: tomato">7.4<small>%</small></span> | 31.1<small>%</small> | 0.24 | -76.3<small>%</small> | -45.1<small>%</small> |
| GLD | <span style="color: tomato">9.6<small>%</small></span> | 17.7<small>%</small> | 0.55 | -45.6<small>%</small> | -17.2<small>%</small> |