| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SMCY](/smcy-vs-smci/) | <span style="color: cornflowerblue">-15.4<small>%</small></span> | 81.5<small>%</small> | -0.19 | -59.7<small>%</small> | -31.2<small>%</small> |
| SMCI | <span style="color: tomato">4.6<small>%</small></span> | 108.0<small>%</small> | 0.04 | -63.3<small>%</small> | -27.0<small>%</small> |