| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SMCY](/smcy-vs-smci/) | <span style="color: cornflowerblue">-18.7<small>%</small></span> | 82.8<small>%</small> | -0.23 | -59.7<small>%</small> | -31.3<small>%</small> |
| SMCI | <span style="color: tomato">1.5<small>%</small></span> | 109.6<small>%</small> | 0.01 | -63.3<small>%</small> | -27.1<small>%</small> |