| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SMCY](/smcy-vs-smci/) | <span style="color: cornflowerblue">-20.2<small>%</small></span> | 86.7<small>%</small> | -0.23 | -59.7<small>%</small> | -31.2<small>%</small> |
| SMCI | <span style="color: tomato">2.5<small>%</small></span> | 115.0<small>%</small> | 0.02 | -63.3<small>%</small> | -27.0<small>%</small> |