| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: tomato">45.9<small>%</small></span> | 50.4<small>%</small> | 0.91 | -50.9<small>%</small> | -11.5<small>%</small> |
| SNOW | <span style="color: tomato">51.9<small>%</small></span> | 59.7<small>%</small> | 0.87 | -56.3<small>%</small> | -14.6<small>%</small> |