| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: tomato">57.4<small>%</small></span> | 43.0<small>%</small> | 1.34 | -26.2<small>%</small> | -6.9<small>%</small> |
| SNOW | <span style="color: tomato">73.0<small>%</small></span> | 54.3<small>%</small> | 1.34 | -32.3<small>%</small> | -10.0<small>%</small> |