| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: tomato">88.8<small>%</small></span> | 48.8<small>%</small> | 1.82 | -17.4<small>%</small> | -6.8<small>%</small> |
| SNOW | <span style="color: tomato">92.7<small>%</small></span> | 62.5<small>%</small> | 1.48 | -24.1<small>%</small> | -12.5<small>%</small> |