| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">10.1<small>%</small></span> | 16.5<small>%</small> | 0.61 | -41.4<small>%</small> | -4.8<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 16.6<small>%</small> | 0.87 | -33.7<small>%</small> | -3.8<small>%</small> |