| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-schd/) | <span style="color: tomato">10.1<small>%</small></span> | 16.5<small>%</small> | 0.61 | -41.4<small>%</small> | -4.8<small>%</small> |
| SCHD | <span style="color: tomato">17.8<small>%</small></span> | 15.8<small>%</small> | 1.13 | -33.4<small>%</small> | -2.8<small>%</small> |