| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">9.7<small>%</small></span> | 16.2<small>%</small> | 0.60 | -41.4<small>%</small> | -4.7<small>%</small> |
| SPY | <span style="color: tomato">14.9<small>%</small></span> | 16.7<small>%</small> | 0.89 | -33.7<small>%</small> | -3.6<small>%</small> |