| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 16.4<small>%</small> | 0.57 | -41.4<small>%</small> | -4.8<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 16.9<small>%</small> | 0.86 | -33.7<small>%</small> | -3.8<small>%</small> |