| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-splv/) | <span style="color: tomato">9.4<small>%</small></span> | 16.4<small>%</small> | 0.58 | -41.4<small>%</small> | -4.8<small>%</small> |
| SPLV | <span style="color: tomato">10.1<small>%</small></span> | 14.7<small>%</small> | 0.69 | -36.3<small>%</small> | -3.7<small>%</small> |