| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-splv/) | <span style="color: tomato">9.0<small>%</small></span> | 16.1<small>%</small> | 0.56 | -41.4<small>%</small> | -4.7<small>%</small> |
| SPLV | <span style="color: tomato">9.3<small>%</small></span> | 14.4<small>%</small> | 0.64 | -36.3<small>%</small> | -3.7<small>%</small> |