| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-schd/) | <span style="color: tomato">9.5<small>%</small></span> | 16.1<small>%</small> | 0.59 | -41.4<small>%</small> | -4.7<small>%</small> |
| SCHD | <span style="color: tomato">13.2<small>%</small></span> | 15.5<small>%</small> | 0.85 | -33.4<small>%</small> | -3.4<small>%</small> |