| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-splv/) | <span style="color: tomato">10.2<small>%</small></span> | 16.5<small>%</small> | 0.62 | -41.4<small>%</small> | -4.8<small>%</small> |
| SPLV | <span style="color: tomato">10.6<small>%</small></span> | 14.8<small>%</small> | 0.72 | -36.3<small>%</small> | -3.8<small>%</small> |