| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLG](/splg-vs-spy/) | <span style="color: tomato">14.4<small>%</small></span> | 17.8<small>%</small> | 0.81 | -33.9<small>%</small> | -4.0<small>%</small> |
| SPY | <span style="color: tomato">14.3<small>%</small></span> | 17.9<small>%</small> | 0.80 | -33.7<small>%</small> | -4.0<small>%</small> |