| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLG](/splg-vs-spy/) | <span style="color: tomato">14.8<small>%</small></span> | 17.7<small>%</small> | 0.84 | -33.9<small>%</small> | -3.9<small>%</small> |
| SPY | <span style="color: tomato">14.7<small>%</small></span> | 17.7<small>%</small> | 0.83 | -33.7<small>%</small> | -3.9<small>%</small> |