| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLV](/splv-vs-spy/) | <span style="color: tomato">10.1<small>%</small></span> | 14.6<small>%</small> | 0.70 | -36.3<small>%</small> | -3.6<small>%</small> |
| SPY | <span style="color: tomato">13.9<small>%</small></span> | 17.2<small>%</small> | 0.81 | -33.7<small>%</small> | -3.9<small>%</small> |