| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLV](/splv-vs-spy/) | <span style="color: tomato">10.5<small>%</small></span> | 14.7<small>%</small> | 0.72 | -36.3<small>%</small> | -3.6<small>%</small> |
| SPY | <span style="color: tomato">13.7<small>%</small></span> | 17.3<small>%</small> | 0.79 | -33.7<small>%</small> | -3.9<small>%</small> |