| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLV](/splv-vs-spy/) | <span style="color: tomato">10.0<small>%</small></span> | 14.4<small>%</small> | 0.69 | -36.3<small>%</small> | -3.5<small>%</small> |
| SPY | <span style="color: tomato">14.1<small>%</small></span> | 17.0<small>%</small> | 0.83 | -33.7<small>%</small> | -3.8<small>%</small> |