| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPMO](/spmo-vs-spy/) | <span style="color: tomato">18.8<small>%</small></span> | 20.3<small>%</small> | 0.93 | -30.9<small>%</small> | -4.6<small>%</small> |
| SPY | <span style="color: tomato">14.8<small>%</small></span> | 17.6<small>%</small> | 0.84 | -33.7<small>%</small> | -4.2<small>%</small> |