| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPMO](/spmo-vs-qqq/) | <span style="color: tomato">18.3<small>%</small></span> | 19.8<small>%</small> | 0.93 | -30.9<small>%</small> | -4.7<small>%</small> |
| QQQ | <span style="color: tomato">19.8<small>%</small></span> | 22.2<small>%</small> | 0.89 | -35.1<small>%</small> | -6.4<small>%</small> |