| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPMO](/spmo-vs-qqq/) | <span style="color: tomato">18.1<small>%</small></span> | 19.9<small>%</small> | 0.91 | -30.9<small>%</small> | -4.8<small>%</small> |
| QQQ | <span style="color: tomato">19.3<small>%</small></span> | 22.4<small>%</small> | 0.86 | -35.1<small>%</small> | -6.4<small>%</small> |