| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPMO](/spmo-vs-spy/) | <span style="color: tomato">18.3<small>%</small></span> | 19.8<small>%</small> | 0.93 | -30.9<small>%</small> | -4.7<small>%</small> |
| SPY | <span style="color: tomato">14.8<small>%</small></span> | 17.9<small>%</small> | 0.83 | -33.7<small>%</small> | -4.4<small>%</small> |