| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-vig/) | <span style="color: tomato">11.1<small>%</small></span> | 19.3<small>%</small> | 0.58 | -55.2<small>%</small> | -7.4<small>%</small> |
| VIG | <span style="color: tomato">10.2<small>%</small></span> | 16.9<small>%</small> | 0.61 | -46.8<small>%</small> | -5.5<small>%</small> |