| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-divo/) | <span style="color: tomato">14.9<small>%</small></span> | 18.5<small>%</small> | 0.80 | -33.7<small>%</small> | -4.7<small>%</small> |
| DIVO | <span style="color: tomato">12.5<small>%</small></span> | 15.1<small>%</small> | 0.83 | -30.0<small>%</small> | -2.7<small>%</small> |