| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-divo/) | <span style="color: tomato">15.2<small>%</small></span> | 18.1<small>%</small> | 0.84 | -33.7<small>%</small> | -4.4<small>%</small> |
| DIVO | <span style="color: tomato">12.9<small>%</small></span> | 14.7<small>%</small> | 0.88 | -30.0<small>%</small> | -2.6<small>%</small> |