| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-shy/) | <span style="color: tomato">10.9<small>%</small></span> | 18.8<small>%</small> | 0.58 | -55.2<small>%</small> | -7.1<small>%</small> |
| SHY | <span style="color: tomato">1.8<small>%</small></span> | 1.5<small>%</small> | 1.21 | -5.7<small>%</small> | -0.5<small>%</small> |