| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-tlt/) | <span style="color: tomato">11.1<small>%</small></span> | 18.9<small>%</small> | 0.59 | -55.2<small>%</small> | -6.9<small>%</small> |
| TLT | <span style="color: tomato">3.9<small>%</small></span> | 14.4<small>%</small> | 0.27 | -48.4<small>%</small> | -13.2<small>%</small> |