| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-idvo/) | <span style="color: tomato">18.8<small>%</small></span> | 17.1<small>%</small> | 1.10 | -18.8<small>%</small> | -2.8<small>%</small> |
| IDVO | <span style="color: tomato">18.2<small>%</small></span> | 16.3<small>%</small> | 1.12 | -15.5<small>%</small> | -2.5<small>%</small> |