| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-tlt/) | <span style="color: tomato">10.8<small>%</small></span> | 18.9<small>%</small> | 0.57 | -55.2<small>%</small> | -7.0<small>%</small> |
| TLT | <span style="color: tomato">3.7<small>%</small></span> | 14.4<small>%</small> | 0.26 | -48.4<small>%</small> | -12.9<small>%</small> |