| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-bil/) | <span style="color: tomato">10.3<small>%</small></span> | 19.9<small>%</small> | 0.52 | -55.2<small>%</small> | -8.0<small>%</small> |
| BIL | <span style="color: tomato">1.3<small>%</small></span> | 0.5<small>%</small> | 2.58 | -0.8<small>%</small> | -0.3<small>%</small> |