| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-ief/) | <span style="color: tomato">10.8<small>%</small></span> | 18.9<small>%</small> | 0.57 | -55.2<small>%</small> | -6.9<small>%</small> |
| IEF | <span style="color: tomato">3.7<small>%</small></span> | 6.9<small>%</small> | 0.53 | -23.9<small>%</small> | -5.1<small>%</small> |