| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-tlt/) | <span style="color: tomato">11.3<small>%</small></span> | 18.7<small>%</small> | 0.60 | -55.2<small>%</small> | -6.7<small>%</small> |
| TLT | <span style="color: tomato">3.5<small>%</small></span> | 14.2<small>%</small> | 0.25 | -48.4<small>%</small> | -14.1<small>%</small> |