| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-idvo/) | <span style="color: tomato">20.0<small>%</small></span> | 16.7<small>%</small> | 1.19 | -18.8<small>%</small> | -2.6<small>%</small> |
| IDVO | <span style="color: tomato">20.5<small>%</small></span> | 16.0<small>%</small> | 1.28 | -15.5<small>%</small> | -2.3<small>%</small> |