| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-schd/) | <span style="color: tomato">15.0<small>%</small></span> | 16.6<small>%</small> | 0.91 | -33.7<small>%</small> | -3.7<small>%</small> |
| SCHD | <span style="color: tomato">11.5<small>%</small></span> | 15.5<small>%</small> | 0.74 | -33.4<small>%</small> | -3.7<small>%</small> |