| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-vig/) | <span style="color: tomato">10.7<small>%</small></span> | 19.5<small>%</small> | 0.55 | -55.2<small>%</small> | -7.7<small>%</small> |
| VIG | <span style="color: tomato">10.0<small>%</small></span> | 17.1<small>%</small> | 0.58 | -46.8<small>%</small> | -5.6<small>%</small> |