| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-ief/) | <span style="color: tomato">11.3<small>%</small></span> | 18.7<small>%</small> | 0.60 | -55.2<small>%</small> | -6.7<small>%</small> |
| IEF | <span style="color: tomato">3.5<small>%</small></span> | 6.8<small>%</small> | 0.52 | -23.9<small>%</small> | -5.4<small>%</small> |