| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-bil/) | <span style="color: tomato">10.7<small>%</small></span> | 19.6<small>%</small> | 0.55 | -55.2<small>%</small> | -7.7<small>%</small> |
| BIL | <span style="color: tomato">1.4<small>%</small></span> | 0.5<small>%</small> | 2.85 | -0.8<small>%</small> | -0.3<small>%</small> |