| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-schd/) | <span style="color: tomato">14.9<small>%</small></span> | 16.6<small>%</small> | 0.90 | -33.7<small>%</small> | -3.7<small>%</small> |
| SCHD | <span style="color: tomato">17.7<small>%</small></span> | 15.6<small>%</small> | 1.13 | -33.4<small>%</small> | -2.7<small>%</small> |