| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-shy/) | <span style="color: tomato">11.0<small>%</small></span> | 18.9<small>%</small> | 0.58 | -55.2<small>%</small> | -6.9<small>%</small> |
| SHY | <span style="color: tomato">2.0<small>%</small></span> | 1.5<small>%</small> | 1.30 | -5.7<small>%</small> | -0.5<small>%</small> |