| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-brk-b/) | <span style="color: tomato">9.9<small>%</small></span> | 19.3<small>%</small> | 0.51 | -55.2<small>%</small> | -10.3<small>%</small> |
| BRK-B | <span style="color: tomato">11.0<small>%</small></span> | 22.3<small>%</small> | 0.50 | -53.9<small>%</small> | -11.3<small>%</small> |