| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYD](/spyd-vs-spy/) | <span style="color: tomato">9.5<small>%</small></span> | 19.4<small>%</small> | 0.49 | -46.4<small>%</small> | -6.1<small>%</small> |
| SPY | <span style="color: tomato">14.8<small>%</small></span> | 17.6<small>%</small> | 0.84 | -33.7<small>%</small> | -4.2<small>%</small> |