| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYD](/spyd-vs-spy/) | <span style="color: tomato">8.7<small>%</small></span> | 20.0<small>%</small> | 0.44 | -46.4<small>%</small> | -6.5<small>%</small> |
| SPY | <span style="color: tomato">14.1<small>%</small></span> | 18.1<small>%</small> | 0.78 | -33.7<small>%</small> | -4.5<small>%</small> |