| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-vug/) | <span style="color: tomato">12.0<small>%</small></span> | 19.4<small>%</small> | 0.62 | -51.3<small>%</small> | -7.0<small>%</small> |
| VUG | <span style="color: tomato">12.4<small>%</small></span> | 20.0<small>%</small> | 0.62 | -50.7<small>%</small> | -7.2<small>%</small> |