| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-schd/) | <span style="color: tomato">16.9<small>%</small></span> | 18.8<small>%</small> | 0.90 | -32.7<small>%</small> | -5.1<small>%</small> |
| SCHD | <span style="color: tomato">12.4<small>%</small></span> | 15.6<small>%</small> | 0.79 | -33.4<small>%</small> | -3.4<small>%</small> |