| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-vug/) | <span style="color: tomato">12.1<small>%</small></span> | 19.4<small>%</small> | 0.63 | -51.3<small>%</small> | -6.9<small>%</small> |
| VUG | <span style="color: tomato">12.2<small>%</small></span> | 19.9<small>%</small> | 0.61 | -50.7<small>%</small> | -7.1<small>%</small> |