| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-vug/) | <span style="color: tomato">11.5<small>%</small></span> | 19.2<small>%</small> | 0.60 | -51.3<small>%</small> | -7.2<small>%</small> |
| VUG | <span style="color: tomato">12.0<small>%</small></span> | 19.8<small>%</small> | 0.61 | -50.7<small>%</small> | -7.3<small>%</small> |