| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-spy/) | <span style="color: tomato">7.3<small>%</small></span> | 21.6<small>%</small> | 0.34 | -67.6<small>%</small> | -24.8<small>%</small> |
| SPY | <span style="color: tomato">8.4<small>%</small></span> | 19.2<small>%</small> | 0.43 | -55.2<small>%</small> | -10.1<small>%</small> |