| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-schd/) | <span style="color: tomato">16.7<small>%</small></span> | 18.8<small>%</small> | 0.89 | -32.7<small>%</small> | -5.2<small>%</small> |
| SCHD | <span style="color: tomato">12.5<small>%</small></span> | 15.6<small>%</small> | 0.81 | -33.4<small>%</small> | -3.4<small>%</small> |