| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-spy/) | <span style="color: tomato">6.7<small>%</small></span> | 21.5<small>%</small> | 0.31 | -67.6<small>%</small> | -25.6<small>%</small> |
| SPY | <span style="color: tomato">8.1<small>%</small></span> | 19.2<small>%</small> | 0.42 | -55.2<small>%</small> | -10.4<small>%</small> |