| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-spy/) | <span style="color: tomato">7.0<small>%</small></span> | 21.7<small>%</small> | 0.32 | -67.6<small>%</small> | -25.1<small>%</small> |
| SPY | <span style="color: tomato">8.1<small>%</small></span> | 19.3<small>%</small> | 0.42 | -55.2<small>%</small> | -10.2<small>%</small> |