| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">14.0<small>%</small></span> | 13.6<small>%</small> | 1.03 | -16.5<small>%</small> | -2.1<small>%</small> |
| XYLD | <span style="color: tomato">9.4<small>%</small></span> | 11.5<small>%</small> | 0.82 | -15.5<small>%</small> | -2.2<small>%</small> |