| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">14.6<small>%</small></span> | 13.4<small>%</small> | 1.09 | -16.5<small>%</small> | -2.0<small>%</small> |
| XYLD | <span style="color: tomato">9.6<small>%</small></span> | 11.3<small>%</small> | 0.84 | -15.5<small>%</small> | -2.3<small>%</small> |