| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">14.2<small>%</small></span> | 11.5<small>%</small> | 1.23 | -10.2<small>%</small> | -1.9<small>%</small> |
| SPY | <span style="color: tomato">21.0<small>%</small></span> | 15.2<small>%</small> | 1.38 | -12.9<small>%</small> | -2.5<small>%</small> |