| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">14.2<small>%</small></span> | 13.6<small>%</small> | 1.05 | -16.5<small>%</small> | -2.1<small>%</small> |
| SPY | <span style="color: tomato">19.3<small>%</small></span> | 17.1<small>%</small> | 1.13 | -18.8<small>%</small> | -2.7<small>%</small> |