| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">15.4<small>%</small></span> | 11.5<small>%</small> | 1.34 | -10.2<small>%</small> | -1.8<small>%</small> |
| SPY | <span style="color: tomato">22.0<small>%</small></span> | 15.2<small>%</small> | 1.44 | -12.9<small>%</small> | -2.5<small>%</small> |