| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">15.2<small>%</small></span> | 12.8<small>%</small> | 1.19 | -16.5<small>%</small> | -1.8<small>%</small> |
| XYLD | <span style="color: tomato">11.7<small>%</small></span> | 10.5<small>%</small> | 1.12 | -15.5<small>%</small> | -1.9<small>%</small> |