| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYM](/spym-vs-spy/) | <span style="color: tomato">11.3<small>%</small></span> | 18.2<small>%</small> | 0.62 | -54.5<small>%</small> | -7.1<small>%</small> |
| SPY | <span style="color: tomato">11.3<small>%</small></span> | 19.1<small>%</small> | 0.59 | -55.2<small>%</small> | -7.2<small>%</small> |