| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">61.7<small>%</small></span> | 38.2<small>%</small> | 1.61 | -20.9<small>%</small> | -8.0<small>%</small> |
| SQ | <span style="color: tomato">80.5<small>%</small></span> | 48.1<small>%</small> | 1.67 | -33.3<small>%</small> | -14.2<small>%</small> |