| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-xyz/) | <span style="color: tomato">10.6<small>%</small></span> | 41.8<small>%</small> | 0.25 | -49.1<small>%</small> | -16.8<small>%</small> |
| XYZ | <span style="color: cornflowerblue">-7.9<small>%</small></span> | 59.2<small>%</small> | -0.13 | -53.0<small>%</small> | -22.7<small>%</small> |