| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">71.6<small>%</small></span> | 37.9<small>%</small> | 1.89 | -20.9<small>%</small> | -7.7<small>%</small> |
| SQ | <span style="color: tomato">78.1<small>%</small></span> | 48.2<small>%</small> | 1.62 | -33.3<small>%</small> | -13.7<small>%</small> |