| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">76.8<small>%</small></span> | 37.8<small>%</small> | 2.03 | -20.9<small>%</small> | -7.8<small>%</small> |
| SQ | <span style="color: tomato">86.7<small>%</small></span> | 48.2<small>%</small> | 1.80 | -33.3<small>%</small> | -13.9<small>%</small> |