| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-xyz/) | <span style="color: tomato">8.2<small>%</small></span> | 41.8<small>%</small> | 0.20 | -49.1<small>%</small> | -17.0<small>%</small> |
| XYZ | <span style="color: cornflowerblue">-10.6<small>%</small></span> | 59.1<small>%</small> | -0.18 | -53.0<small>%</small> | -22.8<small>%</small> |