| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-xyz/) | <span style="color: tomato">6.1<small>%</small></span> | 41.8<small>%</small> | 0.15 | -49.1<small>%</small> | -17.0<small>%</small> |
| XYZ | <span style="color: cornflowerblue">-12.7<small>%</small></span> | 59.1<small>%</small> | -0.22 | -53.0<small>%</small> | -22.9<small>%</small> |