| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-0.1<small>%</small></span> | 11.9<small>%</small> | -0.01 | -18.6<small>%</small> | -9.4<small>%</small> |
| TLT | <span style="color: cornflowerblue">-2.7<small>%</small></span> | 16.3<small>%</small> | -0.16 | -24.5<small>%</small> | -11.9<small>%</small> |