| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-0.4<small>%</small></span> | 11.8<small>%</small> | -0.03 | -18.6<small>%</small> | -9.1<small>%</small> |
| TLT | <span style="color: cornflowerblue">-3.3<small>%</small></span> | 16.0<small>%</small> | -0.20 | -24.5<small>%</small> | -11.8<small>%</small> |