| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-1.7<small>%</small></span> | 11.2<small>%</small> | -0.15 | -18.6<small>%</small> | -8.0<small>%</small> |
| TLT | <span style="color: cornflowerblue">-4.9<small>%</small></span> | 14.9<small>%</small> | -0.33 | -24.5<small>%</small> | -12.1<small>%</small> |