| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TQQQ](/tqqq-vs-qqq/) | <span style="color: tomato">41.7<small>%</small></span> | 61.0<small>%</small> | 0.68 | -81.7<small>%</small> | -18.8<small>%</small> |
| QQQ | <span style="color: tomato">19.1<small>%</small></span> | 20.6<small>%</small> | 0.93 | -35.1<small>%</small> | -5.2<small>%</small> |