| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TQQQ](/tqqq-vs-qqq/) | <span style="color: tomato">42.9<small>%</small></span> | 60.9<small>%</small> | 0.70 | -81.7<small>%</small> | -18.8<small>%</small> |
| QQQ | <span style="color: tomato">19.5<small>%</small></span> | 20.6<small>%</small> | 0.95 | -35.1<small>%</small> | -5.2<small>%</small> |