| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TQQQ](/tqqq-vs-qqq/) | <span style="color: tomato">42.4<small>%</small></span> | 60.3<small>%</small> | 0.70 | -81.7<small>%</small> | -19.0<small>%</small> |
| QQQ | <span style="color: tomato">19.1<small>%</small></span> | 20.4<small>%</small> | 0.94 | -35.1<small>%</small> | -5.3<small>%</small> |