| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLW](/tslw-vs-tsla/) | <span style="color: cornflowerblue">-13.5<small>%</small></span> | 86.7<small>%</small> | -0.16 | -45.1<small>%</small> | -20.0<small>%</small> |
| TSLA | <span style="color: cornflowerblue">-7.0<small>%</small></span> | 72.2<small>%</small> | -0.10 | -38.5<small>%</small> | -16.1<small>%</small> |