| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLW](/tslw-vs-tsla/) | <span style="color: tomato">42.2<small>%</small></span> | 84.4<small>%</small> | 0.50 | -45.1<small>%</small> | -18.1<small>%</small> |
| TSLA | <span style="color: tomato">41.0<small>%</small></span> | 70.4<small>%</small> | 0.58 | -38.5<small>%</small> | -14.6<small>%</small> |