| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLW](/tslw-vs-tsla/) | <span style="color: tomato">36.5<small>%</small></span> | 84.1<small>%</small> | 0.43 | -45.2<small>%</small> | -18.7<small>%</small> |
| TSLA | <span style="color: tomato">44.0<small>%</small></span> | 70.2<small>%</small> | 0.63 | -38.5<small>%</small> | -14.3<small>%</small> |