| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: tomato">16.9<small>%</small></span> | 47.4<small>%</small> | 0.36 | -49.5<small>%</small> | -22.0<small>%</small> |
| TSLA | <span style="color: tomato">35.0<small>%</small></span> | 61.6<small>%</small> | 0.57 | -53.8<small>%</small> | -22.9<small>%</small> |