| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: tomato">8.2<small>%</small></span> | 47.8<small>%</small> | 0.17 | -49.5<small>%</small> | -22.8<small>%</small> |
| TSLA | <span style="color: tomato">24.7<small>%</small></span> | 62.2<small>%</small> | 0.40 | -53.8<small>%</small> | -23.6<small>%</small> |