| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: cornflowerblue">-0.1<small>%</small></span> | 43.6<small>%</small> | -0.00 | -45.6<small>%</small> | -21.9<small>%</small> |
| TSLA | <span style="color: tomato">17.1<small>%</small></span> | 58.2<small>%</small> | 0.29 | -51.6<small>%</small> | -21.7<small>%</small> |