| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSMY](/tsmy-vs-tsm/) | <span style="color: tomato">41.5<small>%</small></span> | 34.5<small>%</small> | 1.21 | -31.2<small>%</small> | -6.4<small>%</small> |
| TSM | <span style="color: tomato">62.7<small>%</small></span> | 42.5<small>%</small> | 1.47 | -36.8<small>%</small> | -8.1<small>%</small> |