| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSMY](/tsmy-vs-tsm/) | <span style="color: tomato">44.0<small>%</small></span> | 34.6<small>%</small> | 1.27 | -31.2<small>%</small> | -6.5<small>%</small> |
| TSM | <span style="color: tomato">67.0<small>%</small></span> | 42.7<small>%</small> | 1.57 | -36.8<small>%</small> | -8.1<small>%</small> |