| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSMY](/tsmy-vs-tsm/) | <span style="color: tomato">36.2<small>%</small></span> | 33.6<small>%</small> | 1.08 | -31.2<small>%</small> | -6.2<small>%</small> |
| TSM | <span style="color: tomato">53.6<small>%</small></span> | 41.4<small>%</small> | 1.30 | -36.8<small>%</small> | -7.8<small>%</small> |