| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VEA](/vea-vs-spy/) | <span style="color: tomato">4.2<small>%</small></span> | 21.7<small>%</small> | 0.20 | -60.7<small>%</small> | -13.8<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 20.0<small>%</small> | 0.52 | -55.2<small>%</small> | -8.1<small>%</small> |