| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VEA](/vea-vs-spy/) | <span style="color: tomato">5.4<small>%</small></span> | 21.4<small>%</small> | 0.25 | -60.7<small>%</small> | -13.1<small>%</small> |
| SPY | <span style="color: tomato">11.0<small>%</small></span> | 19.7<small>%</small> | 0.56 | -55.2<small>%</small> | -7.7<small>%</small> |