| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-schd/) | <span style="color: tomato">13.1<small>%</small></span> | 15.1<small>%</small> | 0.86 | -31.7<small>%</small> | -3.2<small>%</small> |
| SCHD | <span style="color: tomato">12.3<small>%</small></span> | 15.5<small>%</small> | 0.79 | -33.4<small>%</small> | -3.4<small>%</small> |