| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-schd/) | <span style="color: tomato">12.8<small>%</small></span> | 15.2<small>%</small> | 0.84 | -31.7<small>%</small> | -3.2<small>%</small> |
| SCHD | <span style="color: tomato">12.3<small>%</small></span> | 15.6<small>%</small> | 0.79 | -33.4<small>%</small> | -3.3<small>%</small> |