| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-brk-b/) | <span style="color: tomato">10.0<small>%</small></span> | 17.1<small>%</small> | 0.58 | -46.8<small>%</small> | -5.6<small>%</small> |
| BRK-B | <span style="color: tomato">11.3<small>%</small></span> | 21.5<small>%</small> | 0.53 | -53.9<small>%</small> | -10.2<small>%</small> |