| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-brk-b/) | <span style="color: tomato">9.9<small>%</small></span> | 17.2<small>%</small> | 0.58 | -46.8<small>%</small> | -5.8<small>%</small> |
| BRK-B | <span style="color: tomato">11.8<small>%</small></span> | 21.7<small>%</small> | 0.54 | -53.9<small>%</small> | -10.4<small>%</small> |