| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-spy/) | <span style="color: tomato">9.8<small>%</small></span> | 17.2<small>%</small> | 0.57 | -46.8<small>%</small> | -5.8<small>%</small> |
| SPY | <span style="color: tomato">10.3<small>%</small></span> | 19.5<small>%</small> | 0.53 | -55.2<small>%</small> | -7.9<small>%</small> |