| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-divo/) | <span style="color: tomato">12.8<small>%</small></span> | 16.5<small>%</small> | 0.77 | -31.7<small>%</small> | -3.8<small>%</small> |
| DIVO | <span style="color: tomato">12.2<small>%</small></span> | 15.0<small>%</small> | 0.81 | -30.0<small>%</small> | -2.7<small>%</small> |