| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-divo/) | <span style="color: tomato">13.0<small>%</small></span> | 16.1<small>%</small> | 0.81 | -31.7<small>%</small> | -3.6<small>%</small> |
| DIVO | <span style="color: tomato">12.6<small>%</small></span> | 14.6<small>%</small> | 0.86 | -30.0<small>%</small> | -2.6<small>%</small> |