| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-schd/) | <span style="color: tomato">13.2<small>%</small></span> | 15.1<small>%</small> | 0.88 | -31.7<small>%</small> | -3.2<small>%</small> |
| SCHD | <span style="color: tomato">17.5<small>%</small></span> | 15.6<small>%</small> | 1.12 | -33.4<small>%</small> | -2.7<small>%</small> |