| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VNQ](/vnq-vs-spy/) | <span style="color: tomato">7.2<small>%</small></span> | 28.1<small>%</small> | 0.26 | -73.1<small>%</small> | -13.5<small>%</small> |
| SPY | <span style="color: tomato">11.2<small>%</small></span> | 18.7<small>%</small> | 0.60 | -55.2<small>%</small> | -6.9<small>%</small> |