| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VNQ](/vnq-vs-spy/) | <span style="color: tomato">7.4<small>%</small></span> | 28.6<small>%</small> | 0.26 | -73.1<small>%</small> | -13.8<small>%</small> |
| SPY | <span style="color: tomato">11.0<small>%</small></span> | 19.0<small>%</small> | 0.58 | -55.2<small>%</small> | -7.2<small>%</small> |