| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VOO](/voo-vs-spy/) | <span style="color: tomato">14.6<small>%</small></span> | 17.0<small>%</small> | 0.86 | -34.0<small>%</small> | -3.8<small>%</small> |
| SPY | <span style="color: tomato">14.6<small>%</small></span> | 16.9<small>%</small> | 0.87 | -33.7<small>%</small> | -3.8<small>%</small> |