| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VOO](/voo-vs-vti/) | <span style="color: tomato">14.5<small>%</small></span> | 17.2<small>%</small> | 0.84 | -34.0<small>%</small> | -3.8<small>%</small> |
| VTI | <span style="color: tomato">14.1<small>%</small></span> | 17.5<small>%</small> | 0.81 | -35.0<small>%</small> | -4.2<small>%</small> |