| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VT](/vt-vs-vti/) | <span style="color: tomato">7.8<small>%</small></span> | 20.8<small>%</small> | 0.37 | -50.3<small>%</small> | -7.5<small>%</small> |
| VTI | <span style="color: tomato">11.8<small>%</small></span> | 20.1<small>%</small> | 0.58 | -48.0<small>%</small> | -6.2<small>%</small> |