| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VT](/vt-vs-vti/) | <span style="color: tomato">8.4<small>%</small></span> | 20.7<small>%</small> | 0.40 | -50.3<small>%</small> | -7.2<small>%</small> |
| VTI | <span style="color: tomato">11.9<small>%</small></span> | 20.1<small>%</small> | 0.59 | -48.0<small>%</small> | -6.0<small>%</small> |