| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VT](/vt-vs-vti/) | <span style="color: tomato">8.0<small>%</small></span> | 20.8<small>%</small> | 0.39 | -50.3<small>%</small> | -7.3<small>%</small> |
| VTI | <span style="color: tomato">11.6<small>%</small></span> | 20.2<small>%</small> | 0.57 | -48.0<small>%</small> | -6.1<small>%</small> |