| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTI](/vti-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 19.2<small>%</small> | 0.49 | -55.5<small>%</small> | -7.9<small>%</small> |
| SPY | <span style="color: tomato">9.1<small>%</small></span> | 19.1<small>%</small> | 0.47 | -55.2<small>%</small> | -8.2<small>%</small> |