| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTI](/vti-vs-spy/) | <span style="color: tomato">9.8<small>%</small></span> | 19.0<small>%</small> | 0.52 | -55.5<small>%</small> | -7.6<small>%</small> |
| SPY | <span style="color: tomato">9.5<small>%</small></span> | 18.9<small>%</small> | 0.50 | -55.2<small>%</small> | -7.9<small>%</small> |