| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTI](/vti-vs-spy/) | <span style="color: tomato">9.5<small>%</small></span> | 19.1<small>%</small> | 0.50 | -55.5<small>%</small> | -7.8<small>%</small> |
| SPY | <span style="color: tomato">9.2<small>%</small></span> | 19.1<small>%</small> | 0.48 | -55.2<small>%</small> | -8.1<small>%</small> |