| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-schd/) | <span style="color: tomato">12.6<small>%</small></span> | 15.9<small>%</small> | 0.79 | -36.8<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">12.2<small>%</small></span> | 15.5<small>%</small> | 0.79 | -33.4<small>%</small> | -3.4<small>%</small> |