| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-brk-b/) | <span style="color: tomato">9.6<small>%</small></span> | 18.4<small>%</small> | 0.52 | -59.3<small>%</small> | -7.8<small>%</small> |
| BRK-B | <span style="color: tomato">10.0<small>%</small></span> | 20.6<small>%</small> | 0.49 | -53.9<small>%</small> | -10.0<small>%</small> |