| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-brk-b/) | <span style="color: tomato">9.2<small>%</small></span> | 18.8<small>%</small> | 0.49 | -59.3<small>%</small> | -8.3<small>%</small> |
| BRK-B | <span style="color: tomato">10.3<small>%</small></span> | 20.9<small>%</small> | 0.49 | -53.9<small>%</small> | -10.3<small>%</small> |