| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 18.6<small>%</small> | 0.50 | -59.3<small>%</small> | -8.0<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 18.7<small>%</small> | 0.57 | -55.2<small>%</small> | -7.0<small>%</small> |