| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-brk-b/) | <span style="color: tomato">12.1<small>%</small></span> | 19.9<small>%</small> | 0.61 | -50.7<small>%</small> | -7.1<small>%</small> |
| BRK-B | <span style="color: tomato">9.9<small>%</small></span> | 20.7<small>%</small> | 0.48 | -53.9<small>%</small> | -10.0<small>%</small> |