| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-spy/) | <span style="color: tomato">11.6<small>%</small></span> | 19.8<small>%</small> | 0.59 | -50.7<small>%</small> | -7.3<small>%</small> |
| SPY | <span style="color: tomato">10.2<small>%</small></span> | 18.7<small>%</small> | 0.54 | -55.2<small>%</small> | -7.3<small>%</small> |