| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-brk-b/) | <span style="color: tomato">12.3<small>%</small></span> | 20.0<small>%</small> | 0.61 | -50.7<small>%</small> | -7.1<small>%</small> |
| BRK-B | <span style="color: tomato">10.3<small>%</small></span> | 20.8<small>%</small> | 0.49 | -53.9<small>%</small> | -10.1<small>%</small> |