| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-spy/) | <span style="color: tomato">12.0<small>%</small></span> | 20.0<small>%</small> | 0.60 | -50.7<small>%</small> | -7.2<small>%</small> |
| SPY | <span style="color: tomato">10.3<small>%</small></span> | 18.8<small>%</small> | 0.55 | -55.2<small>%</small> | -7.1<small>%</small> |