| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-spy/) | <span style="color: tomato">12.2<small>%</small></span> | 19.9<small>%</small> | 0.61 | -50.7<small>%</small> | -7.1<small>%</small> |
| SPY | <span style="color: tomato">10.8<small>%</small></span> | 18.6<small>%</small> | 0.58 | -55.2<small>%</small> | -6.8<small>%</small> |