| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VWO](/vwo-vs-spy/) | <span style="color: tomato">6.2<small>%</small></span> | 26.4<small>%</small> | 0.23 | -67.7<small>%</small> | -16.4<small>%</small> |
| SPY | <span style="color: tomato">10.5<small>%</small></span> | 19.2<small>%</small> | 0.55 | -55.2<small>%</small> | -7.4<small>%</small> |