| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VWO](/vwo-vs-spy/) | <span style="color: tomato">6.5<small>%</small></span> | 26.2<small>%</small> | 0.25 | -67.7<small>%</small> | -16.1<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 19.1<small>%</small> | 0.56 | -55.2<small>%</small> | -7.3<small>%</small> |