| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VWO](/vwo-vs-spy/) | <span style="color: tomato">6.9<small>%</small></span> | 26.0<small>%</small> | 0.27 | -67.7<small>%</small> | -15.7<small>%</small> |
| SPY | <span style="color: tomato">11.0<small>%</small></span> | 18.9<small>%</small> | 0.58 | -55.2<small>%</small> | -7.1<small>%</small> |