| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VXUS](/vxus-vs-vt/) | <span style="color: tomato">4.8<small>%</small></span> | 17.8<small>%</small> | 0.27 | -36.0<small>%</small> | -8.9<small>%</small> |
| VT | <span style="color: tomato">9.2<small>%</small></span> | 17.2<small>%</small> | 0.54 | -34.2<small>%</small> | -5.5<small>%</small> |