| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VXUS](/vxus-vs-vt/) | <span style="color: tomato">5.9<small>%</small></span> | 17.7<small>%</small> | 0.33 | -36.0<small>%</small> | -8.5<small>%</small> |
| VT | <span style="color: tomato">9.9<small>%</small></span> | 17.2<small>%</small> | 0.57 | -34.2<small>%</small> | -5.3<small>%</small> |