| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VXUS](/vxus-vs-vt/) | <span style="color: tomato">5.4<small>%</small></span> | 17.7<small>%</small> | 0.31 | -36.0<small>%</small> | -8.6<small>%</small> |
| VT | <span style="color: tomato">9.6<small>%</small></span> | 17.3<small>%</small> | 0.55 | -34.2<small>%</small> | -5.4<small>%</small> |