| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VYM](/vym-vs-schd/) | <span style="color: tomato">12.4<small>%</small></span> | 15.3<small>%</small> | 0.81 | -35.2<small>%</small> | -3.0<small>%</small> |
| SCHD | <span style="color: tomato">12.4<small>%</small></span> | 15.5<small>%</small> | 0.80 | -33.4<small>%</small> | -3.4<small>%</small> |