| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WDTE](/wdte-vs-spy/) | <span style="color: tomato">14.0<small>%</small></span> | 11.3<small>%</small> | 1.24 | -15.8<small>%</small> | -1.8<small>%</small> |
| SPY | <span style="color: tomato">21.9<small>%</small></span> | 15.4<small>%</small> | 1.43 | -18.8<small>%</small> | -1.9<small>%</small> |