| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WDTE](/wdte-vs-spy/) | <span style="color: tomato">12.9<small>%</small></span> | 11.1<small>%</small> | 1.16 | -15.8<small>%</small> | -2.0<small>%</small> |
| SPY | <span style="color: tomato">23.3<small>%</small></span> | 16.0<small>%</small> | 1.46 | -18.8<small>%</small> | -2.0<small>%</small> |