| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WDTE](/wdte-vs-xyld/) | <span style="color: tomato">14.2<small>%</small></span> | 11.3<small>%</small> | 1.25 | -15.8<small>%</small> | -1.8<small>%</small> |
| XYLD | <span style="color: tomato">13.2<small>%</small></span> | 10.3<small>%</small> | 1.29 | -15.5<small>%</small> | -1.5<small>%</small> |