| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">20.8<small>%</small></span> | 11.9<small>%</small> | 1.75 | -6.9<small>%</small> | -1.1<small>%</small> |
| ISPY | <span style="color: tomato">19.4<small>%</small></span> | 11.7<small>%</small> | 1.65 | -7.9<small>%</small> | -1.3<small>%</small> |