| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">24.8<small>%</small></span> | 11.7<small>%</small> | 2.12 | -6.9<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">22.4<small>%</small></span> | 12.5<small>%</small> | 1.80 | -8.4<small>%</small> | -1.4<small>%</small> |