| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">26.9<small>%</small></span> | 11.7<small>%</small> | 2.30 | -6.9<small>%</small> | -1.0<small>%</small> |
| SPY | <span style="color: tomato">25.6<small>%</small></span> | 12.5<small>%</small> | 2.05 | -8.4<small>%</small> | -1.3<small>%</small> |