| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">25.5<small>%</small></span> | 12.0<small>%</small> | 2.12 | -6.9<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">22.1<small>%</small></span> | 12.8<small>%</small> | 1.73 | -8.4<small>%</small> | -1.3<small>%</small> |