| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">16.3<small>%</small></span> | 14.3<small>%</small> | 1.14 | -19.1<small>%</small> | -2.6<small>%</small> |
| ISPY | <span style="color: tomato">15.8<small>%</small></span> | 14.2<small>%</small> | 1.11 | -16.9<small>%</small> | -2.4<small>%</small> |