| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">15.2<small>%</small></span> | 14.7<small>%</small> | 1.03 | -19.1<small>%</small> | -2.9<small>%</small> |
| ISPY | <span style="color: tomato">15.1<small>%</small></span> | 14.6<small>%</small> | 1.04 | -16.9<small>%</small> | -2.6<small>%</small> |