| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">9.1<small>%</small></span> | 25.8<small>%</small> | 0.35 | -82.0<small>%</small> | -36.2<small>%</small> |
| QQQ | <span style="color: tomato">10.3<small>%</small></span> | 27.0<small>%</small> | 0.38 | -83.0<small>%</small> | -33.6<small>%</small> |