| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">9.4<small>%</small></span> | 25.8<small>%</small> | 0.36 | -82.0<small>%</small> | -36.0<small>%</small> |
| QQQ | <span style="color: tomato">10.4<small>%</small></span> | 27.0<small>%</small> | 0.39 | -83.0<small>%</small> | -33.5<small>%</small> |