| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">10.2<small>%</small></span> | 25.8<small>%</small> | 0.39 | -82.0<small>%</small> | -35.0<small>%</small> |
| QQQ | <span style="color: tomato">10.8<small>%</small></span> | 26.8<small>%</small> | 0.40 | -83.0<small>%</small> | -32.5<small>%</small> |