| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-spy/) | <span style="color: tomato">10.6<small>%</small></span> | 25.9<small>%</small> | 0.41 | -82.0<small>%</small> | -34.7<small>%</small> |
| SPY | <span style="color: tomato">8.8<small>%</small></span> | 19.1<small>%</small> | 0.46 | -55.2<small>%</small> | -10.4<small>%</small> |