| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-spy/) | <span style="color: tomato">9.7<small>%</small></span> | 25.9<small>%</small> | 0.37 | -82.0<small>%</small> | -35.7<small>%</small> |
| SPY | <span style="color: tomato">8.4<small>%</small></span> | 19.3<small>%</small> | 0.44 | -55.2<small>%</small> | -10.7<small>%</small> |