| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XMLV](/xmlv-vs-ijh/) | <span style="color: tomato">10.2<small>%</small></span> | 16.1<small>%</small> | 0.63 | -39.9<small>%</small> | -4.4<small>%</small> |
| IJH | <span style="color: tomato">11.1<small>%</small></span> | 19.7<small>%</small> | 0.56 | -42.2<small>%</small> | -5.3<small>%</small> |