| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XMLV](/xmlv-vs-ijh/) | <span style="color: tomato">9.7<small>%</small></span> | 15.7<small>%</small> | 0.62 | -39.9<small>%</small> | -4.2<small>%</small> |
| IJH | <span style="color: tomato">10.9<small>%</small></span> | 19.5<small>%</small> | 0.56 | -42.2<small>%</small> | -5.2<small>%</small> |