| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: tomato">0.8<small>%</small></span> | 15.5<small>%</small> | 0.05 | -13.5<small>%</small> | -5.2<small>%</small> |
| XOM | <span style="color: tomato">4.6<small>%</small></span> | 20.4<small>%</small> | 0.23 | -18.7<small>%</small> | -7.0<small>%</small> |