| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: tomato">0.2<small>%</small></span> | 17.7<small>%</small> | 0.01 | -18.9<small>%</small> | -7.7<small>%</small> |
| XOM | <span style="color: tomato">5.3<small>%</small></span> | 21.7<small>%</small> | 0.24 | -18.9<small>%</small> | -8.2<small>%</small> |