| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: tomato">4.4<small>%</small></span> | 15.5<small>%</small> | 0.28 | -13.5<small>%</small> | -5.3<small>%</small> |
| XOM | <span style="color: tomato">10.7<small>%</small></span> | 20.5<small>%</small> | 0.52 | -18.7<small>%</small> | -7.1<small>%</small> |