| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XSLV](/xslv-vs-ijr/) | <span style="color: tomato">7.7<small>%</small></span> | 18.7<small>%</small> | 0.41 | -44.3<small>%</small> | -7.5<small>%</small> |
| IJR | <span style="color: tomato">10.4<small>%</small></span> | 21.2<small>%</small> | 0.49 | -44.4<small>%</small> | -7.8<small>%</small> |