| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYLD](/xyld-vs-spy/) | <span style="color: tomato">7.8<small>%</small></span> | 13.8<small>%</small> | 0.57 | -33.5<small>%</small> | -3.9<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 17.1<small>%</small> | 0.85 | -33.7<small>%</small> | -3.9<small>%</small> |