| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYLD](/xyld-vs-spy/) | <span style="color: tomato">8.4<small>%</small></span> | 13.5<small>%</small> | 0.63 | -33.5<small>%</small> | -3.6<small>%</small> |
| SPY | <span style="color: tomato">14.7<small>%</small></span> | 16.8<small>%</small> | 0.87 | -33.7<small>%</small> | -3.7<small>%</small> |