| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYZY](/xyzy-vs-xyz/) | <span style="color: tomato">9.9<small>%</small></span> | 40.8<small>%</small> | 0.24 | -52.3<small>%</small> | -22.9<small>%</small> |
| XYZ | <span style="color: tomato">17.3<small>%</small></span> | 49.7<small>%</small> | 0.35 | -53.0<small>%</small> | -22.9<small>%</small> |