| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYZY](/xyzy-vs-xyz/) | <span style="color: tomato">11.1<small>%</small></span> | 40.8<small>%</small> | 0.27 | -52.3<small>%</small> | -23.0<small>%</small> |
| XYZ | <span style="color: tomato">18.3<small>%</small></span> | 49.7<small>%</small> | 0.37 | -53.0<small>%</small> | -22.9<small>%</small> |