| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYZY](/xyzy-vs-xyz/) | <span style="color: tomato">10.6<small>%</small></span> | 41.0<small>%</small> | 0.26 | -52.3<small>%</small> | -22.8<small>%</small> |
| XYZ | <span style="color: tomato">19.0<small>%</small></span> | 50.0<small>%</small> | 0.38 | -53.0<small>%</small> | -22.9<small>%</small> |