| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">36.4<small>%</small></span> | 18.9<small>%</small> | 1.93 | -14.3<small>%</small> | -3.3<small>%</small> |
| JEPI | <span style="color: tomato">14.7<small>%</small></span> | 7.4<small>%</small> | 2.00 | -3.9<small>%</small> | -0.7<small>%</small> |