| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">21.7<small>%</small></span> | 20.9<small>%</small> | 1.04 | -26.0<small>%</small> | -4.7<small>%</small> |
| JEPI | <span style="color: tomato">9.1<small>%</small></span> | 10.4<small>%</small> | 0.88 | -13.3<small>%</small> | -1.7<small>%</small> |