| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">33.4<small>%</small></span> | 22.0<small>%</small> | 1.52 | -26.0<small>%</small> | -4.6<small>%</small> |
| JEPQ | <span style="color: tomato">19.6<small>%</small></span> | 16.6<small>%</small> | 1.18 | -20.1<small>%</small> | -2.7<small>%</small> |