| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">30.2<small>%</small></span> | 22.0<small>%</small> | 1.37 | -26.0<small>%</small> | -4.7<small>%</small> |
| QQQ | <span style="color: tomato">24.1<small>%</small></span> | 21.5<small>%</small> | 1.12 | -22.8<small>%</small> | -3.4<small>%</small> |