| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-mags/) | <span style="color: tomato">37.6<small>%</small></span> | 19.1<small>%</small> | 1.97 | -14.3<small>%</small> | -3.1<small>%</small> |
| MAGS | <span style="color: tomato">56.3<small>%</small></span> | 26.2<small>%</small> | 2.15 | -18.1<small>%</small> | -4.1<small>%</small> |