| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-mags/) | <span style="color: tomato">28.5<small>%</small></span> | 22.0<small>%</small> | 1.29 | -26.0<small>%</small> | -4.6<small>%</small> |
| MAGS | <span style="color: tomato">40.0<small>%</small></span> | 29.1<small>%</small> | 1.38 | -29.9<small>%</small> | -5.6<small>%</small> |