| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">22.4<small>%</small></span> | 20.9<small>%</small> | 1.07 | -26.0<small>%</small> | -4.7<small>%</small> |
| JEPQ | <span style="color: tomato">18.0<small>%</small></span> | 16.2<small>%</small> | 1.11 | -20.1<small>%</small> | -2.4<small>%</small> |