| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">39.3<small>%</small></span> | 19.3<small>%</small> | 2.04 | -14.3<small>%</small> | -3.4<small>%</small> |
| JEPI | <span style="color: tomato">16.1<small>%</small></span> | 7.5<small>%</small> | 2.15 | -3.9<small>%</small> | -0.7<small>%</small> |