| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">32.9<small>%</small></span> | 19.1<small>%</small> | 1.72 | -14.3<small>%</small> | -3.3<small>%</small> |
| QQQ | <span style="color: tomato">20.5<small>%</small></span> | 18.2<small>%</small> | 1.12 | -13.6<small>%</small> | -2.9<small>%</small> |