| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">21.4<small>%</small></span> | 20.9<small>%</small> | 1.02 | -26.0<small>%</small> | -4.7<small>%</small> |
| QQQ | <span style="color: tomato">22.5<small>%</small></span> | 21.1<small>%</small> | 1.07 | -22.8<small>%</small> | -3.4<small>%</small> |