| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">33.1<small>%</small></span> | 22.0<small>%</small> | 1.50 | -26.0<small>%</small> | -4.7<small>%</small> |
| JEPQ | <span style="color: tomato">19.5<small>%</small></span> | 16.7<small>%</small> | 1.17 | -20.1<small>%</small> | -2.7<small>%</small> |