| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">32.6<small>%</small></span> | 18.0<small>%</small> | 1.81 | -12.8<small>%</small> | -2.6<small>%</small> |
| QQQ | <span style="color: tomato">30.2<small>%</small></span> | 17.9<small>%</small> | 1.68 | -13.6<small>%</small> | -2.6<small>%</small> |