| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">32.6<small>%</small></span> | 18.0<small>%</small> | 1.81 | -12.8<small>%</small> | -2.6<small>%</small> |
| JEPI | <span style="color: tomato">20.4<small>%</small></span> | 7.3<small>%</small> | 2.79 | -3.9<small>%</small> | -0.6<small>%</small> |