| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">24.7<small>%</small></span> | 18.2<small>%</small> | 1.36 | -12.8<small>%</small> | -2.9<small>%</small> |
| QQQ | <span style="color: tomato">34.0<small>%</small></span> | 18.3<small>%</small> | 1.86 | -13.6<small>%</small> | -2.7<small>%</small> |