| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">36.5<small>%</small></span> | 18.0<small>%</small> | 2.03 | -12.8<small>%</small> | -2.5<small>%</small> |
| JEPQ | <span style="color: tomato">29.1<small>%</small></span> | 12.8<small>%</small> | 2.27 | -10.7<small>%</small> | -1.4<small>%</small> |