| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">25.6<small>%</small></span> | 22.2<small>%</small> | 1.15 | -25.6<small>%</small> | -4.2<small>%</small> |
| JEPI | <span style="color: tomato">10.5<small>%</small></span> | 11.3<small>%</small> | 0.93 | -13.3<small>%</small> | -1.7<small>%</small> |