| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">19.1<small>%</small></span> | 22.4<small>%</small> | 0.85 | -25.6<small>%</small> | -4.4<small>%</small> |
| JEPQ | <span style="color: tomato">20.9<small>%</small></span> | 16.4<small>%</small> | 1.28 | -20.1<small>%</small> | -2.6<small>%</small> |