| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">18.6<small>%</small></span> | 22.5<small>%</small> | 0.83 | -25.6<small>%</small> | -4.3<small>%</small> |
| JEPI | <span style="color: tomato">10.8<small>%</small></span> | 11.0<small>%</small> | 0.98 | -13.3<small>%</small> | -1.6<small>%</small> |