| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">18.3<small>%</small></span> | 22.5<small>%</small> | 0.81 | -25.6<small>%</small> | -4.3<small>%</small> |
| QQQ | <span style="color: tomato">26.1<small>%</small></span> | 21.2<small>%</small> | 1.23 | -22.8<small>%</small> | -3.3<small>%</small> |