| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">24.1<small>%</small></span> | 23.0<small>%</small> | 1.05 | -25.6<small>%</small> | -4.3<small>%</small> |
| JEPQ | <span style="color: tomato">17.9<small>%</small></span> | 17.3<small>%</small> | 1.03 | -20.1<small>%</small> | -3.0<small>%</small> |