## 국내 상장 일반 ETF



### [KODEX 200TR vs KODEX 200](/278530-vs-069500/)<a id="278530-vs-069500"></a>

{% include vs/278530-vs-069500_md.inc %}



### [TIGER MSCI Korea TR vs KODEX 200](/310970-vs-069500/)<a id="310970-vs-069500"></a>

{% include vs/310970-vs-069500_md.inc %}



### [TIGER MSCI Korea TR vs KODEX KRX300](/310970-vs-292190/)<a id="310970-vs-292190"></a>

{% include vs/310970-vs-292190_md.inc %}



### [KODEX KRX300 vs KODEX 200](/292190-vs-069500/)<a id="292190-vs-069500"></a>

{% include vs/292190-vs-069500_md.inc %}



### [KODEX 코스피 vs KODEX 200](/226490-vs-069500/)<a id="226490-vs-069500"></a>

KODEX 코스피는 코스피 지수를 추종합니다.  KODEX 200은 코스피에서 선별된 200개 주요 종목으로 구성된 코스피 200 지수를 추종하는 상품입니다. 시장의 모든 주식을 보유하는 것이 나은지, 아니면 선별된 시총 상위 종목만 보유하는 것이 나은지 살펴봅니다.

{% include vs/226490-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 코스피100 vs KODEX 200](/237350-vs-069500/)<a id="237350-vs-069500"></a>

KODEX 코스피100은 코스피 200 구성종목 중 시총이 큰 상위 100종목을 담은 코스피 100 지수를 추종합니다. 코스피 200 지수를 추종하는 KODEX 200과 비교하여 대형주 효과를 확인해 봅니다.

{% include vs/237350-vs-069500_md.inc %}



### [PLUS 코스피50 vs KODEX 200](/122090-vs-069500/)<a id="122090-vs-069500"></a>

PLUS 코스피 50은 코스피 200 구성종목 중 시총이 큰 상위 50종목을 담은 코스피 50 지수를 추종합니다. 코스피 200 지수를 추종하는 KODEX 200과 비교하여 대형주 효과를 확인해 확인해 봅니다.

{% include vs/122090-vs-069500_md.inc %}



### [KODEX 200exTOP vs KODEX 200](/337150-vs-069500/)<a id="337150-vs-069500"></a>

{% include vs/337150-vs-069500_md.inc %}



### [KODEX 200중소형 vs KODEX 200](/226980-vs-069500/)<a id="226980-vs-069500"></a>

KODEX 200중소형은 코스피 200 구성종목 중 시총 상위 101-200위에 해당하는 100 종목을 코스피 200 중소형주 지수를 추종합니다. 코스피 200 지수를 추종하는 KODEX 200과 비교하여 중소형주 효과를 확인해 확인해 봅니다.

{% include vs/226980-vs-069500_md.inc %}



### [KODEX 코스피대형주 vs KODEX 코스피](/337140-vs-226490/)<a id="337140-vs-226490"></a>

KODEX 코스피대형주는 KOSPI 시장에서 시총 상위 100 종목을 선별한 KOSPI 대행주 지수를 추종합니다. KODEX 코스피는 KOSPI 전 종목에 투자하는 상품입니다. 시총 상위 종목의 선별 효과를 살펴 볼 수 있습니다.

{% include vs/337140-vs-226490_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 코스피중형주 vs KODEX 코스피](/277650-vs-226490/)<a id="277650-vs-226490"></a>

TIGER 코스피중형주는 KOSPI 시장에서 시총 상위 101-300위에 해당하는 종목을 선별한 KOSPI 중형주 지수를 추종합니다. 중간 정도에 시총에 해당하는 종목의 선별 효과를 살펴 볼 수 있습니다.

{% include vs/277650-vs-226490_md.inc %}



### [KOSEF KRX100 vs KODEX KRX300](/100910-vs-292190/)<a id="100910-vs-292190"></a>

KOSEF KRX100과 KODEX KRX300은 각각 KOSPI와 KOSDAQ 시장의 시총 상위 100 또는 300 종목을 선별한 KRX 100과 KRX 300 지수를 추종합니다. 시총 상위 종목의 선별 효과를 살펴 볼 수 있습니다.

{% include vs/100910-vs-292190_md.inc %}



### [TIGER TOP10 vs KODEX KRX300](/292150-vs-292190/)<a id="292150-vs-292190"></a>

TIGER TOP10은 KOSPI와 KOSDAQ 시장의 시총 상위 10 종목을 선별한 FnGuide TOP10 지수를 추종합니다. 초대형주 효과를 살펴 볼 수 있습니다.

{% include vs/292150-vs-292190_md.inc %}



### [KODEX FnTop10동일가중 vs TIGER Top10](/395170-vs-292150/)<a id="395170-vs-292150"></a>

FnGuide TOP 10 동일가중 지수 vs FnGuide TOP10 지수

{% include vs/395170-vs-292150_md.inc %}



## 국내 상장 고배당 ETF



### [PLUS 고배당주 vs KODEX 200](/161510-vs-069500/)<a id="161510-vs-069500"></a>

PLUS 고배당주는 고배당 종목으로 구성한 ETF입니다. 배당 여부를 따지지 않고 시총 상위 종목만 편입한 KODEX 200에 비해 어떤 성과를 거두었는지 살펴봅니다.

{% include vs/161510-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 대형고배당10TR vs PLUS 고배당주](/315960-vs-161510/)<a id="315960-vs-161510"></a>

WISE 대형고배당10TR지수 vs FnGuide 고배당주지수

{% include vs/315960-vs-161510_md.inc %}



### [RISE 고배당 vs PLUS 고배당주](/266160-vs-161510/)<a id="266160-vs-161510"></a>

FnGuide 고배당포커스 지수 vs FnGuide 고배당주지수

{% include vs/266160-vs-161510_md.inc %}



### [KODEX 고배당 vs PLUS 고배당주](/279530-vs-161510/)<a id="279530-vs-161510"></a>

FnGuide 고배당 Plus 지수 vs FnGuide 고배당주지수

{% include vs/279530-vs-161510_md.inc %}



### [TIGER 코스피고배당 vs PLUS 고배당주](/210780-vs-161510/)<a id="210780-vs-161510"></a>

코스피 고배당 50 지수 vs FnGuide 고배당주지수

{% include vs/210780-vs-161510_md.inc %}



### [KOSEF 고배당 vs PLUS 고배당주](/104530-vs-161510/)<a id="104530-vs-161510"></a>

MKF 웰스 고배당 20 지수 vs FnGuide 고배당주지수

{% include vs/104530-vs-161510_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE KQ고배당 vs PLUS 고배당주](/270800-vs-161510/)<a id="270800-vs-161510"></a>

FnGuide KQ고배당포커스 지수 vs FnGuide 고배당주지수

{% include vs/270800-vs-161510_md.inc %}



### [파워 고배당저변동성 vs PLUS 고배당주](/192720-vs-161510/)<a id="192720-vs-161510"></a>

코스피 200 고배당지수 vs FnGuide 고배당주지수

{% include vs/192720-vs-161510_md.inc %}



### [PLUS 고배당저변동50 vs PLUS 고배당주](/251590-vs-161510/)<a id="251590-vs-161510"></a>

FnGuide 고배당저변동50 지수 vs FnGuide 고배당주지수

{% include vs/251590-vs-161510_md.inc %}



### [RISE 중소형고배당 vs PLUS 고배당주](/281990-vs-161510/)<a id="281990-vs-161510"></a>

FnGuide 중소형 고배당포커스 지수 vs FnGuide 고배당주지수

{% include vs/281990-vs-161510_md.inc %}



### [HANARO 고배당 vs PLUS 고배당주](/322410-vs-161510/)<a id="322410-vs-161510"></a>

FnGuide 고배당알파 지수 vs FnGuide 고배당주지수

{% include vs/322410-vs-161510_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 대형고배당10TR vs KODEX 200](/315960-vs-069500/)<a id="315960-vs-069500"></a>

시총 상위 종목 중에서 배당금이 높은 종목에 투자하는 RISE 대형고배당10TR이 일반적인 지수 추종 상품과 어떻게 다른지 비교합니다.

{% include vs/315960-vs-069500_md.inc %}



### [RISE 대형고배당10TR vs TIGER Top10](/315960-vs-292150/)<a id="315960-vs-292150"></a>

시총 상위 종목 중에서 배당금이 높은 종목에 투자하는 RISE 대형고배당10TR이 시총 상위 소수 종목으로 구성한 ETF와 어떻게 다른지 비교합니다.

{% include vs/315960-vs-292150_md.inc %}



### [TIMEFOLIO Korea플러스배당액티브 ETF vs KODEX 200](/441800-vs-069500/)<a id="441800-vs-069500"></a>

{% include vs/441800-vs-069500_md.inc %}



### [TIMEFOLIO Korea플러스배당액티브 ETF vs PLUS 고배당주](/441800-vs-161510/)<a id="441800-vs-161510"></a>

{% include vs/441800-vs-161510_md.inc %}



### [TIMEFOLIO Korea플러스배당액티브 ETF vs RISE 대형고배당10TR](/441800-vs-315960/)<a id="441800-vs-315960"></a>

{% include vs/441800-vs-315960_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 미국S&P500배당귀족커버드콜(합성 H) vs SPY](/276970-vs-spy/)<a id="276970-vs-spy"></a>

{% include vs/276970-vs-spy_md.inc %}



### [KODEX 미국S&P500배당귀족커버드콜(합성 H) vs PLUS 고배당주](/276970-vs-161510/)<a id="276970-vs-161510"></a>

{% include vs/276970-vs-161510_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs PLUS 고배당주](/441640-vs-161510/)<a id="441640-vs-161510"></a>

{% include vs/441640-vs-161510_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs KODEX 미국S&P500배당귀족커버드콜(합성 H)](/441640-vs-276970/)<a id="441640-vs-276970"></a>

{% include vs/441640-vs-276970_md.inc %}



### [TIGER 미국S&P500 vs PLUS 고배당주](/360750-vs-161510/)<a id="360750-vs-161510"></a>

{% include vs/360750-vs-161510_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국나스닥100 vs PLUS 고배당주](/133690-vs-161510/)<a id="133690-vs-161510"></a>

{% include vs/133690-vs-161510_md.inc %}



## 초단기 채권 ETF



### [KODEX CD금리액티브(합성) vs TIGER CD금리투자KIS(합성)](/459580-vs-357870/)<a id="459580-vs-357870"></a>

{% include vs/459580-vs-357870_md.inc %}



### [TIGER KOFR금리액티브(합성) vs KODEX KOFR금리액티브(합성)](/449170-vs-423160/)<a id="449170-vs-423160"></a>

{% include vs/449170-vs-423160_md.inc %}



### [KODEX KOFR금리액티브(합성) vs TIGER CD금리투자KIS(합성)](/423160-vs-357870/)<a id="423160-vs-357870"></a>

{% include vs/423160-vs-357870_md.inc %}



### [RISE 머니마켓액티브 vs TIGER CD금리투자KIS(합성)](/455890-vs-357870/)<a id="455890-vs-357870"></a>

{% include vs/455890-vs-357870_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 머니마켓액티브 vs KODEX KOFR금리액티브(합성)](/455890-vs-423160/)<a id="455890-vs-423160"></a>

{% include vs/455890-vs-423160_md.inc %}



## 동일 가중 ETF



### [KODEX 200 동일가중 vs KODEX 200](/252650-vs-069500/)<a id="252650-vs-069500"></a>

코스피200동일가중지수 vs KOSPI 200 지수

{% include vs/252650-vs-069500_md.inc %}



### [TIGER 미국S&P500동일가중 vs KODEX 미국S&P500TR](/488500-vs-379800/)<a id="488500-vs-379800"></a>

{% include vs/488500-vs-379800_md.inc %}



## 소수 종목 선별 ETF



### [TIGER Top10 vs KODEX 200](/292150-vs-069500/)<a id="292150-vs-069500"></a>

FnGuide TOP10 지수 vs KOSPI 200 지수

{% include vs/292150-vs-069500_md.inc %}



### [SOL 200Top10 vs TIGER Top10](/411540-vs-292150/)<a id="411540-vs-292150"></a>

KOSPI 200Top10 (동일가중) vs FnGuide TOP10 지수

{% include vs/411540-vs-292150_md.inc %}


{% include /commons/ads/adsense.html %}



### [SOL 200Top10 vs KODEX FnTop10동일가중](/411540-vs-395170/)<a id="411540-vs-395170"></a>

KOSPI 200Top10 (동일가중) vs FnGuide TOP 10 동일가중 지수

{% include vs/411540-vs-395170_md.inc %}



## 스마트 베타 ETF



### [TIGER 모멘텀 vs KODEX 200](/147970-vs-069500/)<a id="147970-vs-069500"></a>

{% include vs/147970-vs-069500_md.inc %}



### [TIGER 베타플러스 vs KODEX 200](/170350-vs-069500/)<a id="170350-vs-069500"></a>

{% include vs/170350-vs-069500_md.inc %}



### [TIGER 로우볼 vs KODEX 200](/174350-vs-069500/)<a id="174350-vs-069500"></a>

{% include vs/174350-vs-069500_md.inc %}



### [TIGER 배당성장 vs KODEX 200](/211560-vs-069500/)<a id="211560-vs-069500"></a>

{% include vs/211560-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 가격조정 vs KODEX 200](/217790-vs-069500/)<a id="217790-vs-069500"></a>

{% include vs/217790-vs-069500_md.inc %}



### [ARIRANG 스마트베타Quality vs KODEX 200](/222200-vs-069500/)<a id="222200-vs-069500"></a>

{% include vs/222200-vs-069500_md.inc %}



### [ARIRANG 스마트베타Value vs KODEX 200](/222180-vs-069500/)<a id="222180-vs-069500"></a>

{% include vs/222180-vs-069500_md.inc %}



### [ARIRANG 스마트베타Momentum vs KODEX 200](/222190-vs-069500/)<a id="222190-vs-069500"></a>

{% include vs/222190-vs-069500_md.inc %}



### [TIGER 우량가치 vs KODEX 200](/227570-vs-069500/)<a id="227570-vs-069500"></a>

{% include vs/227570-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [ARIRANG 스마트베타LowVOL vs KODEX 200](/236460-vs-069500/)<a id="236460-vs-069500"></a>

{% include vs/236460-vs-069500_md.inc %}



### [TIGER 지속배당 vs KODEX 200](/266140-vs-069500/)<a id="266140-vs-069500"></a>

{% include vs/266140-vs-069500_md.inc %}



### [TIGER 코스피대형주 vs KODEX 200](/277640-vs-069500/)<a id="277640-vs-069500"></a>

{% include vs/277640-vs-069500_md.inc %}



### [TIGER 대형성장 vs KODEX 200](/292100-vs-069500/)<a id="292100-vs-069500"></a>

{% include vs/292100-vs-069500_md.inc %}



### [TIGER 대형가치 vs KODEX 200](/292110-vs-069500/)<a id="292110-vs-069500"></a>

{% include vs/292110-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 중소형성장 vs KODEX 200](/292130-vs-069500/)<a id="292130-vs-069500"></a>

{% include vs/292130-vs-069500_md.inc %}



### [TIGER 중소형 vs KODEX 200](/292120-vs-069500/)<a id="292120-vs-069500"></a>

{% include vs/292120-vs-069500_md.inc %}



### [TIGER 중소형가치 vs KODEX 200](/292140-vs-069500/)<a id="292140-vs-069500"></a>

{% include vs/292140-vs-069500_md.inc %}



### [ARIRANG 스마트베타4종결합 vs KODEX 200](/244820-vs-069500/)<a id="244820-vs-069500"></a>

{% include vs/244820-vs-069500_md.inc %}



### [PLUS KS로우사이즈가중TR vs KODEX KRX300](/333950-vs-292190/)<a id="333950-vs-292190"></a>

{% include vs/333950-vs-292190_md.inc %}


{% include /commons/ads/adsense.html %}



### [PLUS KS로우볼가중TR vs KODEX KRX300](/333940-vs-292190/)<a id="333940-vs-292190"></a>

{% include vs/333940-vs-292190_md.inc %}



### [PLUS KS퀄리티가중TR vs KODEX KRX300](/333980-vs-292190/)<a id="333980-vs-292190"></a>

{% include vs/333980-vs-292190_md.inc %}



### [PLUS KS모멘텀가중TR vs KODEX KRX300](/333960-vs-292190/)<a id="333960-vs-292190"></a>

{% include vs/333960-vs-292190_md.inc %}



### [PLUS KS밸류가중 vs KODEX KRX300](/333970-vs-292190/)<a id="333970-vs-292190"></a>

{% include vs/333970-vs-292190_md.inc %}



### [PLUS KS로우사이즈가중TR vs KODEX 200](/333950-vs-069500/)<a id="333950-vs-069500"></a>

{% include vs/333950-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [PLUS KS로우볼가중TR vs KODEX 200](/333940-vs-069500/)<a id="333940-vs-069500"></a>

{% include vs/333940-vs-069500_md.inc %}



### [PLUS KS퀄리티가중TR vs KODEX 200](/333980-vs-069500/)<a id="333980-vs-069500"></a>

{% include vs/333980-vs-069500_md.inc %}



### [PLUS KS모멘텀가중TR vs KODEX 200](/333960-vs-069500/)<a id="333960-vs-069500"></a>

{% include vs/333960-vs-069500_md.inc %}



### [PLUS KS밸류가중 vs KODEX 200](/333970-vs-069500/)<a id="333970-vs-069500"></a>

{% include vs/333970-vs-069500_md.inc %}



## 모멘텀 ETF



### [KODEX 모멘텀Plus vs KODEX 200](/244620-vs-069500/)<a id="244620-vs-069500"></a>

{% include vs/244620-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 모멘텀밸류 vs KODEX 200](/252720-vs-069500/)<a id="252720-vs-069500"></a>

{% include vs/252720-vs-069500_md.inc %}



### [RISE 모멘텀로우볼 vs KODEX 200](/252730-vs-069500/)<a id="252730-vs-069500"></a>

{% include vs/252730-vs-069500_md.inc %}



### [ACE 스마트모멘텀 vs KODEX 200](/272220-vs-069500/)<a id="272220-vs-069500"></a>

{% include vs/272220-vs-069500_md.inc %}



### [KODEX MSCI모멘텀 vs KODEX 200](/275280-vs-069500/)<a id="275280-vs-069500"></a>

{% include vs/275280-vs-069500_md.inc %}



## 액티브 ETF



### [ACE 주주환원가치주액티브 vs KODEX 200](/447430-vs-069500/)<a id="447430-vs-069500"></a>

{% include vs/447430-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [ACE 주주환원가치주액티브 vs KODEX KRX300](/447430-vs-292190/)<a id="447430-vs-292190"></a>

{% include vs/447430-vs-292190_md.inc %}



### [ACE 주주환원가치주액티브 vs PLUS 고배당주](/447430-vs-161510/)<a id="447430-vs-161510"></a>

{% include vs/447430-vs-161510_md.inc %}



### [ACE 주주환원가치주액티브 vs TIMEFOLIO Korea플러스배당액티브](/447430-vs-441800/)<a id="447430-vs-441800"></a>

{% include vs/447430-vs-441800_md.inc %}



### [TIMEFOLIO 미국S&P500액티브 ETF vs TIGER 미국S&P500](/426020-vs-360750/)<a id="426020-vs-360750"></a>

{% include vs/426020-vs-360750_md.inc %}



### [TIMEFOLIO 미국나스닥100액티브 vs TIGER 미국나스닥100](/426030-vs-133690/)<a id="426030-vs-133690"></a>

{% include vs/426030-vs-133690_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIMEFOLIO 코스피액티브 vs KODEX 200](/385720-vs-069500/)<a id="385720-vs-069500"></a>

{% include vs/385720-vs-069500_md.inc %}



### [TIMEFOLIO 코스피액티브 vs KODEX 코스피](/385720-vs-226490/)<a id="385720-vs-226490"></a>

{% include vs/385720-vs-226490_md.inc %}



### [1Q K200액티브 vs KODEX 200](/451060-vs-069500/)<a id="451060-vs-069500"></a>

{% include vs/451060-vs-069500_md.inc %}



### [마이다스 코스피액티브 vs KODEX 200](/403790-vs-069500/)<a id="403790-vs-069500"></a>

{% include vs/403790-vs-069500_md.inc %}



### [마이다스 코스피액티브 vs KODEX 코스피](/403790-vs-226490/)<a id="403790-vs-226490"></a>

{% include vs/403790-vs-226490_md.inc %}


{% include /commons/ads/adsense.html %}



## 국내 상장 롱숏 ETF



### [KODEX 200롱코스닥150숏선물 vs KODEX 200](/360140-vs-069500/)<a id="360140-vs-069500"></a>

{% include vs/360140-vs-069500_md.inc %}



### [KODEX 코스닥150롱코스피200숏선물 vs KODEX 200](/360150-vs-069500/)<a id="360150-vs-069500"></a>

{% include vs/360150-vs-069500_md.inc %}



### [KODEX 200롱코스닥150숏선물 vs KODEX 코스닥150](/360140-vs-229200/)<a id="360140-vs-229200"></a>

{% include vs/360140-vs-229200_md.inc %}



### [KODEX 코스닥150롱코스피200숏선물 vs 코스닥150](/360150-vs-229200/)<a id="360150-vs-229200"></a>

{% include vs/360150-vs-229200_md.inc %}



### [KODEX 코스닥150롱코스피200숏선물 vs KODEX 200롱코스닥150숏선물](/360150-vs-360140/)<a id="360150-vs-360140"></a>

{% include vs/360150-vs-360140_md.inc %}


{% include /commons/ads/adsense.html %}



## 자산배분 ETF



### [RISE KRX300미국달러선물혼합 vs KODEX KRX300](/319870-vs-292190/)<a id="319870-vs-292190"></a>

{% include vs/319870-vs-292190_md.inc %}



### [RISE KRX300미국달러선물혼합 vs KOSEF 미국달러선물](/319870-vs-138230/)<a id="319870-vs-138230"></a>

{% include vs/319870-vs-138230_md.inc %}



### [KODEX 200미국채혼합 vs KODEX 200](/284430-vs-069500/)<a id="284430-vs-069500"></a>

{% include vs/284430-vs-069500_md.inc %}



### [KODEX 200미국채혼합 vs TIGER 미국채10년선물](/284430-vs-305080/)<a id="284430-vs-305080"></a>

{% include vs/284430-vs-305080_md.inc %}



## 퀀트 ETF



### [마이티 다이나믹퀀트액티브 vs KODEX 200](/442260-vs-069500/)<a id="442260-vs-069500"></a>

{% include vs/442260-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



## 국내 상장 커버드콜 ETF



### [TIGER 200 커버드콜5%OTM vs KODEX 200](/166400-vs-069500/)<a id="166400-vs-069500"></a>

TIGER 200 커버드콜5%OTM은 KOSPI 200 현물 주식을 보유하면서, KOSPI 200 콜옵션을 매도하는 전형적인 커버드 콜 전략을 쓰는 ETF입니다. KODEX 200은 기초 지수인 KOSPI 200을 추종하는 ETF입니다. 커버드 콜 전략이 KOSPI 200 지수에 얼마나 효과적인지 살펴볼 수 있습니다.

{% include vs/166400-vs-069500_md.inc %}



### [TIGER 200커버드콜ATM vs KODEX 200](/289480-vs-069500/)<a id="289480-vs-069500"></a>

{% include vs/289480-vs-069500_md.inc %}



### [TIGER 200커버드콜ATM vs TIGER 200커버드콜5%OTM](/289480-vs-166400/)<a id="289480-vs-166400"></a>

{% include vs/289480-vs-166400_md.inc %}



### [RISE 200고배당커버드콜ATM vs TIGER 코스피고배당](/290080-vs-210780/)<a id="290080-vs-210780"></a>

RISE 200고배당커버드콜ATM은 코스피 고배당 50 지수 편입 50종목을 보유하는 동시에, 코스피200콜옵션 매도로 안정적인 월분배를 추구하는 ETF입니다. TIGER 코스피고배당은 코스피 고배당 50 지수를 추적대상지수로 하는 ETF입니다. 고배당을 종목을 보유하고 있을 때, 추가로 커버드 콜 전략을 적용하는 것이 효과적인지 살펴볼 수 있습니다.

{% include vs/290080-vs-210780_md.inc %}



### [RISE 200위클리커버드콜 vs KODEX 200](/475720-vs-069500/)<a id="475720-vs-069500"></a>

RISE 200위클리커버드콜은 KOSPI 200 현물 주식을 보유하면서, KOSPI 200 콜옵션을 매도하는 전형적인 커버드콜 전략을 쓰는 ETF입니다. 다른 커버드콜 ETF와는 다르게 주단위로 커버드콜을 발행합니다.

{% include vs/475720-vs-069500_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 200위클리커버드콜 vs TIGER 200 커버드콜5%OTM](/475720-vs-166400/)<a id="475720-vs-166400"></a>

주단위 그리고 월단위 커버드콜 전략을 쓰는 ETF의 성과를 비교해 봅니다.

{% include vs/475720-vs-166400_md.inc %}



### [RISE 200위클리커버드콜 vs TIGER 200커버드콜ATM](/475720-vs-289480/)<a id="475720-vs-289480"></a>

{% include vs/475720-vs-289480_md.inc %}



### [KODEX 200타겟위클리커버드콜 vs KODEX 200](/498400-vs-069500/)<a id="498400-vs-069500"></a>

{% include vs/498400-vs-069500_md.inc %}



### [KODEX 200타겟위클리커버드콜 vs TIGER 200 커버드콜5%OTM](/498400-vs-166400/)<a id="498400-vs-166400"></a>

{% include vs/498400-vs-166400_md.inc %}



### [KODEX 200타겟위클리커버드콜 vs TIGER 200커버드콜ATM](/498400-vs-289480/)<a id="498400-vs-289480"></a>

{% include vs/498400-vs-289480_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 200타겟위클리커버드콜 vs RISE 200위클리커버드콜](/498400-vs-475720/)<a id="498400-vs-475720"></a>

{% include vs/498400-vs-475720_md.inc %}



### [PLUS 고배당주위클리커버드콜 vs PLUS 고배당주](/489030-vs-161510/)<a id="489030-vs-161510"></a>

{% include vs/489030-vs-161510_md.inc %}



### [PLUS 고배당주위클리커버드콜 vs KODEX 200](/489030-vs-069500/)<a id="489030-vs-069500"></a>

{% include vs/489030-vs-069500_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs KODEX S&P500TR](/441640-vs-379800/)<a id="441640-vs-379800"></a>

S&P 500 지수를 추종하는 KODEX S&P500TR과 월배당을 위해 배당성장주를 보유하고, 커버드콜 전략을 쓰는 KODEX 미국배당프리미엄액티브을 비교합니다.

{% include vs/441640-vs-379800_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs ACE 미국배당다우존스](/441640-vs-402970/)<a id="441640-vs-402970"></a>

한국판 DIVO인 KODEX 미국배당프리미엄액티브와 한국판 SCHD인 ACE 미국배당다우존스의 성과를 비교합니다.

{% include vs/441640-vs-402970_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 미국배당프리미엄액티브 vs SOL 미국배당다우존스](/441640-vs-446720/)<a id="441640-vs-446720"></a>

한국판 DIVO인 KODEX 미국배당프리미엄액티브와 한국판 SCHD인 SOL 미국배당다우존스의 성과를 비교합니다.

{% include vs/441640-vs-446720_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs TIGER 미국배당다우존스](/441640-vs-458730/)<a id="441640-vs-458730"></a>

한국판 DIVO인 KODEX 미국배당프리미엄액티브와 한국판 SCHD인 TIGER 미국배당다우존스의 성과를 비교합니다.

{% include vs/441640-vs-458730_md.inc %}



### [KODEX 미국배당프리미엄액티브 vs TIGER 미국배당+3%프리미엄다우존스](/441640-vs-458750/)<a id="441640-vs-458750"></a>

한국판 DIVO인 KODEX 미국배당프리미엄액티브와 비슷한 배당률의 한국판 SCHD에 커버드콜 전략을 쓰는 TIGER 미국배당+3%프리미엄다우존스와 성과를 비교합니다.

{% include vs/441640-vs-458750_md.inc %}



### [ACE 미국500 15%프리미엄분배(합성) vs ACE 미국S&P500](/480030-vs-360200/)<a id="480030-vs-360200"></a>

{% include vs/480030-vs-360200_md.inc %}



### [ACE 미국500 15%프리미엄분배(합성) vs KODEX 미국S&P500TR](/480030-vs-379800/)<a id="480030-vs-379800"></a>

{% include vs/480030-vs-379800_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국S&P500+10%프리미엄초단기옵션 vs TIGER 미국S&P500](/482730-vs-360750/)<a id="482730-vs-360750"></a>

{% include vs/482730-vs-360750_md.inc %}



### [TIGER 미국S&P500+10%프리미엄초단기옵션 vs KODEX 미국S&P500TR](/482730-vs-379800/)<a id="482730-vs-379800"></a>

{% include vs/482730-vs-379800_md.inc %}



### [TIGER 미국S&P500+10%프리미엄초단기옵션 vs ACE 미국500 15%프리미엄분배(합성)](/482730-vs-480030/)<a id="482730-vs-480030"></a>

{% include vs/482730-vs-480030_md.inc %}



### [KODEX 미국S&P500데일리커버드콜OTM vs KODEX S&P500](/0005a0-vs-379800/)<a id="0005a0-vs-379800"></a>

{% include vs/0005a0-vs-379800_md.inc %}



### [KODEX 미국S&P500데일리커버드콜OTM vs TIGER 미국S&P500+10%프리미엄초단기옵션](/0005a0-vs-482730/)<a id="0005a0-vs-482730"></a>

{% include vs/0005a0-vs-482730_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국나스닥100+15%프리미엄초단기 vs KODEX 미국나스닥100TR](/486290-vs-379810/)<a id="486290-vs-379810"></a>

{% include vs/486290-vs-379810_md.inc %}



### [KODEX 미국나스닥100데일리커버드콜OTM vs KODEX 미국나스닥100TR](/494300-vs-379810/)<a id="494300-vs-379810"></a>

{% include vs/494300-vs-379810_md.inc %}



### [KODEX 미국나스닥100데일리커버드콜OTM vs TIGER 미국나스닥100+15%프리미엄초단기](/494300-vs-486290/)<a id="494300-vs-486290"></a>

{% include vs/494300-vs-486290_md.inc %}



### [RISE 미국테크100데일리고정커버드콜 vs KODEX 미국나스닥100TR](/491620-vs-379810/)<a id="491620-vs-379810"></a>

{% include vs/491620-vs-379810_md.inc %}



### [RISE 미국테크100데일리고정커버드콜 vs TIGER 미국나스닥100+15%프리미엄초단기](/491620-vs-486290/)<a id="491620-vs-486290"></a>

{% include vs/491620-vs-486290_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국테크TOP10+10%프리미엄 vs TIGER 미국테크TOP10 INDXX](/474220-vs-381170/)<a id="474220-vs-381170"></a>

미국 테크 TOP 10 종목을 보유하는 TIGER 미국테크TOP10 INDXX와 커버드콜 전략을 최대 40%까지 사용하는 TIGER 미국테크TOP10+10%프리미엄를 비교합니다. (주의) 두 ETF의 이름은 유사하나 기초 자산의 지수가 다릅니다. 각각 Indxx와 Bloomberg가 만든 지수입니다.

{% include vs/474220-vs-381170_md.inc %}



### [TIGER 미국테크TOP10+10%프리미엄 vs PLUS 미국테크10iSelect](/474220-vs-461900/)<a id="474220-vs-461900"></a>

미국 테크 TOP 10 종목을 보유하는 PLUS 미국테크10iSelect와 커버드콜 전략을 최대 40%까지 사용하는 TIGER 미국테크TOP10+10%프리미엄를 비교합니다. (주의) 두 ETF의 이름은 유사하나 기초 자산의 지수가 다릅니다. 각각 iSelect와 Bloomberg가 만든 지수입니다.

{% include vs/474220-vs-461900_md.inc %}



### [ACE 미국빅테크7+ 15%프리미엄분배(합성) vs ACE 미국빅테크TOP7 Plus](/480020-vs-465580/)<a id="480020-vs-465580"></a>

{% include vs/480020-vs-465580_md.inc %}



### [KODEX 미국AI테크TOP10+15%프리미엄 vs KODEX 미국AI테크TOP10](/483280-vs-485540/)<a id="483280-vs-485540"></a>

{% include vs/483280-vs-485540_md.inc %}



## 합성 vs 일반 국내 상장 ETF



### [KOSEF 인도Nifty50(합성) vs KODEX 인도Nifty50](/200250-vs-453810/)<a id="200250-vs-453810"></a>

{% include vs/200250-vs-453810_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 차이나과창판STAR50(합성) vs ACE 중국과창판STAR50](/414780-vs-416090/)<a id="414780-vs-416090"></a>

{% include vs/414780-vs-416090_md.inc %}



### [TIGER 유로스탁스50(합성 H) vs RISE 유로스탁스50(H)](/195930-vs-379790/)<a id="195930-vs-379790"></a>

{% include vs/195930-vs-379790_md.inc %}



### [KODEX S&P글로벌인프라(합성) vs PLUS S&P글로벌인프라](/269420-vs-269530/)<a id="269420-vs-269530"></a>

{% include vs/269420-vs-269530_md.inc %}



## 국내 상장 미국달러선물



### [KODEX 미국달러선물 vs KOSEF 미국달러선물](/261240-vs-138230/)<a id="261240-vs-138230"></a>

{% include vs/261240-vs-138230_md.inc %}



## 국내 상장 미국달러SOFR



### [히어로즈 미국달러SOFR금리액티브(합성) vs TIGER 미국달러SOFR금리액티브(합성)](/460270-vs-456610/)<a id="460270-vs-456610"></a>

{% include vs/460270-vs-456610_md.inc %}


{% include /commons/ads/adsense.html %}



### [PLUS 미국달러SOFR금리액티브(합성) vs TIGER 미국달러SOFR금리액티브(합성)](/456200-vs-456610/)<a id="456200-vs-456610"></a>

{% include vs/456200-vs-456610_md.inc %}



### [히어로즈 미국달러SOFR금리액티브(합성) vs PLUS 미국달러SOFR금리액티브(합성)](/460270-vs-456200/)<a id="460270-vs-456200"></a>

{% include vs/460270-vs-456200_md.inc %}



### [TIGER 미국달러SOFR금리액티브(합성) vs KOSEF 미국달러선물](/456610-vs-138230/)<a id="456610-vs-138230"></a>

{% include vs/456610-vs-138230_md.inc %}



## 국내 상장 레버리지 ETF



### [RISE 코스닥150선물레버리지 vs KODEX 코스닥150레버리지](/278240-vs-233740/)<a id="278240-vs-233740"></a>

KODEX 코스닥150레버리지는 현물 100%와 선물 100%로 2배 레버리지를 구성한 상품입니다. RISE 코스닥150선물레버리지는 선물 200%로만 2배 레버리지를 구성한 상품입니다. 이로 인해 현물 지수가 아닌 선물 지수의 일일등락을 2배로 추종합니다. 선물 비중이 높은 레버리지는 상대적으로 어떤 성과를 거두었는지 살펴봅니다.

{% include vs/278240-vs-233740_md.inc %}



## 국내 상장 해외 ETF



### [TIGER 미국배당다우존스 vs TIGER 미국S&P500](/458730-vs-360750/)<a id="458730-vs-360750"></a>

{% include vs/458730-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국배당다우존스 vs KODEX 미국S&P500TR](/458730-vs-379800/)<a id="458730-vs-379800"></a>

{% include vs/458730-vs-379800_md.inc %}



### [TIGER 미국배당+7%프리미엄다우존스 vs TIGER 미국S&P500](/458760-vs-360750/)<a id="458760-vs-360750"></a>

{% include vs/458760-vs-360750_md.inc %}



### [TIGER 미국배당+7%프리미엄다우존스 vs KODEX 미국S&P500TR](/458760-vs-379800/)<a id="458760-vs-379800"></a>

{% include vs/458760-vs-379800_md.inc %}



### [TIGER 미국배당+7%프리미엄다우존스 vs TIGER 미국배당다우존스](/458760-vs-458730/)<a id="458760-vs-458730"></a>

TIGER 미국배당다우존스는 Dow Jones U.S. Dividend 100 지수(원화환산)(Price Return) 지수를 추종하는 배당성장주 ETF입니다. TIGER 미국배당+7%프리미엄다우존스는 여기에 최대 40%까지 커버드 콜 비중을 두어 단기 배당금을 높인 Dow Jones U.S. Dividend 100 7% Premium Covered Call 지수(Total Return)(원화환산) 지수를 추종하는 ETF입니다. 커버드 콜에 의한 성과 변화가 어떠했는지 살펴봅니다.

{% include vs/458760-vs-458730_md.inc %}



### [TIGER 미국배당+3%프리미엄다우존스 vs TIGER 미국S&P500](/458750-vs-360750/)<a id="458750-vs-360750"></a>

{% include vs/458750-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국배당+3%프리미엄다우존스 vs KODEX 미국S&P500TR](/458750-vs-360750/)<a id="458750-vs-360750"></a>

{% include vs/458750-vs-360750_md.inc %}



### [TIGER 미국배당+3%프리미엄다우존스 vs TIGER 미국배당다우존스](/458750-vs-458730/)<a id="458750-vs-458730"></a>

TIGER 미국배당다우존스는 Dow Jones U.S. Dividend 100 지수(원화환산)(Price Return) 지수를 추종하는 배당성장주 ETF입니다. TIGER 미국배당+3%프리미엄다우존스는 여기에 최대 15%까지 커버드 콜 비중을 두어 단기 배당금을 높인 Dow Jones U.S. Dividend 100 3% Premium Covered Call 지수(Total Return)(원화환산) 지수를 추종하는 ETF입니다. 커버드 콜에 의한 성과 변화가 어떠했는지 살펴봅니다.

{% include vs/458750-vs-458730_md.inc %}



### [KODEX 미국배당+10%프리미엄다우존스 vs TIGER 미국배당다우존스](/483290-vs-458730/)<a id="483290-vs-458730"></a>

{% include vs/483290-vs-458730_md.inc %}



### [KODEX 미국배당+10%프리미엄다우존스 vs TIGER TIGER 미국배당+7%프리미엄다우존스](/483290-vs-458760/)<a id="483290-vs-458760"></a>

{% include vs/483290-vs-458760_md.inc %}



### [KODEX 미국배당+10%프리미엄다우존스 vs KODEX 미국S&P500TR](/483290-vs-360750/)<a id="483290-vs-360750"></a>

{% include vs/483290-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국배당다우존스타겟데일리커버드콜 vs TIGER 미국배당다우존스](/0008s0-vs-458730/)<a id="0008s0-vs-458730"></a>

{% include vs/0008s0-vs-458730_md.inc %}



### [TIGER 미국배당다우존스타겟데일리커버드콜 vs TIGER 미국배당다우존스타겟커버드콜1호](/0008s0-vs-458750/)<a id="0008s0-vs-458750"></a>

{% include vs/0008s0-vs-458750_md.inc %}



### [TIGER 미국배당다우존스타겟데일리커버드콜 vs TIGER 미국배당다우존스타겟커버드콜2호](/0008s0-vs-458760/)<a id="0008s0-vs-458760"></a>

{% include vs/0008s0-vs-458760_md.inc %}



### [TIGER 미국배당다우존스타겟데일리커버드콜 vs KODEX 미국배당다우존스타겟커버드콜](/0008s0-vs-483290/)<a id="0008s0-vs-483290"></a>

{% include vs/0008s0-vs-483290_md.inc %}



### [RISE 미국배당100데일리고정커버드콜 vs KODEX 미국S&P500TR](/490600-vs-360750/)<a id="490600-vs-360750"></a>

{% include vs/490600-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 미국배당100데일리고정커버드콜 vs TIGER 미국배당다우존스](/490600-vs-458730/)<a id="490600-vs-458730"></a>

{% include vs/490600-vs-458730_md.inc %}



### [RISE 미국배당100데일리고정커버드콜 vs TIGER TIGER 미국배당+7%프리미엄다우존스](/490600-vs-458760/)<a id="490600-vs-458760"></a>

{% include vs/490600-vs-458760_md.inc %}



### [RISE 미국배당100데일리고정커버드콜 vs KODEX 미국배당+10%프리미엄다우존스](/490600-vs-483290/)<a id="490600-vs-483290"></a>

{% include vs/490600-vs-483290_md.inc %}



### [PLUS 미국배당증가성장주데일리커버드콜 vs KODEX 미국S&P500TR](/494420-vs-360750/)<a id="494420-vs-360750"></a>

{% include vs/494420-vs-360750_md.inc %}



### [PLUS 미국배당증가성장주데일리커버드콜 vs TIGER 미국배당다우존스](/494420-vs-458730/)<a id="494420-vs-458730"></a>

{% include vs/494420-vs-458730_md.inc %}


{% include /commons/ads/adsense.html %}



### [PLUS 미국배당증가성장주데일리커버드콜 vs TIGER TIGER 미국배당+7%프리미엄다우존스](/494420-vs-458760/)<a id="494420-vs-458760"></a>

{% include vs/494420-vs-458760_md.inc %}



### [PLUS 미국배당증가성장주데일리커버드콜 vs KODEX 미국배당+10%프리미엄다우존스](/494420-vs-483290/)<a id="494420-vs-483290"></a>

{% include vs/494420-vs-483290_md.inc %}



### [PLUS 미국배당증가성장주데일리커버드콜 vs RISE 미국배당100데일리고정커버드콜](/494420-vs-490600/)<a id="494420-vs-490600"></a>

{% include vs/494420-vs-490600_md.inc %}



### [SOL 미국배당다우존스(H) vs SOL 미국배당다우존스](/452360-vs-446720/)<a id="452360-vs-446720"></a>

SOL 미국배당다우존스(H)와 SOL 미국배당다우존스는 모두 Dow Jones U.S. Dividend 100 지수를 추종하지만, SOL 미국배당다우존스(H)는 환헤지가 적용된 ETF입니다. 환헤지가 성과에 어떤 영향을 미쳤는지 살펴봅니다.

{% include vs/452360-vs-446720_md.inc %}



### [TIGER 미국S&P500선물(H) vs TIGER 미국S&P500](/143850-vs-360750/)<a id="143850-vs-360750"></a>

TIGER 미국S&P500선물(H)는 S&P 500 선물지수를 추종하며 환헤지가 적용된 ETF입니다. 이 두 가지가 장기 성과에 어떤 영향을 미쳤는지 살펴봅니다.

{% include vs/143850-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [TIGER 미국나스닥100커버드콜(합성) vs TIGER 미국나스닥100](/441680-vs-133690/)<a id="441680-vs-133690"></a>

TIGER 미국나스닥100커버드콜(합성)은 나스닥 100 지수에 대해 커버드콜 전략을 사용하는 ETF입니다. 커버드 콜 전략이 나스닥 100 지수에 비해 어떤 성과를 거두었는지 살펴봅니다.

{% include vs/441680-vs-133690_md.inc %}



## 국내 상장 해외 ETF (배당다우존스)



### [SOL 미국배당다우존스 vs ACE 미국배당다우존스](/446720-vs-402970/)<a id="446720-vs-402970"></a>

{% include vs/446720-vs-402970_md.inc %}



### [TIGER 미국배당다우존스 vs ACE 미국배당다우존스](/458730-vs-402970/)<a id="458730-vs-402970"></a>

{% include vs/458730-vs-402970_md.inc %}



### [TIGER 미국배당다우존스 vs SOL 미국배당다우존스](/458730-vs-446720/)<a id="458730-vs-446720"></a>

{% include vs/458730-vs-446720_md.inc %}



### [SOL 미국배당다우존스TR vs SOL 미국배당다우존스](/493420-vs-446720/)<a id="493420-vs-446720"></a>

{% include vs/493420-vs-446720_md.inc %}


{% include /commons/ads/adsense.html %}



### [ACE 미국배당다우존스 vs TIGER 미국배당다우존스](/446720-vs-458730/)<a id="446720-vs-458730"></a>

{% include vs/446720-vs-458730_md.inc %}



### [SOL 미국배당다우존스 vs TIGER 미국배당다우존스](/402970-vs-458730/)<a id="402970-vs-458730"></a>

{% include vs/402970-vs-458730_md.inc %}



### [KODEX 미국배당다우존스 vs TIGER 미국배당다우존스](/489250-vs-458730/)<a id="489250-vs-458730"></a>

{% include vs/489250-vs-458730_md.inc %}



## 국내 상장 해외 ETF (S&P 500, base: TIGER 미국S&P500)



### [ACE 미국S&P500 vs TIGER 미국S&P500](/360200-vs-360750/)<a id="360200-vs-360750"></a>

{% include vs/360200-vs-360750_md.inc %}



### [KODEX 미국S&P500TR vs TIGER 미국S&P500](/379800-vs-360750/)<a id="379800-vs-360750"></a>

{% include vs/379800-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 미국S&P500 vs TIGER 미국S&P500](/379780-vs-360750/)<a id="379780-vs-360750"></a>

{% include vs/379780-vs-360750_md.inc %}



### [PLUS 미국S&P500 vs TIGER 미국S&P500](/429760-vs-360750/)<a id="429760-vs-360750"></a>

{% include vs/429760-vs-360750_md.inc %}



### [HANARO 미국S&P500 vs TIGER 미국S&P500](/432840-vs-360750/)<a id="432840-vs-360750"></a>

{% include vs/432840-vs-360750_md.inc %}



### [SOL 미국S&P500 vs TIGER 미국S&P500](/433330-vs-360750/)<a id="433330-vs-360750"></a>

{% include vs/433330-vs-360750_md.inc %}



### [WON 미국S&P500 vs TIGER 미국S&P500](/444490-vs-360750/)<a id="444490-vs-360750"></a>

{% include vs/444490-vs-360750_md.inc %}


{% include /commons/ads/adsense.html %}



### [KOSEF 미국S&P500 vs TIGER 미국S&P500](/449770-vs-360750/)<a id="449770-vs-360750"></a>

{% include vs/449770-vs-360750_md.inc %}



## 국내 상장 해외 ETF (S&P 500, base: KODEX 미국S&P500TR)



### [ACE 미국S&P500 vs KODEX 미국S&P500TR](/360200-vs-379800/)<a id="360200-vs-379800"></a>

{% include vs/360200-vs-379800_md.inc %}



### [TIGER 미국S&P500 vs KODEX 미국S&P500TR](/360750-vs-379800/)<a id="360750-vs-379800"></a>

{% include vs/360750-vs-379800_md.inc %}



### [RISE 미국S&P500 vs KODEX 미국S&P500TR](/379780-vs-379800/)<a id="379780-vs-379800"></a>

{% include vs/379780-vs-379800_md.inc %}



### [PLUS 미국S&P500 vs KODEX 미국S&P500TR](/429760-vs-379800/)<a id="429760-vs-379800"></a>

{% include vs/429760-vs-379800_md.inc %}


{% include /commons/ads/adsense.html %}



### [HANARO 미국S&P500 vs KODEX 미국S&P500TR](/432840-vs-379800/)<a id="432840-vs-379800"></a>

{% include vs/432840-vs-379800_md.inc %}



### [SOL 미국S&P500 vs KODEX 미국S&P500TR](/433330-vs-379800/)<a id="433330-vs-379800"></a>

{% include vs/433330-vs-379800_md.inc %}



### [WON 미국S&P500 vs KODEX 미국S&P500TR](/444490-vs-379800/)<a id="444490-vs-379800"></a>

{% include vs/444490-vs-379800_md.inc %}



### [KOSEF 미국S&P500 vs KODEX 미국S&P500TR](/449770-vs-379800/)<a id="449770-vs-379800"></a>

{% include vs/449770-vs-379800_md.inc %}



## 국내 상장 해외 ETF (나스닥 100, base: TIGER 미국나스닥100)



### [ACE 미국나스닥100 vs TIGER 미국나스닥100](/367380-vs-133690/)<a id="367380-vs-133690"></a>

{% include vs/367380-vs-133690_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 미국나스닥100TR vs TIGER 미국나스닥100](/379810-vs-133690/)<a id="379810-vs-133690"></a>

{% include vs/379810-vs-133690_md.inc %}



### [RISE 미국나스닥100 vs TIGER 미국나스닥100](/368590-vs-133690/)<a id="368590-vs-133690"></a>

{% include vs/368590-vs-133690_md.inc %}



### [SOL 미국나스닥100 vs TIGER 미국나스닥100](/476030-vs-133690/)<a id="476030-vs-133690"></a>

{% include vs/476030-vs-133690_md.inc %}



## 국내 상장 해외 ETF (나스닥 100, base: KODEX 미국나스닥100TR)



### [ACE 미국나스닥100 vs KODEX 미국나스닥100TR](/367380-vs-379810/)<a id="367380-vs-379810"></a>

{% include vs/367380-vs-379810_md.inc %}



### [TIGER 미국나스닥100 vs KODEX 미국나스닥100TR](/133690-vs-379810/)<a id="133690-vs-379810"></a>

{% include vs/133690-vs-379810_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 미국나스닥100 vs KODEX 미국나스닥100TR](/368590-vs-379810/)<a id="368590-vs-379810"></a>

{% include vs/368590-vs-379810_md.inc %}



### [SOL 미국나스닥100 vs KODEX 미국나스닥100TR](/476030-vs-379810/)<a id="476030-vs-379810"></a>

{% include vs/476030-vs-379810_md.inc %}



## 국내 상장 해외 ETF (S&P 500, 환헤지)



### [KODEX 미국S&P500선물(H) vs TIGER 미국S&P500선물(H)](/219480-vs-143850/)<a id="219480-vs-143850"></a>

{% include vs/219480-vs-143850_md.inc %}



### [PLUS 미국S&P500(H) vs TIGER 미국S&P500선물(H)](/269540-vs-143850/)<a id="269540-vs-143850"></a>

{% include vs/269540-vs-143850_md.inc %}



### [KODEX 미국S&P500(H) vs TIGER 미국S&P500선물(H)](/449180-vs-143850/)<a id="449180-vs-143850"></a>

{% include vs/449180-vs-143850_md.inc %}


{% include /commons/ads/adsense.html %}



### [KOSEF 미국S&P500(H) vs TIGER 미국S&P500선물(H)](/449780-vs-143850/)<a id="449780-vs-143850"></a>

{% include vs/449780-vs-143850_md.inc %}



### [RISE 미국S&P500(H) vs TIGER 미국S&P500선물(H)](/453330-vs-143850/)<a id="453330-vs-143850"></a>

{% include vs/453330-vs-143850_md.inc %}



## 국내 상장 해외 ETF (S&P 500, 환헤지, base: PLUS 미국S&P500(H))



### [TIGER 미국S&P500TR(H) vs PLUS 미국S&P500(H)](/448290-vs-269540/)<a id="448290-vs-269540"></a>

{% include vs/448290-vs-269540_md.inc %}



### [KODEX 미국S&P500(H) vs PLUS 미국S&P500(H)](/449180-vs-269540/)<a id="449180-vs-269540"></a>

{% include vs/449180-vs-269540_md.inc %}



### [KOSEF 미국S&P500(H) vs PLUS 미국S&P500(H)](/449780-vs-269540/)<a id="449780-vs-269540"></a>

{% include vs/449780-vs-269540_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 미국S&P500(H) vs PLUS 미국S&P500(H)](/453330-vs-269540/)<a id="453330-vs-269540"></a>

{% include vs/453330-vs-269540_md.inc %}



## 국내 상장 해외 ETF (S&P 500, 환헤지, base: TIGER 미국S&P500TR(H)



### [TIGER 미국S&P500TR(H) vs TIGER 미국S&P500TR(H)](/269540-vs-448290/)<a id="269540-vs-448290"></a>

{% include vs/269540-vs-448290_md.inc %}



### [KODEX 미국S&P500(H) vs TIGER 미국S&P500TR(H)](/449180-vs-448290/)<a id="449180-vs-448290"></a>

{% include vs/449180-vs-448290_md.inc %}



### [KOSEF 미국S&P500(H) vs TIGER 미국S&P500TR(H)](/449780-vs-448290/)<a id="449780-vs-448290"></a>

{% include vs/449780-vs-448290_md.inc %}



### [RISE 미국S&P500(H) vs TIGER 미국S&P500TR(H)](/453330-vs-448290/)<a id="453330-vs-448290"></a>

{% include vs/453330-vs-448290_md.inc %}


{% include /commons/ads/adsense.html %}



## 국내 상장 해외 ETF (나스닥 100, 환헤지)



### [TIGER 미국나스닥100TR(H) vs KODEX 미국나스닥100선물(H)](/448300-vs-304940/)<a id="448300-vs-304940"></a>

{% include vs/448300-vs-304940_md.inc %}



### [KODEX 미국나스닥100(H) vs KODEX 미국나스닥100선물(H)](/449190-vs-304940/)<a id="449190-vs-304940"></a>

{% include vs/449190-vs-304940_md.inc %}



### [KOSEF 미국나스닥100(H) vs KODEX 미국나스닥100선물(H)](/453080-vs-304940/)<a id="453080-vs-304940"></a>

{% include vs/453080-vs-304940_md.inc %}



## 국내 상장 해외 ETF (나스닥 100, 환헤지, base: TIGER 미국나스닥100TR(H))



### [KODEX 미국나스닥100(H) vs TIGER 미국나스닥100TR(H))](/449190-vs-448300/)<a id="449190-vs-448300"></a>

{% include vs/449190-vs-448300_md.inc %}



### [KOSEF 미국나스닥100(H) vs TIGER 미국나스닥100TR(H))](/453080-vs-448300/)<a id="453080-vs-448300"></a>

{% include vs/453080-vs-448300_md.inc %}


{% include /commons/ads/adsense.html %}



## 국내 상장 해외 ETF (인도 Nifty50)



### [KODEX 인도Nifty50 vs KOSEF 인도Nifty50(합성)](/453810-vs-200250/)<a id="453810-vs-200250"></a>

{% include vs/453810-vs-200250_md.inc %}



### [TIGER 인도니프티50 vs KOSEF 인도Nifty50(합성)](/453870-vs-200250/)<a id="453870-vs-200250"></a>

{% include vs/453870-vs-200250_md.inc %}



### [TIGER 인도니프티50 vs KODEX 인도Nifty50](/453870-vs-453810/)<a id="453870-vs-453810"></a>

{% include vs/453870-vs-453810_md.inc %}



## 국내 상장 해외 ETF (레버리지)



### [KODEX 미국나스닥100레버리지(합성 H) vs QLD](/409820-vs-qld/)<a id="409820-vs-qld"></a>

{% include vs/409820-vs-qld_md.inc %}



### [TIGER 미국S&P500레버리지(합성 H) vs SSO](/225040-vs-sso/)<a id="225040-vs-sso"></a>

{% include vs/225040-vs-sso_md.inc %}


{% include /commons/ads/adsense.html %}



## ETF vs ETN (국내)



### [삼성 코스피 200 TR ETN vs KODEX 200](/530117-vs-069500/)<a id="530117-vs-069500"></a>

{% include vs/530117-vs-069500_md.inc %}



### [삼성 코스피 200 TR ETN vs KODEX 200TR](/530117-vs-278530/)<a id="530117-vs-278530"></a>

{% include vs/530117-vs-278530_md.inc %}



### [삼성 코스닥 150 TR ETN vs KODEX 코스닥150](/530118-vs-229200/)<a id="530118-vs-229200"></a>

{% include vs/530118-vs-229200_md.inc %}



### [삼성 미국S&P500 ETN vs KODEX 미국S&P500TR](/530112-vs-379800/)<a id="530112-vs-379800"></a>

{% include vs/530112-vs-379800_md.inc %}



### [삼성 나스닥 100 ETN vs KODEX 미국나스닥100TR](/530120-vs-379810/)<a id="530120-vs-379810"></a>

{% include vs/530120-vs-379810_md.inc %}


{% include /commons/ads/adsense.html %}



## 저변동성



### [KODEX 최소변동성 vs KODEX KRX 300](/279540-vs-292190/)<a id="279540-vs-292190"></a>

KODEX 최소변동성은 하락장에서 손실폭을 줄이기 위해 주가변동이 낮은 종목을 편입합니다. KRX 최소변동성 지수를 추종합니다. 위험 대비 수익률이 개선하고자 하는 목표가 달성되고 있는지 KRX 300 지수를 추종하는 KODEX KRX300의 성과와 비교해 봅니다.

{% include vs/279540-vs-292190_md.inc %}



## 우선주와 일반주



### [TIGER 우선주 vs KODEX 200](/261140-vs-069500/)<a id="261140-vs-069500"></a>

의결권이 없는 대신 배당금이 조금 더 높은 우선주와 의결권이 있는 일반주의 성과가 어떠한지 살펴봅니다. TIGER 우선주는 코스피 우선주 지수를 추종하는 상품으로 시총, 유동성, 배당실적 등을 고려한 지수입니다. KODEX 200은 코스피 200에 편입된 종목을 시총가중 방식으로 투자하는 ETF입니다.

{% include vs/261140-vs-069500_md.inc %}



### [삼성전자 우선주 vs 삼성전자 일반주](/005935-vs-005930/)<a id="005935-vs-005930"></a>

의결권이 없는 대신 배당금이 조금 더 높은 우선주와 의결권이 있는 일반주의 성과가 어떠한지 살펴봅니다.

{% include vs/005935-vs-005930_md.inc %}



## 국내 상장 미국 고정 배당 우선주 ETF



### [RISE 미국고정배당우선증권TR vs PLUS 미국단기회사채(AAA~A)](/354240-vs-332610/)<a id="354240-vs-332610"></a>

{% include vs/354240-vs-332610_md.inc %}



### [RISE 미국고정배당우선증권TR vs PLUS 미국장기우량회사채](/354240-vs-332620/)<a id="354240-vs-332620"></a>

{% include vs/354240-vs-332620_md.inc %}


{% include /commons/ads/adsense.html %}



### [RISE 미국고정배당우선증권TR vs TIGER 미국달러단기채권액티브](/354240-vs-329750/)<a id="354240-vs-329750"></a>

{% include vs/354240-vs-329750_md.inc %}



## 미국 테크/빅테크 ETF/ETN



### [키움 INDXX 미국테크탑10 ETN vs TIGER 미국테크TOP10 INDXX](/760005-vs-381170/)<a id="760005-vs-381170"></a>

{% include vs/760005-vs-381170_md.inc %}



### [PLUS 미국테크TOP10 vs TIGER 미국테크TOP10 INDXX](/461900-vs-381170/)<a id="461900-vs-381170"></a>

{% include vs/461900-vs-381170_md.inc %}



### [ACE 미국빅테크TOP7 Plus vs TIGER 미국테크TOP10 INDXX](/465580-vs-381170/)<a id="465580-vs-381170"></a>

{% include vs/465580-vs-381170_md.inc %}



### [SOL 미국테크TOP10 vs TIGER 미국테크TOP10 INDXX](/481190-vs-381170/)<a id="481190-vs-381170"></a>

{% include vs/481190-vs-381170_md.inc %}


{% include /commons/ads/adsense.html %}



### [KODEX 미국빅테크10(H) vs TIGER 미국테크TOP10 INDXX](/314250-vs-381170/)<a id="314250-vs-381170"></a>

{% include vs/314250-vs-381170_md.inc %}



### [TIGER 미국테크TOP10 INDXX(H) vs TIGER 미국테크TOP10 INDXX](/472160-vs-381170/)<a id="472160-vs-381170"></a>

{% include vs/472160-vs-381170_md.inc %}



### [KODEX 미국빅테크10(H) vs TIGER 미국테크TOP10 INDXX(H)](/314250-vs-472160/)<a id="314250-vs-472160"></a>

{% include vs/314250-vs-472160_md.inc %}



## 기타 국내 상장 해외 ETF



### [RISE 버크셔포트폴리오TOP10 vs KODEX 미국S&P500TR](/475350-vs-379800/)<a id="475350-vs-379800"></a>

{% include vs/475350-vs-379800_md.inc %}



## 해외 상장 해외 ETF (지수 대비)



### [VXUS vs VTI](/vxus-vs-vt/)<a id="vxus-vs-vt"></a>

{% include vs/vxus-vs-vt_md.inc %}


{% include /commons/ads/adsense.html %}



### [VT vs VTI](/vt-vs-vti/)<a id="vt-vs-vti"></a>

전세계 주식에 투자하는 VT와 미국 주식에만 투자하는 VTI의 장기 성과를 비교해 봅니다.

{% include vs/vt-vs-vti_md.inc %}



### [VOO vs VTI](/voo-vs-vti/)<a id="voo-vs-vti"></a>

{% include vs/voo-vs-vti_md.inc %}



### [VTI vs SPY](/vti-vs-spy/)<a id="vti-vs-spy"></a>

미국에 상장된 모든 주식에 투자하는 VTI와 S&P 500 지수에 포함된 대형주에만 투자하는 SPY의 장기 성과를 비교해 봅니다.

{% include vs/vti-vs-spy_md.inc %}



### [VOO vs SPY](/voo-vs-spy/)<a id="voo-vs-spy"></a>

{% include vs/voo-vs-spy_md.inc %}



### [IVV vs SPY](/ivv-vs-spy/)<a id="ivv-vs-spy"></a>

{% include vs/ivv-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [SPLG vs SPY](/splg-vs-spy/)<a id="splg-vs-spy"></a>

{% include vs/splg-vs-spy_md.inc %}



### [VTV vs SPY](/vtv-vs-spy/)<a id="vtv-vs-spy"></a>

{% include vs/vtv-vs-spy_md.inc %}



### [VUG vs SPY](/vug-vs-spy/)<a id="vug-vs-spy"></a>

{% include vs/vug-vs-spy_md.inc %}



### [SPYG vs SPY](/spyg-vs-spy/)<a id="spyg-vs-spy"></a>

{% include vs/spyg-vs-spy_md.inc %}



### [SPYG vs VUG](/spyg-vs-vug/)<a id="spyg-vs-vug"></a>

{% include vs/spyg-vs-vug_md.inc %}


{% include /commons/ads/adsense.html %}



### [SPYG vs SCHD](/spyg-vs-schd/)<a id="spyg-vs-schd"></a>

{% include vs/spyg-vs-schd_md.inc %}



### [QQQ vs SPY](/qqq-vs-spy/)<a id="qqq-vs-spy"></a>

나스닥에서 주요 종목을 선별하는 QQQ와 나스닥을 포함하여 미국 시장에 상장된 주요 종목을 대상으로 하는 SP간의 장기 성과를 비교해 봅니다.

{% include vs/qqq-vs-spy_md.inc %}



### [QQQM vs QQQ](/qqqm-vs-qqq/)<a id="qqqm-vs-qqq"></a>

{% include vs/qqqm-vs-qqq_md.inc %}



### [SPMO vs SPY](/spmo-vs-spy/)<a id="spmo-vs-spy"></a>

{% include vs/spmo-vs-spy_md.inc %}



### [SPMO vs QQQ](/spmo-vs-qqq/)<a id="spmo-vs-qqq"></a>

{% include vs/spmo-vs-qqq_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 상장 해외 ETF (배당)



### [SCHD vs SPY](/schd-vs-spy/)<a id="schd-vs-spy"></a>

배당성장주로 유명한 SCHD를 배당은 고려하지 않고 S&P 500 지수를 추종하는 SPY와 비교해 봅니다.

{% include vs/schd-vs-spy_md.inc %}



### [VIG vs SPY](/vig-vs-spy/)<a id="vig-vs-spy"></a>

VIG는 S&P U.S. Dividend Growers 지수를 추종하는 뱅가드사의 배당성장주 ETF입니다. 장기적인 성과를 SPY와 비교해 봅니다.

{% include vs/vig-vs-spy_md.inc %}



### [PEY vs SPY](/pey-vs-spy/)<a id="pey-vs-spy"></a>

Invesco사의 PEY는 지속적으로 배당금이 성장한 종목을 선별한 Dividend Achiever 50 Index를 추종하는 ETF입니다. 꾸준한 배당금 증액으로 종목을 선별하는 효과를 SPY와 비교해 봅니다.

{% include vs/pey-vs-spy_md.inc %}



### [NOBL vs SPY](/nobl-vs-spy/)<a id="nobl-vs-spy"></a>

ProShares사의 NOBL은 배당금이 꾸준히 증가한 배당귀족주에 투자하는 대표적인 배당 ETF입니다. 꾸준한 배당금 증액의 효과를 SPY와 비교해 봅니다.

{% include vs/nobl-vs-spy_md.inc %}



### [SPYD vs SPY](/spyd-vs-spy/)<a id="spyd-vs-spy"></a>

 SSGA사의 SPYD는 S&P500 편입 종목 중에서 고배당주를 선별한 ETF입니다. 고배당 효과를 SPY와 비교해 봅니다.

{% include vs/spyd-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 상장 해외 ETF (배당, SCHD 대비)



### [VIG vs SCHD](/vig-vs-schd/)<a id="vig-vs-schd"></a>

VIG는 S&P U.S. Dividend Growers 지수를 추종하는 뱅가드사의 배당성장주 ETF입니다. 국내에 널리 알려진 SCHD는 Dow Jones U.S. Dividend 100 지수를 추종하는 대표적인 배당성장주 ETF입니다. 두 상품 모두 비슷한 관점에서 설계했기에, 장기직인 성과는 비슷하리라 예상할 수 있습니다.

{% include vs/vig-vs-schd_md.inc %}



### [VTV vs SCHD](/vtv-vs-schd/)<a id="vtv-vs-schd"></a>

{% include vs/vtv-vs-schd_md.inc %}



### [SPY vs SCHD](/spy-vs-schd/)<a id="spy-vs-schd"></a>

{% include vs/spy-vs-schd_md.inc %}



### [SDY vs SCHD](/sdy-vs-schd/)<a id="sdy-vs-schd"></a>

{% include vs/sdy-vs-schd_md.inc %}



### [HDV vs SCHD](/sdy-vs-schd/)<a id="sdy-vs-schd"></a>

{% include vs/sdy-vs-schd_md.inc %}


{% include /commons/ads/adsense.html %}



### [NOBL vs SCHD](/nobl-vs-schd/)<a id="nobl-vs-schd"></a>

{% include vs/nobl-vs-schd_md.inc %}



### [DIVO vs SCHD](/divo-vs-schd/)<a id="divo-vs-schd"></a>

{% include vs/divo-vs-schd_md.inc %}



### [VYM vs SCHD](/vym-vs-schd/)<a id="vym-vs-schd"></a>

{% include vs/vym-vs-schd_md.inc %}



### [DGRO vs SCHD](/dgro-vs-schd/)<a id="dgro-vs-schd"></a>

{% include vs/dgro-vs-schd_md.inc %}



### [SPHD vs SCHD](/sphd-vs-schd/)<a id="sphd-vs-schd"></a>

{% include vs/sphd-vs-schd_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 상장 해외 ETF (미국 SPY 대비)



### [VEA vs SPY](/vea-vs-spy/)<a id="vea-vs-spy"></a>

미국 외 선진국에 투자하는 VEA를 미국 대행주에 투자하는 SPY와 비교해 봅니다.

{% include vs/vea-vs-spy_md.inc %}



### [VWO vs SPY](/vwo-vs-spy/)<a id="vwo-vs-spy"></a>

신흥국에 투자하는 VWO를 미국 대행주에 투자하는 SPY와 비교해 봅니다.

{% include vs/vwo-vs-spy_md.inc %}



## 해외 상장 비주식 ETF (미국 SPY 대비)



### [DBC vs SPY](/dbc-vs-spy/)<a id="dbc-vs-spy"></a>

원자재 ETF인 DBC를 미국 대행주에 투자하는 SPY와 비교해 봅니다.

{% include vs/dbc-vs-spy_md.inc %}



### [GLD vs SPY](/gld-vs-spy/)<a id="gld-vs-spy"></a>

금 현물 ETF인 GLD를 미국 대행주에 투자하는 SPY와 비교해 봅니다.

{% include vs/gld-vs-spy_md.inc %}



### [VNQ vs SPY](/vnq-vs-spy/)<a id="vnq-vs-spy"></a>

부동산 리츠 ETF인 VNQ를 미국 대행주에 투자하는 SPY와 비교해 봅니다.

{% include vs/vnq-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 상장 해외 ETF (DIVO 대비)



### [SPY vs DIVO](/spy-vs-divo/)<a id="spy-vs-divo"></a>

{% include vs/spy-vs-divo_md.inc %}



### [SCHD vs DIVO](/schd-vs-divo/)<a id="schd-vs-divo"></a>

{% include vs/schd-vs-divo_md.inc %}



### [JEPI vs DIVO](/jepi-vs-divo/)<a id="jepi-vs-divo"></a>

{% include vs/jepi-vs-divo_md.inc %}



### [DGRW vs DIVO](/dgrw-vs-divo/)<a id="dgrw-vs-divo"></a>

{% include vs/dgrw-vs-divo_md.inc %}



### [DGRO vs DIVO](/dgro-vs-divo/)<a id="dgro-vs-divo"></a>

{% include vs/dgro-vs-divo_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 상장 해외 ETF (IDVO 대비)



### [SPY vs IDVO](/spy-vs-idvo/)<a id="spy-vs-idvo"></a>

{% include vs/spy-vs-idvo_md.inc %}



### [DIVO vs IDVO](/divo-vs-idvo/)<a id="divo-vs-idvo"></a>

{% include vs/divo-vs-idvo_md.inc %}



### [SCHD vs IDVO](/schd-vs-idvo/)<a id="schd-vs-idvo"></a>

{% include vs/schd-vs-idvo_md.inc %}



### [NOBL vs IDVO](/nobl-vs-idvo/)<a id="nobl-vs-idvo"></a>

{% include vs/nobl-vs-idvo_md.inc %}



### [JEPI vs IDVO](/jepi-vs-idvo/)<a id="jepi-vs-idvo"></a>

{% include vs/jepi-vs-idvo_md.inc %}


{% include /commons/ads/adsense.html %}



### [EWJ vs IDVO](/ewj-vs-idvo/)<a id="ewj-vs-idvo"></a>

{% include vs/ewj-vs-idvo_md.inc %}



### [EWJV vs IDVO](/ewjv-vs-idvo/)<a id="ewjv-vs-idvo"></a>

{% include vs/ewjv-vs-idvo_md.inc %}



## 해외 상장 해외 ETF (스마트 베타)



### [SCHG vs SPY](/schg-vs-spy/)<a id="schg-vs-spy"></a>

{% include vs/schg-vs-spy_md.inc %}



### [SCHG vs QQQ](/schg-vs-qqq/)<a id="schg-vs-qqq"></a>

{% include vs/schg-vs-qqq_md.inc %}



## 해외 상장 해외 ETF (섹터)



### [XLK vs SPY](/xlk-vs-spy/)<a id="xlk-vs-spy"></a>

{% include vs/xlk-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [XLK vs QQQ](/xlk-vs-qqq/)<a id="xlk-vs-qqq"></a>

{% include vs/xlk-vs-qqq_md.inc %}



## 해외 상장 해외 ETF (커버드 콜)



### [ISPY vs SPY](/ispy-vs-spy/)<a id="ispy-vs-spy"></a>

{% include vs/ispy-vs-spy_md.inc %}



### [ISPY vs XYLD](/ispy-vs-xyld/)<a id="ispy-vs-xyld"></a>

{% include vs/ispy-vs-xyld_md.inc %}



### [ISPY vs XYLG](/ispy-vs-xylg/)<a id="ispy-vs-xylg"></a>

{% include vs/ispy-vs-xylg_md.inc %}



### [ISPY vs JEPI](/ispy-vs-jepi/)<a id="ispy-vs-jepi"></a>

{% include vs/ispy-vs-jepi_md.inc %}


{% include /commons/ads/adsense.html %}



### [ISPY vs SPYI](/ispy-vs-spyi/)<a id="ispy-vs-spyi"></a>

{% include vs/ispy-vs-spyi_md.inc %}



### [ISPY vs JEPY](/ispy-vs-jepy/)<a id="ispy-vs-jepy"></a>

{% include vs/ispy-vs-jepy_md.inc %}



### [ISPY vs GPIX](/ispy-vs-gpix/)<a id="ispy-vs-gpix"></a>

{% include vs/ispy-vs-gpix_md.inc %}



### [ISPY vs BALI](/ispy-vs-bali/)<a id="ispy-vs-bali"></a>

{% include vs/ispy-vs-bali_md.inc %}



### [SPYI vs SPY](/spyi-vs-spy/)<a id="spyi-vs-spy"></a>

S&P 500 지수에 대해 커버드 콜 전략을 쓰는 SPYI와 S&P 500 지수를 추종하는 SPY의 성과를 비교해 봅니다.

{% include vs/spyi-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [QQQI vs QQQ](/qqqi-vs-qqq/)<a id="qqqi-vs-qqq"></a>

{% include vs/qqqi-vs-qqq_md.inc %}



### [SPYI vs XYLD](/spyi-vs-xyld/)<a id="spyi-vs-xyld"></a>

{% include vs/spyi-vs-xyld_md.inc %}



### [JEPI vs SPY](/jepi-vs-spy/)<a id="jepi-vs-spy"></a>

{% include vs/jepi-vs-spy_md.inc %}



### [JEPI vs SCHD](/jepi-vs-schd/)<a id="jepi-vs-schd"></a>

{% include vs/jepi-vs-schd_md.inc %}



### [JEPIX vs SCHD](/jepix-vs-schd/)<a id="jepix-vs-schd"></a>

{% include vs/jepix-vs-schd_md.inc %}


{% include /commons/ads/adsense.html %}



### [JEPI vs JEPIX](/jepi-vs-jepix/)<a id="jepi-vs-jepix"></a>

JEPIX는 JEPI와 동일한 전략을 사용한다고 알려진 JP모건사의 뮤추얼 펀드입니다. JEPIX는 JEPI보다 먼저 설정되었습니다. 두 상품이 동일한지 확인해 봅니다. 참고로 JEPIX의 시세 데이터에 오류가 있는 듯 합니다. JEPIX는 매달 배당금을 지급하는 방식에서 2023년 상반기에 대부분을 펀드에 재투자하는 방식으로 바뀌었습니다. 이로 인한 자산 증가분이 고려되지 않아 JEPI보다 낮은 성과를 보이는 착시가 발생할 수 있습니다.

{% include vs/jepi-vs-jepix_md.inc %}



### [JEPIX vs SPY](/jepix-vs-spy/)<a id="jepix-vs-spy"></a>

JEPIX는 JEPII와 동일한 전략을 사용한다고 알려진 JP모건사 뮤추얼 펀드입니다. JEPIX는 JEPI보다 먼저 설정되었습니다. JEPI/JEPIX의 전략이 유용한 지 좀 더 긴 기간을 대상으로 비교해 봅니다. 참고로 JEPIX의 시세 데이터에 오류가 있는 듯 합니다. JEPIX는 매달 배당금을 지급하는 방식에서 2023년 상반기에 대부분을 펀드에 재투자하는 방식으로 바뀌었습니다. 이로 인한 자산 증가분이 고려되지 않아 JEPI보다 낮은 성과를 보이는 착시가 발생할 수 있습니다. JEPIX 대신 JEPI로 비교하는 것이 현재로는 보다 정확합니다.

{% include vs/jepix-vs-spy_md.inc %}



### [IQQQ vs QQQ](/iqqq-vs-qqq/)<a id="iqqq-vs-qqq"></a>

{% include vs/iqqq-vs-qqq_md.inc %}



### [JEPQ vs QQQ](/jepq-vs-qqq/)<a id="jepq-vs-qqq"></a>

{% include vs/jepq-vs-qqq_md.inc %}



### [JEPQ vs JEPI](/jepq-vs-jepi/)<a id="jepq-vs-jepi"></a>

{% include vs/jepq-vs-jepi_md.inc %}


{% include /commons/ads/adsense.html %}



### [JEPQ vs SPY](/jepq-vs-spy/)<a id="jepq-vs-spy"></a>

{% include vs/jepq-vs-spy_md.inc %}



### [GPIX vs SPY](/gpix-vs-spy/)<a id="gpix-vs-spy"></a>

{% include vs/gpix-vs-spy_md.inc %}



### [GPIQ vs QQQ](/gpiq-vs-qqq/)<a id="gpiq-vs-qqq"></a>

{% include vs/gpiq-vs-qqq_md.inc %}



### [GPIX vs JEPI](/gpix-vs-jepi/)<a id="gpix-vs-jepi"></a>

{% include vs/gpix-vs-jepi_md.inc %}



### [GPIQ vs JEPQ](/gpiq-vs-jepq/)<a id="gpiq-vs-jepq"></a>

{% include vs/gpiq-vs-jepq_md.inc %}


{% include /commons/ads/adsense.html %}



### [XYLD vs SPY](/xyld-vs-spy/)<a id="xyld-vs-spy"></a>

S&P 500 지수에 대해 커버드 콜 전략을 쓰는 XYLD와 S&P 500 지수를 추종하는 SPY의 성과를 비교해 봅니다.

{% include vs/xyld-vs-spy_md.inc %}



### [QYLD vs QQQ](/qyld-vs-qqq/)<a id="qyld-vs-qqq"></a>

나스닥 100 지수에 대해 커버드 콜 전략을 쓰는 QYLD와 나스닥 100 지수를 추종하는 QQQ의 성과를 비교해 봅니다.

{% include vs/qyld-vs-qqq_md.inc %}



### [QYLD vs XYLD](/qyld-vs-xyld/)<a id="qyld-vs-xyld"></a>

{% include vs/qyld-vs-xyld_md.inc %}



### [RYLD vs IWM](/ryld-vs-iwm/)<a id="ryld-vs-iwm"></a>

{% include vs/ryld-vs-iwm_md.inc %}



### [DJIA vs DIA](/djia-vs-dia/)<a id="djia-vs-dia"></a>

전통이 깊은 다우 존스 산업평균지수에 대해 커버드 콜 전략을 쓰는 DIJA를 해당 지수를 추종하는 DIA와 비교해 봅니다.

{% include vs/djia-vs-dia_md.inc %}


{% include /commons/ads/adsense.html %}



### [JEPY vs SPY](/jepy-vs-spy/)<a id="jepy-vs-spy"></a>

S&P 500 지수에 대해 데일리 커버드 콜 전략을 쓰는 JEPY와 S&P 500 지수를 추종하는 SPY의 성과를 비교해 봅니다.

{% include vs/jepy-vs-spy_md.inc %}



### [QQQY vs QQQ](/qqqy-vs-qqq/)<a id="qqqy-vs-qqq"></a>

나스닥 100 지수에 대해 데일리 커버드 콜 전략을 쓰는 QQQY와 나스닥 100 지수를 추종하는 QQQ의 성과를 비교해 봅니다.

{% include vs/qqqy-vs-qqq_md.inc %}



### [IWMY vs IWM](/iwmy-vs-iwm/)<a id="iwmy-vs-iwm"></a>

러셀 2000 지수에 대해 데일리 커버드 콜 전략을 쓰는 IWMY와 러셀 2000 지수를 추종하는 IWM의 성과를 비교해 봅니다.

{% include vs/iwmy-vs-iwm_md.inc %}



### [JEPY vs XYLD](/jepy-vs-xyld/)<a id="jepy-vs-xyld"></a>

{% include vs/jepy-vs-xyld_md.inc %}



### [QQQY vs QYLD](/qqqy-vs-qyld/)<a id="qqqy-vs-qyld"></a>

{% include vs/qqqy-vs-qyld_md.inc %}


{% include /commons/ads/adsense.html %}



### [IWMY vs RYLD](/iwmy-vs-ryld/)<a id="iwmy-vs-ryld"></a>

{% include vs/iwmy-vs-ryld_md.inc %}



### [BALI vs SPY](/bali-vs-spy/)<a id="bali-vs-spy"></a>

{% include vs/bali-vs-spy_md.inc %}



### [BALI vs QQQ](/bali-vs-qqq/)<a id="bali-vs-qqq"></a>

{% include vs/bali-vs-qqq_md.inc %}



### [BALI vs JEPI](/bali-vs-jepi/)<a id="bali-vs-jepi"></a>

{% include vs/bali-vs-jepi_md.inc %}



### [BALI vs JEPQ](/bali-vs-jepq/)<a id="bali-vs-jepq"></a>

{% include vs/bali-vs-jepq_md.inc %}


{% include /commons/ads/adsense.html %}



### [BALI vs JEPY](/bali-vs-jepy/)<a id="bali-vs-jepy"></a>

{% include vs/bali-vs-jepy_md.inc %}



### [BALI vs SPYI](/bali-vs-spyi/)<a id="bali-vs-spyi"></a>

{% include vs/bali-vs-spyi_md.inc %}



### [BALI vs GPIX](/bali-vs-gpix/)<a id="bali-vs-gpix"></a>

{% include vs/bali-vs-gpix_md.inc %}



### [BALI vs GPIQ](/bali-vs-gpiq/)<a id="bali-vs-gpiq"></a>

{% include vs/bali-vs-gpiq_md.inc %}



### [KNG vs NOBL](/kng-vs-nobl/)<a id="kng-vs-nobl"></a>

{% include vs/kng-vs-nobl_md.inc %}


{% include /commons/ads/adsense.html %}



### [TLTW vs TLT](/tltw-vs-tlt/)<a id="tltw-vs-tlt"></a>

TLT는 미국 장기 국채에 투자하는 ETF입니다. TLTW는 미국 장기 국채에 커버드콜 전략을 사용하는 ETF입니다. 변동성이 높은 장기 국채에 커버드콜 전략이 효과가 있는지 비교해 봅니다.

{% include vs/tltw-vs-tlt_md.inc %}



## 주배당 커버드콜



### [XDTE vs SPY](/xdte-vs-spy/)<a id="xdte-vs-spy"></a>

{% include vs/xdte-vs-spy_md.inc %}



### [XDTE vs ISPY](/xdte-vs-ispy/)<a id="xdte-vs-ispy"></a>

{% include vs/xdte-vs-ispy_md.inc %}



### [QDTE vs QQQ](/qdte-vs-qqq/)<a id="qdte-vs-qqq"></a>

{% include vs/qdte-vs-qqq_md.inc %}



### [QDTE vs IQQQ](/qdte-vs-iqqq/)<a id="qdte-vs-iqqq"></a>

{% include vs/qdte-vs-iqqq_md.inc %}


{% include /commons/ads/adsense.html %}



### [RDTE vs IWM](/rdte-vs-iwm/)<a id="rdte-vs-iwm"></a>

{% include vs/rdte-vs-iwm_md.inc %}



## 레버리지



### [QLD vs QQQ](/qld-vs-qqq/)<a id="qld-vs-qqq"></a>

{% include vs/qld-vs-qqq_md.inc %}



### [TQQQ vs QQQ](/tqqq-vs-qqq/)<a id="tqqq-vs-qqq"></a>

{% include vs/tqqq-vs-qqq_md.inc %}



## 해외 상장 해외 ETF (동일 비중)



### [EDOW vs DIA](/edow-vs-dia/)<a id="edow-vs-dia"></a>

다우지수 동일 비중 vs 다우지수

{% include vs/edow-vs-dia_md.inc %}



### [RSP vs SPY](/rsp-vs-spy/)<a id="rsp-vs-spy"></a>

S&P 500 Equal Weight Index vs. S&P 500

{% include vs/rsp-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [QQEW  vs QQQ](/qqew-vs-qqq/)<a id="qqew-vs-qqq"></a>

Nasdaq 100 Equal Weight Index vs. Nasdaq 100

{% include vs/qqew-vs-qqq_md.inc %}



### [EQWS vs IWM](/eqws-vs-iwm/)<a id="eqws-vs-iwm"></a>

{% include vs/eqws-vs-iwm_md.inc %}



## 해외 상장 해외 ETF (저변동성)



### [SPLV vs SPY](/splv-vs-spy/)<a id="splv-vs-spy"></a>

Invesco사의 SPLV는 S&P500 종목 중에서 변동성이 낮은 종목에 투자하는 상품입니다. S&P5 500 지수를 추종하는 SPY와 비교해서 저변동성 종목 편입의 효과를 확인해 봅니다.

{% include vs/splv-vs-spy_md.inc %}



### [SPHD vs SPY](/sphd-vs-spy/)<a id="sphd-vs-spy"></a>

Invesco사의 SPHD는 S&P500 종목 중에서 고배당을 주면서 변동성이 낮은 종목에 투자하는 상품입니다. S&P5 500 지수를 추종하는 SPY와 비교해서 고배당과 저변동성 모두 충족하는 종목에 투자한 효과를 확인해 봅니다.

{% include vs/sphd-vs-spy_md.inc %}



### [SPHD vs SPLV](/sphd-vs-splv/)<a id="sphd-vs-splv"></a>

저변동성만 고려하는 SPLV와 고배당까지  고려하는 SPHD를 비교하여, 고배당의 효과를 살펴 봅니다.

{% include vs/sphd-vs-splv_md.inc %}


{% include /commons/ads/adsense.html %}



### [XMLV vs IJH](/xmlv-vs-ijh/)<a id="xmlv-vs-ijh"></a>

IJH는 S&P 400 중형주 지수를 추종하는 ETF입니다. XMLV는 지수 편입 종목 중에서 저변동성을 고려해서 선별한 S&P MidCap 400 Low Volatility Index를 추종하는 ETF입니다. 저변동성을 이용한 선별이 중형주에 효과가 있는지 살펴볼 수 있습니다.

{% include vs/xmlv-vs-ijh_md.inc %}



### [XSLV vs IJR](/xslv-vs-ijr/)<a id="xslv-vs-ijr"></a>

IJR은 S&P 600 소형주 지수를 추종하는 ETF입니다. XSLV는 지수 편입 종목 중에서 저변동성을 고려해서 선별한 S&P SmallCap 600 Low Volatility Index를 추종하는 ETF입니다. 저변동성을 이용한 선별이 소형주에 효과가 있는지 살펴볼 수 있습니다.

{% include vs/xslv-vs-ijr_md.inc %}



### [ONEV vs IWB](/onev-vs-iwb/)<a id="onev-vs-iwb"></a>

러셀 1000 지수 편입 종목 중에서 저변동성 종목을 선별하는 ONEV와 러셀 100 지수를 추종하는 IWB을 비교합니다.

{% include vs/onev-vs-iwb_md.inc %}



## 해외 상장 해외 ETF (고정 배당 우선주)



### [PGX vs SPY](/pgx-vs-spy/)<a id="pgx-vs-spy"></a>

Invesco사의 PGX는 우선주에 투자하는 상품으로 연 평균 5% 이상의 배당률을 기록해 왔습니다. 이 상품을 S&P5 500 지수를 추종하는 SPY와 비교해 봅니다.

{% include vs/pgx-vs-spy_md.inc %}



### [PFF vs SPY](/pff-vs-spy/)<a id="pff-vs-spy"></a>

iShares사의 PFF는 우선주에도 투자하지만 CB(Convertable Bond; 전환사채)와 같은 하이브리드 증권에도 투자하는 ETF입니다. 이 상품을 S&P 500 지수를 추종하는 SPY와 비교해 봅니다.

{% include vs/pff-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [PFFD vs SPY](/pffd-vs-spy/)<a id="pffd-vs-spy"></a>

{% include vs/pffd-vs-spy_md.inc %}



### [PGX vs PFF](/pgx-vs-pff/)<a id="pgx-vs-pff"></a>

{% include vs/pgx-vs-pff_md.inc %}



### [PFFD vs PFF](/pffd-vs-pff/)<a id="pffd-vs-pff"></a>

{% include vs/pffd-vs-pff_md.inc %}



### [PFFD vs PGX](/pffd-vs-pgx/)<a id="pffd-vs-pgx"></a>

{% include vs/pffd-vs-pgx_md.inc %}



### [PGX vs TLT](/pgx-vs-tlt/)<a id="pgx-vs-tlt"></a>

{% include vs/pgx-vs-tlt_md.inc %}


{% include /commons/ads/adsense.html %}



### [PFF vs TLT](/pff-vs-tlt/)<a id="pff-vs-tlt"></a>

{% include vs/pff-vs-tlt_md.inc %}



### [PFFD vs TLT](/pffd-vs-tlt/)<a id="pffd-vs-tlt"></a>

{% include vs/pffd-vs-tlt_md.inc %}



### [PGX vs AOR](/pgx-vs-aor/)<a id="pgx-vs-aor"></a>

{% include vs/pgx-vs-aor_md.inc %}



### [PFF vs AOR](/pff-vs-aor/)<a id="pff-vs-aor"></a>

{% include vs/pff-vs-aor_md.inc %}



### [PFFD vs AOR](/pffd-vs-aor/)<a id="pffd-vs-aor"></a>

{% include vs/pffd-vs-aor_md.inc %}


{% include /commons/ads/adsense.html %}



### [PGX vs AOM](/pgx-vs-aom/)<a id="pgx-vs-aom"></a>

{% include vs/pgx-vs-aom_md.inc %}



### [PFF vs AOM](/pff-vs-aom/)<a id="pff-vs-aom"></a>

{% include vs/pff-vs-aom_md.inc %}



### [PFFD vs AOM](/pffd-vs-aom/)<a id="pffd-vs-aom"></a>

{% include vs/pffd-vs-aom_md.inc %}



### [PGX vs AOK](/pgx-vs-aok/)<a id="pgx-vs-aok"></a>

{% include vs/pgx-vs-aok_md.inc %}



### [PFF vs AOK](/pff-vs-aok/)<a id="pff-vs-aok"></a>

{% include vs/pff-vs-aok_md.inc %}


{% include /commons/ads/adsense.html %}



### [PFFD vs AOK](/pffd-vs-aok/)<a id="pffd-vs-aok"></a>

{% include vs/pffd-vs-aok_md.inc %}



### [PGX vs LQD](/pgx-vs-lqd/)<a id="pgx-vs-lqd"></a>

{% include vs/pgx-vs-lqd_md.inc %}



### [PFF vs LQD](/pff-vs-lqd/)<a id="pff-vs-lqd"></a>

{% include vs/pff-vs-lqd_md.inc %}



### [PFFD vs LQD](/pffd-vs-lqd/)<a id="pffd-vs-lqd"></a>

{% include vs/pffd-vs-lqd_md.inc %}



## 해외 상장 개별주 커버드콜 (YieldMax)



### [TSLY vs TSLA](/tsly-vs-tsla/)<a id="tsly-vs-tsla"></a>

{% include vs/tsly-vs-tsla_md.inc %}


{% include /commons/ads/adsense.html %}



### [OARK vs ARKK](/oark-vs-arkk/)<a id="oark-vs-arkk"></a>

{% include vs/oark-vs-arkk_md.inc %}



### [APLY vs AAPL](/aply-vs-aapl/)<a id="aply-vs-aapl"></a>

{% include vs/aply-vs-aapl_md.inc %}



### [NVDY vs NVDA](/nvdy-vs-nvda/)<a id="nvdy-vs-nvda"></a>

{% include vs/nvdy-vs-nvda_md.inc %}



### [AMZY vs AMZN](/amzy-vs-amzn/)<a id="amzy-vs-amzn"></a>

{% include vs/amzy-vs-amzn_md.inc %}



### [FBY vs META](/fby-vs-meta/)<a id="fby-vs-meta"></a>

{% include vs/fby-vs-meta_md.inc %}


{% include /commons/ads/adsense.html %}



### [GOOY vs GOOGL](/gooy-vs-googl/)<a id="gooy-vs-googl"></a>

{% include vs/gooy-vs-googl_md.inc %}



### [CONY vs COIN](/cony-vs-coin/)<a id="cony-vs-coin"></a>

{% include vs/cony-vs-coin_md.inc %}



### [DISO vs DIS](/diso-vs-dis/)<a id="diso-vs-dis"></a>

{% include vs/diso-vs-dis_md.inc %}



### [NFLY vs NFLX](/nfly-vs-nflx/)<a id="nfly-vs-nflx"></a>

{% include vs/nfly-vs-nflx_md.inc %}



### [MSFO vs MSFT](/msfo-vs-msft/)<a id="msfo-vs-msft"></a>

{% include vs/msfo-vs-msft_md.inc %}


{% include /commons/ads/adsense.html %}



### [XOMO vs XOM](/xomo-vs-xom/)<a id="xomo-vs-xom"></a>

{% include vs/xomo-vs-xom_md.inc %}



### [JPMO vs JPM](/jpmo-vs-jpm/)<a id="jpmo-vs-jpm"></a>

{% include vs/jpmo-vs-jpm_md.inc %}



### [AMDY vs AMD](/amdy-vs-amd/)<a id="amdy-vs-amd"></a>

{% include vs/amdy-vs-amd_md.inc %}



### [PYPY vs PYPL](/pypy-vs-pypl/)<a id="pypy-vs-pypl"></a>

{% include vs/pypy-vs-pypl_md.inc %}



### [SQY vs XYZ](/sqy-vs-xyz/)<a id="sqy-vs-xyz"></a>

{% include vs/sqy-vs-xyz_md.inc %}


{% include /commons/ads/adsense.html %}



### [MRNY vs MRNA](/mrny-vs-mrna/)<a id="mrny-vs-mrna"></a>

{% include vs/mrny-vs-mrna_md.inc %}



### [AIYY vs AI](/aiyy-vs-ai/)<a id="aiyy-vs-ai"></a>

{% include vs/aiyy-vs-ai_md.inc %}



### [MSTY vs MSTR](/msty-vs-mstr/)<a id="msty-vs-mstr"></a>

{% include vs/msty-vs-mstr_md.inc %}



### [GDXY vs GDX](/gdxy-vs-gdx/)<a id="gdxy-vs-gdx"></a>

{% include vs/gdxy-vs-gdx_md.inc %}



### [SNOY vs SONW](/snoy-vs-snow/)<a id="snoy-vs-snow"></a>

{% include vs/snoy-vs-snow_md.inc %}


{% include /commons/ads/adsense.html %}



### [ABNY vs ABNB](/abny-vs-abnb/)<a id="abny-vs-abnb"></a>

{% include vs/abny-vs-abnb_md.inc %}



### [BABO vs BABA](/babo-vs-baba/)<a id="babo-vs-baba"></a>

{% include vs/babo-vs-baba_md.inc %}



### [TSMY vs TSM](/tsmy-vs-tsm/)<a id="tsmy-vs-tsm"></a>

{% include vs/tsmy-vs-tsm_md.inc %}



### [SMCY vs SMCI](/smcy-vs-smci/)<a id="smcy-vs-smci"></a>

{% include vs/smcy-vs-smci_md.inc %}



### [PLTY vs PLTR](/plty-vs-pltr/)<a id="plty-vs-pltr"></a>

{% include vs/plty-vs-pltr_md.inc %}


{% include /commons/ads/adsense.html %}



### [MARO vs MARA](/maro-vs-mara/)<a id="maro-vs-mara"></a>

{% include vs/maro-vs-mara_md.inc %}



### [CVNY vs CVNA](/cvny-vs-cvna/)<a id="cvny-vs-cvna"></a>

{% include vs/cvny-vs-cvna_md.inc %}



### [SDTY vs SPY](/sdty-vs-spy/)<a id="sdty-vs-spy"></a>

{% include vs/sdty-vs-spy_md.inc %}



### [QDTY vs QQQ](/qdty-vs-qqq/)<a id="qdty-vs-qqq"></a>

{% include vs/qdty-vs-qqq_md.inc %}



### [RDTY vs IWM](/rdty-vs-iwm/)<a id="rdty-vs-iwm"></a>

{% include vs/rdty-vs-iwm_md.inc %}


{% include /commons/ads/adsense.html %}



### [HOOY vs HOOD](/hooy-vs-hood/)<a id="hooy-vs-hood"></a>

{% include vs/hooy-vs-hood_md.inc %}



### [BRKC vs BRK-B](/brkc-vs-brk-b/)<a id="brkc-vs-brk-b"></a>

{% include vs/brkc-vs-brk-b_md.inc %}



### [YMAX vs JEPI](/ymax-vs-jepi/)<a id="ymax-vs-jepi"></a>

{% include vs/ymax-vs-jepi_md.inc %}



### [YMAX vs JEPQ](/ymax-vs-jepq/)<a id="ymax-vs-jepq"></a>

{% include vs/ymax-vs-jepq_md.inc %}



### [YMAX vs QQQ](/ymax-vs-qqq/)<a id="ymax-vs-qqq"></a>

{% include vs/ymax-vs-qqq_md.inc %}


{% include /commons/ads/adsense.html %}



### [YMAG vs JEPI](/ymag-vs-jepi/)<a id="ymag-vs-jepi"></a>

{% include vs/ymag-vs-jepi_md.inc %}



### [YMAG vs JEPQ](/ymag-vs-jepq/)<a id="ymag-vs-jepq"></a>

{% include vs/ymag-vs-jepq_md.inc %}



### [YMAG vs QQQ](/ymag-vs-qqq/)<a id="ymag-vs-qqq"></a>

{% include vs/ymag-vs-qqq_md.inc %}



### [YMAG vs MAGS](/ymag-vs-mags/)<a id="ymag-vs-mags"></a>

{% include vs/ymag-vs-mags_md.inc %}



### [NVDW vs NVDY](/nvdw-vs-nvdy/)<a id="nvdw-vs-nvdy"></a>

{% include vs/nvdw-vs-nvdy_md.inc %}


{% include /commons/ads/adsense.html %}



### [PLTW vs PLTR](/pltw-vs-pltr/)<a id="pltw-vs-pltr"></a>

{% include vs/pltw-vs-pltr_md.inc %}



## 해외 상장 ETF (AI 운용)



### [AIEQ vs SPY](/aieq-vs-spy/)<a id="aieq-vs-spy"></a>

{% include vs/aieq-vs-spy_md.inc %}



### [KOMP vs SPY](/komp-vs-spy/)<a id="komp-vs-spy"></a>

{% include vs/komp-vs-spy_md.inc %}



### [QRFT vs SPY](/qrft-vs-spy/)<a id="qrft-vs-spy"></a>

{% include vs/qrft-vs-spy_md.inc %}



### [AMOM vs SPY](/amom-vs-spy/)<a id="amom-vs-spy"></a>

{% include vs/amom-vs-spy_md.inc %}


{% include /commons/ads/adsense.html %}



### [AIIQ vs SPY](/aiiq-vs-spy/)<a id="aiiq-vs-spy"></a>

{% include vs/aiiq-vs-spy_md.inc %}



### [HDIV vs SPY](/hdiv-vs-spy/)<a id="hdiv-vs-spy"></a>

{% include vs/hdiv-vs-spy_md.inc %}



### [NVQ vs SPY](/nvq-vs-spy/)<a id="nvq-vs-spy"></a>

{% include vs/nvq-vs-spy_md.inc %}



## 해외 상장 ETF (특정 ETF - MAGS)



### [MAGS vs SPY](/mags-vs-spy/)<a id="mags-vs-spy"></a>

{% include vs/mags-vs-spy_md.inc %}



### [MAGS vs QQQ](/mags-vs-qqq/)<a id="mags-vs-qqq"></a>

{% include vs/mags-vs-qqq_md.inc %}


{% include /commons/ads/adsense.html %}



### [MAGS vs QLD](/mags-vs-qld/)<a id="mags-vs-qld"></a>

{% include vs/mags-vs-qld_md.inc %}



### [MAGS vs TQQQ](/mags-vs-tqqq/)<a id="mags-vs-tqqq"></a>

{% include vs/mags-vs-tqqq_md.inc %}



## 해외 상장 ETF (특정 ETF - ARKK)



### [ARKK vs QQQ](/arkk-vs-qqq/)<a id="arkk-vs-qqq"></a>

{% include vs/arkk-vs-qqq_md.inc %}



### [ARKK vs QLD](/arkk-vs-qld/)<a id="arkk-vs-qld"></a>

{% include vs/arkk-vs-qld_md.inc %}



### [ARKG vs XBI](/arkg-vs-xbi/)<a id="arkg-vs-xbi"></a>

{% include vs/arkg-vs-xbi_md.inc %}


{% include /commons/ads/adsense.html %}



## 해외 종목



### [BRK-A vs S&P 500](/brk-a-vs-us500/)<a id="brk-a-vs-us500"></a>

워런 버핏이 CEO로 있는 버크셔 해서웨이(BRK-A)와 미국 대표 지수인 S&P 500(배당 미고려)의 성과를 비교해 봅니다.

{% include vs/brk-a-vs-us500_md.inc %}



### [BRK-A vs SPY](/brk-a-vs-spy/)<a id="brk-a-vs-spy"></a>

워런 버핏이 CEO로 있는 버크셔 해서웨이(BRK-A)와 미국 대표 지수를 추종하는 SPY의 성과를 비교해 봅니다.

{% include vs/brk-a-vs-spy_md.inc %}



### [BRK-B vs SPY](/brk-b-vs-spy/)<a id="brk-b-vs-spy"></a>

워런 버핏이 CEO로 있는 버크셔 해서웨이(BRK-B)와 미국 대표 지수를 추종하는 SPY의 성과를 비교해 봅니다.

{% include vs/brk-b-vs-spy_md.inc %}



### [BRK-B vs BRK-A](/brk-b-vs-brk-a/)<a id="brk-b-vs-brk-a"></a>

워런 버핏이 CEO로 있는 버크셔 해서웨이의 A주(BRK.A)와 B주(BRK-B)의 성과를 비교해 봅니다.

{% include vs/brk-b-vs-brk-a_md.inc %}



### [MOAT vs SCHD](/moat-vs-schd/)<a id="moat-vs-schd"></a>

{% include vs/moat-vs-schd_md.inc %}


{% include /commons/ads/adsense.html %}



### [MOAT vs SPY](/moat-vs-spy/)<a id="moat-vs-spy"></a>

{% include vs/moat-vs-spy_md.inc %}



## vs. 버커셔 해서웨이(BRK-B)



### [SPY vs BRK-B](/spy-vs-brk-b/)<a id="spy-vs-brk-b"></a>

{% include vs/spy-vs-brk-b_md.inc %}



### [VTV vs BRK-B](/vtv-vs-brk-b/)<a id="vtv-vs-brk-b"></a>

{% include vs/vtv-vs-brk-b_md.inc %}



### [VUG vs BRK-B](/vug-vs-brk-b/)<a id="vug-vs-brk-b"></a>

{% include vs/vug-vs-brk-b_md.inc %}



### [IWF vs BRK-B](/iwf-vs-brk-b/)<a id="iwf-vs-brk-b"></a>

{% include vs/iwf-vs-brk-b_md.inc %}


{% include /commons/ads/adsense.html %}



### [SCHD vs BRK-B](/schd-vs-brk-b/)<a id="schd-vs-brk-b"></a>

{% include vs/schd-vs-brk-b_md.inc %}



### [VIG vs BRK-B](/vig-vs-brk-b/)<a id="vig-vs-brk-b"></a>

{% include vs/vig-vs-brk-b_md.inc %}



### [MOAT vs BRK-B](/moat-vs-brk-b/)<a id="moat-vs-brk-b"></a>

{% include vs/moat-vs-brk-b_md.inc %}



### [FMAG vs SPY](/fmag-vs-spy/)<a id="fmag-vs-spy"></a>

{% include vs/fmag-vs-spy_md.inc %}



### [FMAG vs QQQ](/fmag-vs-qqq/)<a id="fmag-vs-qqq"></a>

{% include vs/fmag-vs-qqq_md.inc %}


{% include /commons/ads/adsense.html %}



### [PRNHX vs SPY](/prnhx-vs-spy/)<a id="prnhx-vs-spy"></a>

{% include vs/prnhx-vs-spy_md.inc %}



### [PRNHX vs QQQ](/prnhx-vs-qqq/)<a id="prnhx-vs-qqq"></a>

{% include vs/prnhx-vs-qqq_md.inc %}



### [PRNHX vs IWM](/prnhx-vs-iwm/)<a id="prnhx-vs-iwm"></a>

{% include vs/prnhx-vs-iwm_md.inc %}



### [PRNHX vs IWO](/prnhx-vs-iwo/)<a id="prnhx-vs-iwo"></a>

{% include vs/prnhx-vs-iwo_md.inc %}



## FNGU/FNGO



### [FNGU vs BULZ](/fngu-vs-bulz/)<a id="fngu-vs-bulz"></a>

{% include vs/fngu-vs-bulz_md.inc %}


{% include /commons/ads/adsense.html %}



### [FNGU vs TQQQ](/fngu-vs-tqqq/)<a id="fngu-vs-tqqq"></a>

{% include vs/fngu-vs-tqqq_md.inc %}



### [FNGO vs QLD](/fngo-vs-qld/)<a id="fngo-vs-qld"></a>

{% include vs/fngo-vs-qld_md.inc %}



### [FNGO vs TQQQ](/fngo-vs-tqqq/)<a id="fngo-vs-tqqq"></a>

{% include vs/fngo-vs-tqqq_md.inc %}



## 기타



### [PLUS 미국S&P500(H) vs SPY](/269540-vs-spy/)<a id="269540-vs-spy"></a>

{% include vs/269540-vs-spy_md.inc %}



### [TIGER 미국나스닥100TR(H) vs QQQ](/448300-vs-qqq/)<a id="448300-vs-qqq"></a>

{% include vs/448300-vs-qqq_md.inc %}


{% include /commons/ads/adsense.html %}



### [ACE 일본Nikkei225(H) vs 1329.T](/238720-vs-1329/)<a id="238720-vs-1329"></a>

{% include vs/238720-vs-1329_md.inc %}



### [RISE 차이나HSCEI(H) vs 2828.HK](/250730-vs-2828/)<a id="250730-vs-2828"></a>

{% include vs/250730-vs-2828_md.inc %}



## 미국 상장 채권 vs 주식 ETF



### [SPY vs BIL](/spy-vs-bil/)<a id="spy-vs-bil"></a>

{% include vs/spy-vs-bil_md.inc %}



### [SPY vs SHY](/spy-vs-shy/)<a id="spy-vs-shy"></a>

{% include vs/spy-vs-shy_md.inc %}



### [SPY vs IEF](/spy-vs-ief/)<a id="spy-vs-ief"></a>

{% include vs/spy-vs-ief_md.inc %}


{% include /commons/ads/adsense.html %}



### [SPY vs TLT](/spy-vs-tlt/)<a id="spy-vs-tlt"></a>

{% include vs/spy-vs-tlt_md.inc %}



## 미국 상장 채권 ETF



### [iShares 20+ Year US Treasury Bond JPY Hedged ETF vs iShares 20+ Year Treasury Bond ETF](/2621-vs-tlt/)<a id="2621-vs-tlt"></a>

{% include vs/2621-vs-tlt_md.inc %}



### [CSHI vs BIL](/cshi-vs-bil/)<a id="cshi-vs-bil"></a>

{% include vs/cshi-vs-bil_md.inc %}



### [BNDI vs BND](/bndi-vs-bnd/)<a id="bndi-vs-bnd"></a>

{% include vs/bndi-vs-bnd_md.inc %}



### [BNDW vs BND](/bndw-vs-bnd/)<a id="bndw-vs-bnd"></a>

{% include vs/bndw-vs-bnd_md.inc %}


{% include /commons/ads/adsense.html %}



### [SHY vs TLT](/shy-vs-tlt/)<a id="shy-vs-tlt"></a>

{% include vs/shy-vs-tlt_md.inc %}



### [IEF vs TLT](/ief-vs-tlt/)<a id="ief-vs-tlt"></a>

{% include vs/ief-vs-tlt_md.inc %}



### [HYT vs SHY](/hyt-vs-shy/)<a id="hyt-vs-shy"></a>

{% include vs/hyt-vs-shy_md.inc %}



### [GOF vs SHY](/gof-vs-shy/)<a id="gof-vs-shy"></a>

{% include vs/gof-vs-shy_md.inc %}



### [PDI vs SHY](/pdi-vs-shy/)<a id="pdi-vs-shy"></a>

{% include vs/pdi-vs-shy_md.inc %}


{% include /commons/ads/adsense.html %}



### [HYT vs SPY](/hyt-vs-spy/)<a id="hyt-vs-spy"></a>

{% include vs/hyt-vs-spy_md.inc %}



### [GOF vs SPY](/gof-vs-spy/)<a id="gof-vs-spy"></a>

{% include vs/gof-vs-spy_md.inc %}



### [PDI vs SPY](/pdi-vs-spy/)<a id="pdi-vs-spy"></a>

{% include vs/pdi-vs-spy_md.inc %}



### [GOF vs HYT](/gof-vs-hyt/)<a id="gof-vs-hyt"></a>

{% include vs/gof-vs-hyt_md.inc %}



### [PDI vs HYT](/pdi-vs-hyt/)<a id="pdi-vs-hyt"></a>

{% include vs/pdi-vs-hyt_md.inc %}


{% include /commons/ads/adsense.html %}