## 국내 지수



### KOSPI 200 지수<a id="069500"></a>

{% include lev/069500_md.inc %}



### KOSDAQ 150 지수<a id="229200"></a>

{% include lev/229200_md.inc %}



### KRX 300 지수<a id="292190"></a>

{% include lev/292190_md.inc %}



### 달러 환율<a id="261240"></a>

{% include lev/261240_md.inc %}



### FnGuide 2차전지 산업 지수<a id="305720"></a>

{% include lev/305720_md.inc %}


{% include /commons/ads/adsense.html %}



### KRX 2차전지 TOP 10 지수<a id="364980"></a>

{% include lev/364980_md.inc %}



### iSelect 2차전지 TOP10 지수<a id="465330"></a>

{% include lev/465330_md.inc %}



## 국내 상장 해외 지수



### S&P 500 지수 (환헤지)<a id="449180"></a>

{% include lev/449180_md.inc %}



### 나스닥 100 지수 (환헤지)<a id="449190"></a>

{% include lev/449190_md.inc %}



## 미국 지수



### 다우 존스 산업평균 지수<a id="DIA"></a>

{% include lev/dia_md.inc %}


{% include /commons/ads/adsense.html %}



### S&P 500 지수<a id="SPY"></a>

{% include lev/spy_md.inc %}



### 나스닥 100 지수<a id="QQQ"></a>

{% include lev/qqq_md.inc %}



### 러셀 2000 지수<a id="IWM"></a>

{% include lev/iwm_md.inc %}



### 미국 20+년 장기채<a id="TLT"></a>

{% include lev/tlt_md.inc %}



### 미국 변동성 지수<a id="VIXY"></a>

{% include lev/vixy_md.inc %}


{% include /commons/ads/adsense.html %}



## 미국 섹터 지수



### 필라델피아 반도체 지수<a id="SOXQ"></a>

{% include lev/soxq_md.inc %}



### 기술 섹터 지수<a id="XLK"></a>

{% include lev/xlk_md.inc %}



### S&P 바이오기술 지수<a id="XBI"></a>

{% include lev/xbi_md.inc %}



### NYSE FANG+ 지수<a id="FNGS"></a>

{% include lev/fngs_md.inc %}



## 해외 지수



### MSCI Japan 지수<a id="EWJ"></a>

{% include lev/ewj_md.inc %}


{% include /commons/ads/adsense.html %}



### FTSE China A50 지수<a id="FXI"></a>

{% include lev/fxi_md.inc %}



### MSCI India 지수<a id="INDA"></a>

{% include lev/inda_md.inc %}



### CSI 중국 인터넷 지수<a id="KWEB"></a>

{% include lev/kweb_md.inc %}



## 해외 개별 종목



### Magnificent Seven (M7)<a id="MAGS"></a>

{% include lev/mags_md.inc %}



### 애플<a id="AAPL"></a>

{% include lev/aapl_md.inc %}


{% include /commons/ads/adsense.html %}



### 테슬라<a id="TSLA"></a>

{% include lev/tsla_md.inc %}



### 엔비디아<a id="NVDA"></a>

{% include lev/nvda_md.inc %}